# -*- coding: utf-8 -*-
import json, os
DIR = os.path.dirname(os.path.abspath(__file__))

T = {
    'All fields request': {'fr': 'Tous les champs requis', 'es': 'Todos los campos requeridos', 'de': 'Alle Felder erforderlich', 'it': 'Tutti i campi richiesti', 'pt': 'Todos os campos obrigatórios', 'nl': 'Alle velden vereist', 'ca': 'Tots els camps requerits', 'ro': 'Toate câmpurile sunt obligatorii', 'bg': 'Всички полета са задължителни', 'el': 'Όλα τα πεδία απαιτούνται', 'ar': 'جميع الحقول مطلوبة', 'he': 'כל השדות נדרשים', 'id': 'Semua bidang diperlukan', 'ja': 'すべてのフィールドが必須'},
    'Authorization To Publish': {'fr': 'Autorisation de publier', 'es': 'Autorización para publicar', 'de': 'Veröffentlichungsgenehmigung', 'it': 'Autorizzazione alla pubblicazione', 'pt': 'Autorização para publicar', 'nl': 'Publicatietoestemming', 'ca': 'Autorització per publicar', 'ro': 'Autorizație de publicare', 'bg': 'Разрешение за публикуване', 'el': 'Άδεια δημοσίευσης', 'ar': 'إذن النشر', 'he': 'אישור לפרסום', 'id': 'Izin Publikasi', 'ja': '出版許可'},
    'Authorization document': {'fr': 'Document d\'autorisation', 'es': 'Documento de autorización', 'de': 'Genehmigungsdokument', 'it': 'Documento di autorizzazione', 'pt': 'Documento de autorização', 'nl': 'Autorisatiedocument', 'ca': 'Document d\'autorització', 'ro': 'Document de autorizare', 'bg': 'Документ за разрешение', 'el': 'Έγγραφο άδειας', 'ar': 'وثيقة التفويض', 'he': 'מסמך הרשאה', 'id': 'Dokumen otorisasi', 'ja': '許可文書'},
    'Authorization from authors': {'fr': 'Autorisation des auteurs', 'es': 'Autorización de los autores', 'de': 'Genehmigung der Autoren', 'it': 'Autorizzazione degli autori', 'pt': 'Autorização dos autores', 'nl': 'Toestemming van auteurs', 'ca': 'Autorització dels autors', 'ro': 'Autorizație de la autori', 'bg': 'Разрешение от авторите', 'el': 'Άδεια από τους συγγραφείς', 'ar': 'إذن من المؤلفين', 'he': 'אישור מהמחברים', 'id': 'Izin dari penulis', 'ja': '著者からの許可'},
    'Authorization present in GrottoCenter': {'fr': 'Autorisation présente dans GrottoCenter', 'es': 'Autorización presente en GrottoCenter', 'de': 'Genehmigung in GrottoCenter vorhanden', 'it': 'Autorizzazione presente in GrottoCenter', 'pt': 'Autorização presente no GrottoCenter', 'nl': 'Toestemming aanwezig in GrottoCenter', 'ca': 'Autorització present a GrottoCenter', 'ro': 'Autorizație prezentă în GrottoCenter', 'bg': 'Разрешение в GrottoCenter', 'el': 'Άδεια παρούσα στο GrottoCenter', 'ar': 'الإذن موجود في GrottoCenter', 'he': 'אישור קיים ב-GrottoCenter', 'id': 'Otorisasi ada di GrottoCenter', 'ja': 'GrottoCenterに許可あり'},
    'Average rating': {'fr': 'Note moyenne', 'es': 'Valoración media', 'de': 'Durchschnittsbewertung', 'it': 'Valutazione media', 'pt': 'Classificação média', 'nl': 'Gemiddelde beoordeling', 'ca': 'Valoració mitjana', 'ro': 'Evaluare medie', 'bg': 'Средна оценка', 'el': 'Μέση βαθμολογία', 'ar': 'متوسط التقييم', 'he': 'דירוג ממוצע', 'id': 'Penilaian rata-rata', 'ja': '平均評価'},
    'Calculated on': {'fr': 'Calculé le', 'es': 'Calculado el', 'de': 'Berechnet am', 'it': 'Calcolato il', 'pt': 'Calculado em', 'nl': 'Berekend op', 'ca': 'Calculat el', 'ro': 'Calculat pe', 'bg': 'Изчислено на', 'el': 'Υπολογίστηκε στις', 'ar': 'محسوب في', 'he': 'חושב בתאריך', 'id': 'Dihitung pada', 'ja': '計算日'},
    'Cannot ban yourself': {'fr': 'Vous ne pouvez pas vous bannir vous-même', 'es': 'No puedes banearte a ti mismo', 'de': 'Sie können sich nicht selbst sperren', 'it': 'Non puoi bannare te stesso', 'pt': 'Não pode banir-se a si próprio', 'nl': 'Je kunt jezelf niet bannen', 'ca': 'No pots bannejar-te a tu mateix', 'ro': 'Nu te poți bana pe tine însuți', 'bg': 'Не можете да забраните себе си', 'el': 'Δεν μπορείς να αποκλείσεις τον εαυτό σου', 'ar': 'لا يمكنك حظر نفسك', 'he': 'אינך יכול לחסום את עצמך', 'id': 'Tidak bisa memblokir diri sendiri', 'ja': '自分自身をBANすることはできません'},
    'Caver not found': {'fr': 'Spéléologue introuvable', 'es': 'Espeleólogo no encontrado', 'de': 'Höhlenforscher nicht gefunden', 'it': 'Speleologo non trovato', 'pt': 'Espeleólogo não encontrado', 'nl': 'Speleoloog niet gevonden', 'ca': 'Espeleòleg no trobat', 'ro': 'Speolog negăsit', 'bg': 'Спелеолог не е намерен', 'el': 'Ο σπηλαιολόγος δεν βρέθηκε', 'ar': 'لم يتم العثور على المستكشف', 'he': 'הספלאולוג לא נמצא', 'id': 'Penjelajah gua tidak ditemukan', 'ja': '洞窟探検家が見つかりません'},
    'Caves statistics': {'fr': 'Statistiques des cavités', 'es': 'Estadísticas de cuevas', 'de': 'Höhlenstatistiken', 'it': 'Statistiche delle grotte', 'pt': 'Estatísticas de cavernas', 'nl': 'Grotsstatistieken', 'ca': 'Estadístiques de coves', 'ro': 'Statistici peșteri', 'bg': 'Статистика на пещерите', 'el': 'Στατιστικά σπηλαίων', 'ar': 'إحصاءات الكهوف', 'he': 'סטטיסטיקות מערות', 'id': 'Statistik gua', 'ja': '洞窟統計'},
    'Check the veracity of the information': {'fr': 'Vérifier la véracité de l\'information', 'es': 'Verificar la veracidad de la información', 'de': 'Die Richtigkeit der Informationen prüfen', 'it': 'Verificare la veridicità delle informazioni', 'pt': 'Verificar a veracidade da informação', 'nl': 'Controleer de juistheid van de informatie', 'ca': 'Verificar la veracitat de la informació', 'ro': 'Verificați veridicitatea informațiilor', 'bg': 'Проверете достоверността на информацията', 'el': 'Ελέγξτε την αλήθεια των πληροφοριών', 'ar': 'تحقق من صحة المعلومات', 'he': 'בדוק את אמינות המידע', 'id': 'Periksa kebenaran informasi', 'ja': '情報の正確性を確認'},
    'Check your email to reset your password.': {'fr': 'Vérifiez votre email pour réinitialiser votre mot de passe.', 'es': 'Comprueba tu correo para restablecer tu contraseña.', 'de': 'Überprüfen Sie Ihre E-Mail zum Zurücksetzen Ihres Passworts.', 'it': 'Controlla la tua email per reimpostare la password.', 'pt': 'Verifique o seu email para redefinir a sua palavra-passe.', 'nl': 'Controleer je e-mail om je wachtwoord te resetten.', 'ca': 'Comprova el teu correu per restablir la contrasenya.', 'ro': 'Verificați e-mailul pentru a reseta parola.', 'bg': 'Проверете имейла си за нулиране на паролата.', 'el': 'Ελέγξτε το email σας για να επαναφέρετε τον κωδικό.', 'ar': 'تحقق من بريدك لإعادة تعيين كلمة المرور.', 'he': 'בדוק את האימייל שלך לאיפוס הסיסמה.', 'id': 'Periksa email untuk mereset kata sandi.', 'ja': 'パスワードリセットのメールを確認してください。'},
    'Checking your rights...': {'fr': 'Vérification de vos droits...', 'es': 'Verificando sus derechos...', 'de': 'Ihre Rechte werden überprüft...', 'it': 'Controllo dei tuoi diritti...', 'pt': 'A verificar os seus direitos...', 'nl': 'Uw rechten worden gecontroleerd...', 'ca': 'Comprovant els vostres drets...', 'ro': 'Se verifică drepturile dvs...', 'bg': 'Проверка на правата ви...', 'el': 'Έλεγχος δικαιωμάτων...', 'ar': 'جارٍ التحقق من صلاحياتك...', 'he': 'בודק את ההרשאות שלך...', 'id': 'Memeriksa hak akses...', 'ja': '権限を確認中...'},
    'Child documents': {'fr': 'Documents enfants', 'es': 'Documentos secundarios', 'de': 'Untergeordnete Dokumente', 'it': 'Documenti figli', 'pt': 'Documentos filhos', 'nl': 'Onderliggende documenten', 'ca': 'Documents fills', 'ro': 'Documente subordonate', 'bg': 'Дъщерни документи', 'el': 'Θυγατρικά έγγραφα', 'ar': 'المستندات الفرعية', 'he': 'מסמכי צאצא', 'id': 'Dokumen turunan', 'ja': '子ドキュメント'},
    'Clean gear required': {'fr': 'Matériel propre requis', 'es': 'Equipo limpio requerido', 'de': 'Saubere Ausrüstung erforderlich', 'it': 'Attrezzatura pulita richiesta', 'pt': 'Equipamento limpo necessário', 'nl': 'Schone uitrusting vereist', 'ca': 'Equipament net requerit', 'ro': 'Echipament curat necesar', 'bg': 'Необходимо е чисто оборудване', 'el': 'Απαιτείται καθαρός εξοπλισμός', 'ar': 'معدات نظيفة مطلوبة', 'he': 'נדרש ציוד נקי', 'id': 'Peralatan bersih diperlukan', 'ja': '清潔な装備が必要'},
    'Clear all layers': {'fr': 'Effacer toutes les couches', 'es': 'Limpiar todas las capas', 'de': 'Alle Ebenen löschen', 'it': 'Cancella tutti i livelli', 'pt': 'Limpar todas as camadas', 'nl': 'Alle lagen wissen', 'ca': 'Esborrar totes les capes', 'ro': 'Șterge toate straturile', 'bg': 'Изчисти всички слоеве', 'el': 'Εκκαθάριση όλων των επιπέδων', 'ar': 'مسح جميع الطبقات', 'he': 'נקה את כל השכבות', 'id': 'Hapus semua lapisan', 'ja': 'すべてのレイヤーをクリア'},
}

with open(os.path.join(DIR, 'en.json'), encoding='utf-8') as f:
    en = json.load(f)

total = 0
for lang in ['fr','es','it','pt','de','nl','ca','ro','bg','el','ar','he','id','ja']:
    path = os.path.join(DIR, f'{lang}.json')
    with open(path, encoding='utf-8') as f:
        d = json.load(f)
    n = 0
    for k, langs in T.items():
        if k in en and lang in langs and (k not in d or d[k] == en[k]):
            d[k] = langs[lang]; n += 1
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(dict(sorted(d.items())), f, ensure_ascii=False, indent=2)
    total += n
    print(f'{lang}: +{n}')
print(f'Total: {total}')
