# -*- coding: utf-8 -*-
import json, os
DIR = os.path.dirname(os.path.abspath(__file__))

T = {
    'Click cancel to undo changes': {'fr': 'Cliquer sur annuler pour annuler les modifications', 'es': 'Haz clic en cancelar para deshacer los cambios', 'de': 'Auf Abbrechen klicken, um Änderungen rückgängig zu machen', 'it': 'Clicca su annulla per annullare le modifiche', 'pt': 'Clique em cancelar para desfazer as alterações', 'nl': 'Klik op annuleren om wijzigingen ongedaan te maken', 'ca': 'Fes clic a cancel·lar per desfer els canvis', 'ro': 'Faceți clic pe anulare pentru a anula modificările', 'bg': 'Щракнете върху отказ за отмяна на промените', 'el': 'Κάντε κλικ στην ακύρωση για αναίρεση αλλαγών', 'ar': 'انقر فوق إلغاء للتراجع عن التغييرات', 'he': 'לחץ על ביטול לביטול השינויים', 'id': 'Klik batal untuk membatalkan perubahan', 'ja': 'キャンセルをクリックして変更を元に戻す'},
    'Click first point to close this shape.': {'fr': 'Cliquez sur le premier point pour fermer cette forme.', 'es': 'Haz clic en el primer punto para cerrar esta forma.', 'de': 'Klicken Sie auf den ersten Punkt, um diese Form zu schließen.', 'it': 'Clicca sul primo punto per chiudere questa forma.', 'pt': 'Clique no primeiro ponto para fechar esta forma.', 'nl': 'Klik op het eerste punt om deze vorm te sluiten.', 'ca': 'Fes clic al primer punt per tancar aquesta forma.', 'ro': 'Faceți clic pe primul punct pentru a închide această formă.', 'bg': 'Щракнете върху първата точка за затваряне на фигурата.', 'el': 'Κάντε κλικ στο πρώτο σημείο για να κλείσετε αυτό το σχήμα.', 'ar': 'انقر على النقطة الأولى لإغلاق هذا الشكل.', 'he': 'לחץ על הנקודה הראשונה לסגירת הצורה.', 'id': 'Klik titik pertama untuk menutup bentuk ini.', 'ja': '最初の点をクリックしてこの形状を閉じる。'},
    'Click on a feature to remove.': {'fr': 'Cliquez sur un élément pour le supprimer.', 'es': 'Haz clic en un elemento para eliminarlo.', 'de': 'Klicken Sie auf ein Element, um es zu entfernen.', 'it': 'Clicca su un elemento per rimuoverlo.', 'pt': 'Clique num elemento para o remover.', 'nl': 'Klik op een element om het te verwijderen.', 'ca': 'Fes clic en un element per eliminar-lo.', 'ro': 'Faceți clic pe un element pentru a-l elimina.', 'bg': 'Щракнете върху елемент за премахване.', 'el': 'Κάντε κλικ σε ένα στοιχείο για να το αφαιρέσετε.', 'ar': 'انقر على عنصر لإزالته.', 'he': 'לחץ על אלמנט להסרתו.', 'id': 'Klik fitur untuk menghapus.', 'ja': '要素をクリックして削除。'},
    'Click the cross to unsubscribe': {'fr': 'Cliquez sur la croix pour vous désabonner', 'es': 'Haz clic en la cruz para cancelar la suscripción', 'de': 'Klicken Sie auf das Kreuz, um sich abzumelden', 'it': 'Clicca sulla croce per annullare l\'iscrizione', 'pt': 'Clique na cruz para cancelar a subscrição', 'nl': 'Klik op het kruisje om te annuleren', 'ca': 'Fes clic a la creu per cancel·lar la subscripció', 'ro': 'Faceți clic pe cruce pentru a vă dezabona', 'bg': 'Щракнете на кръста за отписване', 'el': 'Κάντε κλικ στον σταυρό για κατάργηση εγγραφής', 'ar': 'انقر على الصليب لإلغاء الاشتراك', 'he': 'לחץ על ה-X לביטול המנוי', 'id': 'Klik tanda silang untuk berhenti berlangganan', 'ja': 'クロスをクリックして購読解除'},
    'Click the same rating to remove it': {'fr': 'Cliquez sur la même note pour la supprimer', 'es': 'Haz clic en la misma valoración para eliminarla', 'de': 'Klicken Sie auf dieselbe Bewertung, um sie zu entfernen', 'it': 'Clicca sulla stessa valutazione per rimuoverla', 'pt': 'Clique na mesma classificação para a remover', 'nl': 'Klik op dezelfde beoordeling om deze te verwijderen', 'ca': 'Fes clic a la mateixa valoració per eliminar-la', 'ro': 'Faceți clic pe aceeași evaluare pentru a o elimina', 'bg': 'Щракнете на същата оценка за премахване', 'el': 'Κάντε κλικ στην ίδια βαθμολογία για να την αφαιρέσετε', 'ar': 'انقر على نفس التقييم لإزالته', 'he': 'לחץ על אותו דירוג להסרתו', 'id': 'Klik penilaian yang sama untuk menghapusnya', 'ja': '同じ評価をクリックして削除'},
    'Click to continue drawing shape.': {'fr': 'Cliquez pour continuer à dessiner la forme.', 'es': 'Haz clic para continuar dibujando la forma.', 'de': 'Klicken Sie, um das Zeichnen der Form fortzusetzen.', 'it': 'Clicca per continuare a disegnare la forma.', 'pt': 'Clique para continuar a desenhar a forma.', 'nl': 'Klik om door te gaan met het tekenen van de vorm.', 'ca': 'Fes clic per continuar dibuixant la forma.', 'ro': 'Faceți clic pentru a continua desenarea formei.', 'bg': 'Щракнете, за да продължите да рисувате фигурата.', 'el': 'Κάντε κλικ για να συνεχίσετε το σχεδιασμό.', 'ar': 'انقر للمتابعة في رسم الشكل.', 'he': 'לחץ להמשך ציור הצורה.', 'id': 'Klik untuk melanjutkan menggambar bentuk.', 'ja': 'クリックして形状の描画を続行。'},
    'Click to start drawing shape.': {'fr': 'Cliquez pour commencer à dessiner la forme.', 'es': 'Haz clic para empezar a dibujar la forma.', 'de': 'Klicken Sie, um mit dem Zeichnen der Form zu beginnen.', 'it': 'Clicca per iniziare a disegnare la forma.', 'pt': 'Clique para começar a desenhar a forma.', 'nl': 'Klik om te beginnen met het tekenen van de vorm.', 'ca': 'Fes clic per començar a dibuixar la forma.', 'ro': 'Faceți clic pentru a începe desenarea formei.', 'bg': 'Щракнете, за да започнете да рисувате фигурата.', 'el': 'Κάντε κλικ για να ξεκινήσετε το σχεδιασμό.', 'ar': 'انقر لبدء رسم الشكل.', 'he': 'לחץ להתחלת ציור הצורה.', 'id': 'Klik untuk mulai menggambar bentuk.', 'ja': 'クリックして形状の描画を開始。'},
    'Code area': {'fr': 'Zone de code', 'es': 'Área de código', 'de': 'Codebereich', 'it': 'Area codice', 'pt': 'Área de código', 'nl': 'Codegebied', 'ca': 'Àrea de codi', 'ro': 'Zonă cod', 'bg': 'Зона с код', 'el': 'Περιοχή κώδικα', 'ar': 'منطقة الرمز', 'he': 'אזור קוד', 'id': 'Area kode', 'ja': 'コードエリア'},
    'Confirm or Rollback': {'fr': 'Confirmer ou Annuler', 'es': 'Confirmar o Revertir', 'de': 'Bestätigen oder Zurücksetzen', 'it': 'Conferma o Ripristina', 'pt': 'Confirmar ou Reverter', 'nl': 'Bevestigen of Terugdraaien', 'ca': 'Confirmar o Revertir', 'ro': 'Confirmați sau Reveniți', 'bg': 'Потвърди или Върни', 'el': 'Επιβεβαίωση ή Επαναφορά', 'ar': 'تأكيد أو تراجع', 'he': 'אשר או החזר', 'id': 'Konfirmasi atau Batalkan', 'ja': '確認またはロールバック'},
    'Confirmation of document approval': {'fr': 'Confirmation d\'approbation du document', 'es': 'Confirmación de aprobación del documento', 'de': 'Bestätigung der Dokumentgenehmigung', 'it': 'Conferma dell\'approvazione del documento', 'pt': 'Confirmação de aprovação do documento', 'nl': 'Bevestiging van documentgoedkeuring', 'ca': 'Confirmació d\'aprovació del document', 'ro': 'Confirmare aprobare document', 'bg': 'Потвърждение за одобрение на документ', 'el': 'Επιβεβαίωση έγκρισης εγγράφου', 'ar': 'تأكيد الموافقة على المستند', 'he': 'אישור אישור מסמך', 'id': 'Konfirmasi persetujuan dokumen', 'ja': '文書承認の確認'},
    'Confirmation of document refusal': {'fr': 'Confirmation de refus du document', 'es': 'Confirmación de rechazo del documento', 'de': 'Bestätigung der Dokumentablehnung', 'it': 'Conferma del rifiuto del documento', 'pt': 'Confirmação de recusa do documento', 'nl': 'Bevestiging van documentweigering', 'ca': 'Confirmació de rebuig del document', 'ro': 'Confirmare refuz document', 'bg': 'Потвърждение за отказ на документ', 'el': 'Επιβεβαίωση άρνησης εγγράφου', 'ar': 'تأكيد رفض المستند', 'he': 'אישור דחיית מסמך', 'id': 'Konfirmasi penolakan dokumen', 'ja': '文書却下の確認'},
    'Coordinates precision unavailable for restricted access entrance.': {'fr': 'Précision des coordonnées indisponible pour une entrée à accès restreint.', 'es': 'Precisión de coordenadas no disponible para entrada de acceso restringido.', 'de': 'Koordinatengenauigkeit für Eingang mit eingeschränktem Zugang nicht verfügbar.', 'it': 'Precisione coordinate non disponibile per ingresso ad accesso limitato.', 'pt': 'Precisão de coordenadas indisponível para entrada de acesso restrito.', 'nl': 'Coördinatennauwkeurigheid niet beschikbaar voor ingang met beperkte toegang.', 'ca': 'Precisió de coordenades no disponible per a entrada d\'accés restringit.', 'ro': 'Precizia coordonatelor indisponibilă pentru intrarea cu acces restricționat.', 'bg': 'Точността на координатите е недостъпна за вход с ограничен достъп.', 'el': 'Η ακρίβεια συντεταγμένων δεν είναι διαθέσιμη για είσοδο περιορισμένης πρόσβασης.', 'ar': 'دقة الإحداثيات غير متاحة لمدخل الوصول المقيد.', 'he': 'דיוק הקואורדינטות אינו זמין למכניסה עם גישה מוגבלת.', 'id': 'Presisi koordinat tidak tersedia untuk pintu masuk akses terbatas.', 'ja': 'アクセス制限された入口では座標精度が利用できません。'},
    'Coordinates precision unknown.': {'fr': 'Précision des coordonnées inconnue.', 'es': 'Precisión de coordenadas desconocida.', 'de': 'Koordinatengenauigkeit unbekannt.', 'it': 'Precisione delle coordinate sconosciuta.', 'pt': 'Precisão de coordenadas desconhecida.', 'nl': 'Coördinatennauwkeurigheid onbekend.', 'ca': 'Precisió de coordenades desconeguda.', 'ro': 'Precizia coordonatelor necunoscută.', 'bg': 'Точността на координатите е неизвестна.', 'el': 'Άγνωστη ακρίβεια συντεταγμένων.', 'ar': 'دقة الإحداثيات غير معروفة.', 'he': 'דיוק הקואורדינטות אינו ידוע.', 'id': 'Presisi koordinat tidak diketahui.', 'ja': '座標精度不明。'},
    'Coordinates precision: ±{precision}m': {'fr': 'Précision des coordonnées : ±{precision}m', 'es': 'Precisión de coordenadas: ±{precision}m', 'de': 'Koordinatengenauigkeit: ±{precision}m', 'it': 'Precisione coordinate: ±{precision}m', 'pt': 'Precisão de coordenadas: ±{precision}m', 'nl': 'Coördinatennauwkeurigheid: ±{precision}m', 'ca': 'Precisió de coordenades: ±{precision}m', 'ro': 'Precizia coordonatelor: ±{precision}m', 'bg': 'Точност на координатите: ±{precision}м', 'el': 'Ακρίβεια συντεταγμένων: ±{precision}m', 'ar': 'دقة الإحداثيات: ±{precision}م', 'he': 'דיוק קואורדינטות: ±{precision}מ', 'id': 'Presisi koordinat: ±{precision}m', 'ja': '座標精度: ±{precision}m'},
    'Create new entity': {'fr': 'Créer une nouvelle entité', 'es': 'Crear nueva entidad', 'de': 'Neue Entität erstellen', 'it': 'Crea nuova entità', 'pt': 'Criar nova entidade', 'nl': 'Nieuwe entiteit aanmaken', 'ca': 'Crear nova entitat', 'ro': 'Creați o nouă entitate', 'bg': 'Създай нова единица', 'el': 'Δημιουργία νέας οντότητας', 'ar': 'إنشاء كيان جديد', 'he': 'צור ישות חדשה', 'id': 'Buat entitas baru', 'ja': '新しいエンティティを作成'},
    'Created by an unknown author': {'fr': 'Créé par un auteur inconnu', 'es': 'Creado por un autor desconocido', 'de': 'Von einem unbekannten Autor erstellt', 'it': 'Creato da un autore sconosciuto', 'pt': 'Criado por um autor desconhecido', 'nl': 'Gemaakt door een onbekende auteur', 'ca': 'Creat per un autor desconegut', 'ro': 'Creat de un autor necunoscut', 'bg': 'Създадено от неизвестен автор', 'el': 'Δημιουργήθηκε από άγνωστο συγγραφέα', 'ar': 'أنشأه مؤلف مجهول', 'he': 'נוצר על ידי מחבר לא ידוע', 'id': 'Dibuat oleh penulis tidak dikenal', 'ja': '不明な著者によって作成'},
    'Creator comment': {'fr': 'Commentaire du créateur', 'es': 'Comentario del creador', 'de': 'Kommentar des Erstellers', 'it': 'Commento del creatore', 'pt': 'Comentário do criador', 'nl': 'Opmerking van maker', 'ca': 'Comentari del creador', 'ro': 'Comentariul creatorului', 'bg': 'Коментар на създателя', 'el': 'Σχόλιο δημιουργού', 'ar': 'تعليق المنشئ', 'he': 'הערת היוצר', 'id': 'Komentar pembuat', 'ja': '作成者のコメント'},
    'Data quality score: {value}/100': {'fr': 'Score de qualité des données : {value}/100', 'es': 'Puntuación de calidad de datos: {value}/100', 'de': 'Datenqualitätspunktzahl: {value}/100', 'it': 'Punteggio qualità dati: {value}/100', 'pt': 'Pontuação de qualidade de dados: {value}/100', 'nl': 'Datakwaliteitsscore: {value}/100', 'ca': 'Puntuació de qualitat de dades: {value}/100', 'ro': 'Scor calitate date: {value}/100', 'bg': 'Оценка на качеството на данните: {value}/100', 'el': 'Βαθμολογία ποιότητας δεδομένων: {value}/100', 'ar': 'درجة جودة البيانات: {value}/100', 'he': 'ציון איכות נתונים: {value}/100', 'id': 'Skor kualitas data: {value}/100', 'ja': 'データ品質スコア: {value}/100'},
    'Date of last data update :': {'fr': 'Date de la dernière mise à jour des données :', 'es': 'Fecha de la última actualización de datos:', 'de': 'Datum der letzten Datenaktualisierung:', 'it': 'Data dell\'ultimo aggiornamento dati:', 'pt': 'Data da última atualização de dados:', 'nl': 'Datum van laatste gegevensupdate:', 'ca': 'Data de l\'última actualització de dades:', 'ro': 'Data ultimei actualizări a datelor:', 'bg': 'Дата на последна актуализация на данните:', 'el': 'Ημερομηνία τελευταίας ενημέρωσης δεδομένων:', 'ar': 'تاريخ آخر تحديث للبيانات:', 'he': 'תאריך עדכון נתונים אחרון:', 'id': 'Tanggal pembaruan data terakhir:', 'ja': 'データ最終更新日:'},
    'Delete last point drawn': {'fr': 'Supprimer le dernier point dessiné', 'es': 'Eliminar el último punto dibujado', 'de': 'Letzten gezeichneten Punkt löschen', 'it': 'Elimina l\'ultimo punto disegnato', 'pt': 'Eliminar o último ponto desenhado', 'nl': 'Verwijder het laatste getekende punt', 'ca': 'Eliminar l\'últim punt dibuixat', 'ro': 'Șterge ultimul punct desenat', 'bg': 'Изтрий последната начертана точка', 'el': 'Διαγραφή τελευταίου σχεδιαζόμενου σημείου', 'ar': 'احذف آخر نقطة مرسومة', 'he': 'מחק את הנקודה האחרונה שצוירה', 'id': 'Hapus titik terakhir yang digambar', 'ja': '最後に描いた点を削除'},
    'Delete this line': {'fr': 'Supprimer cette ligne', 'es': 'Eliminar esta línea', 'de': 'Diese Zeile löschen', 'it': 'Elimina questa riga', 'pt': 'Eliminar esta linha', 'nl': 'Verwijder deze regel', 'ca': 'Elimina aquesta línia', 'ro': 'Șterge această linie', 'bg': 'Изтрий тази линия', 'el': 'Διαγραφή αυτής της γραμμής', 'ar': 'احذف هذا السطر', 'he': 'מחק שורה זו', 'id': 'Hapus baris ini', 'ja': 'この行を削除'},
}

with open(os.path.join(DIR, 'en.json'), encoding='utf-8') as f:
    en = json.load(f)

total = 0
for lang in ['fr','es','it','pt','de','nl','ca','ro','bg','el','ar','he','id','ja']:
    path = os.path.join(DIR, f'{lang}.json')
    with open(path, encoding='utf-8') as f:
        d = json.load(f)
    n = 0
    for k, langs in T.items():
        if k in en and lang in langs and (k not in d or d[k] == en[k]):
            d[k] = langs[lang]; n += 1
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(dict(sorted(d.items())), f, ensure_ascii=False, indent=2)
    total += n
    print(f'{lang}: +{n}')
print(f'Total: {total}')
