# -*- coding: utf-8 -*-
import json, os
DIR = os.path.dirname(os.path.abspath(__file__))

T = {
    'Depository Library': {'fr': 'Bibliothèque de dépôt', 'es': 'Biblioteca depositaria', 'de': 'Pflichtbibliothek', 'it': 'Biblioteca depositaria', 'pt': 'Biblioteca depositária', 'nl': 'Depotbibliotheek', 'ca': 'Biblioteca dipositària', 'ro': 'Bibliotecă depozitară', 'bg': 'Библиотека-депозитар', 'el': 'Βιβλιοθήκη κατάθεσης', 'ar': 'مكتبة الإيداع', 'he': 'ספריית פיקדון', 'id': 'Perpustakaan depositari', 'ja': '納本図書館'},
    'Description of the massif': {'fr': 'Description du massif', 'es': 'Descripción del macizo', 'de': 'Beschreibung des Massivs', 'it': 'Descrizione del massiccio', 'pt': 'Descrição do maciço', 'nl': 'Beschrijving van het massief', 'ca': 'Descripció del massís', 'ro': 'Descrierea masivului', 'bg': 'Описание на масива', 'el': 'Περιγραφή του ογκόλιθου', 'ar': 'وصف الكتلة الجبلية', 'he': 'תיאור המסיף', 'id': 'Deskripsi massif', 'ja': 'マッシーフの説明'},
    'Description of the organization': {'fr': 'Description de l\'organisation', 'es': 'Descripción de la organización', 'de': 'Beschreibung der Organisation', 'it': 'Descrizione dell\'organizzazione', 'pt': 'Descrição da organização', 'nl': 'Beschrijving van de organisatie', 'ca': 'Descripció de l\'organització', 'ro': 'Descrierea organizației', 'bg': 'Описание на организацията', 'el': 'Περιγραφή οργανισμού', 'ar': 'وصف المنظمة', 'he': 'תיאור הארגון', 'id': 'Deskripsi organisasi', 'ja': '組織の説明'},
    'Detailed document view': {'fr': 'Vue détaillée du document', 'es': 'Vista detallada del documento', 'de': 'Detaillierte Dokumentansicht', 'it': 'Vista dettagliata del documento', 'pt': 'Vista detalhada do documento', 'nl': 'Gedetailleerde documentweergave', 'ca': 'Vista detallada del document', 'ro': 'Vizualizare detaliată document', 'bg': 'Подробен изглед на документа', 'el': 'Λεπτομερής προβολή εγγράφου', 'ar': 'عرض تفصيلي للمستند', 'he': 'תצוגה מפורטת של מסמך', 'id': 'Tampilan dokumen terperinci', 'ja': '文書の詳細表示'},
    'Detailed view': {'fr': 'Vue détaillée', 'es': 'Vista detallada', 'de': 'Detailansicht', 'it': 'Vista dettagliata', 'pt': 'Vista detalhada', 'nl': 'Gedetailleerde weergave', 'ca': 'Vista detallada', 'ro': 'Vizualizare detaliată', 'bg': 'Подробен изглед', 'el': 'Λεπτομερής προβολή', 'ar': 'عرض مفصل', 'he': 'תצוגה מפורטת', 'id': 'Tampilan terperinci', 'ja': '詳細表示'},
    'Discover the numbers about this country and its massifs and caves.': {'fr': 'Découvrez les chiffres sur ce pays et ses massifs et grottes.', 'es': 'Descubra los números sobre este país y sus macizos y cuevas.', 'de': 'Entdecken Sie die Zahlen über dieses Land und seine Massive und Höhlen.', 'it': 'Scopri i numeri su questo paese e i suoi massicci e grotte.', 'pt': 'Descubra os números sobre este país e os seus maciços e cavernas.', 'nl': 'Ontdek de cijfers over dit land en zijn massieven en grotten.', 'ca': 'Descobreix les xifres sobre aquest país i els seus massissos i coves.', 'ro': 'Descoperiți cifrele despre această țară și masivele și peșterile sale.', 'bg': 'Открийте числата за тази страна и нейните масиви и пещери.', 'el': 'Ανακαλύψτε τα στοιχεία για αυτή τη χώρα και τους ογκόλιθους και σπήλαιά της.', 'ar': 'اكتشف أرقام هذا البلد وكتله الجبلية وكهوفه.', 'he': 'גלה את המספרים על מדינה זו והמסיפים והמערות שלה.', 'id': 'Temukan angka-angka tentang negara ini dan massif serta guanya.', 'ja': 'この国とそのマッシーフ・洞窟に関する統計を見る。'},
    'Discover the numbers about this massif and its caves.': {'fr': 'Découvrez les chiffres sur ce massif et ses grottes.', 'es': 'Descubra los números sobre este macizo y sus cuevas.', 'de': 'Entdecken Sie die Zahlen über dieses Massiv und seine Höhlen.', 'it': 'Scopri i numeri su questo massiccio e le sue grotte.', 'pt': 'Descubra os números sobre este maciço e as suas cavernas.', 'nl': 'Ontdek de cijfers over dit massief en zijn grotten.', 'ca': 'Descobreix les xifres sobre aquest massís i les seves coves.', 'ro': 'Descoperiți cifrele despre acest masiv și peșterile sale.', 'bg': 'Открийте числата за този масив и неговите пещери.', 'el': 'Ανακαλύψτε τα στοιχεία για αυτόν τον ογκόλιθο και τα σπήλαιά του.', 'ar': 'اكتشف أرقام هذه الكتلة الجبلية وكهوفها.', 'he': 'גלה את המספרים על מסיף זה והמערות שלו.', 'id': 'Temukan angka-angka tentang massif ini dan guanya.', 'ja': 'このマッシーフとその洞窟に関する統計を見る。'},
    'Discover the numbers about this region and its caves.': {'fr': 'Découvrez les chiffres sur cette région et ses grottes.', 'es': 'Descubra los números sobre esta región y sus cuevas.', 'de': 'Entdecken Sie die Zahlen über diese Region und ihre Höhlen.', 'it': 'Scopri i numeri su questa regione e le sue grotte.', 'pt': 'Descubra os números sobre esta região e as suas cavernas.', 'nl': 'Ontdek de cijfers over deze regio en zijn grotten.', 'ca': 'Descobreix les xifres sobre aquesta regió i les seves coves.', 'ro': 'Descoperiți cifrele despre această regiune și peșterile sale.', 'bg': 'Открийте числата за този регион и неговите пещери.', 'el': 'Ανακαλύψτε τα στοιχεία για αυτή την περιοχή και τα σπήλαιά της.', 'ar': 'اكتشف أرقام هذه المنطقة وكهوفها.', 'he': 'גלה את המספרים על אזור זה והמערות שלו.', 'id': 'Temukan angka-angka tentang wilayah ini dan guanya.', 'ja': 'この地域とその洞窟に関する統計を見る。'},
    'Distance must be an integer (in m)': {'fr': 'La distance doit être un entier (en m)', 'es': 'La distancia debe ser un número entero (en m)', 'de': 'Die Entfernung muss eine ganze Zahl sein (in m)', 'it': 'La distanza deve essere un intero (in m)', 'pt': 'A distância deve ser um número inteiro (em m)', 'nl': 'De afstand moet een geheel getal zijn (in m)', 'ca': 'La distància ha de ser un enter (en m)', 'ro': 'Distanța trebuie să fie un număr întreg (în m)', 'bg': 'Разстоянието трябва да е цяло число (в м)', 'el': 'Η απόσταση πρέπει να είναι ακέραιος (σε m)', 'ar': 'يجب أن تكون المسافة عدداً صحيحاً (بالمتر)', 'he': 'המרחק חייב להיות מספר שלם (במטרים)', 'id': 'Jarak harus bilangan bulat (dalam m)', 'ja': '距離は整数でなければなりません（m単位）'},
    'Distance must be superior or equal to 0': {'fr': 'La distance doit être supérieure ou égale à 0', 'es': 'La distancia debe ser mayor o igual a 0', 'de': 'Die Entfernung muss größer oder gleich 0 sein', 'it': 'La distanza deve essere maggiore o uguale a 0', 'pt': 'A distância deve ser maior ou igual a 0', 'nl': 'De afstand moet groter of gelijk aan 0 zijn', 'ca': 'La distància ha de ser superior o igual a 0', 'ro': 'Distanța trebuie să fie mai mare sau egală cu 0', 'bg': 'Разстоянието трябва да е по-голямо или равно на 0', 'el': 'Η απόσταση πρέπει να είναι μεγαλύτερη ή ίση με 0', 'ar': 'يجب أن تكون المسافة أكبر من أو تساوي 0', 'he': 'המרחק חייב להיות גדול מ-0 או שווה לו', 'id': 'Jarak harus lebih besar atau sama dengan 0', 'ja': '距離は0以上でなければなりません'},
    'Document main language': {'fr': 'Langue principale du document', 'es': 'Idioma principal del documento', 'de': 'Hauptsprache des Dokuments', 'it': 'Lingua principale del documento', 'pt': 'Língua principal do documento', 'nl': 'Hoofdtaal van het document', 'ca': 'Llengua principal del document', 'ro': 'Limba principală a documentului', 'bg': 'Основен език на документа', 'el': 'Κύρια γλώσσα εγγράφου', 'ar': 'اللغة الرئيسية للمستند', 'he': 'שפה ראשית של המסמך', 'id': 'Bahasa utama dokumen', 'ja': '文書の主要言語'},
    'Document parent': {'fr': 'Document parent', 'es': 'Documento padre', 'de': 'Übergeordnetes Dokument', 'it': 'Documento padre', 'pt': 'Documento pai', 'nl': 'Bovenliggend document', 'ca': 'Document pare', 'ro': 'Document părinte', 'bg': 'Родителски документ', 'el': 'Γονικό έγγραφο', 'ar': 'المستند الأصل', 'he': 'מסמך אב', 'id': 'Dokumen induk', 'ja': '親文書'},
    'Drag and drop your logo here': {'fr': 'Glissez et déposez votre logo ici', 'es': 'Arrastra y suelta tu logo aquí', 'de': 'Ihr Logo hier hinziehen und ablegen', 'it': 'Trascina e rilascia il tuo logo qui', 'pt': 'Arraste e solte o seu logótipo aqui', 'nl': 'Sleep uw logo hier naartoe', 'ca': 'Arrossega i deixa anar el teu logotip aquí', 'ro': 'Trageți și plasați logo-ul dvs. aici', 'bg': 'Плъзнете и пуснете логото си тук', 'el': 'Σύρετε και αφήστε το λογότυπό σας εδώ', 'ar': 'اسحب وأفلت شعارك هنا', 'he': 'גרור ושחרר את הלוגו שלך כאן', 'id': 'Seret dan lepas logo Anda di sini', 'ja': 'ロゴをここにドラッグ＆ドロップ'},
    'Drag handles or markers to edit features.': {'fr': 'Faites glisser les poignées ou les marqueurs pour modifier les éléments.', 'es': 'Arrastra los controladores o marcadores para editar elementos.', 'de': 'Ziehen Sie Griffe oder Markierungen, um Elemente zu bearbeiten.', 'it': 'Trascina le maniglie o i marcatori per modificare gli elementi.', 'pt': 'Arraste as alças ou marcadores para editar elementos.', 'nl': 'Sleep grepen of markeringen om elementen te bewerken.', 'ca': 'Arrossega les nanses o els marcadors per editar elements.', 'ro': 'Trageți mânere sau marcatori pentru a edita elemente.', 'bg': 'Плъзнете дръжки или маркери за редактиране.', 'el': 'Σύρετε λαβές ή δείκτες για επεξεργασία στοιχείων.', 'ar': 'اسحب المقابض أو العلامات لتعديل العناصر.', 'he': 'גרור ידיות או סמנים לעריכת אלמנטים.', 'id': 'Seret pegangan atau penanda untuk mengedit fitur.', 'ja': 'ハンドルまたはマーカーをドラッグして要素を編集。'},
    'Drop CSV file here or click to upload.': {'fr': 'Déposez un fichier CSV ici ou cliquez pour télécharger.', 'es': 'Suelta el archivo CSV aquí o haz clic para cargar.', 'de': 'CSV-Datei hier ablegen oder klicken zum Hochladen.', 'it': 'Rilascia il file CSV qui o clicca per caricare.', 'pt': 'Largue o ficheiro CSV aqui ou clique para carregar.', 'nl': 'Zet CSV-bestand hier neer of klik om te uploaden.', 'ca': 'Deixa anar el fitxer CSV aquí o fes clic per pujar.', 'ro': 'Plasați fișierul CSV aici sau faceți clic pentru încărcare.', 'bg': 'Пуснете CSV файла тук или кликнете за качване.', 'el': 'Αφήστε το αρχείο CSV εδώ ή κάντε κλικ για μεταφόρτωση.', 'ar': 'أفلت ملف CSV هنا أو انقر للتحميل.', 'he': 'שחרר קובץ CSV כאן או לחץ להעלאה.', 'id': 'Lepas file CSV di sini atau klik untuk mengunggah.', 'ja': 'CSVファイルをここにドロップするかクリックしてアップロード。'},
    'Duplicate from database': {'fr': 'Doublon de la base de données', 'es': 'Duplicado de la base de datos', 'de': 'Duplikat aus der Datenbank', 'it': 'Duplicato dal database', 'pt': 'Duplicado da base de dados', 'nl': 'Duplicaat uit database', 'ca': 'Duplicat de la base de dades', 'ro': 'Duplicat din baza de date', 'bg': 'Дубликат от базата данни', 'el': 'Διπλότυπο από τη βάση δεδομένων', 'ar': 'مكرر من قاعدة البيانات', 'he': 'כפיל ממסד הנתונים', 'id': 'Duplikat dari database', 'ja': 'データベースの重複'},
    'Duplicate from import': {'fr': 'Doublon de l\'importation', 'es': 'Duplicado de la importación', 'de': 'Duplikat aus dem Import', 'it': 'Duplicato dall\'importazione', 'pt': 'Duplicado da importação', 'nl': 'Duplicaat uit import', 'ca': 'Duplicat de la importació', 'ro': 'Duplicat din import', 'bg': 'Дубликат от импорта', 'el': 'Διπλότυπο από εισαγωγή', 'ar': 'مكرر من الاستيراد', 'he': 'כפיל מהייבוא', 'id': 'Duplikat dari impor', 'ja': 'インポートの重複'},
    'Duplicates Tool': {'fr': 'Outil de doublons', 'es': 'Herramienta de duplicados', 'de': 'Duplikate-Werkzeug', 'it': 'Strumento duplicati', 'pt': 'Ferramenta de duplicados', 'nl': 'Duplicatengereedschap', 'ca': 'Eina de duplicats', 'ro': 'Instrument duplicate', 'bg': 'Инструмент за дубликати', 'el': 'Εργαλείο διπλοτύπων', 'ar': 'أداة التكرارات', 'he': 'כלי כפילויות', 'id': 'Alat duplikat', 'ja': '重複ツール'},
    'Duplicates list': {'fr': 'Liste des doublons', 'es': 'Lista de duplicados', 'de': 'Duplikatliste', 'it': 'Elenco duplicati', 'pt': 'Lista de duplicados', 'nl': 'Lijst met duplicaten', 'ca': 'Llista de duplicats', 'ro': 'Lista duplicatelor', 'bg': 'Списък с дубликати', 'el': 'Λίστα διπλοτύπων', 'ar': 'قائمة التكرارات', 'he': 'רשימת כפילויות', 'id': 'Daftar duplikat', 'ja': '重複リスト'},
    'Editing an unknown user': {'fr': 'Modification d\'un utilisateur inconnu', 'es': 'Editando un usuario desconocido', 'de': 'Bearbeitung eines unbekannten Benutzers', 'it': 'Modifica di un utente sconosciuto', 'pt': 'A editar um utilizador desconhecido', 'nl': 'Een onbekende gebruiker bewerken', 'ca': 'Editant un usuari desconegut', 'ro': 'Editare utilizator necunoscut', 'bg': 'Редактиране на неизвестен потребител', 'el': 'Επεξεργασία άγνωστου χρήστη', 'ar': 'تعديل مستخدم مجهول', 'he': 'עריכת משתמש לא ידוע', 'id': 'Mengedit pengguna tidak dikenal', 'ja': '不明なユーザーを編集'},
}

with open(os.path.join(DIR, 'en.json'), encoding='utf-8') as f:
    en = json.load(f)

total = 0
for lang in ['fr','es','it','pt','de','nl','ca','ro','bg','el','ar','he','id','ja']:
    path = os.path.join(DIR, f'{lang}.json')
    with open(path, encoding='utf-8') as f:
        d = json.load(f)
    n = 0
    for k, langs in T.items():
        if k in en and lang in langs and (k not in d or d[k] == en[k]):
            d[k] = langs[lang]; n += 1
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(dict(sorted(d.items())), f, ensure_ascii=False, indent=2)
    total += n
    print(f'{lang}: +{n}')
print(f'Total: {total}')
