# -*- coding: utf-8 -*-
import json, os
DIR = os.path.dirname(os.path.abspath(__file__))

T = {
    'End Page': {'fr': 'Page de fin', 'es': 'Página final', 'de': 'Endseite', 'it': 'Pagina finale', 'pt': 'Página final', 'nl': 'Eindpagina', 'ca': 'Pàgina final', 'ro': 'Pagina finală', 'bg': 'Крайна страница', 'el': 'Τελευταία σελίδα', 'ar': 'الصفحة الأخيرة', 'he': 'עמוד סיום', 'id': 'Halaman akhir', 'ja': '終了ページ'},
    'Enter a number': {'fr': 'Entrez un nombre', 'es': 'Introduce un número', 'de': 'Geben Sie eine Zahl ein', 'it': 'Inserisci un numero', 'pt': 'Introduza um número', 'nl': 'Voer een getal in', 'ca': 'Introduïu un nombre', 'ro': 'Introduceți un număr', 'bg': 'Въведете число', 'el': 'Εισάγετε αριθμό', 'ar': 'أدخل رقماً', 'he': 'הכנס מספר', 'id': 'Masukkan angka', 'ja': '数字を入力'},
    'Entrance icon': {'fr': 'Icône d\'entrée', 'es': 'Icono de entrada', 'de': 'Eingangssymbol', 'it': 'Icona ingresso', 'pt': 'Ícone de entrada', 'nl': 'Ingang icoon', 'ca': 'Icona d\'entrada', 'ro': 'Pictogramă intrare', 'bg': 'Икона на вход', 'el': 'Εικονίδιο εισόδου', 'ar': 'أيقونة المدخل', 'he': 'אייקון כניסה', 'id': 'Ikon pintu masuk', 'ja': '入口アイコン'},
    'Entrance list and available data quality': {'fr': 'Liste des entrées et qualité des données disponibles', 'es': 'Lista de entradas y calidad de datos disponibles', 'de': 'Eingangsliste und verfügbare Datenqualität', 'it': 'Elenco ingressi e qualità dei dati disponibili', 'pt': 'Lista de entradas e qualidade de dados disponíveis', 'nl': 'Ingangslijst en beschikbare datakwaliteit', 'ca': 'Llista d\'entrades i qualitat de dades disponibles', 'ro': 'Lista intrărilor și calitatea datelor disponibile', 'bg': 'Списък на входовете и качество на данните', 'el': 'Λίστα εισόδων και διαθέσιμη ποιότητα δεδομένων', 'ar': 'قائمة المداخل وجودة البيانات المتاحة', 'he': 'רשימת כניסות ואיכות נתונים זמינה', 'id': 'Daftar pintu masuk dan kualitas data yang tersedia', 'ja': '入口リストと利用可能なデータ品質'},
    'Entrance name language': {'fr': 'Langue du nom d\'entrée', 'es': 'Idioma del nombre de entrada', 'de': 'Sprache des Eingangsnamens', 'it': 'Lingua del nome dell\'ingresso', 'pt': 'Língua do nome da entrada', 'nl': 'Taal van de ingangsnaam', 'ca': 'Idioma del nom de l\'entrada', 'ro': 'Limba numelui intrării', 'bg': 'Език на името на входа', 'el': 'Γλώσσα ονόματος εισόδου', 'ar': 'لغة اسم المدخل', 'he': 'שפת שם הכניסה', 'id': 'Bahasa nama pintu masuk', 'ja': '入口名の言語'},
    'Entrance successfully moved from {initialCave} to {finalCave}!': {'fr': 'Entrée déplacée avec succès de {initialCave} vers {finalCave}!', 'es': '¡Entrada movida exitosamente de {initialCave} a {finalCave}!', 'de': 'Eingang erfolgreich von {initialCave} nach {finalCave} verschoben!', 'it': 'Ingresso spostato con successo da {initialCave} a {finalCave}!', 'pt': 'Entrada movida com sucesso de {initialCave} para {finalCave}!', 'nl': 'Ingang succesvol verplaatst van {initialCave} naar {finalCave}!', 'ca': 'Entrada moguda amb èxit de {initialCave} a {finalCave}!', 'ro': 'Intrarea mutată cu succes din {initialCave} în {finalCave}!', 'bg': 'Входът е преместен успешно от {initialCave} към {finalCave}!', 'el': 'Η είσοδος μετακινήθηκε επιτυχώς από {initialCave} σε {finalCave}!', 'ar': 'تم نقل المدخل بنجاح من {initialCave} إلى {finalCave}!', 'he': 'הכניסה הועברה בהצלחה מ-{initialCave} ל-{finalCave}!', 'id': 'Pintu masuk berhasil dipindahkan dari {initialCave} ke {finalCave}!', 'ja': '入口を{initialCave}から{finalCave}に正常に移動しました！'},
    'Error loading regions': {'fr': 'Erreur lors du chargement des régions', 'es': 'Error al cargar regiones', 'de': 'Fehler beim Laden der Regionen', 'it': 'Errore nel caricamento delle regioni', 'pt': 'Erro ao carregar regiões', 'nl': 'Fout bij laden van regio\'s', 'ca': 'Error en carregar les regions', 'ro': 'Eroare la încărcarea regiunilor', 'bg': 'Грешка при зареждане на регионите', 'el': 'Σφάλμα φόρτωσης περιοχών', 'ar': 'خطأ في تحميل المناطق', 'he': 'שגיאה בטעינת אזורים', 'id': 'Gagal memuat wilayah', 'ja': '地域の読み込みエラー'},
    'Error while updating the ban status': {'fr': 'Erreur lors de la mise à jour du statut de bannissement', 'es': 'Error al actualizar el estado de baneo', 'de': 'Fehler beim Aktualisieren des Sperrstatus', 'it': 'Errore durante l\'aggiornamento dello stato di ban', 'pt': 'Erro ao atualizar o estado de banimento', 'nl': 'Fout bij bijwerken van banstatus', 'ca': 'Error en actualitzar l\'estat de bloqueig', 'ro': 'Eroare la actualizarea stării de blocare', 'bg': 'Грешка при актуализиране на статуса на забраната', 'el': 'Σφάλμα κατά την ενημέρωση κατάστασης αποκλεισμού', 'ar': 'خطأ أثناء تحديث حالة الحظر', 'he': 'שגיאה בעדכון סטטוס החסימה', 'id': 'Kesalahan saat memperbarui status ban', 'ja': '禁止ステータス更新エラー'},
    'Error while updating the user groups': {'fr': 'Erreur lors de la mise à jour des groupes d\'utilisateurs', 'es': 'Error al actualizar los grupos de usuarios', 'de': 'Fehler beim Aktualisieren der Benutzergruppen', 'it': 'Errore durante l\'aggiornamento dei gruppi utente', 'pt': 'Erro ao atualizar os grupos de utilizadores', 'nl': 'Fout bij bijwerken van gebruikersgroepen', 'ca': 'Error en actualitzar els grups d\'usuaris', 'ro': 'Eroare la actualizarea grupurilor de utilizatori', 'bg': 'Грешка при актуализиране на потребителските групи', 'el': 'Σφάλμα κατά την ενημέρωση ομάδων χρηστών', 'ar': 'خطأ أثناء تحديث مجموعات المستخدمين', 'he': 'שגיאה בעדכון קבוצות המשתמש', 'id': 'Kesalahan saat memperbarui grup pengguna', 'ja': 'ユーザーグループ更新エラー'},
    'Error, the country data you are looking for is not available.': {'fr': 'Erreur, les données du pays que vous recherchez ne sont pas disponibles.', 'es': 'Error, los datos del país que busca no están disponibles.', 'de': 'Fehler, die Länderdaten, nach denen Sie suchen, sind nicht verfügbar.', 'it': 'Errore, i dati del paese che stai cercando non sono disponibili.', 'pt': 'Erro, os dados do país que procura não estão disponíveis.', 'nl': 'Fout, de landsgegevens die u zoekt zijn niet beschikbaar.', 'ca': 'Error, les dades del país que busqueu no estan disponibles.', 'ro': 'Eroare, datele țării pe care le căutați nu sunt disponibile.', 'bg': 'Грешка, данните за страната не са налични.', 'el': 'Σφάλμα, τα δεδομένα της χώρας που αναζητάτε δεν είναι διαθέσιμα.', 'ar': 'خطأ، بيانات البلد التي تبحث عنها غير متاحة.', 'he': 'שגיאה, נתוני המדינה שחיפשת אינם זמינים.', 'id': 'Kesalahan, data negara yang Anda cari tidak tersedia.', 'ja': 'エラー：お探しの国データは利用できません。'},
    'Error, the data you are looking for is not available.': {'fr': 'Erreur, les données que vous recherchez ne sont pas disponibles.', 'es': 'Error, los datos que busca no están disponibles.', 'de': 'Fehler, die gesuchten Daten sind nicht verfügbar.', 'it': 'Errore, i dati che stai cercando non sono disponibili.', 'pt': 'Erro, os dados que procura não estão disponíveis.', 'nl': 'Fout, de gegevens die u zoekt zijn niet beschikbaar.', 'ca': 'Error, les dades que busqueu no estan disponibles.', 'ro': 'Eroare, datele pe care le căutați nu sunt disponibile.', 'bg': 'Грешка, търсените данни не са налични.', 'el': 'Σφάλμα, τα δεδομένα που αναζητάτε δεν είναι διαθέσιμα.', 'ar': 'خطأ، البيانات التي تبحث عنها غير متاحة.', 'he': 'שגיאה, הנתונים שחיפשת אינם זמינים.', 'id': 'Kesalahan, data yang Anda cari tidak tersedia.', 'ja': 'エラー：お探しのデータは利用できません。'},
    'Error, the entrance data you are looking for is not available.': {'fr': 'Erreur, les données d\'entrée que vous recherchez ne sont pas disponibles.', 'es': 'Error, los datos de entrada que busca no están disponibles.', 'de': 'Fehler, die gesuchten Eingangsdaten sind nicht verfügbar.', 'it': 'Errore, i dati dell\'ingresso che stai cercando non sono disponibili.', 'pt': 'Erro, os dados da entrada que procura não estão disponíveis.', 'nl': 'Fout, de ingangsgegevens die u zoekt zijn niet beschikbaar.', 'ca': 'Error, les dades de l\'entrada que busqueu no estan disponibles.', 'ro': 'Eroare, datele intrării pe care le căutați nu sunt disponibile.', 'bg': 'Грешка, данните за входа не са налични.', 'el': 'Σφάλμα, τα δεδομένα εισόδου δεν είναι διαθέσιμα.', 'ar': 'خطأ، بيانات المدخل غير متاحة.', 'he': 'שגיאה, נתוני הכניסה אינם זמינים.', 'id': 'Kesalahan, data pintu masuk tidak tersedia.', 'ja': 'エラー：入口データは利用できません。'},
    'Error, the massif data you are looking for is not available.': {'fr': 'Erreur, les données du massif que vous recherchez ne sont pas disponibles.', 'es': 'Error, los datos del macizo que busca no están disponibles.', 'de': 'Fehler, die gesuchten Massivdaten sind nicht verfügbar.', 'it': 'Errore, i dati del massiccio non sono disponibili.', 'pt': 'Erro, os dados do maciço não estão disponíveis.', 'nl': 'Fout, de massiefsgegevens zijn niet beschikbaar.', 'ca': 'Error, les dades del massís no estan disponibles.', 'ro': 'Eroare, datele masivului nu sunt disponibile.', 'bg': 'Грешка, данните за масива не са налични.', 'el': 'Σφάλμα, τα δεδομένα του ογκόλιθου δεν είναι διαθέσιμα.', 'ar': 'خطأ، بيانات الكتلة الجبلية غير متاحة.', 'he': 'שגיאה, נתוני המסיף אינם זמינים.', 'id': 'Kesalahan, data massif tidak tersedia.', 'ja': 'エラー：マッシーフデータは利用できません。'},
    'Error, the organization data you are looking for is not available.': {'fr': 'Erreur, les données de l\'organisation ne sont pas disponibles.', 'es': 'Error, los datos de la organización no están disponibles.', 'de': 'Fehler, die Organisationsdaten sind nicht verfügbar.', 'it': 'Errore, i dati dell\'organizzazione non sono disponibili.', 'pt': 'Erro, os dados da organização não estão disponíveis.', 'nl': 'Fout, de organisatiegegevens zijn niet beschikbaar.', 'ca': 'Error, les dades de l\'organització no estan disponibles.', 'ro': 'Eroare, datele organizației nu sunt disponibile.', 'bg': 'Грешка, данните за организацията не са налични.', 'el': 'Σφάλμα, τα δεδομένα οργανισμού δεν είναι διαθέσιμα.', 'ar': 'خطأ، بيانات المنظمة غير متاحة.', 'he': 'שגיאה, נתוני הארגון אינם זמינים.', 'id': 'Kesalahan, data organisasi tidak tersedia.', 'ja': 'エラー：組織データは利用できません。'},
    'Error, the person you are looking for is not available.': {'fr': 'Erreur, la personne que vous recherchez n\'est pas disponible.', 'es': 'Error, la persona que busca no está disponible.', 'de': 'Fehler, die gesuchte Person ist nicht verfügbar.', 'it': 'Errore, la persona che stai cercando non è disponibile.', 'pt': 'Erro, a pessoa que procura não está disponível.', 'nl': 'Fout, de persoon die u zoekt is niet beschikbaar.', 'ca': 'Error, la persona que busqueu no està disponible.', 'ro': 'Eroare, persoana căutată nu este disponibilă.', 'bg': 'Грешка, търсеното лице не е налично.', 'el': 'Σφάλμα, το άτομο που αναζητάτε δεν είναι διαθέσιμο.', 'ar': 'خطأ، الشخص الذي تبحث عنه غير متاح.', 'he': 'שגיאה, האדם שחיפשת אינו זמין.', 'id': 'Kesalahan, orang yang Anda cari tidak tersedia.', 'ja': 'エラー：お探しの人物データは利用できません。'},
    'Explored caves': {'fr': 'Cavités explorées', 'es': 'Cuevas exploradas', 'de': 'Erkundete Höhlen', 'it': 'Grotte esplorate', 'pt': 'Cavernas exploradas', 'nl': 'Verkennen grotten', 'ca': 'Coves explorades', 'ro': 'Peșteri explorate', 'bg': 'Изследвани пещери', 'el': 'Εξερευνημένα σπήλαια', 'ar': 'الكهوف المستكشفة', 'he': 'מערות שנחקרו', 'id': 'Gua yang dijelajahi', 'ja': '探検済み洞窟'},
    'Explored entrances': {'fr': 'Entrées explorées', 'es': 'Entradas exploradas', 'de': 'Erkundete Eingänge', 'it': 'Ingressi esplorati', 'pt': 'Entradas exploradas', 'nl': 'Verkennen ingangen', 'ca': 'Entrades explorades', 'ro': 'Intrări explorate', 'bg': 'Изследвани входове', 'el': 'Εξερευνημένες είσοδοι', 'ar': 'المداخل المستكشفة', 'he': 'כניסות שנחקרו', 'id': 'Pintu masuk yang dijelajahi', 'ja': '探検済み入口'},
    'Explored networks': {'fr': 'Réseaux explorés', 'es': 'Redes exploradas', 'de': 'Erkundete Netzwerke', 'it': 'Reti esplorate', 'pt': 'Redes exploradas', 'nl': 'Verkennen netwerken', 'ca': 'Xarxes explorades', 'ro': 'Rețele explorate', 'bg': 'Изследвани мрежи', 'el': 'Εξερευνημένα δίκτυα', 'ar': 'الشبكات المستكشفة', 'he': 'רשתות שנחקרו', 'id': 'Jaringan yang dijelajahi', 'ja': '探検済みネットワーク'},
    'Export to CSV': {'fr': 'Exporter en CSV', 'es': 'Exportar a CSV', 'de': 'Als CSV exportieren', 'it': 'Esporta in CSV', 'pt': 'Exportar para CSV', 'nl': 'Exporteren naar CSV', 'ca': 'Exportar a CSV', 'ro': 'Exportați în CSV', 'bg': 'Експортиране в CSV', 'el': 'Εξαγωγή σε CSV', 'ar': 'تصدير إلى CSV', 'he': 'ייצוא ל-CSV', 'id': 'Ekspor ke CSV', 'ja': 'CSVにエクスポート'},
    'Flooding risk': {'fr': 'Risque d\'inondation', 'es': 'Riesgo de inundación', 'de': 'Überschwemmungsrisiko', 'it': 'Rischio di inondazione', 'pt': 'Risco de inundação', 'nl': 'Overstromingsrisico', 'ca': 'Risc d\'inundació', 'ro': 'Risc de inundație', 'bg': 'Риск от наводнение', 'el': 'Κίνδυνος πλημμύρας', 'ar': 'خطر الفيضانات', 'he': 'סיכון הצפה', 'id': 'Risiko banjir', 'ja': '洪水リスク'},
    'For security reasons please create a new password.': {'fr': 'Pour des raisons de sécurité, veuillez créer un nouveau mot de passe.', 'es': 'Por razones de seguridad, por favor crea una nueva contraseña.', 'de': 'Bitte erstellen Sie aus Sicherheitsgründen ein neues Passwort.', 'it': 'Per motivi di sicurezza, crea una nuova password.', 'pt': 'Por razões de segurança, crie uma nova palavra-passe.', 'nl': 'Maak om veiligheidsredenen een nieuw wachtwoord.', 'ca': 'Per raons de seguretat, creeu una nova contrasenya.', 'ro': 'Din motive de securitate, creați o nouă parolă.', 'bg': 'По съображения за сигурност, моля създайте нова парола.', 'el': 'Για λόγους ασφαλείας δημιουργήστε νέο κωδικό.', 'ar': 'لأسباب أمنية، يرجى إنشاء كلمة مرور جديدة.', 'he': 'מסיבות אבטחה, אנא צור סיסמה חדשה.', 'id': 'Untuk alasan keamanan, buat kata sandi baru.', 'ja': 'セキュリティのため、新しいパスワードを作成してください。'},
}

with open(os.path.join(DIR, 'en.json'), encoding='utf-8') as f:
    en = json.load(f)

total = 0
for lang in ['fr','es','it','pt','de','nl','ca','ro','bg','el','ar','he','id','ja']:
    path = os.path.join(DIR, f'{lang}.json')
    with open(path, encoding='utf-8') as f:
        d = json.load(f)
    n = 0
    for k, langs in T.items():
        if k in en and lang in langs and (k not in d or d[k] == en[k]):
            d[k] = langs[lang]; n += 1
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(dict(sorted(d.items())), f, ensure_ascii=False, indent=2)
    total += n
    print(f'{lang}: +{n}')
print(f'Total: {total}')
