# -*- coding: utf-8 -*-
import json, os
DIR = os.path.dirname(os.path.abspath(__file__))

T = {
    'Forgot password?': {'fr': 'Mot de passe oublié ?', 'es': '¿Olvidaste tu contraseña?', 'de': 'Passwort vergessen?', 'it': 'Password dimenticata?', 'pt': 'Esqueceu a palavra-passe?', 'nl': 'Wachtwoord vergeten?', 'ca': 'Has oblidat la contrasenya?', 'ro': 'Ați uitat parola?', 'bg': 'Забравена парола?', 'el': 'Ξεχάσατε τον κωδικό;', 'ar': 'هل نسيت كلمة المرور؟', 'he': 'שכחת סיסמה?', 'id': 'Lupa kata sandi?', 'ja': 'パスワードを忘れましたか？'},
    'General Information': {'fr': 'Informations générales', 'es': 'Información general', 'de': 'Allgemeine Informationen', 'it': 'Informazioni generali', 'pt': 'Informações gerais', 'nl': 'Algemene informatie', 'ca': 'Informació general', 'ro': 'Informații generale', 'bg': 'Обща информация', 'el': 'Γενικές πληροφορίες', 'ar': 'معلومات عامة', 'he': 'מידע כללי', 'id': 'Informasi umum', 'ja': '一般情報'},
    'Go back': {'fr': 'Retour', 'es': 'Volver', 'de': 'Zurück', 'it': 'Torna indietro', 'pt': 'Voltar', 'nl': 'Terug', 'ca': 'Torna enrere', 'ro': 'Înapoi', 'bg': 'Назад', 'el': 'Πίσω', 'ar': 'رجوع', 'he': 'חזור', 'id': 'Kembali', 'ja': '戻る'},
    'Go back to user profile': {'fr': 'Retourner au profil utilisateur', 'es': 'Volver al perfil de usuario', 'de': 'Zurück zum Benutzerprofil', 'it': 'Torna al profilo utente', 'pt': 'Voltar ao perfil do utilizador', 'nl': 'Terug naar gebruikersprofiel', 'ca': 'Torna al perfil d\'usuari', 'ro': 'Înapoi la profilul utilizatorului', 'bg': 'Върни се към потребителския профил', 'el': 'Επιστροφή στο προφίλ χρήστη', 'ar': 'العودة إلى ملف المستخدم', 'he': 'חזור לפרופיל המשתמש', 'id': 'Kembali ke profil pengguna', 'ja': 'ユーザープロフィールに戻る'},
    'Go to home page': {'fr': 'Aller à la page d\'accueil', 'es': 'Ir a la página de inicio', 'de': 'Zur Startseite gehen', 'it': 'Vai alla pagina principale', 'pt': 'Ir para a página inicial', 'nl': 'Ga naar de startpagina', 'ca': 'Anar a la pàgina d\'inici', 'ro': 'Mergeți la pagina de start', 'bg': 'Отиди на началната страница', 'el': 'Μεταβείτε στην αρχική σελίδα', 'ar': 'اذهب إلى الصفحة الرئيسية', 'he': 'עבור לדף הבית', 'id': 'Pergi ke halaman beranda', 'ja': 'ホームページへ'},
    'Groups updated with success!': {'fr': 'Groupes mis à jour avec succès !', 'es': '¡Grupos actualizados con éxito!', 'de': 'Gruppen erfolgreich aktualisiert!', 'it': 'Gruppi aggiornati con successo!', 'pt': 'Grupos atualizados com sucesso!', 'nl': 'Groepen succesvol bijgewerkt!', 'ca': 'Grups actualitzats amb èxit!', 'ro': 'Grupurile au fost actualizate cu succes!', 'bg': 'Групите са актуализирани успешно!', 'el': 'Οι ομάδες ενημερώθηκαν επιτυχώς!', 'ar': 'تم تحديث المجموعات بنجاح!', 'he': 'הקבוצות עודכנו בהצלחה!', 'id': 'Grup berhasil diperbarui!', 'ja': 'グループが正常に更新されました！'},
    'Has siphons': {'fr': 'Possède des siphons', 'es': 'Tiene sifones', 'de': 'Hat Siphons', 'it': 'Ha sifoni', 'pt': 'Tem sifões', 'nl': 'Heeft sifons', 'ca': 'Té sifons', 'ro': 'Are sifonuri', 'bg': 'Има сифони', 'el': 'Έχει σίφωνες', 'ar': 'يحتوي على سيفونات', 'he': 'יש סיפונים', 'id': 'Memiliki sifon', 'ja': 'サイフォンあり'},
    'Hidden columns': {'fr': 'Colonnes cachées', 'es': 'Columnas ocultas', 'de': 'Ausgeblendete Spalten', 'it': 'Colonne nascoste', 'pt': 'Colunas ocultas', 'nl': 'Verborgen kolommen', 'ca': 'Columnes ocultes', 'ro': 'Coloane ascunse', 'bg': 'Скрити колони', 'el': 'Κρυφές στήλες', 'ar': 'الأعمدة المخفية', 'he': 'עמודות מוסתרות', 'id': 'Kolom tersembunyi', 'ja': '非表示列'},
    'Hide from map': {'fr': 'Masquer de la carte', 'es': 'Ocultar del mapa', 'de': 'Von der Karte ausblenden', 'it': 'Nascondi dalla mappa', 'pt': 'Ocultar do mapa', 'nl': 'Verbergen op kaart', 'ca': 'Amagar del mapa', 'ro': 'Ascundeți de pe hartă', 'bg': 'Скрий от картата', 'el': 'Απόκρυψη από χάρτη', 'ar': 'إخفاء من الخريطة', 'he': 'הסתר מהמפה', 'id': 'Sembunyikan dari peta', 'ja': '地図から非表示'},
    'Home page': {'fr': 'Page d\'accueil', 'es': 'Página de inicio', 'de': 'Startseite', 'it': 'Pagina principale', 'pt': 'Página inicial', 'nl': 'Startpagina', 'ca': 'Pàgina d\'inici', 'ro': 'Pagina de start', 'bg': 'Начална страница', 'el': 'Αρχική σελίδα', 'ar': 'الصفحة الرئيسية', 'he': 'דף הבית', 'id': 'Halaman beranda', 'ja': 'ホームページ'},
    'ISO 3166-2 codes (eg: FR-OCC)': {'fr': 'Codes ISO 3166-2 (ex : FR-OCC)', 'es': 'Códigos ISO 3166-2 (ej: FR-OCC)', 'de': 'ISO 3166-2 Codes (z.B.: FR-OCC)', 'it': 'Codici ISO 3166-2 (es: FR-OCC)', 'pt': 'Códigos ISO 3166-2 (ex: FR-OCC)', 'nl': 'ISO 3166-2 codes (bv: FR-OCC)', 'ca': 'Codis ISO 3166-2 (ex: FR-OCC)', 'ro': 'Coduri ISO 3166-2 (ex: FR-OCC)', 'bg': 'Кодове ISO 3166-2 (напр. FR-OCC)', 'el': 'Κωδικοί ISO 3166-2 (π.χ.: FR-OCC)', 'ar': 'رموز ISO 3166-2 (مثال: FR-OCC)', 'he': 'קודי ISO 3166-2 (לדוגמה: FR-OCC)', 'id': 'Kode ISO 3166-2 (mis: FR-OCC)', 'ja': 'ISO 3166-2コード（例：FR-OCC）'},
    'Identifier Type': {'fr': 'Type d\'identifiant', 'es': 'Tipo de identificador', 'de': 'Identifikatortyp', 'it': 'Tipo di identificatore', 'pt': 'Tipo de identificador', 'nl': 'Identificatortype', 'ca': 'Tipus d\'identificador', 'ro': 'Tip de identificator', 'bg': 'Тип идентификатор', 'el': 'Τύπος αναγνωριστικού', 'ar': 'نوع المعرّف', 'he': 'סוג מזהה', 'id': 'Jenis pengidentifikasi', 'ja': '識別子タイプ'},
    'If you click YES, the content of this revision will be saved as the new current revision.': {'fr': 'Si vous cliquez sur OUI, le contenu de cette révision sera enregistré comme la nouvelle révision actuelle.', 'es': 'Si hace clic en SÍ, el contenido de esta revisión se guardará como la nueva revisión actual.', 'de': 'Wenn Sie auf JA klicken, wird der Inhalt dieser Revision als neue aktuelle Revision gespeichert.', 'it': 'Se fai clic su SÌ, il contenuto di questa revisione verrà salvato come nuova revisione corrente.', 'pt': 'Se clicar em SIM, o conteúdo desta revisão será guardado como a nova revisão atual.', 'nl': 'Als u op JA klikt, wordt de inhoud van deze revisie opgeslagen als de nieuwe huidige revisie.', 'ca': 'Si feu clic a SÍ, el contingut d\'aquesta revisió es desarà com a nova revisió actual.', 'ro': 'Dacă faceți clic pe DA, conținutul acestei revizuiri va fi salvat ca noua revizuire curentă.', 'bg': 'Ако кликнете ДА, съдържанието на тази ревизия ще бъде запазено като новата текуща ревизия.', 'el': 'Εάν κάνετε κλικ ΝΑΙ, το περιεχόμενο αυτής της αναθεώρησης θα αποθηκευτεί ως η νέα τρέχουσα αναθεώρηση.', 'ar': 'إذا نقرت على نعم، سيتم حفظ محتوى هذه المراجعة كمراجعة حالية جديدة.', 'he': 'אם תלחץ כן, תוכן הגרסה הזו יישמר כגרסה הנוכחית החדשה.', 'id': 'Jika Anda mengklik YA, konten revisi ini akan disimpan sebagai revisi saat ini yang baru.', 'ja': 'はいをクリックすると、このリビジョンの内容が新しい現在のリビジョンとして保存されます。'},
    'If you leave now, some data would be lost. Are you sure you want to leave this page?': {'fr': 'Si vous partez maintenant, certaines données seront perdues. Êtes-vous sûr de vouloir quitter cette page ?', 'es': 'Si sale ahora, se perderán algunos datos. ¿Está seguro de que desea salir de esta página?', 'de': 'Wenn Sie jetzt gehen, gehen einige Daten verloren. Sind Sie sicher, dass Sie diese Seite verlassen möchten?', 'it': 'Se esci ora, alcuni dati andranno persi. Sei sicuro di voler lasciare questa pagina?', 'pt': 'Se sair agora, alguns dados serão perdidos. Tem a certeza que quer sair desta página?', 'nl': 'Als u nu vertrekt, gaan sommige gegevens verloren. Weet u zeker dat u deze pagina wilt verlaten?', 'ca': 'Si sortiu ara, es perdran algunes dades. Esteu segurs que voleu sortir d\'aquesta pàgina?', 'ro': 'Dacă plecați acum, unele date vor fi pierdute. Sigur doriți să părăsiți această pagină?', 'bg': 'Ако напуснете сега, някои данни ще бъдат загубени. Сигурни ли сте, че искате да напуснете?', 'el': 'Εάν φύγετε τώρα, κάποια δεδομένα θα χαθούν. Είστε σίγουροι;', 'ar': 'إذا غادرت الآن، ستفقد بعض البيانات. هل أنت متأكد من أنك تريد مغادرة هذه الصفحة؟', 'he': 'אם תצא עכשיו, חלק מהנתונים יאבדו. האם אתה בטוח שברצונך לעזוב דף זה?', 'id': 'Jika Anda pergi sekarang, beberapa data akan hilang. Anda yakin ingin meninggalkan halaman ini?', 'ja': '今ページを離れると一部のデータが失われます。このページを離れてよろしいですか？'},
    'Import Shapefile': {'fr': 'Importer un Shapefile', 'es': 'Importar Shapefile', 'de': 'Shapefile importieren', 'it': 'Importa Shapefile', 'pt': 'Importar Shapefile', 'nl': 'Shapefile importeren', 'ca': 'Importar Shapefile', 'ro': 'Importați Shapefile', 'bg': 'Импортиране на Shapefile', 'el': 'Εισαγωγή Shapefile', 'ar': 'استيراد ملف الشكل', 'he': 'ייבוא Shapefile', 'id': 'Impor Shapefile', 'ja': 'シェープファイルをインポート'},
    'In meters': {'fr': 'En mètres', 'es': 'En metros', 'de': 'In Metern', 'it': 'In metri', 'pt': 'Em metros', 'nl': 'In meters', 'ca': 'En metres', 'ro': 'În metri', 'bg': 'В метри', 'el': 'Σε μέτρα', 'ar': 'بالأمتار', 'he': 'במטרים', 'id': 'Dalam meter', 'ja': 'メートル単位'},
    'Invalid Date Format': {'fr': 'Format de date invalide', 'es': 'Formato de fecha inválido', 'de': 'Ungültiges Datumsformat', 'it': 'Formato data non valido', 'pt': 'Formato de data inválido', 'nl': 'Ongeldig datumformaat', 'ca': 'Format de data no vàlid', 'ro': 'Format dată invalid', 'bg': 'Невалиден формат на датата', 'el': 'Μη έγκυρη μορφή ημερομηνίας', 'ar': 'تنسيق التاريخ غير صالح', 'he': 'פורמט תאריך לא תקין', 'id': 'Format tanggal tidak valid', 'ja': '無効な日付形式'},
    'Invalid email or password.': {'fr': 'Email ou mot de passe invalide.', 'es': 'Correo electrónico o contraseña no válidos.', 'de': 'Ungültige E-Mail oder ungültiges Passwort.', 'it': 'Email o password non validi.', 'pt': 'Email ou palavra-passe inválidos.', 'nl': 'Ongeldig e-mailadres of wachtwoord.', 'ca': 'Correu electrònic o contrasenya no vàlids.', 'ro': 'Email sau parolă invalide.', 'bg': 'Невалиден имейл или парола.', 'el': 'Μη έγκυρο email ή κωδικός.', 'ar': 'البريد الإلكتروني أو كلمة المرور غير صالحة.', 'he': 'אימייל או סיסמה לא תקינים.', 'id': 'Email atau kata sandi tidak valid.', 'ja': 'メールまたはパスワードが無効です。'},
    'Join Grottocenter': {'fr': 'Rejoindre GrottoCenter', 'es': 'Unirse a GrottoCenter', 'de': 'GrottoCenter beitreten', 'it': 'Unisciti a GrottoCenter', 'pt': 'Juntar-se ao GrottoCenter', 'nl': 'GrottoCenter aansluiten', 'ca': 'Unir-se a GrottoCenter', 'ro': 'Alăturați-vă GrottoCenter', 'bg': 'Присъединете се към GrottoCenter', 'el': 'Εγγραφείτε στο GrottoCenter', 'ar': 'انضم إلى GrottoCenter', 'he': 'הצטרף ל-GrottoCenter', 'id': 'Bergabung dengan GrottoCenter', 'ja': 'GrottoCenterに参加'},
    'Last update': {'fr': 'Dernière mise à jour', 'es': 'Última actualización', 'de': 'Letzte Aktualisierung', 'it': 'Ultimo aggiornamento', 'pt': 'Última atualização', 'nl': 'Laatste update', 'ca': 'Última actualització', 'ro': 'Ultima actualizare', 'bg': 'Последна актуализация', 'el': 'Τελευταία ενημέρωση', 'ar': 'آخر تحديث', 'he': 'עדכון אחרון', 'id': 'Pembaruan terakhir', 'ja': '最終更新'},
    'License in files': {'fr': 'Licence dans les fichiers', 'es': 'Licencia en los archivos', 'de': 'Lizenz in den Dateien', 'it': 'Licenza nei file', 'pt': 'Licença nos ficheiros', 'nl': 'Licentie in bestanden', 'ca': 'Llicència als fitxers', 'ro': 'Licența în fișiere', 'bg': 'Лиценз в файловете', 'el': 'Άδεια στα αρχεία', 'ar': 'الترخيص في الملفات', 'he': 'רישיון בקבצים', 'id': 'Lisensi dalam file', 'ja': 'ファイル内のライセンス'},
    'License type': {'fr': 'Type de licence', 'es': 'Tipo de licencia', 'de': 'Lizenztyp', 'it': 'Tipo di licenza', 'pt': 'Tipo de licença', 'nl': 'Licentietype', 'ca': 'Tipus de llicència', 'ro': 'Tip de licență', 'bg': 'Тип лиценз', 'el': 'Τύπος άδειας', 'ar': 'نوع الترخيص', 'he': 'סוג רישיון', 'id': 'Jenis lisensi', 'ja': 'ライセンスタイプ'},
}

with open(os.path.join(DIR, 'en.json'), encoding='utf-8') as f:
    en = json.load(f)

total = 0
for lang in ['fr','es','it','pt','de','nl','ca','ro','bg','el','ar','he','id','ja']:
    path = os.path.join(DIR, f'{lang}.json')
    with open(path, encoding='utf-8') as f:
        d = json.load(f)
    n = 0
    for k, langs in T.items():
        if k in en and lang in langs and (k not in d or d[k] == en[k]):
            d[k] = langs[lang]; n += 1
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(dict(sorted(d.items())), f, ensure_ascii=False, indent=2)
    total += n
    print(f'{lang}: +{n}')
print(f'Total: {total}')
