# -*- coding: utf-8 -*-
import json, os
DIR = os.path.dirname(os.path.abspath(__file__))

T = {
    'List of administrators': {'fr': 'Liste des administrateurs', 'es': 'Lista de administradores', 'de': 'Liste der Administratoren', 'it': 'Elenco degli amministratori', 'pt': 'Lista de administradores', 'nl': 'Lijst van beheerders', 'ca': 'Llista d\'administradors', 'ro': 'Lista administratorilor', 'bg': 'Списък на администраторите', 'el': 'Λίστα διαχειριστών', 'ar': 'قائمة المديرين', 'he': 'רשימת מנהלים', 'id': 'Daftar administrator', 'ja': '管理者リスト'},
    'List of banned cavers': {'fr': 'Liste des spéléologues bannis', 'es': 'Lista de espeleólogos baneados', 'de': 'Liste gesperrter Höhlenforscher', 'it': 'Elenco degli speleologi bannati', 'pt': 'Lista de espeleólogos banidos', 'nl': 'Lijst van verbannen speleologen', 'ca': 'Llista d\'espeleòlegs bannejats', 'ro': 'Lista speologilor blocați', 'bg': 'Списък на забранените спелеолози', 'el': 'Λίστα αποκλεισμένων σπηλαιολόγων', 'ar': 'قائمة المستكشفين المحظورين', 'he': 'רשימת חשפנים חסומים', 'id': 'Daftar penjelajah gua yang diblokir', 'ja': 'BANされた洞窟探検家リスト'},
    'List of explored caves': {'fr': 'Liste des cavités explorées', 'es': 'Lista de cuevas exploradas', 'de': 'Liste erkundeter Höhlen', 'it': 'Elenco delle grotte esplorate', 'pt': 'Lista de cavernas exploradas', 'nl': 'Lijst van verkennen grotten', 'ca': 'Llista de coves explorades', 'ro': 'Lista peșterilor explorate', 'bg': 'Списък на изследваните пещери', 'el': 'Λίστα εξερευνημένων σπηλαίων', 'ar': 'قائمة الكهوف المستكشفة', 'he': 'רשימת מערות שנחקרו', 'id': 'Daftar gua yang dijelajahi', 'ja': '探検済み洞窟リスト'},
    'List of leaders': {'fr': 'Liste des responsables', 'es': 'Lista de líderes', 'de': 'Liste der Leiter', 'it': 'Elenco dei responsabili', 'pt': 'Lista de líderes', 'nl': 'Lijst van leiders', 'ca': 'Llista de líders', 'ro': 'Lista liderilor', 'bg': 'Списък на ръководителите', 'el': 'Λίστα αρχηγών', 'ar': 'قائمة القادة', 'he': 'רשימת מנהיגים', 'id': 'Daftar pemimpin', 'ja': 'リーダーリスト'},
    'List of moderators': {'fr': 'Liste des modérateurs', 'es': 'Lista de moderadores', 'de': 'Liste der Moderatoren', 'it': 'Elenco dei moderatori', 'pt': 'Lista de moderadores', 'nl': 'Lijst van moderatoren', 'ca': 'Llista de moderadors', 'ro': 'Lista moderatorilor', 'bg': 'Списък на модераторите', 'el': 'Λίστα διαμεσολαβητών', 'ar': 'قائمة المشرفين', 'he': 'רשימת מנחים', 'id': 'Daftar moderator', 'ja': 'モデレーターリスト'},
    'Load more': {'fr': 'Charger plus', 'es': 'Cargar más', 'de': 'Mehr laden', 'it': 'Carica altro', 'pt': 'Carregar mais', 'nl': 'Meer laden', 'ca': 'Carrega més', 'ro': 'Încarcați mai mult', 'bg': 'Зареди повече', 'el': 'Φόρτωση περισσότερων', 'ar': 'تحميل المزيد', 'he': 'טען עוד', 'id': 'Muat lebih banyak', 'ja': 'もっと読み込む'},
    'Loading ...': {'fr': 'Chargement...', 'es': 'Cargando...', 'de': 'Wird geladen...', 'it': 'Caricamento...', 'pt': 'A carregar...', 'nl': 'Laden...', 'ca': 'Carregant...', 'ro': 'Se încarcă...', 'bg': 'Зареждане...', 'el': 'Φόρτωση...', 'ar': 'جارٍ التحميل...', 'he': 'טוען...', 'id': 'Memuat...', 'ja': '読み込み中...'},
    'Loading entrances...': {'fr': 'Chargement des entrées...', 'es': 'Cargando entradas...', 'de': 'Eingänge werden geladen...', 'it': 'Caricamento ingressi...', 'pt': 'A carregar entradas...', 'nl': 'Ingangen laden...', 'ca': 'Carregant entrades...', 'ro': 'Se încarcă intrările...', 'bg': 'Зареждане на входове...', 'el': 'Φόρτωση εισόδων...', 'ar': 'جارٍ تحميل المداخل...', 'he': 'טוען כניסות...', 'id': 'Memuat pintu masuk...', 'ja': '入口を読み込み中...'},
    'Loading full data, please wait...': {'fr': 'Chargement des données complètes, veuillez patienter...', 'es': 'Cargando datos completos, por favor espere...', 'de': 'Vollständige Daten werden geladen, bitte warten...', 'it': 'Caricamento dati completi, attendere...', 'pt': 'A carregar dados completos, aguarde...', 'nl': 'Volledige gegevens laden, even geduld...', 'ca': 'Carregant dades completes, espereu...', 'ro': 'Se încarcă datele complete, vă rugăm așteptați...', 'bg': 'Зареждане на пълни данни, моля изчакайте...', 'el': 'Φόρτωση πλήρων δεδομένων, παρακαλώ περιμένετε...', 'ar': 'جارٍ تحميل البيانات الكاملة، يرجى الانتظار...', 'he': 'טוען נתונים מלאים, אנא המתן...', 'id': 'Memuat data lengkap, harap tunggu...', 'ja': 'すべてのデータを読み込み中、しばらくお待ちください...'},
    'Loading massif data...': {'fr': 'Chargement des données du massif...', 'es': 'Cargando datos del macizo...', 'de': 'Massivdaten werden geladen...', 'it': 'Caricamento dati massiccio...', 'pt': 'A carregar dados do maciço...', 'nl': 'Massiefsgegevens laden...', 'ca': 'Carregant dades del massís...', 'ro': 'Se încarcă datele masivului...', 'bg': 'Зареждане на данни за масива...', 'el': 'Φόρτωση δεδομένων ογκόλιθου...', 'ar': 'جارٍ تحميل بيانات الكتلة الجبلية...', 'he': 'טוען נתוני מסיף...', 'id': 'Memuat data massif...', 'ja': 'マッシーフデータを読み込み中...'},
    'Loading the organization data...': {'fr': 'Chargement des données de l\'organisation...', 'es': 'Cargando datos de la organización...', 'de': 'Organisationsdaten werden geladen...', 'it': 'Caricamento dati organizzazione...', 'pt': 'A carregar dados da organização...', 'nl': 'Organisatiegegevens laden...', 'ca': 'Carregant dades de l\'organització...', 'ro': 'Se încarcă datele organizației...', 'bg': 'Зареждане на данни за организацията...', 'el': 'Φόρτωση δεδομένων οργανισμού...', 'ar': 'جارٍ تحميل بيانات المنظمة...', 'he': 'טוען נתוני ארגון...', 'id': 'Memuat data organisasi...', 'ja': '組織データを読み込み中...'},
    'Log in': {'fr': 'Se connecter', 'es': 'Iniciar sesión', 'de': 'Anmelden', 'it': 'Accedi', 'pt': 'Entrar', 'nl': 'Inloggen', 'ca': 'Iniciar sessió', 'ro': 'Autentificare', 'bg': 'Влизане', 'el': 'Σύνδεση', 'ar': 'تسجيل الدخول', 'he': 'התחבר', 'id': 'Masuk', 'ja': 'ログイン'},
    'Log in to activate the editor mode.': {'fr': 'Connectez-vous pour activer le mode éditeur.', 'es': 'Inicia sesión para activar el modo editor.', 'de': 'Melden Sie sich an, um den Editormodus zu aktivieren.', 'it': 'Accedi per attivare la modalità editor.', 'pt': 'Inicie sessão para ativar o modo editor.', 'nl': 'Log in om de editormodus te activeren.', 'ca': 'Inicieu sessió per activar el mode editor.', 'ro': 'Autentificați-vă pentru a activa modul editor.', 'bg': 'Влезте, за да активирате режима на редактор.', 'el': 'Συνδεθείτε για να ενεργοποιήσετε τη λειτουργία επεξεργαστή.', 'ar': 'قم بتسجيل الدخول لتفعيل وضع المحرر.', 'he': 'התחבר כדי להפעיל מצב עריכה.', 'id': 'Masuk untuk mengaktifkan mode editor.', 'ja': 'エディターモードを有効にするにはログインしてください。'},
    'Log out': {'fr': 'Se déconnecter', 'es': 'Cerrar sesión', 'de': 'Abmelden', 'it': 'Disconnetti', 'pt': 'Sair', 'nl': 'Uitloggen', 'ca': 'Tancar sessió', 'ro': 'Deconectare', 'bg': 'Излизане', 'el': 'Αποσύνδεση', 'ar': 'تسجيل الخروج', 'he': 'התנתק', 'id': 'Keluar', 'ja': 'ログアウト'},
    'Manage Users': {'fr': 'Gérer les utilisateurs', 'es': 'Gestionar usuarios', 'de': 'Benutzer verwalten', 'it': 'Gestisci utenti', 'pt': 'Gerir utilizadores', 'nl': 'Gebruikers beheren', 'ca': 'Gestionar usuaris', 'ro': 'Gestionați utilizatorii', 'bg': 'Управление на потребителите', 'el': 'Διαχείριση χρηστών', 'ar': 'إدارة المستخدمين', 'he': 'נהל משתמשים', 'id': 'Kelola pengguna', 'ja': 'ユーザー管理'},
    'Merge and permanently delete': {'fr': 'Fusionner et supprimer définitivement', 'es': 'Fusionar y eliminar permanentemente', 'de': 'Zusammenführen und dauerhaft löschen', 'it': 'Unisci ed elimina definitivamente', 'pt': 'Mesclar e eliminar permanentemente', 'nl': 'Samenvoegen en permanent verwijderen', 'ca': 'Fusiona i elimina permanentment', 'ro': 'Îmbinați și ștergeți definitiv', 'bg': 'Слей и изтрий окончателно', 'el': 'Συγχώνευση και μόνιμη διαγραφή', 'ar': 'دمج وحذف نهائي', 'he': 'מזג ומחק לצמיתות', 'id': 'Gabungkan dan hapus permanen', 'ja': 'マージして完全に削除'},
    'Modification completed': {'fr': 'Modification terminée', 'es': 'Modificación completada', 'de': 'Änderung abgeschlossen', 'it': 'Modifica completata', 'pt': 'Modificação concluída', 'nl': 'Wijziging voltooid', 'ca': 'Modificació completada', 'ro': 'Modificare finalizată', 'bg': 'Модификацията е завършена', 'el': 'Η τροποποίηση ολοκληρώθηκε', 'ar': 'اكتمل التعديل', 'he': 'השינוי הושלם', 'id': 'Modifikasi selesai', 'ja': '変更完了'},
    'Modifications summary': {'fr': 'Résumé des modifications', 'es': 'Resumen de modificaciones', 'de': 'Zusammenfassung der Änderungen', 'it': 'Riepilogo delle modifiche', 'pt': 'Resumo das modificações', 'nl': 'Samenvatting wijzigingen', 'ca': 'Resum de les modificacions', 'ro': 'Rezumatul modificărilor', 'bg': 'Резюме на промените', 'el': 'Περίληψη τροποποιήσεων', 'ar': 'ملخص التعديلات', 'he': 'סיכום שינויים', 'id': 'Ringkasan modifikasi', 'ja': '変更の概要'},
    'Move down': {'fr': 'Déplacer vers le bas', 'es': 'Mover hacia abajo', 'de': 'Nach unten verschieben', 'it': 'Sposta in basso', 'pt': 'Mover para baixo', 'nl': 'Omlaag verplaatsen', 'ca': 'Mou cap avall', 'ro': 'Mutați în jos', 'bg': 'Премести надолу', 'el': 'Μετακίνηση κάτω', 'ar': 'تحريك للأسفل', 'he': 'הזז למטה', 'id': 'Pindah ke bawah', 'ja': '下に移動'},
    'Move up': {'fr': 'Déplacer vers le haut', 'es': 'Mover hacia arriba', 'de': 'Nach oben verschieben', 'it': 'Sposta in alto', 'pt': 'Mover para cima', 'nl': 'Omhoog verplaatsen', 'ca': 'Mou cap amunt', 'ro': 'Mutați în sus', 'bg': 'Премести нагоре', 'el': 'Μετακίνηση πάνω', 'ar': 'تحريك للأعلى', 'he': 'הזז למעלה', 'id': 'Pindah ke atas', 'ja': '上に移動'},
    'Moving entrance to a new cave or network': {'fr': 'Déplacer l\'entrée vers une nouvelle cavité ou un nouveau réseau', 'es': 'Mover la entrada a una nueva cueva o red', 'de': 'Eingang in eine neue Höhle oder ein neues Netzwerk verschieben', 'it': 'Spostare l\'ingresso in una nuova grotta o rete', 'pt': 'Mover a entrada para uma nova caverna ou rede', 'nl': 'Ingang verplaatsen naar een nieuwe grot of netwerk', 'ca': 'Moure l\'entrada a una nova cova o xarxa', 'ro': 'Mutați intrarea la o nouă peșteră sau rețea', 'bg': 'Преместване на вход към нова пещера или мрежа', 'el': 'Μετακίνηση εισόδου σε νέο σπήλαιο ή δίκτυο', 'ar': 'نقل المدخل إلى كهف أو شبكة جديدة', 'he': 'העברת כניסה למערה או רשת חדשה', 'id': 'Memindahkan pintu masuk ke gua atau jaringan baru', 'ja': '入口を新しい洞窟またはネットワークに移動'},
    'My Account': {'fr': 'Mon compte', 'es': 'Mi cuenta', 'de': 'Mein Konto', 'it': 'Il mio account', 'pt': 'A minha conta', 'nl': 'Mijn account', 'ca': 'El meu compte', 'ro': 'Contul meu', 'bg': 'Моят акаунт', 'el': 'Ο λογαριασμός μου', 'ar': 'حسابي', 'he': 'החשבון שלי', 'id': 'Akun saya', 'ja': 'マイアカウント'},
    'My contributions': {'fr': 'Mes contributions', 'es': 'Mis contribuciones', 'de': 'Meine Beiträge', 'it': 'I miei contributi', 'pt': 'As minhas contribuições', 'nl': 'Mijn bijdragen', 'ca': 'Les meves contribucions', 'ro': 'Contribuțiile mele', 'bg': 'Моите приноси', 'el': 'Οι συνεισφορές μου', 'ar': 'مساهماتي', 'he': 'התרומות שלי', 'id': 'Kontribusi saya', 'ja': '私の投稿'},
    'My notifications': {'fr': 'Mes notifications', 'es': 'Mis notificaciones', 'de': 'Meine Benachrichtigungen', 'it': 'Le mie notifiche', 'pt': 'As minhas notificações', 'nl': 'Mijn meldingen', 'ca': 'Les meves notificacions', 'ro': 'Notificările mele', 'bg': 'Моите известия', 'el': 'Οι ειδοποιήσεις μου', 'ar': 'إشعاراتي', 'he': 'ההתראות שלי', 'id': 'Notifikasi saya', 'ja': '私の通知'},
}

with open(os.path.join(DIR, 'en.json'), encoding='utf-8') as f:
    en = json.load(f)

total = 0
for lang in ['fr','es','it','pt','de','nl','ca','ro','bg','el','ar','he','id','ja']:
    path = os.path.join(DIR, f'{lang}.json')
    with open(path, encoding='utf-8') as f:
        d = json.load(f)
    n = 0
    for k, langs in T.items():
        if k in en and lang in langs and (k not in d or d[k] == en[k]):
            d[k] = langs[lang]; n += 1
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(dict(sorted(d.items())), f, ensure_ascii=False, indent=2)
    total += n
    print(f'{lang}: +{n}')
print(f'Total: {total}')
