# -*- coding: utf-8 -*-
import json, os
DIR = os.path.dirname(os.path.abspath(__file__))

T = {
    'No Rating': {'fr': 'Pas de note', 'es': 'Sin valoración', 'de': 'Keine Bewertung', 'it': 'Nessuna valutazione', 'pt': 'Sem classificação', 'nl': 'Geen beoordeling', 'ca': 'Sense valoració', 'ro': 'Fără evaluare', 'bg': 'Няма оценка', 'el': 'Χωρίς βαθμολογία', 'ar': 'لا يوجد تقييم', 'he': 'ללא דירוג', 'id': 'Tidak ada penilaian', 'ja': '評価なし'},
    'No account yet?': {'fr': 'Pas encore de compte ?', 'es': '¿Aún no tienes cuenta?', 'de': 'Noch kein Konto?', 'it': 'Non hai ancora un account?', 'pt': 'Ainda não tem conta?', 'nl': 'Nog geen account?', 'ca': 'Encara no tens compte?', 'ro': 'Nu ai un cont încă?', 'bg': 'Нямате акаунт?', 'el': 'Δεν έχετε λογαριασμό;', 'ar': 'ليس لديك حساب بعد؟', 'he': 'עדיין אין לך חשבון?', 'id': 'Belum punya akun?', 'ja': 'まだアカウントをお持ちでないですか？'},
    'No explored entrances found.': {'fr': 'Aucune entrée explorée trouvée.', 'es': 'No se encontraron entradas exploradas.', 'de': 'Keine erkundeten Eingänge gefunden.', 'it': 'Nessun ingresso esplorato trovato.', 'pt': 'Nenhuma entrada explorada encontrada.', 'nl': 'Geen verkende ingangen gevonden.', 'ca': 'No s\'han trobat entrades explorades.', 'ro': 'Nu s-au găsit intrări explorate.', 'bg': 'Не са намерени изследвани входове.', 'el': 'Δεν βρέθηκαν εξερευνημένες είσοδοι.', 'ar': 'لم يتم العثور على مداخل مستكشفة.', 'he': 'לא נמצאו כניסות שנחקרו.', 'id': 'Tidak ditemukan pintu masuk yang dijelajahi.', 'ja': '探検済み入口が見つかりません。'},
    'No explored networks found.': {'fr': 'Aucun réseau exploré trouvé.', 'es': 'No se encontraron redes exploradas.', 'de': 'Keine erkundeten Netzwerke gefunden.', 'it': 'Nessuna rete esplorata trovata.', 'pt': 'Nenhuma rede explorada encontrada.', 'nl': 'Geen verkende netwerken gevonden.', 'ca': 'No s\'han trobat xarxes explorades.', 'ro': 'Nu s-au găsit rețele explorate.', 'bg': 'Не са намерени изследвани мрежи.', 'el': 'Δεν βρέθηκαν εξερευνημένα δίκτυα.', 'ar': 'لم يتم العثور على شبكات مستكشفة.', 'he': 'לא נמצאו רשתות שנחקרו.', 'id': 'Tidak ditemukan jaringan yang dijelajahi.', 'ja': '探検済みネットワークが見つかりません。'},
    'No layers to delete': {'fr': 'Aucune couche à supprimer', 'es': 'No hay capas para eliminar', 'de': 'Keine Ebenen zum Löschen', 'it': 'Nessun livello da eliminare', 'pt': 'Sem camadas para eliminar', 'nl': 'Geen lagen om te verwijderen', 'ca': 'No hi ha capes per eliminar', 'ro': 'Nu există straturi de șters', 'bg': 'Няма слоеве за изтриване', 'el': 'Δεν υπάρχουν επίπεδα προς διαγραφή', 'ar': 'لا توجد طبقات للحذف', 'he': 'אין שכבות למחיקה', 'id': 'Tidak ada lapisan untuk dihapus', 'ja': '削除するレイヤーがありません'},
    'No result.': {'fr': 'Aucun résultat.', 'es': 'Sin resultados.', 'de': 'Kein Ergebnis.', 'it': 'Nessun risultato.', 'pt': 'Sem resultado.', 'nl': 'Geen resultaat.', 'ca': 'Cap resultat.', 'ro': 'Niciun rezultat.', 'bg': 'Няма резултат.', 'el': 'Κανένα αποτέλεσμα.', 'ar': 'لا توجد نتائج.', 'he': 'אין תוצאות.', 'id': 'Tidak ada hasil.', 'ja': '結果なし。'},
    'Not implemented yet': {'fr': 'Pas encore implémenté', 'es': 'Aún no implementado', 'de': 'Noch nicht implementiert', 'it': 'Non ancora implementato', 'pt': 'Ainda não implementado', 'nl': 'Nog niet geïmplementeerd', 'ca': 'Encara no implementat', 'ro': 'Încă neimplementat', 'bg': 'Все още не е имплементирано', 'el': 'Δεν έχει υλοποιηθεί ακόμα', 'ar': 'لم يتم تطبيقه بعد', 'he': 'עדיין לא מומש', 'id': 'Belum diimplementasikan', 'ja': 'まだ実装されていません'},
    'Number of contributors': {'fr': 'Nombre de contributeurs', 'es': 'Número de colaboradores', 'de': 'Anzahl der Beitragleistenden', 'it': 'Numero di contributori', 'pt': 'Número de contribuidores', 'nl': 'Aantal bijdragers', 'ca': 'Nombre de col·laboradors', 'ro': 'Numărul de contribuitori', 'bg': 'Брой сътрудници', 'el': 'Αριθμός συνεισφερόντων', 'ar': 'عدد المساهمين', 'he': 'מספר תורמים', 'id': 'Jumlah kontributor', 'ja': '投稿者数'},
    'Number of entrances': {'fr': 'Nombre d\'entrées', 'es': 'Número de entradas', 'de': 'Anzahl der Eingänge', 'it': 'Numero di ingressi', 'pt': 'Número de entradas', 'nl': 'Aantal ingangen', 'ca': 'Nombre d\'entrades', 'ro': 'Numărul de intrări', 'bg': 'Брой входове', 'el': 'Αριθμός εισόδων', 'ar': 'عدد المداخل', 'he': 'מספר כניסות', 'id': 'Jumlah pintu masuk', 'ja': '入口数'},
    'Number of minutes between parking and entrance': {'fr': 'Nombre de minutes entre le parking et l\'entrée', 'es': 'Número de minutos entre el aparcamiento y la entrada', 'de': 'Anzahl der Minuten zwischen Parkplatz und Eingang', 'it': 'Minuti tra il parcheggio e l\'ingresso', 'pt': 'Número de minutos entre o estacionamento e a entrada', 'nl': 'Minuten tussen parkeerplaats en ingang', 'ca': 'Minuts entre l\'aparcament i l\'entrada', 'ro': 'Minute între parcare și intrare', 'bg': 'Минути между паркинга и входа', 'el': 'Λεπτά μεταξύ πάρκινγκ και εισόδου', 'ar': 'دقائق بين موقف السيارات والمدخل', 'he': 'דקות בין החנייה לכניסה', 'id': 'Menit antara parkir dan pintu masuk', 'ja': '駐車場から入口までの分数'},
    'Number of minutes spent underground': {'fr': 'Nombre de minutes passées sous terre', 'es': 'Número de minutos bajo tierra', 'de': 'Anzahl der Minuten unter der Erde', 'it': 'Minuti trascorsi sottoterra', 'pt': 'Número de minutos passados no subsolo', 'nl': 'Minuten ondergronds', 'ca': 'Minuts sota terra', 'ro': 'Minute petrecute sub pământ', 'bg': 'Минути прекарани под земята', 'el': 'Λεπτά υπόγεια', 'ar': 'دقائق تحت الأرض', 'he': 'דקות שהוצאו מתחת לאדמה', 'id': 'Menit yang dihabiskan di bawah tanah', 'ja': '地下で過ごした分数'},
    'Open on Google Maps': {'fr': 'Ouvrir dans Google Maps', 'es': 'Abrir en Google Maps', 'de': 'In Google Maps öffnen', 'it': 'Apri in Google Maps', 'pt': 'Abrir no Google Maps', 'nl': 'Openen in Google Maps', 'ca': 'Obrir a Google Maps', 'ro': 'Deschideți în Google Maps', 'bg': 'Отвори в Google Maps', 'el': 'Άνοιγμα στο Google Maps', 'ar': 'فتح في Google Maps', 'he': 'פתח ב-Google Maps', 'id': 'Buka di Google Maps', 'ja': 'Google Mapsで開く'},
    'Open on OpenStreetMap': {'fr': 'Ouvrir dans OpenStreetMap', 'es': 'Abrir en OpenStreetMap', 'de': 'In OpenStreetMap öffnen', 'it': 'Apri in OpenStreetMap', 'pt': 'Abrir no OpenStreetMap', 'nl': 'Openen in OpenStreetMap', 'ca': 'Obrir a OpenStreetMap', 'ro': 'Deschideți în OpenStreetMap', 'bg': 'Отвори в OpenStreetMap', 'el': 'Άνοιγμα στο OpenStreetMap', 'ar': 'فتح في OpenStreetMap', 'he': 'פתח ב-OpenStreetMap', 'id': 'Buka di OpenStreetMap', 'ja': 'OpenStreetMapで開く'},
    'Order updated': {'fr': 'Ordre mis à jour', 'es': 'Orden actualizado', 'de': 'Reihenfolge aktualisiert', 'it': 'Ordine aggiornato', 'pt': 'Ordem atualizada', 'nl': 'Volgorde bijgewerkt', 'ca': 'Ordre actualitzat', 'ro': 'Ordinea actualizată', 'bg': 'Редът е актуализиран', 'el': 'Σειρά ενημερώθηκε', 'ar': 'تم تحديث الترتيب', 'he': 'הסדר עודכן', 'id': 'Urutan diperbarui', 'ja': '順序更新済み'},
    'Organization name': {'fr': 'Nom de l\'organisation', 'es': 'Nombre de la organización', 'de': 'Name der Organisation', 'it': 'Nome dell\'organizzazione', 'pt': 'Nome da organização', 'nl': 'Naam van de organisatie', 'ca': 'Nom de l\'organització', 'ro': 'Numele organizației', 'bg': 'Име на организацията', 'el': 'Όνομα οργανισμού', 'ar': 'اسم المنظمة', 'he': 'שם הארגון', 'id': 'Nama organisasi', 'ja': '組織名'},
    'Organization properties': {'fr': 'Propriétés de l\'organisation', 'es': 'Propiedades de la organización', 'de': 'Eigenschaften der Organisation', 'it': 'Proprietà dell\'organizzazione', 'pt': 'Propriedades da organização', 'nl': 'Eigenschappen van de organisatie', 'ca': 'Propietats de l\'organització', 'ro': 'Proprietățile organizației', 'bg': 'Свойства на организацията', 'el': 'Ιδιότητες οργανισμού', 'ar': 'خصائص المنظمة', 'he': 'מאפייני ארגון', 'id': 'Properti organisasi', 'ja': '組織プロパティ'},
    'Parent Document': {'fr': 'Document parent', 'es': 'Documento padre', 'de': 'Übergeordnetes Dokument', 'it': 'Documento padre', 'pt': 'Documento pai', 'nl': 'Bovenliggend document', 'ca': 'Document pare', 'ro': 'Document părinte', 'bg': 'Родителски документ', 'el': 'Γονικό έγγραφο', 'ar': 'المستند الأصل', 'he': 'מסמך אב', 'id': 'Dokumen induk', 'ja': '親文書'},
    'Password Reset': {'fr': 'Réinitialisation du mot de passe', 'es': 'Restablecimiento de contraseña', 'de': 'Passwort zurücksetzen', 'it': 'Reset della password', 'pt': 'Redefinição de palavra-passe', 'nl': 'Wachtwoord resetten', 'ca': 'Restabliment de contrasenya', 'ro': 'Resetare parolă', 'bg': 'Нулиране на парола', 'el': 'Επαναφορά κωδικού', 'ar': 'إعادة تعيين كلمة المرور', 'he': 'איפוס סיסמה', 'id': 'Reset kata sandi', 'ja': 'パスワードリセット'},
    'Password confirmation': {'fr': 'Confirmation du mot de passe', 'es': 'Confirmación de contraseña', 'de': 'Passwortbestätigung', 'it': 'Conferma password', 'pt': 'Confirmação de palavra-passe', 'nl': 'Wachtwoordbevestiging', 'ca': 'Confirmació de contrasenya', 'ro': 'Confirmare parolă', 'bg': 'Потвърждение на паролата', 'el': 'Επιβεβαίωση κωδικού', 'ar': 'تأكيد كلمة المرور', 'he': 'אישור סיסמה', 'id': 'Konfirmasi kata sandi', 'ja': 'パスワード確認'},
    'Password too short.': {'fr': 'Mot de passe trop court.', 'es': 'Contraseña demasiado corta.', 'de': 'Passwort zu kurz.', 'it': 'Password troppo corta.', 'pt': 'Palavra-passe demasiado curta.', 'nl': 'Wachtwoord te kort.', 'ca': 'Contrasenya massa curta.', 'ro': 'Parola prea scurtă.', 'bg': 'Паролата е прекалено кратка.', 'el': 'Ο κωδικός είναι πολύ μικρός.', 'ar': 'كلمة المرور قصيرة جداً.', 'he': 'הסיסמה קצרה מדי.', 'id': 'Kata sandi terlalu pendek.', 'ja': 'パスワードが短すぎます。'},
    'Permanently delete': {'fr': 'Supprimer définitivement', 'es': 'Eliminar permanentemente', 'de': 'Dauerhaft löschen', 'it': 'Elimina definitivamente', 'pt': 'Eliminar permanentemente', 'nl': 'Permanent verwijderen', 'ca': 'Eliminar permanentment', 'ro': 'Ștergeți definitiv', 'bg': 'Изтрий окончателно', 'el': 'Μόνιμη διαγραφή', 'ar': 'حذف نهائي', 'he': 'מחק לצמיתות', 'id': 'Hapus permanen', 'ja': '完全に削除'},
    'Pollution risk': {'fr': 'Risque de pollution', 'es': 'Riesgo de contaminación', 'de': 'Verschmutzungsrisiko', 'it': 'Rischio di inquinamento', 'pt': 'Risco de poluição', 'nl': 'Vervuilingsrisico', 'ca': 'Risc de contaminació', 'ro': 'Risc de poluare', 'bg': 'Риск от замърсяване', 'el': 'Κίνδυνος ρύπανσης', 'ar': 'خطر التلوث', 'he': 'סיכון זיהום', 'id': 'Risiko polusi', 'ja': '汚染リスク'},
    'Previous cave': {'fr': 'Cavité précédente', 'es': 'Cueva anterior', 'de': 'Vorherige Höhle', 'it': 'Grotta precedente', 'pt': 'Caverna anterior', 'nl': 'Vorige grot', 'ca': 'Cova anterior', 'ro': 'Peștera anterioară', 'bg': 'Предишна пещера', 'el': 'Προηγούμενο σπήλαιο', 'ar': 'الكهف السابق', 'he': 'מערה קודמת', 'id': 'Gua sebelumnya', 'ja': '前の洞窟'},
    'Previous network': {'fr': 'Réseau précédent', 'es': 'Red anterior', 'de': 'Vorheriges Netzwerk', 'it': 'Rete precedente', 'pt': 'Rede anterior', 'nl': 'Vorig netwerk', 'ca': 'Xarxa anterior', 'ro': 'Rețeaua anterioară', 'bg': 'Предишна мрежа', 'el': 'Προηγούμενο δίκτυο', 'ar': 'الشبكة السابقة', 'he': 'רשת קודמת', 'id': 'Jaringan sebelumnya', 'ja': '前のネットワーク'},
}

with open(os.path.join(DIR, 'en.json'), encoding='utf-8') as f:
    en = json.load(f)

total = 0
for lang in ['fr','es','it','pt','de','nl','ca','ro','bg','el','ar','he','id','ja']:
    path = os.path.join(DIR, f'{lang}.json')
    with open(path, encoding='utf-8') as f:
        d = json.load(f)
    n = 0
    for k, langs in T.items():
        if k in en and lang in langs and (k not in d or d[k] == en[k]):
            d[k] = langs[lang]; n += 1
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(dict(sorted(d.items())), f, ensure_ascii=False, indent=2)
    total += n
    print(f'{lang}: +{n}')
print(f'Total: {total}')
