# -*- coding: utf-8 -*-
import json, os
DIR = os.path.dirname(os.path.abspath(__file__))

T = {
    'Processing, this may take some time...': {'fr': 'Traitement en cours, cela peut prendre du temps...', 'es': 'Procesando, esto puede tardar un poco...', 'de': 'Verarbeitung läuft, das kann einige Zeit dauern...', 'it': 'Elaborazione in corso, potrebbe richiedere del tempo...', 'pt': 'A processar, isso pode demorar algum tempo...', 'nl': 'Verwerken, dit kan enige tijd duren...', 'ca': 'Processant, pot trigar una mica...', 'ro': 'Procesare în curs, poate dura ceva timp...', 'bg': 'Обработка, това може да отнеме малко...', 'el': 'Επεξεργασία, αυτό μπορεί να διαρκέσει λίγο...', 'ar': 'جارٍ المعالجة، قد يستغرق هذا بعض الوقت...', 'he': 'מעבד, זה עשוי לקחת קצת זמן...', 'id': 'Memproses, ini mungkin membutuhkan waktu...', 'ja': '処理中、しばらく時間がかかる場合があります...'},
    'Rockfall risk': {'fr': 'Risque de chute de pierres', 'es': 'Riesgo de desprendimiento', 'de': 'Steinschlaggefahr', 'it': 'Rischio di caduta massi', 'pt': 'Risco de queda de pedras', 'nl': 'Steenvalsrisico', 'ca': 'Risc de despreniment', 'ro': 'Risc de prăbușire', 'bg': 'Риск от падане на камъни', 'el': 'Κίνδυνος πτώσης βράχων', 'ar': 'خطر سقوط الصخور', 'he': 'סיכון נפילת סלעים', 'id': 'Risiko jatuhnya batu', 'ja': '落石リスク'},
    'Save changes': {'fr': 'Enregistrer les modifications', 'es': 'Guardar cambios', 'de': 'Änderungen speichern', 'it': 'Salva modifiche', 'pt': 'Guardar alterações', 'nl': 'Wijzigingen opslaan', 'ca': 'Desa els canvis', 'ro': 'Salvați modificările', 'bg': 'Запази промените', 'el': 'Αποθήκευση αλλαγών', 'ar': 'حفظ التغييرات', 'he': 'שמור שינויים', 'id': 'Simpan perubahan', 'ja': '変更を保存'},
    'Search a language': {'fr': 'Rechercher une langue', 'es': 'Buscar un idioma', 'de': 'Eine Sprache suchen', 'it': 'Cerca una lingua', 'pt': 'Pesquisar uma língua', 'nl': 'Zoek een taal', 'ca': 'Cerca una llengua', 'ro': 'Căutați o limbă', 'bg': 'Търсене на език', 'el': 'Αναζήτηση γλώσσας', 'ar': 'ابحث عن لغة', 'he': 'חפש שפה', 'id': 'Cari bahasa', 'ja': '言語を検索'},
    'Search for a document...': {'fr': 'Rechercher un document...', 'es': 'Buscar un documento...', 'de': 'Nach einem Dokument suchen...', 'it': 'Cerca un documento...', 'pt': 'Pesquisar um documento...', 'nl': 'Zoek naar een document...', 'ca': 'Cerca un document...', 'ro': 'Căutați un document...', 'bg': 'Търсене на документ...', 'el': 'Αναζήτηση εγγράφου...', 'ar': 'ابحث عن مستند...', 'he': 'חפש מסמך...', 'id': 'Cari dokumen...', 'ja': 'ドキュメントを検索...'},
    'Search for a library...': {'fr': 'Rechercher une bibliothèque...', 'es': 'Buscar una biblioteca...', 'de': 'Nach einer Bibliothek suchen...', 'it': 'Cerca una biblioteca...', 'pt': 'Pesquisar uma biblioteca...', 'nl': 'Zoek naar een bibliotheek...', 'ca': 'Cerca una biblioteca...', 'ro': 'Căutați o bibliotecă...', 'bg': 'Търсене на библиотека...', 'el': 'Αναζήτηση βιβλιοθήκης...', 'ar': 'ابحث عن مكتبة...', 'he': 'חפש ספרייה...', 'id': 'Cari perpustakaan...', 'ja': '図書館を検索...'},
    'Search on all fields': {'fr': 'Rechercher sur tous les champs', 'es': 'Buscar en todos los campos', 'de': 'In allen Feldern suchen', 'it': 'Cerca in tutti i campi', 'pt': 'Pesquisar em todos os campos', 'nl': 'Zoeken in alle velden', 'ca': 'Cerca en tots els camps', 'ro': 'Căutați în toate câmpurile', 'bg': 'Търсене във всички полета', 'el': 'Αναζήτηση σε όλα τα πεδία', 'ar': 'البحث في جميع الحقول', 'he': 'חפש בכל השדות', 'id': 'Cari di semua bidang', 'ja': 'すべてのフィールドで検索'},
    'Search on specific fields': {'fr': 'Rechercher sur des champs spécifiques', 'es': 'Buscar en campos específicos', 'de': 'In bestimmten Feldern suchen', 'it': 'Cerca in campi specifici', 'pt': 'Pesquisar em campos específicos', 'nl': 'Zoeken in specifieke velden', 'ca': 'Cerca en camps específics', 'ro': 'Căutați în câmpuri specifice', 'bg': 'Търсене в конкретни полета', 'el': 'Αναζήτηση σε συγκεκριμένα πεδία', 'ar': 'البحث في حقول محددة', 'he': 'חפש בשדות ספציפיים', 'id': 'Cari di bidang tertentu', 'ja': '特定のフィールドで検索'},
    'Section under development': {'fr': 'Section en cours de développement', 'es': 'Sección en desarrollo', 'de': 'Abschnitt in Entwicklung', 'it': 'Sezione in sviluppo', 'pt': 'Secção em desenvolvimento', 'nl': 'Sectie in ontwikkeling', 'ca': 'Secció en desenvolupament', 'ro': 'Secțiune în curs de dezvoltare', 'bg': 'Раздел в процес на разработка', 'el': 'Ενότητα υπό ανάπτυξη', 'ar': 'قسم قيد التطوير', 'he': 'קטע בפיתוח', 'id': 'Bagian dalam pengembangan', 'ja': '開発中のセクション'},
    'See all notifications': {'fr': 'Voir toutes les notifications', 'es': 'Ver todas las notificaciones', 'de': 'Alle Benachrichtigungen anzeigen', 'it': 'Vedi tutte le notifiche', 'pt': 'Ver todas as notificações', 'nl': 'Alle meldingen bekijken', 'ca': 'Veure totes les notificacions', 'ro': 'Vedeți toate notificările', 'bg': 'Виж всички известия', 'el': 'Δείτε όλες τις ειδοποιήσεις', 'ar': 'عرض جميع الإشعارات', 'he': 'ראה את כל ההתראות', 'id': 'Lihat semua notifikasi', 'ja': 'すべての通知を見る'},
    'Select a document type': {'fr': 'Sélectionner un type de document', 'es': 'Seleccionar un tipo de documento', 'de': 'Dokumenttyp auswählen', 'it': 'Seleziona un tipo di documento', 'pt': 'Selecionar um tipo de documento', 'nl': 'Selecteer een documenttype', 'ca': 'Selecciona un tipus de document', 'ro': 'Selectați un tip de document', 'bg': 'Изберете тип документ', 'el': 'Επιλέξτε τύπο εγγράφου', 'ar': 'حدد نوع المستند', 'he': 'בחר סוג מסמך', 'id': 'Pilih jenis dokumen', 'ja': '文書タイプを選択'},
    'Select a language': {'fr': 'Sélectionner une langue', 'es': 'Seleccionar un idioma', 'de': 'Sprache auswählen', 'it': 'Seleziona una lingua', 'pt': 'Selecionar uma língua', 'nl': 'Selecteer een taal', 'ca': 'Selecciona una llengua', 'ro': 'Selectați o limbă', 'bg': 'Изберете език', 'el': 'Επιλέξτε γλώσσα', 'ar': 'حدد لغة', 'he': 'בחר שפה', 'id': 'Pilih bahasa', 'ja': '言語を選択'},
    'Select a license': {'fr': 'Sélectionner une licence', 'es': 'Seleccionar una licencia', 'de': 'Lizenz auswählen', 'it': 'Seleziona una licenza', 'pt': 'Selecionar uma licença', 'nl': 'Selecteer een licentie', 'ca': 'Selecciona una llicència', 'ro': 'Selectați o licență', 'bg': 'Изберете лиценз', 'el': 'Επιλέξτε άδεια', 'ar': 'حدد ترخيصاً', 'he': 'בחר רישיון', 'id': 'Pilih lisensi', 'ja': 'ライセンスを選択'},
    'Send reset email': {'fr': 'Envoyer l\'email de réinitialisation', 'es': 'Enviar email de restablecimiento', 'de': 'Zurücksetz-E-Mail senden', 'it': 'Invia email di reset', 'pt': 'Enviar email de redefinição', 'nl': 'Reset-e-mail verzenden', 'ca': 'Envia correu de restabliment', 'ro': 'Trimiteți emailul de resetare', 'bg': 'Изпрати имейл за нулиране', 'el': 'Αποστολή email επαναφοράς', 'ar': 'إرسال بريد إعادة التعيين', 'he': 'שלח אימייל לאיפוס', 'id': 'Kirim email reset', 'ja': 'リセットメールを送信'},
    'Show on map': {'fr': 'Afficher sur la carte', 'es': 'Mostrar en el mapa', 'de': 'Auf der Karte anzeigen', 'it': 'Mostra sulla mappa', 'pt': 'Mostrar no mapa', 'nl': 'Weergeven op kaart', 'ca': 'Mostra al mapa', 'ro': 'Afișați pe hartă', 'bg': 'Покажи на картата', 'el': 'Εμφάνιση στον χάρτη', 'ar': 'عرض على الخريطة', 'he': 'הצג על המפה', 'id': 'Tampilkan di peta', 'ja': '地図に表示'},
    'Sign up form': {'fr': 'Formulaire d\'inscription', 'es': 'Formulario de registro', 'de': 'Anmeldeformular', 'it': 'Modulo di registrazione', 'pt': 'Formulário de inscrição', 'nl': 'Aanmeldformulier', 'ca': 'Formulari de registre', 'ro': 'Formular de înregistrare', 'bg': 'Формуляр за регистрация', 'el': 'Φόρμα εγγραφής', 'ar': 'نموذج التسجيل', 'he': 'טופס הרשמה', 'id': 'Formulir pendaftaran', 'ja': '登録フォーム'},
    'Sorry, something went wrong...': {'fr': 'Désolé, quelque chose s\'est mal passé...', 'es': 'Lo sentimos, algo salió mal...', 'de': 'Entschuldigung, etwas ist schiefgelaufen...', 'it': 'Spiacenti, qualcosa è andato storto...', 'pt': 'Desculpe, algo correu mal...', 'nl': 'Sorry, er is iets misgegaan...', 'ca': 'Ho sentim, alguna cosa ha fallat...', 'ro': 'Ne pare rău, ceva a mers prost...', 'bg': 'Съжаляваме, нещо се обърка...', 'el': 'Συγγνώμη, κάτι πήγε στραβά...', 'ar': 'عذراً، حدث خطأ ما...', 'he': 'סליחה, משהו השתבש...', 'id': 'Maaf, terjadi kesalahan...', 'ja': '申し訳ありません、問題が発生しました...'},
    'Start Page': {'fr': 'Page de début', 'es': 'Página de inicio', 'de': 'Startseite', 'it': 'Pagina iniziale', 'pt': 'Página inicial', 'nl': 'Beginpagina', 'ca': 'Pàgina d\'inici', 'ro': 'Pagina de început', 'bg': 'Начална страница', 'el': 'Αρχική σελίδα', 'ar': 'الصفحة الأولى', 'he': 'עמוד התחלה', 'id': 'Halaman awal', 'ja': '開始ページ'},
    'Submission date': {'fr': 'Date de soumission', 'es': 'Fecha de envío', 'de': 'Einreichungsdatum', 'it': 'Data di invio', 'pt': 'Data de submissão', 'nl': 'Indieningsdatum', 'ca': 'Data d\'enviament', 'ro': 'Data depunerii', 'bg': 'Дата на подаване', 'el': 'Ημερομηνία υποβολής', 'ar': 'تاريخ التقديم', 'he': 'תאריך הגשה', 'id': 'Tanggal pengiriman', 'ja': '提出日'},
    'Submit another article': {'fr': 'Soumettre un autre article', 'es': 'Enviar otro artículo', 'de': 'Einen weiteren Artikel einreichen', 'it': 'Invia un altro articolo', 'pt': 'Submeter outro artigo', 'nl': 'Nog een artikel indienen', 'ca': 'Enviar un altre article', 'ro': 'Trimiteți un alt articol', 'bg': 'Изпрати друга статия', 'el': 'Υποβολή άλλου άρθρου', 'ar': 'إرسال مقال آخر', 'he': 'שלח מאמר נוסף', 'id': 'Kirim artikel lain', 'ja': '別の記事を提出'},
    'Submit another document': {'fr': 'Soumettre un autre document', 'es': 'Enviar otro documento', 'de': 'Ein weiteres Dokument einreichen', 'it': 'Invia un altro documento', 'pt': 'Submeter outro documento', 'nl': 'Nog een document indienen', 'ca': 'Enviar un altre document', 'ro': 'Trimiteți un alt document', 'bg': 'Изпрати друг документ', 'el': 'Υποβολή άλλου εγγράφου', 'ar': 'إرسال مستند آخر', 'he': 'שלח מסמך נוסף', 'id': 'Kirim dokumen lain', 'ja': '別の文書を提出'},
    'Technical speleology': {'fr': 'Spéléologie technique', 'es': 'Espeleología técnica', 'de': 'Technische Speläologie', 'it': 'Speleologia tecnica', 'pt': 'Espeleologia técnica', 'nl': 'Technische speleologie', 'ca': 'Espeleologia tècnica', 'ro': 'Speologie tehnică', 'bg': 'Техническа спелеология', 'el': 'Τεχνική σπηλαιολογία', 'ar': 'علم الكهوف التقني', 'he': 'ספלאולוגיה טכנית', 'id': 'Speleologi teknis', 'ja': '技術洞窟学'},
    'This {entity} has been deleted': {'fr': 'Ce {entity} a été supprimé', 'es': 'Este {entity} ha sido eliminado', 'de': 'Dieses {entity} wurde gelöscht', 'it': 'Questo {entity} è stato eliminato', 'pt': 'Este {entity} foi eliminado', 'nl': 'Dit {entity} is verwijderd', 'ca': 'Aquest {entity} ha estat eliminat', 'ro': 'Acest {entity} a fost șters', 'bg': 'Тази {entity} е изтрита', 'el': 'Αυτή η {entity} διαγράφηκε', 'ar': 'تم حذف هذا {entity}', 'he': 'ה-{entity} הזה נמחק', 'id': '{entity} ini telah dihapus', 'ja': 'この{entity}は削除されました'},
    'Title Language': {'fr': 'Langue du titre', 'es': 'Idioma del título', 'de': 'Titelsprache', 'it': 'Lingua del titolo', 'pt': 'Língua do título', 'nl': 'Titeltaal', 'ca': 'Idioma del títol', 'ro': 'Limba titlului', 'bg': 'Език на заглавието', 'el': 'Γλώσσα τίτλου', 'ar': 'لغة العنوان', 'he': 'שפת הכותרת', 'id': 'Bahasa judul', 'ja': 'タイトルの言語'},
    'Title and description language': {'fr': 'Langue du titre et de la description', 'es': 'Idioma del título y la descripción', 'de': 'Sprache des Titels und der Beschreibung', 'it': 'Lingua del titolo e della descrizione', 'pt': 'Língua do título e da descrição', 'nl': 'Taal van de titel en beschrijving', 'ca': 'Idioma del títol i la descripció', 'ro': 'Limba titlului și descrierii', 'bg': 'Език на заглавието и описанието', 'el': 'Γλώσσα τίτλου και περιγραφής', 'ar': 'لغة العنوان والوصف', 'he': 'שפת הכותרת והתיאור', 'id': 'Bahasa judul dan deskripsi', 'ja': 'タイトルと説明の言語'},
}

with open(os.path.join(DIR, 'en.json'), encoding='utf-8') as f:
    en = json.load(f)

total = 0
for lang in ['fr','es','it','pt','de','nl','ca','ro','bg','el','ar','he','id','ja']:
    path = os.path.join(DIR, f'{lang}.json')
    with open(path, encoding='utf-8') as f:
        d = json.load(f)
    n = 0
    for k, langs in T.items():
        if k in en and lang in langs and (k not in d or d[k] == en[k]):
            d[k] = langs[lang]; n += 1
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(dict(sorted(d.items())), f, ensure_ascii=False, indent=2)
    total += n
    print(f'{lang}: +{n}')
print(f'Total: {total}')
