# -*- coding: utf-8 -*-
import json, os
DIR = os.path.dirname(os.path.abspath(__file__))

T = {
    'Update my profile': {'fr': 'Mettre à jour mon profil', 'es': 'Actualizar mi perfil', 'de': 'Mein Profil aktualisieren', 'it': 'Aggiorna il mio profilo', 'pt': 'Atualizar o meu perfil', 'nl': 'Mijn profiel bijwerken', 'ca': 'Actualitzar el meu perfil', 'ro': 'Actualizați-mi profilul', 'bg': 'Актуализирай моя профил', 'el': 'Ενημέρωση προφίλ μου', 'ar': 'تحديث ملفي الشخصي', 'he': 'עדכן את הפרופיל שלי', 'id': 'Perbarui profil saya', 'ja': 'プロフィールを更新'},
    'Update password': {'fr': 'Mettre à jour le mot de passe', 'es': 'Actualizar contraseña', 'de': 'Passwort aktualisieren', 'it': 'Aggiorna la password', 'pt': 'Atualizar palavra-passe', 'nl': 'Wachtwoord bijwerken', 'ca': 'Actualitzar la contrasenya', 'ro': 'Actualizați parola', 'bg': 'Актуализирай паролата', 'el': 'Ενημέρωση κωδικού', 'ar': 'تحديث كلمة المرور', 'he': 'עדכן סיסמה', 'id': 'Perbarui kata sandi', 'ja': 'パスワードを更新'},
    'User information': {'fr': 'Informations utilisateur', 'es': 'Información del usuario', 'de': 'Benutzerinformationen', 'it': 'Informazioni utente', 'pt': 'Informações do utilizador', 'nl': 'Gebruikersinformatie', 'ca': 'Informació de l\'usuari', 'ro': 'Informații utilizator', 'bg': 'Потребителска информация', 'el': 'Πληροφορίες χρήστη', 'ar': 'معلومات المستخدم', 'he': 'מידע משתמש', 'id': 'Informasi pengguna', 'ja': 'ユーザー情報'},
    'User successfully updated': {'fr': 'Utilisateur mis à jour avec succès', 'es': 'Usuario actualizado con éxito', 'de': 'Benutzer erfolgreich aktualisiert', 'it': 'Utente aggiornato con successo', 'pt': 'Utilizador atualizado com sucesso', 'nl': 'Gebruiker succesvol bijgewerkt', 'ca': 'Usuari actualitzat amb èxit', 'ro': 'Utilizatorul a fost actualizat cu succes', 'bg': 'Потребителят е актуализиран успешно', 'el': 'Ο χρήστης ενημερώθηκε επιτυχώς', 'ar': 'تم تحديث المستخدم بنجاح', 'he': 'המשתמש עודכן בהצלחה', 'id': 'Pengguna berhasil diperbarui', 'ja': 'ユーザーが正常に更新されました'},
    'Validation date': {'fr': 'Date de validation', 'es': 'Fecha de validación', 'de': 'Validierungsdatum', 'it': 'Data di validazione', 'pt': 'Data de validação', 'nl': 'Validatiedatum', 'ca': 'Data de validació', 'ro': 'Data validării', 'bg': 'Дата на валидиране', 'el': 'Ημερομηνία επικύρωσης', 'ar': 'تاريخ التحقق', 'he': 'תאריך אימות', 'id': 'Tanggal validasi', 'ja': '検証日'},
    'View detail': {'fr': 'Voir le détail', 'es': 'Ver detalle', 'de': 'Detail anzeigen', 'it': 'Visualizza dettaglio', 'pt': 'Ver detalhe', 'nl': 'Detail bekijken', 'ca': 'Veure detall', 'ro': 'Vizualizare detaliu', 'bg': 'Виж детайли', 'el': 'Προβολή λεπτομερειών', 'ar': 'عرض التفاصيل', 'he': 'הצג פרט', 'id': 'Lihat detail', 'ja': '詳細を表示'},
    'Work in progress': {'fr': 'Travail en cours', 'es': 'Trabajo en progreso', 'de': 'Arbeit in Bearbeitung', 'it': 'Lavoro in corso', 'pt': 'Trabalho em progresso', 'nl': 'Werk in uitvoering', 'ca': 'Treball en curs', 'ro': 'Lucrare în curs', 'bg': 'Работа в ход', 'el': 'Σε εξέλιξη', 'ar': 'قيد التطوير', 'he': 'עבודה בתהליך', 'id': 'Sedang dalam proses', 'ja': '作業中'},
    'Year of publication': {'fr': 'Année de publication', 'es': 'Año de publicación', 'de': 'Erscheinungsjahr', 'it': 'Anno di pubblicazione', 'pt': 'Ano de publicação', 'nl': 'Publicatiejaar', 'ca': 'Any de publicació', 'ro': 'Anul publicării', 'bg': 'Година на публикуване', 'el': 'Έτος δημοσίευσης', 'ar': 'سنة النشر', 'he': 'שנת פרסום', 'id': 'Tahun publikasi', 'ja': '発行年'},
    'You are connected': {'fr': 'Vous êtes connecté', 'es': 'Estás conectado', 'de': 'Sie sind angemeldet', 'it': 'Sei connesso', 'pt': 'Está ligado', 'nl': 'U bent verbonden', 'ca': 'Esteu connectat', 'ro': 'Ești conectat', 'bg': 'Свързан сте', 'el': 'Είστε συνδεδεμένος', 'ar': 'أنت متصل', 'he': 'אתה מחובר', 'id': 'Anda terhubung', 'ja': 'ログイン中'},
    'You are not authorized': {'fr': 'Vous n\'êtes pas autorisé', 'es': 'No estás autorizado', 'de': 'Sie sind nicht autorisiert', 'it': 'Non sei autorizzato', 'pt': 'Não está autorizado', 'nl': 'U bent niet geautoriseerd', 'ca': 'No esteu autoritzat', 'ro': 'Nu ești autorizat', 'bg': 'Нямате разрешение', 'el': 'Δεν είστε εξουσιοδοτημένος', 'ar': 'غير مصرح لك', 'he': 'אינך מורשה', 'id': 'Anda tidak diotorisasi', 'ja': '権限がありません'},
    'You are not authorized to create a document.': {'fr': 'Vous n\'êtes pas autorisé à créer un document.', 'es': 'No está autorizado a crear un documento.', 'de': 'Sie sind nicht berechtigt, ein Dokument zu erstellen.', 'it': 'Non sei autorizzato a creare un documento.', 'pt': 'Não está autorizado a criar um documento.', 'nl': 'U bent niet gemachtigd een document te maken.', 'ca': 'No esteu autoritzat a crear un document.', 'ro': 'Nu ești autorizat să creezi un document.', 'bg': 'Нямате разрешение да създадете документ.', 'el': 'Δεν είστε εξουσιοδοτημένος να δημιουργήσετε έγγραφο.', 'ar': 'غير مصرح لك بإنشاء مستند.', 'he': 'אינך מורשה ליצור מסמך.', 'id': 'Anda tidak diotorisasi untuk membuat dokumen.', 'ja': '文書を作成する権限がありません。'},
    'You are not logged in.': {'fr': 'Vous n\'êtes pas connecté.', 'es': 'No has iniciado sesión.', 'de': 'Sie sind nicht angemeldet.', 'it': 'Non sei connesso.', 'pt': 'Não está ligado.', 'nl': 'U bent niet ingelogd.', 'ca': 'No heu iniciat sessió.', 'ro': 'Nu ești autentificat.', 'bg': 'Не сте влезли в системата.', 'el': 'Δεν έχετε συνδεθεί.', 'ar': 'أنت لست مسجل الدخول.', 'he': 'אינך מחובר.', 'id': 'Anda belum masuk.', 'ja': 'ログインしていません。'},
    'You are subscribed to the country.': {'fr': 'Vous êtes abonné au pays.', 'es': 'Estás suscrito al país.', 'de': 'Sie haben das Land abonniert.', 'it': 'Sei iscritto al paese.', 'pt': 'Está subscrito ao país.', 'nl': 'U bent geabonneerd op het land.', 'ca': 'Esteu subscrit al país.', 'ro': 'Ești abonat la țară.', 'bg': 'Абонирани сте за страната.', 'el': 'Έχετε εγγραφεί στη χώρα.', 'ar': 'أنت مشترك في البلد.', 'he': 'אתה מנוי למדינה.', 'id': 'Anda berlangganan ke negara.', 'ja': '国を購読しています。'},
    'You are subscribed to the massif.': {'fr': 'Vous êtes abonné au massif.', 'es': 'Estás suscrito al macizo.', 'de': 'Sie haben das Massiv abonniert.', 'it': 'Sei iscritto al massiccio.', 'pt': 'Está subscrito ao maciço.', 'nl': 'U bent geabonneerd op het massief.', 'ca': 'Esteu subscrit al massís.', 'ro': 'Ești abonat la masiv.', 'bg': 'Абонирани сте за масива.', 'el': 'Έχετε εγγραφεί στον ογκόλιθο.', 'ar': 'أنت مشترك في الكتلة الجبلية.', 'he': 'אתה מנוי למסיף.', 'id': 'Anda berlangganan ke massif.', 'ja': 'マッシーフを購読しています。'},
    'You are subscribed to the region.': {'fr': 'Vous êtes abonné à la région.', 'es': 'Estás suscrito a la región.', 'de': 'Sie haben die Region abonniert.', 'it': 'Sei iscritto alla regione.', 'pt': 'Está subscrito à região.', 'nl': 'U bent geabonneerd op de regio.', 'ca': 'Esteu subscrit a la regió.', 'ro': 'Ești abonat la regiune.', 'bg': 'Абонирани сте за региона.', 'el': 'Έχετε εγγραφεί στην περιοχή.', 'ar': 'أنت مشترك في المنطقة.', 'he': 'אתה מנוי לאזור.', 'id': 'Anda berlangganan ke wilayah.', 'ja': '地域を購読しています。'},
    'You are unsubscribed from the country.': {'fr': 'Vous êtes désabonné du pays.', 'es': 'Te has desuscrito del país.', 'de': 'Sie haben das Land abbestellt.', 'it': 'Ti sei discritto dal paese.', 'pt': 'Cancelou a subscrição do país.', 'nl': 'U heeft het land afgemeld.', 'ca': 'Heu cancel·lat la subscripció al país.', 'ro': 'Ești dezabonat din țară.', 'bg': 'Отписани сте от страната.', 'el': 'Έχετε καταργήσει την εγγραφή από τη χώρα.', 'ar': 'تم إلغاء اشتراكك في البلد.', 'he': 'ביטלת את המנוי למדינה.', 'id': 'Anda berhenti berlangganan dari negara.', 'ja': '国の購読を解除しました。'},
    'You have no notifications.': {'fr': 'Vous n\'avez aucune notification.', 'es': 'No tienes notificaciones.', 'de': 'Sie haben keine Benachrichtigungen.', 'it': 'Non hai notifiche.', 'pt': 'Não tem notificações.', 'nl': 'U heeft geen meldingen.', 'ca': 'No teniu notificacions.', 'ro': 'Nu ai notificări.', 'bg': 'Нямате известия.', 'el': 'Δεν έχετε ειδοποιήσεις.', 'ar': 'ليس لديك إشعارات.', 'he': 'אין לך התראות.', 'id': 'Anda tidak memiliki notifikasi.', 'ja': '通知はありません。'},
    'You must be authenticated': {'fr': 'Vous devez être authentifié', 'es': 'Debes estar autenticado', 'de': 'Sie müssen authentifiziert sein', 'it': 'Devi essere autenticato', 'pt': 'Deve estar autenticado', 'nl': 'U moet geauthenticeerd zijn', 'ca': 'Heu d\'estar autenticat', 'ro': 'Trebuie să fii autentificat', 'bg': 'Трябва да сте удостоверени', 'el': 'Πρέπει να είστε πιστοποιημένος', 'ar': 'يجب أن تكون مصادقاً', 'he': 'עליך להיות מאומת', 'id': 'Anda harus terautentikasi', 'ja': '認証が必要です'},
    'You must provide a valid email.': {'fr': 'Vous devez fournir un email valide.', 'es': 'Debe proporcionar un correo electrónico válido.', 'de': 'Sie müssen eine gültige E-Mail angeben.', 'it': 'Devi fornire un email valido.', 'pt': 'Deve fornecer um email válido.', 'nl': 'U moet een geldig e-mailadres opgeven.', 'ca': 'Heu de proporcionar un correu electrònic vàlid.', 'ro': 'Trebuie să furnizați un email valid.', 'bg': 'Трябва да предоставите валиден имейл.', 'el': 'Πρέπει να παρέχετε έγκυρο email.', 'ar': 'يجب تقديم بريد إلكتروني صالح.', 'he': 'עליך לספק אימייל תקין.', 'id': 'Anda harus memberikan email yang valid.', 'ja': '有効なメールアドレスを入力してください。'},
    'Your account has been successfully created!': {'fr': 'Votre compte a été créé avec succès !', 'es': '¡Tu cuenta ha sido creada exitosamente!', 'de': 'Ihr Konto wurde erfolgreich erstellt!', 'it': 'Il tuo account è stato creato con successo!', 'pt': 'A sua conta foi criada com sucesso!', 'nl': 'Uw account is succesvol aangemaakt!', 'ca': 'El vostre compte ha estat creat amb èxit!', 'ro': 'Contul dvs. a fost creat cu succes!', 'bg': 'Акаунтът ви е създаден успешно!', 'el': 'Ο λογαριασμός σας δημιουργήθηκε επιτυχώς!', 'ar': 'تم إنشاء حسابك بنجاح!', 'he': 'החשבון שלך נוצר בהצלחה!', 'id': 'Akun Anda berhasil dibuat!', 'ja': 'アカウントが正常に作成されました！'},
    'Your document has been successfully submitted, thank you!': {'fr': 'Votre document a été soumis avec succès, merci !', 'es': '¡Tu documento ha sido enviado exitosamente, gracias!', 'de': 'Ihr Dokument wurde erfolgreich eingereicht, danke!', 'it': 'Il tuo documento è stato inviato con successo, grazie!', 'pt': 'O seu documento foi submetido com sucesso, obrigado!', 'nl': 'Uw document is succesvol ingediend, dank u!', 'ca': 'El vostre document s\'ha enviat amb èxit, gràcies!', 'ro': 'Documentul dvs. a fost trimis cu succes, mulțumim!', 'bg': 'Документът ви е изпратен успешно, благодарим!', 'el': 'Το έγγραφό σας υποβλήθηκε επιτυχώς, ευχαριστούμε!', 'ar': 'تم تقديم مستندك بنجاح، شكراً!', 'he': 'המסמך שלך הוגש בהצלחה, תודה!', 'id': 'Dokumen Anda berhasil dikirimkan, terima kasih!', 'ja': '文書が正常に提出されました。ありがとうございます！'},
    'Your password has been successfully updated!': {'fr': 'Votre mot de passe a été mis à jour avec succès !', 'es': '¡Tu contraseña ha sido actualizada exitosamente!', 'de': 'Ihr Passwort wurde erfolgreich aktualisiert!', 'it': 'La tua password è stata aggiornata con successo!', 'pt': 'A sua palavra-passe foi atualizada com sucesso!', 'nl': 'Uw wachtwoord is succesvol bijgewerkt!', 'ca': 'La vostra contrasenya s\'ha actualitzat amb èxit!', 'ro': 'Parola dvs. a fost actualizată cu succes!', 'bg': 'Паролата ви е актуализирана успешно!', 'el': 'Ο κωδικός σας ενημερώθηκε επιτυχώς!', 'ar': 'تم تحديث كلمة المرور بنجاح!', 'he': 'הסיסמה שלך עודכנה בהצלחה!', 'id': 'Kata sandi Anda berhasil diperbarui!', 'ja': 'パスワードが正常に更新されました！'},
    'Your session has expired: please log in again.': {'fr': 'Votre session a expiré : veuillez vous reconnecter.', 'es': 'Tu sesión ha expirado: inicia sesión de nuevo.', 'de': 'Ihre Sitzung ist abgelaufen: bitte melden Sie sich erneut an.', 'it': 'La tua sessione è scaduta: accedi di nuovo.', 'pt': 'A sua sessão expirou: inicie sessão novamente.', 'nl': 'Uw sessie is verlopen: log opnieuw in.', 'ca': 'La vostra sessió ha expirat: torneu a iniciar sessió.', 'ro': 'Sesiunea dvs. a expirat: vă rugăm să vă autentificați din nou.', 'bg': 'Сесията ви е изтекла: моля влезте отново.', 'el': 'Η συνεδρία σας έχει λήξει: παρακαλώ συνδεθείτε ξανά.', 'ar': 'انتهت جلستك: يرجى تسجيل الدخول مرة أخرى.', 'he': 'פגה תוקף הסשן שלך: אנא התחבר שוב.', 'id': 'Sesi Anda telah kedaluwarsa: harap masuk kembali.', 'ja': 'セッションが期限切れです：再度ログインしてください。'},
}

with open(os.path.join(DIR, 'en.json'), encoding='utf-8') as f:
    en = json.load(f)

total = 0
for lang in ['fr','es','it','pt','de','nl','ca','ro','bg','el','ar','he','id','ja']:
    path = os.path.join(DIR, f'{lang}.json')
    with open(path, encoding='utf-8') as f:
        d = json.load(f)
    n = 0
    for k, langs in T.items():
        if k in en and lang in langs and (k not in d or d[k] == en[k]):
            d[k] = langs[lang]; n += 1
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(dict(sorted(d.items())), f, ensure_ascii=False, indent=2)
    total += n
    print(f'{lang}: +{n}')
print(f'Total: {total}')
