# -*- coding: utf-8 -*-
import json, os
DIR = os.path.dirname(os.path.abspath(__file__))

T = {
    'no name': {'fr': 'sans nom', 'es': 'sin nombre', 'de': 'kein Name', 'it': 'senza nome', 'pt': 'sem nome', 'nl': 'geen naam', 'ca': 'sense nom', 'ro': 'fără nume', 'bg': 'без име', 'el': 'χωρίς όνομα', 'ar': 'بدون اسم', 'he': 'ללא שם', 'id': 'tanpa nama', 'ja': '名前なし'},
    'notifications of current user': {'fr': 'notifications de l\'utilisateur actuel', 'es': 'notificaciones del usuario actual', 'de': 'Benachrichtigungen des aktuellen Benutzers', 'it': 'notifiche dell\'utente attuale', 'pt': 'notificações do utilizador atual', 'nl': 'meldingen van huidige gebruiker', 'ca': 'notificacions de l\'usuari actual', 'ro': 'notificările utilizatorului curent', 'bg': 'известия на текущия потребител', 'el': 'ειδοποιήσεις τρέχοντος χρήστη', 'ar': 'إشعارات المستخدم الحالي', 'he': 'התראות המשתמש הנוכחי', 'id': 'notifikasi pengguna saat ini', 'ja': '現在のユーザーの通知'},
    'on': {'fr': 'le', 'es': 'el', 'de': 'am', 'it': 'il', 'pt': 'em', 'nl': 'op', 'ca': 'el', 'ro': 'pe', 'bg': 'на', 'el': 'στις', 'ar': 'في', 'he': 'ב', 'id': 'pada', 'ja': '日付'},
    'open drawer': {'fr': 'ouvrir le tiroir', 'es': 'abrir el cajón', 'de': 'Schublade öffnen', 'it': 'apri il cassetto', 'pt': 'abrir gaveta', 'nl': 'lade openen', 'ca': 'obrir el calaix', 'ro': 'deschide sertarul', 'bg': 'отвори чекмеджето', 'el': 'άνοιγμα συρταριού', 'ar': 'فتح الدرج', 'he': 'פתח מגירה', 'id': 'buka laci', 'ja': 'ドロワーを開く'},
    'organization': {'fr': 'organisation', 'es': 'organización', 'de': 'Organisation', 'it': 'organizzazione', 'pt': 'organização', 'nl': 'organisatie', 'ca': 'organització', 'ro': 'organizație', 'bg': 'организация', 'el': 'οργανισμός', 'ar': 'منظمة', 'he': 'ארגון', 'id': 'organisasi', 'ja': '組織'},
    'partners': {'fr': 'partenaires', 'es': 'socios', 'de': 'Partner', 'it': 'partner', 'pt': 'parceiros', 'nl': 'partners', 'ca': 'socis', 'ro': 'parteneri', 'bg': 'партньори', 'el': 'εταίροι', 'ar': 'شركاء', 'he': 'שותפים', 'id': 'mitra', 'ja': 'パートナー'},
    'password.length.error': {'fr': 'Le mot de passe doit comporter au moins {passwordMinLength} caractères.', 'es': 'La contraseña debe tener al menos {passwordMinLength} caracteres.', 'de': 'Das Passwort muss mindestens {passwordMinLength} Zeichen lang sein.', 'it': 'La password deve avere almeno {passwordMinLength} caratteri.', 'pt': 'A palavra-passe deve ter pelo menos {passwordMinLength} caracteres.', 'nl': 'Het wachtwoord moet minimaal {passwordMinLength} tekens bevatten.', 'ca': 'La contrasenya ha de tenir almenys {passwordMinLength} caràcters.', 'ro': 'Parola trebuie să aibă cel puțin {passwordMinLength} caractere.', 'bg': 'Паролата трябва да е поне {passwordMinLength} знака.', 'el': 'Ο κωδικός πρέπει να έχει τουλάχιστον {passwordMinLength} χαρακτήρες.', 'ar': 'يجب أن تتكون كلمة المرور من {passwordMinLength} أحرف على الأقل.', 'he': 'הסיסמה חייבת להיות לפחות {passwordMinLength} תווים.', 'id': 'Kata sandi harus minimal {passwordMinLength} karakter.', 'ja': 'パスワードは{passwordMinLength}文字以上が必要です。'},
    'refBbs': {'fr': 'Réf. BBS', 'es': 'Ref. BBS', 'de': 'Ref. BBS', 'it': 'Rif. BBS', 'pt': 'Ref. BBS', 'nl': 'Ref. BBS', 'ca': 'Ref. BBS', 'ro': 'Ref. BBS', 'bg': 'Реф. BBS', 'el': 'Αναφ. BBS', 'ar': 'مرجع BBS', 'he': 'מזהה BBS', 'id': 'Ref. BBS', 'ja': 'BBS参照'},
    'remove': {'fr': 'supprimer', 'es': 'eliminar', 'de': 'entfernen', 'it': 'rimuovi', 'pt': 'remover', 'nl': 'verwijderen', 'ca': 'eliminar', 'ro': 'elimina', 'bg': 'премахни', 'el': 'αφαίρεση', 'ar': 'إزالة', 'he': 'הסר', 'id': 'hapus', 'ja': '削除'},
    'restore': {'fr': 'restaurer', 'es': 'restaurar', 'de': 'wiederherstellen', 'it': 'ripristina', 'pt': 'restaurar', 'nl': 'herstellen', 'ca': 'restaurar', 'ro': 'restaura', 'bg': 'възстанови', 'el': 'επαναφορά', 'ar': 'استعادة', 'he': 'שחזר', 'id': 'pulihkan', 'ja': '復元'},
    'restored': {'fr': 'restauré', 'es': 'restaurado', 'de': 'wiederhergestellt', 'it': 'ripristinato', 'pt': 'restaurado', 'nl': 'hersteld', 'ca': 'restaurat', 'ro': 'restaurat', 'bg': 'възстановено', 'el': 'αποκαταστάθηκε', 'ar': 'مُستعاد', 'he': 'שוחזר', 'id': 'dipulihkan', 'ja': '復元済み'},
    'rigging': {'fr': 'équipement', 'es': 'equipamiento', 'de': 'Ausrüstung', 'it': 'equipaggiamento', 'pt': 'equipamento', 'nl': 'uitrusting', 'ca': 'equipament', 'ro': 'echipament', 'bg': 'оборудване', 'el': 'εξοπλισμός', 'ar': 'تجهيزات', 'he': 'ציוד', 'id': 'peralatan', 'ja': 'リギング'},
    'ropes': {'fr': 'cordes', 'es': 'cuerdas', 'de': 'Seile', 'it': 'corde', 'pt': 'cordas', 'nl': 'touwen', 'ca': 'cordes', 'ro': 'frânghii', 'bg': 'въжета', 'el': 'σχοινιά', 'ar': 'حبال', 'he': 'חבלים', 'id': 'tali', 'ja': 'ロープ'},
    'since': {'fr': 'depuis', 'es': 'desde', 'de': 'seit', 'it': 'da', 'pt': 'desde', 'nl': 'sinds', 'ca': 'des de', 'ro': 'de la', 'bg': 'от', 'el': 'από', 'ar': 'منذ', 'he': 'מאז', 'id': 'sejak', 'ja': '以来'},
    'speleological abstracts are referenced': {'fr': 'résumés spéléologiques sont référencés', 'es': 'resúmenes espeleológicos están referenciados', 'de': 'Speläologische Zusammenfassungen sind referenziert', 'it': 'abstract speleologici sono referenziati', 'pt': 'resumos espeleológicos são referenciados', 'nl': 'speleologische samenvattingen zijn gerefereerd', 'ca': 'resums espeleològics estan referenciats', 'ro': 'rezumate speleologice sunt referențiate', 'bg': 'спелеологически абстракти са посочени', 'el': 'σπηλαιολογικά περιλήψεις αναφέρονται', 'ar': 'ملخصات الكهوف مُشار إليها', 'he': 'תקצירים ספלאולוגיים מוזכרים', 'id': 'abstrak speleologi direferensikan', 'ja': '洞窟学要旨が参照済み'},
    'surname': {'fr': 'nom de famille', 'es': 'apellido', 'de': 'Nachname', 'it': 'cognome', 'pt': 'apelido', 'nl': 'achternaam', 'ca': 'cognom', 'ro': 'prenume', 'bg': 'фамилия', 'el': 'επώνυμο', 'ar': 'اسم العائلة', 'he': 'שם משפחה', 'id': 'nama belakang', 'ja': '姓'},
    'take all': {'fr': 'tout prendre', 'es': 'tomar todo', 'de': 'alles nehmen', 'it': 'prendi tutto', 'pt': 'tomar tudo', 'nl': 'alles nemen', 'ca': 'agafar-ho tot', 'ro': 'luați tot', 'bg': 'вземи всичко', 'el': 'πάρτε όλα', 'ar': 'خذ الكل', 'he': 'קח הכל', 'id': 'ambil semua', 'ja': 'すべて取得'},
    'the cave': {'fr': 'la cavité', 'es': 'la cueva', 'de': 'die Höhle', 'it': 'la grotta', 'pt': 'a caverna', 'nl': 'de grot', 'ca': 'la cova', 'ro': 'peștera', 'bg': 'пещерата', 'el': 'το σπήλαιο', 'ar': 'الكهف', 'he': 'המערה', 'id': 'gua', 'ja': '洞窟'},
    'the document': {'fr': 'le document', 'es': 'el documento', 'de': 'das Dokument', 'it': 'il documento', 'pt': 'o documento', 'nl': 'het document', 'ca': 'el document', 'ro': 'documentul', 'bg': 'документа', 'el': 'το έγγραφο', 'ar': 'المستند', 'he': 'המסמך', 'id': 'dokumen', 'ja': '文書'},
    'the entrance': {'fr': 'l\'entrée', 'es': 'la entrada', 'de': 'der Eingang', 'it': 'l\'ingresso', 'pt': 'a entrada', 'nl': 'de ingang', 'ca': 'l\'entrada', 'ro': 'intrarea', 'bg': 'входа', 'el': 'η είσοδος', 'ar': 'المدخل', 'he': 'הכניסה', 'id': 'pintu masuk', 'ja': '入口'},
    'the organization': {'fr': 'l\'organisation', 'es': 'la organización', 'de': 'die Organisation', 'it': 'l\'organizzazione', 'pt': 'a organização', 'nl': 'de organisatie', 'ca': 'l\'organització', 'ro': 'organizația', 'bg': 'организацията', 'el': 'ο οργανισμός', 'ar': 'المنظمة', 'he': 'הארגון', 'id': 'organisasi', 'ja': '組織'},
    'title duplicate': {'fr': 'titre en double', 'es': 'título duplicado', 'de': 'Doppelter Titel', 'it': 'titolo duplicato', 'pt': 'título duplicado', 'nl': 'dubbele titel', 'ca': 'títol duplicat', 'ro': 'titlu duplicat', 'bg': 'дублиращо заглавие', 'el': 'διπλός τίτλος', 'ar': 'عنوان مكرر', 'he': 'כותרת כפולה', 'id': 'judul duplikat', 'ja': 'タイトル重複'},
    'toggle password visibility': {'fr': 'afficher/masquer le mot de passe', 'es': 'mostrar/ocultar contraseña', 'de': 'Passwort-Sichtbarkeit umschalten', 'it': 'mostra/nascondi password', 'pt': 'alternar visibilidade da palavra-passe', 'nl': 'wachtwoordzichtbaarheid wisselen', 'ca': 'alternar visibilitat de la contrasenya', 'ro': 'comutare vizibilitate parolă', 'bg': 'превключи видимостта на паролата', 'el': 'εναλλαγή ορατότητας κωδικού', 'ar': 'تبديل ظهور كلمة المرور', 'he': 'החלף נראות סיסמה', 'id': 'alihkan visibilitas kata sandi', 'ja': 'パスワード表示切替'},
    'unexpected error': {'fr': 'erreur inattendue', 'es': 'error inesperado', 'de': 'unerwarteter Fehler', 'it': 'errore imprevisto', 'pt': 'erro inesperado', 'nl': 'onverwachte fout', 'ca': 'error inesperat', 'ro': 'eroare neașteptată', 'bg': 'неочаквана грешка', 'el': 'απροσδόκητο σφάλμα', 'ar': 'خطأ غير متوقع', 'he': 'שגיאה בלתי צפויה', 'id': 'kesalahan tak terduga', 'ja': '予期しないエラー'},
    'unknown': {'fr': 'inconnu', 'es': 'desconocido', 'de': 'unbekannt', 'it': 'sconosciuto', 'pt': 'desconhecido', 'nl': 'onbekend', 'ca': 'desconegut', 'ro': 'necunoscut', 'bg': 'неизвестен', 'el': 'άγνωστο', 'ar': 'مجهول', 'he': 'לא ידוע', 'id': 'tidak dikenal', 'ja': '不明'},
    'unlink': {'fr': 'délier', 'es': 'desvincular', 'de': 'verknüpfung aufheben', 'it': 'scollega', 'pt': 'desvincular', 'nl': 'ontkoppelen', 'ca': 'desenllaçar', 'ro': 'dezleaga', 'bg': 'премахни връзката', 'el': 'αποσύνδεση', 'ar': 'إلغاء الربط', 'he': 'בטל קישור', 'id': 'putuskan tautan', 'ja': 'リンク解除'},
    'updated': {'fr': 'mis à jour', 'es': 'actualizado', 'de': 'aktualisiert', 'it': 'aggiornato', 'pt': 'atualizado', 'nl': 'bijgewerkt', 'ca': 'actualitzat', 'ro': 'actualizat', 'bg': 'актуализирано', 'el': 'ενημερώθηκε', 'ar': 'محدّث', 'he': 'עודכן', 'id': 'diperbarui', 'ja': '更新済み'},
    'validated': {'fr': 'validé', 'es': 'validado', 'de': 'validiert', 'it': 'validato', 'pt': 'validado', 'nl': 'gevalideerd', 'ca': 'validat', 'ro': 'validat', 'bg': 'валидирано', 'el': 'επικυρώθηκε', 'ar': 'تم التحقق', 'he': 'אושר', 'id': 'divalidasi', 'ja': '検証済み'},
    'vertices': {'fr': 'sommets', 'es': 'vértices', 'de': 'Knoten', 'it': 'vertici', 'pt': 'vértices', 'nl': 'hoekpunten', 'ca': 'vèrtexs', 'ro': 'vârfuri', 'bg': 'върхове', 'el': 'κορυφές', 'ar': 'رؤوس', 'he': 'צמתים', 'id': 'simpul', 'ja': '頂点'},
    'with': {'fr': 'avec', 'es': 'con', 'de': 'mit', 'it': 'con', 'pt': 'com', 'nl': 'met', 'ca': 'amb', 'ro': 'cu', 'bg': 'с', 'el': 'με', 'ar': 'مع', 'he': 'עם', 'id': 'dengan', 'ja': 'で'},
    '{0} h': {'fr': '{0} h', 'es': '{0} h', 'de': '{0} Std.', 'it': '{0} h', 'pt': '{0} h', 'nl': '{0} u', 'ca': '{0} h', 'ro': '{0} h', 'bg': '{0} ч', 'el': '{0} ώ', 'ar': '{0} س', 'he': '{0} ש', 'id': '{0} j', 'ja': '{0} 時間'},
    '{0} h {1}': {'fr': '{0} h {1}', 'es': '{0} h {1}', 'de': '{0} Std. {1} Min.', 'it': '{0} h {1}', 'pt': '{0} h {1}', 'nl': '{0} u {1}', 'ca': '{0} h {1}', 'ro': '{0} h {1}', 'bg': '{0} ч {1}', 'el': '{0} ω {1}', 'ar': '{0} س {1}', 'he': '{0} ש {1}', 'id': '{0} j {1}', 'ja': '{0}時間{1}分'},
    '{0} min': {'fr': '{0} min', 'es': '{0} min', 'de': '{0} Min.', 'it': '{0} min', 'pt': '{0} min', 'nl': '{0} min', 'ca': '{0} min', 'ro': '{0} min', 'bg': '{0} мин', 'el': '{0} λεπτ.', 'ar': '{0} دق', 'he': '{0} דק', 'id': '{0} mnt', 'ja': '{0}分'},
    '{entity} created': {'fr': '{entity} créé', 'es': '{entity} creado', 'de': '{entity} erstellt', 'it': '{entity} creato', 'pt': '{entity} criado', 'nl': '{entity} aangemaakt', 'ca': '{entity} creat', 'ro': '{entity} creat', 'bg': '{entity} създаден', 'el': '{entity} δημιουργήθηκε', 'ar': 'تم إنشاء {entity}', 'he': '{entity} נוצר', 'id': '{entity} dibuat', 'ja': '{entity}が作成されました'},
    '{entity} deleted': {'fr': '{entity} supprimé', 'es': '{entity} eliminado', 'de': '{entity} gelöscht', 'it': '{entity} eliminato', 'pt': '{entity} eliminado', 'nl': '{entity} verwijderd', 'ca': '{entity} eliminat', 'ro': '{entity} șters', 'bg': '{entity} изтрит', 'el': '{entity} διαγράφηκε', 'ar': 'تم حذف {entity}', 'he': '{entity} נמחק', 'id': '{entity} dihapus', 'ja': '{entity}が削除されました'},
    '{entity} updated': {'fr': '{entity} mis à jour', 'es': '{entity} actualizado', 'de': '{entity} aktualisiert', 'it': '{entity} aggiornato', 'pt': '{entity} atualizado', 'nl': '{entity} bijgewerkt', 'ca': '{entity} actualitzat', 'ro': '{entity} actualizat', 'bg': '{entity} актуализиран', 'el': '{entity} ενημερώθηκε', 'ar': 'تم تحديث {entity}', 'he': '{entity} עודכן', 'id': '{entity} diperbarui', 'ja': '{entity}が更新されました'},
}

with open(os.path.join(DIR, 'en.json'), encoding='utf-8') as f:
    en = json.load(f)

total = 0
for lang in ['fr','es','it','pt','de','nl','ca','ro','bg','el','ar','he','id','ja']:
    path = os.path.join(DIR, f'{lang}.json')
    with open(path, encoding='utf-8') as f:
        d = json.load(f)
    n = 0
    for k, langs in T.items():
        if k in en and lang in langs and (k not in d or d[k] == en[k]):
            d[k] = langs[lang]; n += 1
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(dict(sorted(d.items())), f, ensure_ascii=False, indent=2)
    total += n
    print(f'{lang}: +{n}')
print(f'Total: {total}')
