# -*- coding: utf-8 -*-
import json, os
DIR = os.path.dirname(os.path.abspath(__file__))

T = {
    'Apha 2 format (eg: FR)': {'fr': 'Format Alpha 2 (ex : FR)', 'es': 'Formato Alfa 2 (ej: FR)', 'de': 'Alpha-2-Format (z.B.: FR)', 'it': 'Formato Alfa 2 (es: FR)', 'pt': 'Formato Alfa 2 (ex: FR)', 'nl': 'Alfa-2-formaat (bv: FR)', 'ca': 'Format Alfa 2 (ex: FR)', 'ro': 'Format Alpha 2 (ex: FR)', 'bg': 'Формат Алфа 2 (напр. FR)', 'el': 'Μορφή Άλφα 2 (π.χ.: FR)', 'ar': 'صيغة ألفا 2 (مثال: FR)', 'he': 'פורמט אלפא 2 (לדוגמה: FR)', 'id': 'Format Alpha 2 (mis: FR)', 'ja': 'アルファ2形式（例：FR）'},
    'Are you sure you want to unlink this document of this entity?': {'fr': 'Êtes-vous sûr de vouloir délier ce document de cette entité ?', 'es': '¿Está seguro de que desea desvincular este documento de esta entidad?', 'de': 'Sind Sie sicher, dass Sie dieses Dokument von dieser Entität trennen möchten?', 'it': 'Sei sicuro di voler scollegare questo documento da questa entità?', 'pt': 'Tem a certeza que quer desvincular este documento desta entidade?', 'nl': 'Weet u zeker dat u dit document van deze entiteit wilt ontkoppelen?', 'ca': 'Esteu segurs que voleu desvincular aquest document d\'aquesta entitat?', 'ro': 'Sigur doriți să deconectați acest document de această entitate?', 'bg': 'Сигурни ли сте, че искате да премахнете връзката на този документ с тази единица?', 'el': 'Είστε σίγουροι ότι θέλετε να αποσυνδέσετε αυτό το έγγραφο από αυτή την οντότητα;', 'ar': 'هل أنت متأكد من أنك تريد إلغاء ربط هذا المستند بهذا الكيان؟', 'he': 'האם אתה בטוח שברצונך לנתק מסמך זה מישות זו?', 'id': 'Anda yakin ingin memutuskan tautan dokumen ini dari entitas ini?', 'ja': 'このドキュメントをこのエンティティからリンク解除しますか？'},
    'BBS icon': {'fr': 'Icône BBS', 'es': 'Icono BBS', 'de': 'BBS-Symbol', 'it': 'Icona BBS', 'pt': 'Ícone BBS', 'nl': 'BBS-pictogram', 'ca': 'Icona BBS', 'ro': 'Pictogramă BBS', 'bg': 'Икона BBS', 'el': 'Εικονίδιο BBS', 'ar': 'أيقونة BBS', 'he': 'אייקון BBS', 'id': 'Ikon BBS', 'ja': 'BBSアイコン'},
    'Can be a volume (vol.2) or a magazine issue (n°38) for example. Use what is written on the cover of the document.': {'fr': 'Peut être un volume (vol.2) ou un numéro de magazine (n°38) par exemple. Utilisez ce qui est écrit sur la couverture du document.', 'es': 'Puede ser un volumen (vol.2) o un número de revista (n°38) por ejemplo. Use lo que está escrito en la portada del documento.', 'de': 'Kann z.B. ein Band (Bd.2) oder eine Zeitschriftennummer (Nr.38) sein. Verwenden Sie, was auf dem Deckblatt des Dokuments steht.', 'it': 'Può essere un volume (vol.2) o un numero di rivista (n°38) per esempio. Usa ciò che è scritto sulla copertina del documento.', 'pt': 'Pode ser um volume (vol.2) ou um número de revista (n°38) por exemplo. Use o que está escrito na capa do documento.', 'nl': 'Kan een volume (vol.2) of een tijdschriftnummer (nr.38) zijn. Gebruik wat op het omslag van het document staat.', 'ca': 'Pot ser un volum (vol.2) o un número de revista (n°38) per exemple. Useu el que hi ha escrit a la portada del document.', 'ro': 'Poate fi un volum (vol.2) sau un număr de revistă (nr.38) de exemplu. Folosiți ce este scris pe coperta documentului.', 'bg': 'Може да е том (т.2) или брой на списание (бр.38). Използвайте написаното на корицата на документа.', 'el': 'Μπορεί να είναι τόμος (τ.2) ή τεύχος περιοδικού (τ.38). Χρησιμοποιήστε αυτό που αναγράφεται στο εξώφυλλο.', 'ar': 'يمكن أن يكون مجلداً (مج.2) أو عدداً من مجلة (ع.38). استخدم ما هو مكتوب على غلاف المستند.', 'he': 'יכול להיות כרך (כ.2) או גיליון כתב עת (מ.38). השתמש במה שכתוב על כריכת המסמך.', 'id': 'Bisa berupa volume (vol.2) atau edisi majalah (n°38). Gunakan apa yang tertulis di sampul dokumen.', 'ja': '例えばボリューム（vol.2）や雑誌号（n°38）。文書の表紙に書かれているものを使用してください。'},
    'Choose from the types of documents available.': {'fr': 'Choisissez parmi les types de documents disponibles.', 'es': 'Elija entre los tipos de documentos disponibles.', 'de': 'Wählen Sie aus den verfügbaren Dokumenttypen.', 'it': 'Scegli tra i tipi di documenti disponibili.', 'pt': 'Escolha entre os tipos de documentos disponíveis.', 'nl': 'Kies uit de beschikbare documenttypen.', 'ca': 'Trieu entre els tipus de documents disponibles.', 'ro': 'Alegeți dintre tipurile de documente disponibile.', 'bg': 'Изберете от наличните типове документи.', 'el': 'Επιλέξτε από τους διαθέσιμους τύπους εγγράφων.', 'ar': 'اختر من أنواع المستندات المتاحة.', 'he': 'בחר מסוגי המסמכים הזמינים.', 'id': 'Pilih dari jenis dokumen yang tersedia.', 'ja': '利用可能な文書タイプから選択してください。'},
    'Code for designating a document in a unique way. This can be a DOI, URL, ISBN or ISSN.': {'fr': 'Code permettant de désigner un document de manière unique. Il peut s\'agir d\'un DOI, d\'une URL, d\'un ISBN ou d\'un ISSN.', 'es': 'Código para designar un documento de forma única. Puede ser un DOI, URL, ISBN o ISSN.', 'de': 'Code zur eindeutigen Bezeichnung eines Dokuments. Dies kann ein DOI, eine URL, eine ISBN oder eine ISSN sein.', 'it': 'Codice per designare un documento in modo univoco. Può essere un DOI, URL, ISBN o ISSN.', 'pt': 'Código para designar um documento de forma única. Pode ser um DOI, URL, ISBN ou ISSN.', 'nl': 'Code om een document op unieke wijze aan te duiden. Dit kan een DOI, URL, ISBN of ISSN zijn.', 'ca': 'Codi per designar un document de manera única. Pot ser un DOI, URL, ISBN o ISSN.', 'ro': 'Cod pentru desemnarea unică a unui document. Poate fi un DOI, URL, ISBN sau ISSN.', 'bg': 'Код за уникално обозначаване на документ. Може да е DOI, URL, ISBN или ISSN.', 'el': 'Κωδικός για τον μοναδικό χαρακτηρισμό ενός εγγράφου. Μπορεί να είναι DOI, URL, ISBN ή ISSN.', 'ar': 'رمز لتعيين مستند بشكل فريد. يمكن أن يكون DOI أو URL أو ISBN أو ISSN.', 'he': 'קוד לציון מסמך באופן ייחודי. יכול להיות DOI, URL, ISBN או ISSN.', 'id': 'Kode untuk menunjuk dokumen secara unik. Bisa berupa DOI, URL, ISBN atau ISSN.', 'ja': '文書を一意に指定するコード。DOI、URL、ISBN、またはISSNが使用できます。'},
    'Contact us if you have any questions or if you want to participate in the project.': {'fr': 'Contactez-nous si vous avez des questions ou si vous souhaitez participer au projet.', 'es': 'Contáctenos si tiene alguna pregunta o si desea participar en el proyecto.', 'de': 'Kontaktieren Sie uns, wenn Sie Fragen haben oder am Projekt teilnehmen möchten.', 'it': 'Contattaci se hai domande o se vuoi partecipare al progetto.', 'pt': 'Contacte-nos se tiver dúvidas ou se quiser participar no projeto.', 'nl': 'Neem contact met ons op als u vragen heeft of als u wilt deelnemen aan het project.', 'ca': 'Contacteu-nos si teniu preguntes o si voleu participar al projecte.', 'ro': 'Contactați-ne dacă aveți întrebări sau dacă doriți să participați la proiect.', 'bg': 'Свържете се с нас, ако имате въпроси или искате да участвате в проекта.', 'el': 'Επικοινωνήστε μαζί μας αν έχετε ερωτήσεις ή θέλετε να συμμετάσχετε στο έργο.', 'ar': 'اتصل بنا إذا كان لديك أي أسئلة أو إذا كنت تريد المشاركة في المشروع.', 'he': 'צור קשר אם יש לך שאלות או אם תרצה להשתתף בפרויקט.', 'id': 'Hubungi kami jika Anda memiliki pertanyaan atau ingin berpartisipasi dalam proyek.', 'ja': 'ご質問やプロジェクトへの参加をご希望の方はお問い合わせください。'},
    'Csv content': {'fr': 'Contenu CSV', 'es': 'Contenido CSV', 'de': 'CSV-Inhalt', 'it': 'Contenuto CSV', 'pt': 'Conteúdo CSV', 'nl': 'CSV-inhoud', 'ca': 'Contingut CSV', 'ro': 'Conținut CSV', 'bg': 'CSV съдържание', 'el': 'Περιεχόμενο CSV', 'ar': 'محتوى CSV', 'he': 'תוכן CSV', 'id': 'Konten CSV', 'ja': 'CSVコンテンツ'},
    'Custom message': {'fr': 'Message personnalisé', 'es': 'Mensaje personalizado', 'de': 'Benutzerdefinierte Nachricht', 'it': 'Messaggio personalizzato', 'pt': 'Mensagem personalizada', 'nl': 'Aangepast bericht', 'ca': 'Missatge personalitzat', 'ro': 'Mesaj personalizat', 'bg': 'Персонализирано съобщение', 'el': 'Προσαρμοσμένο μήνυμα', 'ar': 'رسالة مخصصة', 'he': 'הודעה מותאמת אישית', 'id': 'Pesan kustom', 'ja': 'カスタムメッセージ'},
    'Data encoded in a defined structure': {'fr': 'Données encodées dans une structure définie', 'es': 'Datos codificados en una estructura definida', 'de': 'In einer definierten Struktur kodierte Daten', 'it': 'Dati codificati in una struttura definita', 'pt': 'Dados codificados numa estrutura definida', 'nl': 'Gegevens gecodeerd in een gedefinieerde structuur', 'ca': 'Dades codificades en una estructura definida', 'ro': 'Date codificate într-o structură definită', 'bg': 'Данни кодирани в определена структура', 'el': 'Δεδομένα κωδικοποιημένα σε καθορισμένη δομή', 'ar': 'بيانات مشفرة في بنية محددة', 'he': 'נתונים מקודדים במבנה מוגדר', 'id': 'Data yang dikodekan dalam struktur yang ditentukan', 'ja': '定義された構造でエンコードされたデータ'},
    'Data is already in the database and should be selected when possible': {'fr': 'Les données sont déjà dans la base de données et doivent être sélectionnées si possible', 'es': 'Los datos ya están en la base de datos y deben seleccionarse cuando sea posible', 'de': 'Die Daten sind bereits in der Datenbank und sollten wenn möglich ausgewählt werden', 'it': 'I dati sono già nel database e devono essere selezionati quando possibile', 'pt': 'Os dados já estão na base de dados e devem ser selecionados quando possível', 'nl': 'Gegevens zijn al in de database en moeten indien mogelijk worden geselecteerd', 'ca': 'Les dades ja estan a la base de dades i s\'han de seleccionar quan sigui possible', 'ro': 'Datele sunt deja în baza de date și trebuie selectate când este posibil', 'bg': 'Данните вече са в базата данни и трябва да бъдат избрани когато е възможно', 'el': 'Τα δεδομένα βρίσκονται ήδη στη βάση και πρέπει να επιλεγούν όταν είναι δυνατόν', 'ar': 'البيانات موجودة بالفعل في قاعدة البيانات ويجب تحديدها عند الإمكان', 'he': 'הנתונים כבר במסד הנתונים ויש לבחור בהם כשאפשר', 'id': 'Data sudah ada di database dan harus dipilih jika memungkinkan', 'ja': 'データはすでにデータベースにあり、可能な場合は選択する必要があります'},
    'Data is not in the database and will be created when selected': {'fr': 'Les données ne sont pas dans la base de données et seront créées lors de la sélection', 'es': 'Los datos no están en la base de datos y se crearán al seleccionarlos', 'de': 'Die Daten befinden sich nicht in der Datenbank und werden bei Auswahl erstellt', 'it': 'I dati non sono nel database e verranno creati alla selezione', 'pt': 'Os dados não estão na base de dados e serão criados ao selecionar', 'nl': 'Gegevens staan niet in de database en worden aangemaakt bij selectie', 'ca': 'Les dades no estan a la base de dades i es crearan en seleccionar-les', 'ro': 'Datele nu sunt în baza de date și vor fi create la selectare', 'bg': 'Данните не са в базата данни и ще бъдат създадени при избор', 'el': 'Τα δεδομένα δεν βρίσκονται στη βάση και θα δημιουργηθούν κατά την επιλογή', 'ar': 'البيانات غير موجودة في قاعدة البيانات وسيتم إنشاؤها عند التحديد', 'he': 'הנתונים אינם במסד הנתונים וייוצרו בעת הבחירה', 'id': 'Data tidak ada di database dan akan dibuat saat dipilih', 'ja': 'データはデータベースになく、選択時に作成されます'},
    'Dear %s': {'fr': 'Cher %s', 'es': 'Estimado %s', 'de': 'Sehr geehrte/r %s', 'it': 'Caro %s', 'pt': 'Caro %s', 'nl': 'Geachte %s', 'ca': 'Benvolgut %s', 'ro': 'Stimate %s', 'bg': 'Уважаеми %s', 'el': 'Αγαπητέ %s', 'ar': 'عزيزي %s', 'he': 'יקר/ה %s', 'id': 'Yang terhormat %s', 'ja': '拝啓 %s 様'},
    'Document attesting to the authorization to publish other documents under a defined licence': {'fr': 'Document attestant l\'autorisation de publier d\'autres documents sous une licence définie', 'es': 'Documento que acredita la autorización para publicar otros documentos bajo una licencia definida', 'de': 'Dokument, das die Genehmigung zur Veröffentlichung anderer Dokumente unter einer definierten Lizenz bescheinigt', 'it': 'Documento che attesta l\'autorizzazione a pubblicare altri documenti sotto una licenza definita', 'pt': 'Documento que atesta a autorização para publicar outros documentos sob uma licença definida', 'nl': 'Document dat de toestemming bevestigt om andere documenten te publiceren onder een gedefinieerde licentie', 'ca': 'Document que acredita l\'autorització per publicar altres documents sota una llicència definida', 'ro': 'Document care atestă autorizația de a publica alte documente sub o licență definită', 'bg': 'Документ, удостоверяващ разрешение за публикуване на други документи под определен лиценз', 'el': 'Έγγραφο που βεβαιώνει την άδεια δημοσίευσης άλλων εγγράφων υπό ορισμένη άδεια', 'ar': 'مستند يثبت الإذن بنشر مستندات أخرى بموجب ترخيص محدد', 'he': 'מסמך המעיד על רשות לפרסם מסמכים אחרים תחת רישיון מוגדר', 'id': 'Dokumen yang membuktikan izin untuk menerbitkan dokumen lain di bawah lisensi yang ditentukan', 'ja': '定義されたライセンスの下で他の文書を公開する許可を証明する文書'},
    'Documentary speleology': {'fr': 'Spéléologie documentaire', 'es': 'Espeleología documental', 'de': 'Dokumentarische Speläologie', 'it': 'Speleologia documentaria', 'pt': 'Espeleologia documental', 'nl': 'Documentaire speleologie', 'ca': 'Espeleologia documental', 'ro': 'Speologie documentară', 'bg': 'Документална спелеология', 'el': 'Τεκμηριωτική σπηλαιολογία', 'ar': 'علم الكهوف التوثيقي', 'he': 'ספלאולוגיה תיעודית', 'id': 'Speleologi dokumenter', 'ja': '文献洞窟学'},
    "Don't leave it too late though, this link is only available for 24 hours.": {'fr': "Ne tardez pas trop, ce lien n'est disponible que 24 heures.", 'es': 'No lo deje para demasiado tarde, este enlace solo está disponible durante 24 horas.', 'de': 'Beeilen Sie sich jedoch, dieser Link ist nur 24 Stunden lang verfügbar.', 'it': 'Non aspettare troppo però, questo link è disponibile solo per 24 ore.', 'pt': 'Não tarde, no entanto, este link só está disponível durante 24 horas.', 'nl': 'Wacht echter niet te lang, deze link is slechts 24 uur beschikbaar.', 'ca': 'No tardeu massa, aquest enllaç només està disponible durant 24 hores.', 'ro': 'Nu întârziați, totuși, acest link este disponibil doar 24 de ore.', 'bg': 'Не чакайте обаче, тази връзка е достъпна само 24 часа.', 'el': 'Μην αργείτε όμως, αυτός ο σύνδεσμος είναι διαθέσιμος μόνο για 24 ώρες.', 'ar': 'لا تتأخر كثيراً، هذا الرابط متاح فقط لمدة 24 ساعة.', 'he': 'אל תאחר מדי, קישור זה זמין רק למשך 24 שעות.', 'id': 'Jangan terlambat, tautan ini hanya tersedia selama 24 jam.', 'ja': '急いでください。このリンクは24時間のみ有効です。'},
    "Don't leave this page while the document is being created.": {'fr': 'Ne quittez pas cette page pendant la création du document.', 'es': 'No abandone esta página mientras se crea el documento.', 'de': 'Verlassen Sie diese Seite nicht, während das Dokument erstellt wird.', 'it': 'Non lasciare questa pagina mentre il documento viene creato.', 'pt': 'Não saia desta página enquanto o documento está a ser criado.', 'nl': 'Verlaat deze pagina niet terwijl het document wordt aangemaakt.', 'ca': 'No sortiu d\'aquesta pàgina mentre es crea el document.', 'ro': 'Nu părăsiți această pagină în timp ce documentul este creat.', 'bg': 'Не напускайте тази страница докато документът се създава.', 'el': 'Μην αφήσετε αυτή τη σελίδα ενώ δημιουργείται το έγγραφο.', 'ar': 'لا تغادر هذه الصفحة أثناء إنشاء المستند.', 'he': 'אל תעזוב דף זה בזמן יצירת המסמך.', 'id': 'Jangan tinggalkan halaman ini saat dokumen sedang dibuat.', 'ja': '文書が作成中はこのページを離れないでください。'},
    'Duplicate id': {'fr': 'Id en double', 'es': 'Id duplicado', 'de': 'Doppelte ID', 'it': 'ID duplicato', 'pt': 'ID duplicado', 'nl': 'Dubbele ID', 'ca': 'ID duplicat', 'ro': 'ID duplicat', 'bg': 'Дублиращо ID', 'el': 'Διπλό αναγνωριστικό', 'ar': 'معرف مكرر', 'he': 'מזהה כפול', 'id': 'ID duplikat', 'ja': '重複ID'},
    'Duplicates from CSV import tool': {'fr': 'Doublons de l\'outil d\'importation CSV', 'es': 'Duplicados de la herramienta de importación CSV', 'de': 'Duplikate aus dem CSV-Importwerkzeug', 'it': 'Duplicati dallo strumento di importazione CSV', 'pt': 'Duplicados da ferramenta de importação CSV', 'nl': 'Duplicaten uit CSV-importtool', 'ca': 'Duplicats de l\'eina d\'importació CSV', 'ro': 'Duplicate din instrumentul de import CSV', 'bg': 'Дубликати от инструмента за CSV импорт', 'el': 'Διπλότυπα από εργαλείο εισαγωγής CSV', 'ar': 'التكرارات من أداة استيراد CSV', 'he': 'כפילויות מכלי ייבוא CSV', 'id': 'Duplikat dari alat impor CSV', 'ja': 'CSVインポートツールからの重複'},
    'Entries icon': {'fr': 'Icône d\'entrées', 'es': 'Icono de entradas', 'de': 'Eingänge-Symbol', 'it': 'Icona ingressi', 'pt': 'Ícone de entradas', 'nl': 'Ingangen-pictogram', 'ca': 'Icona d\'entrades', 'ro': 'Pictogramă intrări', 'bg': 'Икона на входове', 'el': 'Εικονίδιο εισόδων', 'ar': 'أيقونة المداخل', 'he': 'אייקון כניסות', 'id': 'Ikon pintu masuk', 'ja': '入口アイコン'},
    'Error, the document data you are looking for is not available.': {'fr': 'Erreur, les données du document que vous recherchez ne sont pas disponibles.', 'es': 'Error, los datos del documento que busca no están disponibles.', 'de': 'Fehler, die Dokumentdaten sind nicht verfügbar.', 'it': 'Errore, i dati del documento non sono disponibili.', 'pt': 'Erro, os dados do documento não estão disponíveis.', 'nl': 'Fout, de documentgegevens zijn niet beschikbaar.', 'ca': 'Error, les dades del document no estan disponibles.', 'ro': 'Eroare, datele documentului nu sunt disponibile.', 'bg': 'Грешка, данните за документа не са налични.', 'el': 'Σφάλμα, τα δεδομένα εγγράφου δεν είναι διαθέσιμα.', 'ar': 'خطأ، بيانات المستند غير متاحة.', 'he': 'שגיאה, נתוני המסמך אינם זמינים.', 'id': 'Kesalahan, data dokumen tidak tersedia.', 'ja': 'エラー：文書データは利用できません。'},
    'Error, the network data you are looking for is not available.': {'fr': 'Erreur, les données du réseau que vous recherchez ne sont pas disponibles.', 'es': 'Error, los datos de la red no están disponibles.', 'de': 'Fehler, die Netzwerkdaten sind nicht verfügbar.', 'it': 'Errore, i dati della rete non sono disponibili.', 'pt': 'Erro, os dados da rede não estão disponíveis.', 'nl': 'Fout, de netwerkgegevens zijn niet beschikbaar.', 'ca': 'Error, les dades de la xarxa no estan disponibles.', 'ro': 'Eroare, datele rețelei nu sunt disponibile.', 'bg': 'Грешка, данните за мрежата не са налични.', 'el': 'Σφάλμα, τα δεδομένα δικτύου δεν είναι διαθέσιμα.', 'ar': 'خطأ، بيانات الشبكة غير متاحة.', 'he': 'שגיאה, נתוני הרשת אינם זמינים.', 'id': 'Kesalahan, data jaringan tidak tersedia.', 'ja': 'エラー：ネットワークデータは利用できません。'},
    'Error, the region data you are looking for is not available.': {'fr': 'Erreur, les données de la région ne sont pas disponibles.', 'es': 'Error, los datos de la región no están disponibles.', 'de': 'Fehler, die Regionsdaten sind nicht verfügbar.', 'it': 'Errore, i dati della regione non sono disponibili.', 'pt': 'Erro, os dados da região não estão disponíveis.', 'nl': 'Fout, de regiogegevens zijn niet beschikbaar.', 'ca': 'Error, les dades de la regió no estan disponibles.', 'ro': 'Eroare, datele regiunii nu sunt disponibile.', 'bg': 'Грешка, данните за региона не са налични.', 'el': 'Σφάλμα, τα δεδομένα περιοχής δεν είναι διαθέσιμα.', 'ar': 'خطأ، بيانات المنطقة غير متاحة.', 'he': 'שגיאה, נתוני האזור אינם זמינים.', 'id': 'Kesalahan, data wilayah tidak tersedia.', 'ja': 'エラー：地域データは利用できません。'},
    'Expiration Date: {expirationDate} at {expirationHourAndMinutes}': {'fr': 'Date d\'expiration : {expirationDate} à {expirationHourAndMinutes}', 'es': 'Fecha de vencimiento: {expirationDate} a las {expirationHourAndMinutes}', 'de': 'Ablaufdatum: {expirationDate} um {expirationHourAndMinutes}', 'it': 'Data di scadenza: {expirationDate} alle {expirationHourAndMinutes}', 'pt': 'Data de expiração: {expirationDate} às {expirationHourAndMinutes}', 'nl': 'Vervaldatum: {expirationDate} om {expirationHourAndMinutes}', 'ca': 'Data d\'expiració: {expirationDate} a les {expirationHourAndMinutes}', 'ro': 'Data expirării: {expirationDate} la {expirationHourAndMinutes}', 'bg': 'Дата на изтичане: {expirationDate} в {expirationHourAndMinutes}', 'el': 'Ημερομηνία λήξης: {expirationDate} στις {expirationHourAndMinutes}', 'ar': 'تاريخ الانتهاء: {expirationDate} في {expirationHourAndMinutes}', 'he': 'תאריך תפוגה: {expirationDate} בשעה {expirationHourAndMinutes}', 'id': 'Tanggal kedaluwarsa: {expirationDate} pukul {expirationHourAndMinutes}', 'ja': '有効期限: {expirationDate} {expirationHourAndMinutes}'},
    'Exploring organizations': {'fr': 'Organisations exploratrices', 'es': 'Organizaciones exploradoras', 'de': 'Erkundungsorganisationen', 'it': 'Organizzazioni esploratrici', 'pt': 'Organizações exploradoras', 'nl': 'Verkenningsorganisaties', 'ca': 'Organitzacions exploradores', 'ro': 'Organizații exploratoare', 'bg': 'Изследователски организации', 'el': 'Εξερευνητικές οργανώσεις', 'ar': 'منظمات الاستكشاف', 'he': 'ארגוני חקירה', 'id': 'Organisasi penjelajah', 'ja': '探検組織'},
}

with open(os.path.join(DIR, 'en.json'), encoding='utf-8') as f:
    en = json.load(f)

total = 0
for lang in ['fr','es','it','pt','de','nl','ca','ro','bg','el','ar','he','id','ja']:
    path = os.path.join(DIR, f'{lang}.json')
    with open(path, encoding='utf-8') as f:
        d = json.load(f)
    n = 0
    for k, langs in T.items():
        if k in en and lang in langs and (k not in d or d[k] == en[k]):
            d[k] = langs[lang]; n += 1
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(dict(sorted(d.items())), f, ensure_ascii=False, indent=2)
    total += n
    print(f'{lang}: +{n}')
print(f'Total: {total}')
