# -*- coding: utf-8 -*-
import json, os
DIR = os.path.dirname(os.path.abspath(__file__))

T = {
    'Failed to parse file': {'fr': 'Échec de l\'analyse du fichier', 'es': 'Error al analizar el archivo', 'de': 'Datei konnte nicht geparst werden', 'it': 'Impossibile analizzare il file', 'pt': 'Falha ao analisar o ficheiro', 'nl': 'Bestand kon niet worden geparsed', 'ca': 'Error en analitzar el fitxer', 'ro': 'Eșec la parsarea fișierului', 'bg': 'Неуспешен анализ на файла', 'el': 'Αποτυχία ανάλυσης αρχείου', 'ar': 'فشل تحليل الملف', 'he': 'כשל בניתוח הקובץ', 'id': 'Gagal mengurai file', 'ja': 'ファイルの解析に失敗'},
    'Failed to parse shapefile. Please check the file format.': {'fr': 'Échec de l\'analyse du shapefile. Veuillez vérifier le format du fichier.', 'es': 'Error al analizar el shapefile. Por favor verifique el formato del archivo.', 'de': 'Shapefile konnte nicht geparst werden. Bitte überprüfen Sie das Dateiformat.', 'it': 'Impossibile analizzare lo shapefile. Verificare il formato del file.', 'pt': 'Falha ao analisar o shapefile. Verifique o formato do ficheiro.', 'nl': 'Shapefile kon niet worden geparsed. Controleer het bestandsformaat.', 'ca': 'Error en analitzar el shapefile. Verifiqueu el format del fitxer.', 'ro': 'Eșec la parsarea fișierului shapefile. Verificați formatul fișierului.', 'bg': 'Неуспешен анализ на shapefile. Моля проверете формата на файла.', 'el': 'Αποτυχία ανάλυσης shapefile. Ελέγξτε τη μορφή του αρχείου.', 'ar': 'فشل تحليل ملف الشكل. يرجى التحقق من تنسيق الملف.', 'he': 'כשל בניתוח ה-Shapefile. אנא בדוק את פורמט הקובץ.', 'id': 'Gagal mengurai shapefile. Periksa format file.', 'ja': 'シェープファイルの解析に失敗しました。ファイル形式を確認してください。'},
    'File input': {'fr': 'Entrée de fichier', 'es': 'Entrada de archivo', 'de': 'Dateieingabe', 'it': 'Input file', 'pt': 'Entrada de ficheiro', 'nl': 'Bestandsinvoer', 'ca': 'Entrada de fitxer', 'ro': 'Intrare fișier', 'bg': 'Файлов вход', 'el': 'Είσοδος αρχείου', 'ar': 'إدخال الملف', 'he': 'קלט קובץ', 'id': 'Input file', 'ja': 'ファイル入力'},
    'Final result': {'fr': 'Résultat final', 'es': 'Resultado final', 'de': 'Endergebnis', 'it': 'Risultato finale', 'pt': 'Resultado final', 'nl': 'Eindresultaat', 'ca': 'Resultat final', 'ro': 'Rezultat final', 'bg': 'Краен резултат', 'el': 'Τελικό αποτέλεσμα', 'ar': 'النتيجة النهائية', 'he': 'תוצאה סופית', 'id': 'Hasil akhir', 'ja': '最終結果'},
    'Finish drawing': {'fr': 'Terminer le dessin', 'es': 'Terminar el dibujo', 'de': 'Zeichnen beenden', 'it': 'Termina il disegno', 'pt': 'Terminar o desenho', 'nl': 'Tekenen voltooien', 'ca': 'Acabar el dibuix', 'ro': 'Terminați desenul', 'bg': 'Завърши рисуването', 'el': 'Τέλος σχεδιασμού', 'ar': 'إنهاء الرسم', 'he': 'סיים ציור', 'id': 'Selesai menggambar', 'ja': '描画を終了'},
    'First name': {'fr': 'Prénom', 'es': 'Nombre', 'de': 'Vorname', 'it': 'Nome', 'pt': 'Primeiro nome', 'nl': 'Voornaam', 'ca': 'Nom', 'ro': 'Prenume', 'bg': 'Собствено име', 'el': 'Όνομα', 'ar': 'الاسم الأول', 'he': 'שם פרטי', 'id': 'Nama depan', 'ja': '名'},
    'Follow us on Facebook': {'fr': 'Suivez-nous sur Facebook', 'es': 'Síguenos en Facebook', 'de': 'Folgen Sie uns auf Facebook', 'it': 'Seguici su Facebook', 'pt': 'Siga-nos no Facebook', 'nl': 'Volg ons op Facebook', 'ca': 'Seguiu-nos a Facebook', 'ro': 'Urmăriți-ne pe Facebook', 'bg': 'Последвайте ни в Facebook', 'el': 'Ακολουθήστε μας στο Facebook', 'ar': 'تابعنا على فيسبوك', 'he': 'עקוב אחרינו בפייסבוק', 'id': 'Ikuti kami di Facebook', 'ja': 'Facebookでフォロー'},
    'Full Date': {'fr': 'Date complète', 'es': 'Fecha completa', 'de': 'Vollständiges Datum', 'it': 'Data completa', 'pt': 'Data completa', 'nl': 'Volledige datum', 'ca': 'Data completa', 'ro': 'Dată completă', 'bg': 'Пълна дата', 'el': 'Πλήρης ημερομηνία', 'ar': 'تاريخ كامل', 'he': 'תאריך מלא', 'id': 'Tanggal lengkap', 'ja': '完全な日付'},
    'Geospeleology and Karstology': {'fr': 'Géospéléologie et Karstologie', 'es': 'Geospeleología y Karstología', 'de': 'Geospeläologie und Karstologie', 'it': 'Geospeleologia e Karstologia', 'pt': 'Geospeleologia e Carstologia', 'nl': 'Geospeleologie en Karstologie', 'ca': 'Geospeleologia i Carstologia', 'ro': 'Geospeleologie și Carstologie', 'bg': 'Геоспелеология и Карстология', 'el': 'Γεωσπηλαιολογία και Καρστολογία', 'ar': 'الجيوكهوفية والكارستولوجيا', 'he': 'גיאוספלאולוגיה וקרסטולוגיה', 'id': 'Geospeleologi dan Karstologi', 'ja': '地質洞窟学とカルスト学'},
    'Grottocenter blog': {'fr': 'Blog GrottoCenter', 'es': 'Blog de GrottoCenter', 'de': 'GrottoCenter-Blog', 'it': 'Blog di GrottoCenter', 'pt': 'Blog do GrottoCenter', 'nl': 'GrottoCenter-blog', 'ca': 'Blog de GrottoCenter', 'ro': 'Blogul GrottoCenter', 'bg': 'Блог на GrottoCenter', 'el': 'Ιστολόγιο GrottoCenter', 'ar': 'مدونة GrottoCenter', 'he': 'בלוג GrottoCenter', 'id': 'Blog GrottoCenter', 'ja': 'GrottoCenterブログ'},
    'Grottocenter in numbers': {'fr': 'GrottoCenter en chiffres', 'es': 'GrottoCenter en números', 'de': 'GrottoCenter in Zahlen', 'it': 'GrottoCenter in numeri', 'pt': 'GrottoCenter em números', 'nl': 'GrottoCenter in cijfers', 'ca': 'GrottoCenter en xifres', 'ro': 'GrottoCenter în cifre', 'bg': 'GrottoCenter в числа', 'el': 'GrottoCenter σε αριθμούς', 'ar': 'GrottoCenter بالأرقام', 'he': 'GrottoCenter במספרים', 'id': 'GrottoCenter dalam angka', 'ja': 'GrottoCenterを数字で'},
    'Grottocenter is supported by the FSE and the UIS': {'fr': 'GrottoCenter est soutenu par la FSE et l\'UIS', 'es': 'GrottoCenter está apoyado por la FSE y la UIS', 'de': 'GrottoCenter wird von der FSE und der UIS unterstützt', 'it': 'GrottoCenter è supportato dalla FSE e dall\'UIS', 'pt': 'GrottoCenter é apoiado pela FSE e pela UIS', 'nl': 'GrottoCenter wordt ondersteund door de FSE en de UIS', 'ca': 'GrottoCenter està recolzat per la FSE i la UIS', 'ro': 'GrottoCenter este susținut de FSE și UIS', 'bg': 'GrottoCenter се подкрепя от FSE и UIS', 'el': 'Το GrottoCenter υποστηρίζεται από την FSE και την UIS', 'ar': 'GrottoCenter مدعوم من FSE وUIS', 'he': 'GrottoCenter נתמך על ידי FSE ו-UIS', 'id': 'GrottoCenter didukung oleh FSE dan UIS', 'ja': 'GrottoCenterはFSEとUISに支援されています'},
    'Hidden columns': {'fr': 'Colonnes masquées', 'es': 'Columnas ocultas', 'de': 'Versteckte Spalten', 'it': 'Colonne nascoste', 'pt': 'Colunas ocultas', 'nl': 'Verborgen kolommen', 'ca': 'Columnes ocultes', 'ro': 'Coloane ascunse', 'bg': 'Скрити колони', 'el': 'Κρυφές στήλες', 'ar': 'الأعمدة المخفية', 'he': 'עמודות מוסתרות', 'id': 'Kolom tersembunyi', 'ja': '非表示列'},
    'High vertex count may cause performance issues. Consider increasing simplification.': {'fr': 'Un nombre élevé de sommets peut causer des problèmes de performance. Envisagez d\'augmenter la simplification.', 'es': 'Un número alto de vértices puede causar problemas de rendimiento. Considere aumentar la simplificación.', 'de': 'Eine hohe Knotenanzahl kann Leistungsprobleme verursachen. Erwägen Sie eine stärkere Vereinfachung.', 'it': 'Un numero elevato di vertici può causare problemi di prestazioni. Considera di aumentare la semplificazione.', 'pt': 'Uma contagem alta de vértices pode causar problemas de desempenho. Considere aumentar a simplificação.', 'nl': 'Een hoog aantal hoekpunten kan prestatieproblemen veroorzaken. Overweeg vereenvoudiging te verhogen.', 'ca': 'Un nombre alt de vèrtexs pot causar problemes de rendiment. Considereu augmentar la simplificació.', 'ro': 'Un număr mare de vârfuri poate cauza probleme de performanță. Luați în considerare creșterea simplificării.', 'bg': 'Голям брой върхове може да причини проблеми с производителността. Помислете за увеличаване на опростяването.', 'el': 'Μεγάλος αριθμός κορυφών μπορεί να προκαλέσει προβλήματα απόδοσης. Εξετάστε την αύξηση της απλοποίησης.', 'ar': 'قد يسبب عدد كبير من الرؤوس مشكلات في الأداء. فكر في زيادة التبسيط.', 'he': 'מספר רב של צמתים עלול לגרום לבעיות ביצועים. שקול להגדיל את הפישוט.', 'id': 'Jumlah simpul yang tinggi dapat menyebabkan masalah kinerja. Pertimbangkan meningkatkan penyederhanaan.', 'ja': '頂点数が多いとパフォーマンスの問題が生じる場合があります。簡略化を増やすことを検討してください。'},
    'Import geometry': {'fr': 'Importer la géométrie', 'es': 'Importar geometría', 'de': 'Geometrie importieren', 'it': 'Importa geometria', 'pt': 'Importar geometria', 'nl': 'Geometrie importeren', 'ca': 'Importar geometria', 'ro': 'Importați geometria', 'bg': 'Импортиране на геометрия', 'el': 'Εισαγωγή γεωμετρίας', 'ar': 'استيراد الهندسة', 'he': 'ייבוא גיאומטריה', 'id': 'Impor geometri', 'ja': 'ジオメトリをインポート'},
    'Import source': {'fr': 'Source d\'importation', 'es': 'Fuente de importación', 'de': 'Importquelle', 'it': 'Fonte di importazione', 'pt': 'Fonte de importação', 'nl': 'Importbron', 'ca': 'Font d\'importació', 'ro': 'Sursa importului', 'bg': 'Извор на импорт', 'el': 'Πηγή εισαγωγής', 'ar': 'مصدر الاستيراد', 'he': 'מקור ייבוא', 'id': 'Sumber impor', 'ja': 'インポートソース'},
    'Insufficient permissions to ban this user': {'fr': 'Permissions insuffisantes pour bannir cet utilisateur', 'es': 'Permisos insuficientes para banear a este usuario', 'de': 'Unzureichende Berechtigungen, um diesen Benutzer zu sperren', 'it': 'Permessi insufficienti per bannare questo utente', 'pt': 'Permissões insuficientes para banir este utilizador', 'nl': 'Onvoldoende rechten om deze gebruiker te bannen', 'ca': 'Permisos insuficients per bannir aquest usuari', 'ro': 'Permisiuni insuficiente pentru a bloca acest utilizator', 'bg': 'Недостатъчни права за забрана на този потребител', 'el': 'Ανεπαρκή δικαιώματα για αποκλεισμό αυτού του χρήστη', 'ar': 'صلاحيات غير كافية لحظر هذا المستخدم', 'he': 'הרשאות לא מספיקות לחסימת משתמש זה', 'id': 'Izin tidak cukup untuk memblokir pengguna ini', 'ja': 'このユーザーをBANする権限が不足しています'},
    'Is Part of': {'fr': 'Fait partie de', 'es': 'Es parte de', 'de': 'Ist Teil von', 'it': 'Fa parte di', 'pt': 'Faz parte de', 'nl': 'Maakt deel uit van', 'ca': 'És part de', 'ro': 'Parte din', 'bg': 'Е част от', 'el': 'Αποτελεί μέρος του', 'ar': 'جزء من', 'he': 'חלק מ', 'id': 'Bagian dari', 'ja': '一部である'},
    'Is a partner': {'fr': 'Est un partenaire', 'es': 'Es un socio', 'de': 'Ist ein Partner', 'it': 'È un partner', 'pt': 'É um parceiro', 'nl': 'Is een partner', 'ca': 'És un soci', 'ro': 'Este un partener', 'bg': 'Е партньор', 'el': 'Είναι συνεργάτης', 'ar': 'شريك', 'he': 'הוא שותף', 'id': 'Adalah mitra', 'ja': 'パートナーである'},
    'Is validated': {'fr': 'Est validé', 'es': 'Está validado', 'de': 'Ist validiert', 'it': 'È validato', 'pt': 'Está validado', 'nl': 'Is gevalideerd', 'ca': 'Està validat', 'ro': 'Este validat', 'bg': 'Е валидиран', 'el': 'Είναι επικυρωμένο', 'ar': 'تم التحقق منه', 'he': 'מאושר', 'id': 'Telah divalidasi', 'ja': '検証済み'},
    'It has no impact to select one or the other': {'fr': 'Il n\'y a aucun impact à sélectionner l\'un ou l\'autre', 'es': 'No tiene ningún impacto seleccionar uno u otro', 'de': 'Es hat keinen Einfluss, ob man das eine oder das andere auswählt', 'it': 'Non ha alcun impatto selezionare l\'uno o l\'altro', 'pt': 'Não há impacto em selecionar um ou outro', 'nl': 'Het heeft geen impact om het ene of het andere te selecteren', 'ca': 'No té cap impacte seleccionar l\'un o l\'altre', 'ro': 'Nu are niciun impact să selectați una sau alta', 'bg': 'Няма значение дали ще изберете едното или другото', 'el': 'Δεν έχει καμία επίδραση να επιλέξετε το ένα ή το άλλο', 'ar': 'ليس هناك أي تأثير لاختيار أحدهما أو الآخر', 'he': 'אין השפעה בבחירה באחת מהאפשרויות', 'id': 'Tidak ada dampaknya untuk memilih salah satu atau yang lain', 'ja': 'どちらを選択しても影響はありません'},
    'It will be verified by one of ours moderators.': {'fr': 'Il sera vérifié par l\'un de nos modérateurs.', 'es': 'Será verificado por uno de nuestros moderadores.', 'de': 'Es wird von einem unserer Moderatoren überprüft.', 'it': 'Sarà verificato da uno dei nostri moderatori.', 'pt': 'Será verificado por um dos nossos moderadores.', 'nl': 'Het wordt geverifieerd door een van onze moderatoren.', 'ca': 'Serà verificat per un dels nostres moderadors.', 'ro': 'Va fi verificat de unul dintre moderatorii noștri.', 'bg': 'Ще бъде проверено от един от нашите модератори.', 'el': 'Θα επαληθευτεί από έναν από τους διαχειριστές μας.', 'ar': 'سيتم التحقق منه بواسطة أحد المشرفين لدينا.', 'he': 'זה יאומת על ידי אחד המנחים שלנו.', 'id': 'Ini akan diverifikasi oleh salah satu moderator kami.', 'ja': '私たちのモデレーターの一人が確認します。'},
    'Label language': {'fr': 'Langue de l\'étiquette', 'es': 'Idioma de la etiqueta', 'de': 'Beschriftungssprache', 'it': 'Lingua dell\'etichetta', 'pt': 'Língua do rótulo', 'nl': 'Labeltaal', 'ca': 'Idioma de l\'etiqueta', 'ro': 'Limba etichetei', 'bg': 'Език на етикета', 'el': 'Γλώσσα ετικέτας', 'ar': 'لغة التسمية', 'he': 'שפת התווית', 'id': 'Bahasa label', 'ja': 'ラベルの言語'},
    'Last name': {'fr': 'Nom de famille', 'es': 'Apellido', 'de': 'Nachname', 'it': 'Cognome', 'pt': 'Apelido', 'nl': 'Achternaam', 'ca': 'Cognom', 'ro': 'Nume de familie', 'bg': 'Фамилия', 'el': 'Επώνυμο', 'ar': 'اسم العائلة', 'he': 'שם משפחה', 'id': 'Nama belakang', 'ja': '姓'},
}

with open(os.path.join(DIR, 'en.json'), encoding='utf-8') as f:
    en = json.load(f)

total = 0
for lang in ['fr','es','it','pt','de','nl','ca','ro','bg','el','ar','he','id','ja']:
    path = os.path.join(DIR, f'{lang}.json')
    with open(path, encoding='utf-8') as f:
        d = json.load(f)
    n = 0
    for k, langs in T.items():
        if k in en and lang in langs and (k not in d or d[k] == en[k]):
            d[k] = langs[lang]; n += 1
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(dict(sorted(d.items())), f, ensure_ascii=False, indent=2)
    total += n
    print(f'{lang}: +{n}')
print(f'Total: {total}')
