# -*- coding: utf-8 -*-
import json, os
DIR = os.path.dirname(os.path.abspath(__file__))

T = {
    'Latest date of refresh': {'fr': 'Date de dernière actualisation', 'es': 'Fecha de última actualización', 'de': 'Letztes Aktualisierungsdatum', 'it': 'Data ultimo aggiornamento', 'pt': 'Data da última atualização', 'nl': 'Laatste ververssingsdatum', 'ca': 'Data d\'última actualització', 'ro': 'Data ultimei actualizări', 'bg': 'Дата на последно обновяване', 'el': 'Ημερομηνία τελευταίας ανανέωσης', 'ar': 'تاريخ آخر تحديث', 'he': 'תאריך רענון אחרון', 'id': 'Tanggal refresh terakhir', 'ja': '最終更新日'},
    'Length icon': {'fr': 'Icône longueur', 'es': 'Icono longitud', 'de': 'Längen-Symbol', 'it': 'Icona lunghezza', 'pt': 'Ícone comprimento', 'nl': 'Lengte icoon', 'ca': 'Icona longitud', 'ro': 'Pictogramă lungime', 'bg': 'Икона дължина', 'el': 'Εικονίδιο μήκους', 'ar': 'أيقونة الطول', 'he': 'אייקון אורך', 'id': 'Ikon panjang', 'ja': '長さアイコン'},
    'Library': {'fr': 'Bibliothèque', 'es': 'Biblioteca', 'de': 'Bibliothek', 'it': 'Biblioteca', 'pt': 'Biblioteca', 'nl': 'Bibliotheek', 'ca': 'Biblioteca', 'ro': 'Bibliotecă', 'bg': 'Библиотека', 'el': 'Βιβλιοθήκη', 'ar': 'مكتبة', 'he': 'ספרייה', 'id': 'Perpustakaan', 'ja': '図書館'},
    'License: CC-BY-SA': {'fr': 'Licence : CC-BY-SA', 'es': 'Licencia: CC-BY-SA', 'de': 'Lizenz: CC-BY-SA', 'it': 'Licenza: CC-BY-SA', 'pt': 'Licença: CC-BY-SA', 'nl': 'Licentie: CC-BY-SA', 'ca': 'Llicència: CC-BY-SA', 'ro': 'Licență: CC-BY-SA', 'bg': 'Лиценз: CC-BY-SA', 'el': 'Άδεια: CC-BY-SA', 'ar': 'الترخيص: CC-BY-SA', 'he': 'רישיון: CC-BY-SA', 'id': 'Lisensi: CC-BY-SA', 'ja': 'ライセンス: CC-BY-SA'},
    'Link': {'fr': 'Lien', 'es': 'Enlace', 'de': 'Link', 'it': 'Collegamento', 'pt': 'Ligação', 'nl': 'Koppeling', 'ca': 'Enllaç', 'ro': 'Legătură', 'bg': 'Връзка', 'el': 'Σύνδεσμος', 'ar': 'رابط', 'he': 'קישור', 'id': 'Tautan', 'ja': 'リンク'},
    'Linked Information': {'fr': 'Informations liées', 'es': 'Información vinculada', 'de': 'Verknüpfte Informationen', 'it': 'Informazioni collegate', 'pt': 'Informação vinculada', 'nl': 'Gekoppelde informatie', 'ca': 'Informació vinculada', 'ro': 'Informații legate', 'bg': 'Свързана информация', 'el': 'Συνδεδεμένες πληροφορίες', 'ar': 'معلومات مرتبطة', 'he': 'מידע מקושר', 'id': 'Informasi terkait', 'ja': 'リンク情報'},
    'Linked entities': {'fr': 'Entités liées', 'es': 'Entidades vinculadas', 'de': 'Verknüpfte Entitäten', 'it': 'Entità collegate', 'pt': 'Entidades vinculadas', 'nl': 'Gekoppelde entiteiten', 'ca': 'Entitats vinculades', 'ro': 'Entități legate', 'bg': 'Свързани обекти', 'el': 'Συνδεδεμένες οντότητες', 'ar': 'كيانات مرتبطة', 'he': 'ישויות מקושרות', 'id': 'Entitas terkait', 'ja': 'リンクエンティティ'},
    'Locations': {'fr': 'Emplacements', 'es': 'Ubicaciones', 'de': 'Standorte', 'it': 'Posizioni', 'pt': 'Localizações', 'nl': 'Locaties', 'ca': 'Ubicacions', 'ro': 'Locații', 'bg': 'Местоположения', 'el': 'Τοποθεσίες', 'ar': 'المواقع', 'he': 'מיקומים', 'id': 'Lokasi', 'ja': '場所'},
    'Logged as {userNickname}': {'fr': 'Connecté en tant que {userNickname}', 'es': 'Conectado como {userNickname}', 'de': 'Angemeldet als {userNickname}', 'it': 'Connesso come {userNickname}', 'pt': 'Ligado como {userNickname}', 'nl': 'Ingelogd als {userNickname}', 'ca': 'Connectat com a {userNickname}', 'ro': 'Autentificat ca {userNickname}', 'bg': 'Влязъл като {userNickname}', 'el': 'Συνδεδεμένος ως {userNickname}', 'ar': 'مسجل الدخول باسم {userNickname}', 'he': 'מחובר כ-{userNickname}', 'id': 'Masuk sebagai {userNickname}', 'ja': '{userNickname}としてログイン'},
    'Mail': {'fr': 'Courriel', 'es': 'Correo electrónico', 'de': 'E-Mail', 'it': 'Email', 'pt': 'Correio eletrónico', 'nl': 'E-mail', 'ca': 'Correu electrònic', 'ro': 'E-mail', 'bg': 'Имейл', 'el': 'Ηλεκτρονικό ταχυδρομείο', 'ar': 'بريد إلكتروني', 'he': 'דואר אלקטרוני', 'id': 'Surat', 'ja': 'メール'},
    'Main language of the document': {'fr': 'Langue principale du document', 'es': 'Idioma principal del documento', 'de': 'Hauptsprache des Dokuments', 'it': 'Lingua principale del documento', 'pt': 'Língua principal do documento', 'nl': 'Hoofdtaal van het document', 'ca': 'Idioma principal del document', 'ro': 'Limba principală a documentului', 'bg': 'Основен език на документа', 'el': 'Κύρια γλώσσα του εγγράφου', 'ar': 'اللغة الرئيسية للوثيقة', 'he': 'שפה ראשית של המסמך', 'id': 'Bahasa utama dokumen', 'ja': '文書の主要言語'},
    "Main title of the document. Don't enter the issue number here if you are submitting a magazine for example: it will be asked later in the form.": {'fr': "Titre principal du document. N'entrez pas le numéro de parution ici si vous soumettez un magazine par exemple : il vous sera demandé plus tard dans le formulaire.", 'es': "Título principal del documento. No ingrese el número de publicación aquí si está enviando una revista, por ejemplo: se le pedirá más adelante en el formulario.", 'de': "Haupttitel des Dokuments. Geben Sie hier nicht die Ausgabennummer ein, wenn Sie z.B. eine Zeitschrift einreichen: diese wird später im Formular abgefragt.", 'it': "Titolo principale del documento. Non inserire il numero di pubblicazione qui se stai inviando una rivista ad esempio: verrà richiesto più avanti nel modulo.", 'pt': "Título principal do documento. Não insira o número de publicação aqui se estiver a submeter uma revista por exemplo: será pedido mais tarde no formulário.", 'nl': "Hoofdtitel van het document. Voer hier niet het publicatienummer in als u bijvoorbeeld een tijdschrift indient: dit wordt later in het formulier gevraagd.", 'ca': "Títol principal del document. No introduïu el número de publicació aquí si envieu una revista per exemple: es demanarà més endavant al formulari.", 'ro': "Titlul principal al documentului. Nu introduceți numărul ediției aici dacă trimiteți o revistă de exemplu: va fi solicitat mai târziu în formular.", 'bg': 'Основното заглавие на документа. Не въвеждайте номера на изданието тук, ако изпращате списание например: ще бъде поискано по-късно във формуляра.', 'el': 'Κύριος τίτλος του εγγράφου. Μην εισάγετε τον αριθμό έκδοσης εδώ αν υποβάλλετε ένα περιοδικό για παράδειγμα: θα ζητηθεί αργότερα στη φόρμα.', 'ar': 'العنوان الرئيسي للوثيقة. لا تدخل رقم الإصدار هنا إذا كنت تقدم مجلة مثلاً: سيُطلب منك لاحقاً في النموذج.', 'he': 'הכותרת הראשית של המסמך. אל תכניס את מספר הגיליון כאן אם אתה מגיש מגזין למשל: הוא יתבקש מאוחר יותר בטופס.', 'id': 'Judul utama dokumen. Jangan masukkan nomor terbitan di sini jika Anda mengirimkan majalah misalnya: akan ditanyakan nanti dalam formulir.', 'ja': '文書の主タイトル。例えば雑誌を提出する場合、ここに号数を入力しないでください：後でフォームで求められます。'},
    'Make a precise sentence that is pleasant to read and uses keywords.': {'fr': 'Faites une phrase précise qui soit agréable à lire et utilise des mots-clés.', 'es': 'Haga una oración precisa que sea agradable de leer y use palabras clave.', 'de': 'Schreiben Sie einen präzisen Satz, der angenehm zu lesen ist und Schlüsselwörter verwendet.', 'it': 'Fai una frase precisa che sia piacevole da leggere e usi parole chiave.', 'pt': 'Faça uma frase precisa que seja agradável de ler e use palavras-chave.', 'nl': 'Maak een precieze zin die prettig leest en trefwoorden gebruikt.', 'ca': 'Feu una frase precisa que sigui agradable de llegir i faci servir paraules clau.', 'ro': 'Faceți o propoziție precisă care să fie plăcută de citit și să folosească cuvinte cheie.', 'bg': 'Напишете точно изречение, което е приятно за четене и използва ключови думи.', 'el': 'Κάντε μια ακριβή πρόταση που να είναι ευχάριστη στην ανάγνωση και να χρησιμοποιεί λέξεις-κλειδιά.', 'ar': 'اكتب جملة دقيقة ومريحة للقراءة وتستخدم الكلمات المفتاحية.', 'he': 'כתוב משפט מדויק שנעים לקריאה ומשתמש במילות מפתח.', 'id': 'Buat kalimat yang tepat, enak dibaca, dan menggunakan kata kunci.', 'ja': '正確で読みやすく、キーワードを使った文を作成してください。'},
    'Manage': {'fr': 'Gérer', 'es': 'Gestionar', 'de': 'Verwalten', 'it': 'Gestisci', 'pt': 'Gerir', 'nl': 'Beheren', 'ca': 'Gestionar', 'ro': 'Gestionați', 'bg': 'Управление', 'el': 'Διαχείριση', 'ar': 'إدارة', 'he': 'נהל', 'id': 'Kelola', 'ja': '管理'},
    'Manage users': {'fr': 'Gérer les utilisateurs', 'es': 'Gestionar usuarios', 'de': 'Benutzer verwalten', 'it': 'Gestisci utenti', 'pt': 'Gerir utilizadores', 'nl': 'Gebruikers beheren', 'ca': 'Gestionar usuaris', 'ro': 'Gestionați utilizatori', 'bg': 'Управление на потребители', 'el': 'Διαχείριση χρηστών', 'ar': 'إدارة المستخدمين', 'he': 'נהל משתמשים', 'id': 'Kelola pengguna', 'ja': 'ユーザー管理'},
    'Many more features are still in the works and we aim to get Grottocenter 3 fully operational in the coming months.': {'fr': "De nombreuses autres fonctionnalités sont encore en développement et nous visons à rendre Grottocenter 3 entièrement opérationnel dans les prochains mois.", 'es': 'Muchas más funciones están en desarrollo y nuestro objetivo es que Grottocenter 3 esté completamente operativo en los próximos meses.', 'de': 'Viele weitere Funktionen sind noch in Entwicklung und wir streben an, Grottocenter 3 in den kommenden Monaten vollständig betriebsbereit zu machen.', 'it': 'Molte altre funzionalità sono ancora in sviluppo e miriamo a rendere Grottocenter 3 completamente operativo nei prossimi mesi.', 'pt': 'Muitas mais funcionalidades estão ainda em desenvolvimento e pretendemos tornar o Grottocenter 3 totalmente operacional nos próximos meses.', 'nl': 'Veel meer functies zijn nog in ontwikkeling en we streven ernaar Grottocenter 3 in de komende maanden volledig operationeel te maken.', 'ca': "Moltes altres funcions estan en desenvolupament i el nostre objectiu és que Grottocenter 3 estigui completament operatiu en els propers mesos.", 'ro': 'Multe alte funcții sunt încă în lucru și ne propunem ca Grottocenter 3 să fie pe deplin operațional în lunile următoare.', 'bg': 'Много повече функции все още се разработват и целим Grottocenter 3 да бъде напълно функционален в следващите месеци.', 'el': 'Πολλές ακόμη λειτουργίες βρίσκονται σε εξέλιξη και στοχεύουμε στο να καταστήσουμε το Grottocenter 3 πλήρως λειτουργικό τους επόμενους μήνες.', 'ar': 'لا تزال العديد من الميزات الأخرى قيد التطوير ونهدف إلى جعل Grottocenter 3 يعمل بالكامل في الأشهر القادمة.', 'he': 'עוד הרבה תכונות עדיין בפיתוח ואנו שואפים להפעיל את Grottocenter 3 במלואו בחודשים הקרובים.', 'id': 'Banyak fitur lainnya masih dalam pengerjaan dan kami bertujuan agar Grottocenter 3 beroperasi penuh dalam beberapa bulan ke depan.', 'ja': 'さらに多くの機能が開発中であり、今後数か月でGrottocenter 3を完全に稼働させることを目指しています。'},
    'Mark this polygon as a hole (inner ring) within another polygon': {'fr': 'Marquer ce polygone comme un trou (anneau intérieur) dans un autre polygone', 'es': 'Marcar este polígono como un agujero (anillo interior) dentro de otro polígono', 'de': 'Dieses Polygon als Loch (innerer Ring) in einem anderen Polygon markieren', 'it': 'Contrassegna questo poligono come un foro (anello interno) all\'interno di un altro poligono', 'pt': 'Marcar este polígono como um buraco (anel interno) dentro de outro polígono', 'nl': 'Markeer dit polygoon als een gat (binnenste ring) in een ander polygoon', 'ca': 'Marcar aquest polígon com un forat (anell interior) dins d\'un altre polígon', 'ro': 'Marcați acest poligon ca un decupaj (inel interior) în interiorul altui poligon', 'bg': 'Маркирайте този полигон като дупка (вътрешен пръстен) в друг полигон', 'el': 'Επισήμανση αυτού του πολυγώνου ως οπή (εσωτερικός δακτύλιος) μέσα σε άλλο πολύγωνο', 'ar': 'تمييز هذا المضلع كفتحة (حلقة داخلية) داخل مضلع آخر', 'he': 'סמן פוליגון זה כחור (טבעת פנימית) בתוך פוליגון אחר', 'id': 'Tandai poligon ini sebagai lubang (cincin dalam) di dalam poligon lain', 'ja': 'このポリゴンを別のポリゴン内の穴（内側リング）としてマーク'},
    'Matching all fields': {'fr': 'Correspondant à tous les champs', 'es': 'Coincidiendo con todos los campos', 'de': 'Alle Felder übereinstimmend', 'it': 'Corrispondente a tutti i campi', 'pt': 'Correspondendo a todos os campos', 'nl': 'Overeenkomend met alle velden', 'ca': 'Coincidint amb tots els camps', 'ro': 'Corespunzând tuturor câmpurilor', 'bg': 'Съответстващо на всички полета', 'el': 'Ταίριασμα όλων των πεδίων', 'ar': 'مطابقة جميع الحقول', 'he': 'תואם את כל השדות', 'id': 'Cocok dengan semua bidang', 'ja': 'すべてのフィールドに一致'},
    'Members (former members)': {'fr': 'Membres (anciens membres)', 'es': 'Miembros (antiguos miembros)', 'de': 'Mitglieder (ehemalige Mitglieder)', 'it': 'Membri (ex membri)', 'pt': 'Membros (ex-membros)', 'nl': 'Leden (voormalige leden)', 'ca': 'Membres (antics membres)', 'ro': 'Membri (foști membri)', 'bg': 'Членове (бивши членове)', 'el': 'Μέλη (πρώην μέλη)', 'ar': 'الأعضاء (الأعضاء السابقون)', 'he': 'חברים (חברים לשעבר)', 'id': 'Anggota (mantan anggota)', 'ja': 'メンバー（元メンバー）'},
}

with open(os.path.join(DIR, 'en.json'), encoding='utf-8') as f:
    en = json.load(f)

total = 0
for lang in ['fr','es','it','pt','de','nl','ca','ro','bg','el','ar','he','id','ja']:
    path = os.path.join(DIR, f'{lang}.json')
    with open(path, encoding='utf-8') as f:
        d = json.load(f)
    n = 0
    for k, langs in T.items():
        if k in en and lang in langs and (k not in d or d[k] == en[k]):
            d[k] = langs[lang]; n += 1
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(dict(sorted(d.items())), f, ensure_ascii=False, indent=2)
    total += n
    print(f'{lang}: +{n}')
print(f'Total: {total}')
