# -*- coding: utf-8 -*-
import json, os
DIR = os.path.dirname(os.path.abspath(__file__))

T = {
    'Networks list': {'fr': 'Liste des réseaux', 'es': 'Lista de redes', 'de': 'Netzwerkliste', 'it': 'Elenco reti', 'pt': 'Lista de redes', 'nl': 'Netwerklijst', 'ca': 'Llista de xarxes', 'ro': 'Lista rețelelor', 'bg': 'Списък с мрежи', 'el': 'Λίστα δικτύων', 'ar': 'قائمة الشبكات', 'he': 'רשימת רשתות', 'id': 'Daftar jaringan', 'ja': 'ネットワーク一覧'},
    'New cave or network': {'fr': 'Nouvelle cavité ou réseau', 'es': 'Nueva cueva o red', 'de': 'Neue Höhle oder Netzwerk', 'it': 'Nuova grotta o rete', 'pt': 'Nova caverna ou rede', 'nl': 'Nieuwe grot of netwerk', 'ca': 'Nova cova o xarxa', 'ro': 'Peșteră sau rețea nouă', 'bg': 'Нова пещера или мрежа', 'el': 'Νέο σπήλαιο ή δίκτυο', 'ar': 'كهف أو شبكة جديدة', 'he': 'מערה או רשת חדשה', 'id': 'Gua atau jaringan baru', 'ja': '新しい洞窟またはネットワーク'},
    'New document': {'fr': 'Nouveau document', 'es': 'Nuevo documento', 'de': 'Neues Dokument', 'it': 'Nuovo documento', 'pt': 'Novo documento', 'nl': 'Nieuw document', 'ca': 'Nou document', 'ro': 'Document nou', 'bg': 'Нов документ', 'el': 'Νέο έγγραφο', 'ar': 'مستند جديد', 'he': 'מסמך חדש', 'id': 'Dokumen baru', 'ja': '新しい文書'},
    'New email': {'fr': 'Nouvel e-mail', 'es': 'Nuevo correo electrónico', 'de': 'Neue E-Mail', 'it': 'Nuova email', 'pt': 'Novo e-mail', 'nl': 'Nieuw e-mailadres', 'ca': 'Nou correu electrònic', 'ro': 'E-mail nou', 'bg': 'Нов имейл', 'el': 'Νέο e-mail', 'ar': 'بريد إلكتروني جديد', 'he': 'אימייל חדש', 'id': 'Email baru', 'ja': '新しいメール'},
    'New line': {'fr': 'Nouvelle ligne', 'es': 'Nueva línea', 'de': 'Neue Zeile', 'it': 'Nuova riga', 'pt': 'Nova linha', 'nl': 'Nieuwe lijn', 'ca': 'Nova línia', 'ro': 'Linie nouă', 'bg': 'Нов ред', 'el': 'Νέα γραμμή', 'ar': 'سطر جديد', 'he': 'שורה חדשה', 'id': 'Baris baru', 'ja': '新しい行'},
    'New password': {'fr': 'Nouveau mot de passe', 'es': 'Nueva contraseña', 'de': 'Neues Passwort', 'it': 'Nuova password', 'pt': 'Nova palavra-passe', 'nl': 'Nieuw wachtwoord', 'ca': 'Nova contrasenya', 'ro': 'Parolă nouă', 'bg': 'Нова парола', 'el': 'Νέος κωδικός', 'ar': 'كلمة مرور جديدة', 'he': 'סיסמה חדשה', 'id': 'Kata sandi baru', 'ja': '新しいパスワード'},
    'Next Page': {'fr': 'Page suivante', 'es': 'Página siguiente', 'de': 'Nächste Seite', 'it': 'Pagina successiva', 'pt': 'Página seguinte', 'nl': 'Volgende pagina', 'ca': 'Pàgina següent', 'ro': 'Pagina următoare', 'bg': 'Следваща страница', 'el': 'Επόμενη σελίδα', 'ar': 'الصفحة التالية', 'he': 'עמוד הבא', 'id': 'Halaman berikutnya', 'ja': '次のページ'},
    'No author matches you search criteria': {'fr': "Aucun auteur ne correspond à vos critères de recherche", 'es': 'Ningún autor coincide con sus criterios de búsqueda', 'de': 'Kein Autor entspricht Ihren Suchkriterien', 'it': 'Nessun autore corrisponde ai criteri di ricerca', 'pt': 'Nenhum autor corresponde aos seus critérios de pesquisa', 'nl': 'Geen auteur komt overeen met uw zoekcriteria', 'ca': 'Cap autor coincideix amb els vostres criteris de cerca', 'ro': 'Niciun autor nu corespunde criteriilor de căutare', 'bg': 'Нито един автор не отговаря на критериите за търсене', 'el': 'Κανένας συγγραφέας δεν ταιριάζει με τα κριτήρια αναζήτησης', 'ar': 'لا يوجد مؤلف يطابق معايير البحث', 'he': 'אין מחבר שתואם לקריטריוני החיפוש', 'id': 'Tidak ada penulis yang cocok dengan kriteria pencarian', 'ja': '検索条件に一致する著者がいません'},
    'No country subscriptions': {'fr': "Pas d'abonnements par pays", 'es': 'No hay suscripciones por país', 'de': 'Keine Länderabonnements', 'it': 'Nessun abbonamento per paese', 'pt': 'Sem subscrições por país', 'nl': 'Geen landabonnementen', 'ca': 'Cap subscripció per país', 'ro': 'Nicio abonare la țară', 'bg': 'Няма абонаменти за страна', 'el': 'Δεν υπάρχουν συνδρομές χώρας', 'ar': 'لا توجد اشتراكات بلد', 'he': 'אין מנויים לפי מדינה', 'id': 'Tidak ada langganan negara', 'ja': '国のサブスクリプションなし'},
    'No layers to edit': {'fr': 'Aucune couche à modifier', 'es': 'No hay capas para editar', 'de': 'Keine Ebenen zum Bearbeiten', 'it': 'Nessun livello da modificare', 'pt': 'Sem camadas para editar', 'nl': 'Geen lagen om te bewerken', 'ca': 'Cap capa per editar', 'ro': 'Niciun strat de editat', 'bg': 'Няма слоеве за редактиране', 'el': 'Δεν υπάρχουν επίπεδα για επεξεργασία', 'ar': 'لا توجد طبقات للتعديل', 'he': 'אין שכבות לעריכה', 'id': 'Tidak ada lapisan untuk diedit', 'ja': '編集するレイヤーなし'},
    'No partner entrances found.': {'fr': 'Aucune entrée partenaire trouvée.', 'es': 'No se encontraron entradas de socios.', 'de': 'Keine Partnereingänge gefunden.', 'it': 'Nessun ingresso partner trovato.', 'pt': 'Nenhuma entrada de parceiro encontrada.', 'nl': 'Geen partneringangen gevonden.', 'ca': "No s'han trobat entrades de soci.", 'ro': 'Nu au fost găsite intrări partenere.', 'bg': 'Не са намерени входове на партньори.', 'el': 'Δεν βρέθηκαν είσοδοι συνεργατών.', 'ar': 'لم يتم العثور على مداخل شريكة.', 'he': 'לא נמצאו כניסות שותפים.', 'id': 'Tidak ada pintu masuk mitra yang ditemukan.', 'ja': 'パートナーの入口が見つかりません。'},
    'No partner networks found.': {'fr': 'Aucun réseau partenaire trouvé.', 'es': 'No se encontraron redes de socios.', 'de': 'Keine Partnernetzwerke gefunden.', 'it': 'Nessuna rete partner trovata.', 'pt': 'Nenhuma rede de parceiro encontrada.', 'nl': 'Geen partnernetwerken gevonden.', 'ca': "No s'han trobat xarxes de soci.", 'ro': 'Nu au fost găsite rețele partenere.', 'bg': 'Не са намерени мрежи на партньори.', 'el': 'Δεν βρέθηκαν δίκτυα συνεργατών.', 'ar': 'لم يتم العثور على شبكات شريكة.', 'he': 'לא נמצאו רשתות שותפים.', 'id': 'Tidak ada jaringan mitra yang ditemukan.', 'ja': 'パートナーネットワークが見つかりません。'},
    'No polygon geometries found in GeoJSON': {'fr': 'Aucune géométrie de polygone trouvée dans le GeoJSON', 'es': 'No se encontraron geometrías de polígono en GeoJSON', 'de': 'Keine Polygongeometrien in GeoJSON gefunden', 'it': 'Nessuna geometria poligonale trovata nel GeoJSON', 'pt': 'Nenhuma geometria de polígono encontrada no GeoJSON', 'nl': 'Geen polygoongeometrieën gevonden in GeoJSON', 'ca': 'No s\'han trobat geometries de polígon al GeoJSON', 'ro': 'Nu s-au găsit geometrii poligonale în GeoJSON', 'bg': 'Не са намерени полигонни геометрии в GeoJSON', 'el': 'Δεν βρέθηκαν γεωμετρίες πολυγώνου στο GeoJSON', 'ar': 'لم يتم العثور على أشكال هندسية متعددة الأضلاع في GeoJSON', 'he': 'לא נמצאו גיאומטריות פוליגון ב-GeoJSON', 'id': 'Tidak ada geometri poligon ditemukan di GeoJSON', 'ja': 'GeoJSONにポリゴンジオメトリが見つかりません'},
    'No polygon geometries found in shapefile.': {'fr': 'Aucune géométrie de polygone trouvée dans le shapefile.', 'es': 'No se encontraron geometrías de polígono en el shapefile.', 'de': 'Keine Polygongeometrien in der Shapefile gefunden.', 'it': 'Nessuna geometria poligonale trovata nel shapefile.', 'pt': 'Nenhuma geometria de polígono encontrada no shapefile.', 'nl': 'Geen polygoongeometrieën gevonden in shapefile.', 'ca': "No s'han trobat geometries de polígon al shapefile.", 'ro': 'Nu s-au găsit geometrii poligonale în fișierul shapefile.', 'bg': 'Не са намерени полигонни геометрии в shapefile.', 'el': 'Δεν βρέθηκαν γεωμετρίες πολυγώνου στο shapefile.', 'ar': 'لم يتم العثور على أشكال هندسية متعددة الأضلاع في ملف الشكل.', 'he': 'לא נמצאו גיאומטריות פוליגון בקובץ ה-shapefile.', 'id': 'Tidak ada geometri poligon ditemukan dalam shapefile.', 'ja': 'シェープファイルにポリゴンジオメトリが見つかりません。'},
    'No region matches you search criteria': {'fr': 'Aucune région ne correspond à vos critères de recherche', 'es': 'Ninguna región coincide con sus criterios de búsqueda', 'de': 'Keine Region entspricht Ihren Suchkriterien', 'it': 'Nessuna regione corrisponde ai criteri di ricerca', 'pt': 'Nenhuma região corresponde aos seus critérios de pesquisa', 'nl': 'Geen regio komt overeen met uw zoekcriteria', 'ca': 'Cap regió coincideix amb els vostres criteris de cerca', 'ro': 'Nicio regiune nu corespunde criteriilor de căutare', 'bg': 'Нито един регион не отговаря на критериите за търсене', 'el': 'Καμία περιοχή δεν ταιριάζει με τα κριτήρια αναζήτησης', 'ar': 'لا توجد منطقة تطابق معايير البحث', 'he': 'אין אזור שתואם לקריטריוני החיפוש', 'id': 'Tidak ada wilayah yang cocok dengan kriteria pencarian', 'ja': '検索条件に一致する地域がありません'},
    'No region subscriptions': {'fr': "Pas d'abonnements par région", 'es': 'No hay suscripciones por región', 'de': 'Keine Regionsabonnements', 'it': 'Nessun abbonamento per regione', 'pt': 'Sem subscrições por região', 'nl': 'Geen regioabonnementen', 'ca': 'Cap subscripció per regió', 'ro': 'Nicio abonare la regiune', 'bg': 'Няма абонаменти за регион', 'el': 'Δεν υπάρχουν συνδρομές περιοχής', 'ar': 'لا توجد اشتراكات منطقة', 'he': 'אין מנויים לפי אזור', 'id': 'Tidak ada langganan wilayah', 'ja': '地域のサブスクリプションなし'},
    'No regions found': {'fr': 'Aucune région trouvée', 'es': 'No se encontraron regiones', 'de': 'Keine Regionen gefunden', 'it': 'Nessuna regione trovata', 'pt': 'Nenhuma região encontrada', 'nl': 'Geen regio\'s gevonden', 'ca': 'No s\'han trobat regions', 'ro': 'Nu s-au găsit regiuni', 'bg': 'Не са намерени региони', 'el': 'Δεν βρέθηκαν περιοχές', 'ar': 'لم يتم العثور على مناطق', 'he': 'לא נמצאו אזורים', 'id': 'Tidak ada wilayah yang ditemukan', 'ja': '地域が見つかりません'},
    'No result (enter at least {count} characters)': {'fr': 'Aucun résultat (saisissez au moins {count} caractères)', 'es': 'Sin resultados (ingrese al menos {count} caracteres)', 'de': 'Kein Ergebnis (mindestens {count} Zeichen eingeben)', 'it': 'Nessun risultato (inserire almeno {count} caratteri)', 'pt': 'Sem resultado (insira pelo menos {count} caracteres)', 'nl': 'Geen resultaat (voer minimaal {count} tekens in)', 'ca': 'Cap resultat (introduïu almenys {count} caràcters)', 'ro': 'Niciun rezultat (introduceți cel puțin {count} caractere)', 'bg': 'Няма резултат (въведете поне {count} знака)', 'el': 'Κανένα αποτέλεσμα (εισαγάγετε τουλάχιστον {count} χαρακτήρες)', 'ar': 'لا توجد نتائج (أدخل {count} أحرف على الأقل)', 'he': 'אין תוצאות (הזן לפחות {count} תווים)', 'id': 'Tidak ada hasil (masukkan minimal {count} karakter)', 'ja': '結果なし（少なくとも{count}文字を入力してください）'},
    'No subject matches you search criteria': {'fr': 'Aucun sujet ne correspond à vos critères de recherche', 'es': 'Ningún tema coincide con sus criterios de búsqueda', 'de': 'Kein Thema entspricht Ihren Suchkriterien', 'it': 'Nessun argomento corrisponde ai criteri di ricerca', 'pt': 'Nenhum assunto corresponde aos seus critérios de pesquisa', 'nl': 'Geen onderwerp komt overeen met uw zoekcriteria', 'ca': 'Cap tema coincideix amb els vostres criteris de cerca', 'ro': 'Niciun subiect nu corespunde criteriilor de căutare', 'bg': 'Нито един субект не отговаря на критериите за търсене', 'el': 'Κανένα θέμα δεν ταιριάζει με τα κριτήρια αναζήτησης', 'ar': 'لا يوجد موضوع يطابق معايير البحث', 'he': 'אין נושא שתואם לקריטריוני החיפוש', 'id': 'Tidak ada subjek yang cocok dengan kriteria pencarian', 'ja': '検索条件に一致する件名がありません'},
    'Non spéléo': {'fr': 'Non spéléo', 'es': 'No espeleológico', 'de': 'Nicht-Speleologisch', 'it': 'Non speleologico', 'pt': 'Não espeleológico', 'nl': 'Niet-speleologisch', 'ca': 'No espeleològic', 'ro': 'Non-speologic', 'bg': 'Неспелеоложки', 'el': 'Μη σπηλαιολογικό', 'ar': 'غير كهفي', 'he': 'לא ספלאולוגי', 'id': 'Non-speleologi', 'ja': '非スペレオロジー'},
    'Notification type': {'fr': 'Type de notification', 'es': 'Tipo de notificación', 'de': 'Benachrichtigungstyp', 'it': 'Tipo di notifica', 'pt': 'Tipo de notificação', 'nl': 'Meldingstype', 'ca': 'Tipus de notificació', 'ro': 'Tipul de notificare', 'bg': 'Тип известие', 'el': 'Τύπος ειδοποίησης', 'ar': 'نوع الإشعار', 'he': 'סוג התראה', 'id': 'Jenis notifikasi', 'ja': '通知タイプ'},
}

with open(os.path.join(DIR, 'en.json'), encoding='utf-8') as f:
    en = json.load(f)

total = 0
for lang in ['fr','es','it','pt','de','nl','ca','ro','bg','el','ar','he','id','ja']:
    path = os.path.join(DIR, f'{lang}.json')
    with open(path, encoding='utf-8') as f:
        d = json.load(f)
    n = 0
    for k, langs in T.items():
        if k in en and lang in langs and (k not in d or d[k] == en[k]):
            d[k] = langs[lang]; n += 1
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(dict(sorted(d.items())), f, ensure_ascii=False, indent=2)
    total += n
    print(f'{lang}: +{n}')
print(f'Total: {total}')
