# -*- coding: utf-8 -*-
import json, os
DIR = os.path.dirname(os.path.abspath(__file__))

T = {
    'Notified': {'fr': 'Notifié', 'es': 'Notificado', 'de': 'Benachrichtigt', 'it': 'Notificato', 'pt': 'Notificado', 'nl': 'Gemeld', 'ca': 'Notificat', 'ro': 'Notificat', 'bg': 'Уведомен', 'el': 'Ειδοποιήθηκε', 'ar': 'تم الإشعار', 'he': 'הוּדַע', 'id': 'Diberitahu', 'ja': '通知済み'},
    'Notifier': {'fr': 'Notificateur', 'es': 'Notificador', 'de': 'Benachrichtiger', 'it': 'Notificatore', 'pt': 'Notificador', 'nl': 'Melder', 'ca': 'Notificador', 'ro': 'Notificator', 'bg': 'Известител', 'el': 'Ειδοποιητής', 'ar': 'جهاز الإشعار', 'he': 'מַתרִיע', 'id': 'Pemberi notifikasi', 'ja': '通知者'},
    'Number of explored entrances': {'fr': "Nombre d'entrées explorées", 'es': 'Número de entradas exploradas', 'de': 'Anzahl erkundeter Eingänge', 'it': 'Numero di ingressi esplorati', 'pt': 'Número de entradas exploradas', 'nl': 'Aantal verkende ingangen', 'ca': "Nombre d'entrades explorades", 'ro': 'Numărul de intrări explorat', 'bg': 'Брой изследвани входове', 'el': 'Αριθμός εξερευνημένων εισόδων', 'ar': 'عدد المداخل المستكشفة', 'he': 'מספר כניסות שנחקרו', 'id': 'Jumlah pintu masuk yang dieksplorasi', 'ja': '探索済み入口数'},
    'Number of explored networks': {'fr': 'Nombre de réseaux explorés', 'es': 'Número de redes exploradas', 'de': 'Anzahl erkundeter Netzwerke', 'it': 'Numero di reti esplorate', 'pt': 'Número de redes exploradas', 'nl': 'Aantal verkende netwerken', 'ca': 'Nombre de xarxes explorades', 'ro': 'Numărul de rețele explorate', 'bg': 'Брой изследвани мрежи', 'el': 'Αριθμός εξερευνημένων δικτύων', 'ar': 'عدد الشبكات المستكشفة', 'he': 'מספר רשתות שנחקרו', 'id': 'Jumlah jaringan yang dieksplorasi', 'ja': '探索済みネットワーク数'},
    'OAI-PMH Server': {'fr': 'Serveur OAI-PMH', 'es': 'Servidor OAI-PMH', 'de': 'OAI-PMH-Server', 'it': 'Server OAI-PMH', 'pt': 'Servidor OAI-PMH', 'nl': 'OAI-PMH-server', 'ca': 'Servidor OAI-PMH', 'ro': 'Server OAI-PMH', 'bg': 'OAI-PMH сървър', 'el': 'Διακομιστής OAI-PMH', 'ar': 'خادم OAI-PMH', 'he': 'שרת OAI-PMH', 'id': 'Server OAI-PMH', 'ja': 'OAI-PMHサーバー'},
    'Ok': {'fr': 'Ok', 'es': 'Aceptar', 'de': 'Ok', 'it': 'Ok', 'pt': 'Ok', 'nl': 'Ok', 'ca': 'D\'acord', 'ro': 'Ok', 'bg': 'Добре', 'el': 'Εντάξει', 'ar': 'حسناً', 'he': 'אישור', 'id': 'Ok', 'ja': 'OK'},
    'One of my caving buddies told me I should NOT post anything at all on GrottoCenter. That sometimes makes it hard to contribute!': {'fr': "Un de mes amis spéléo m'a dit de ne RIEN poster sur GrottoCenter. Ça rend parfois difficile de contribuer !", 'es': 'Uno de mis amigos espeleólogos me dijo que NO debería publicar nada en GrottoCenter. ¡A veces eso hace difícil contribuir!', 'de': 'Einer meiner Höhlenkunden sagte mir, ich sollte NICHTS auf GrottoCenter posten. Das macht das Beitragen manchmal schwer!', 'it': 'Uno dei miei amici speleologi mi ha detto che NON dovrei pubblicare niente su GrottoCenter. A volte questo rende difficile contribuire!', 'pt': 'Um dos meus amigos espeleólogos disse-me que NÃO devo publicar nada no GrottoCenter. Isso às vezes dificulta a contribuição!', 'nl': 'Een van mijn speleoloogvrienden zei dat ik NIETS op GrottoCenter moest posten. Dat maakt het soms moeilijk om bij te dragen!', 'ca': 'Un dels meus amics espeleòlegs em va dir que NO hauria de publicar res a GrottoCenter. De vegades això fa difícil contribuir!', 'ro': 'Unul dintre prietenii mei speologi mi-a spus că NU ar trebui să postez nimic pe GrottoCenter. Uneori asta îngreunează contribuția!', 'bg': 'Един от приятелите ми спелеолози ми каза, че НЕ трябва да публикувам нищо в GrottoCenter. Понякога това затруднява приноса!', 'el': 'Ένας από τους φίλους μου σπηλαιολόγους μου είπε ότι δεν πρέπει να δημοσιεύω ΤΙΠΟΤΑ στο GrottoCenter. Αυτό μερικές φορές δυσκολεύει τη συνεισφορά!', 'ar': 'أخبرني أحد أصدقائي من مستكشفي الكهوف أنه لا يجب أن أنشر أي شيء على GrottoCenter. يجعل ذلك المساهمة صعبة أحياناً!', 'he': 'אחד מחברי לחקר מערות אמר לי שלא כדאי לפרסם שום דבר ב-GrottoCenter. זה לפעמים מקשה על התרומה!', 'id': 'Salah satu teman spelunking saya mengatakan saya sebaiknya TIDAK memposting apa pun di GrottoCenter. Kadang itu membuat kontribusi menjadi sulit!', 'ja': '洞窟仲間の一人から、GrottoCenterには何も投稿しない方がいいと言われました。それで時々貢献しにくくなります！'},
    'Opacity': {'fr': 'Opacité', 'es': 'Opacidad', 'de': 'Deckkraft', 'it': 'Opacità', 'pt': 'Opacidade', 'nl': 'Dekking', 'ca': 'Opacitat', 'ro': 'Opacitate', 'bg': 'Непрозрачност', 'el': 'Αδιαφάνεια', 'ar': 'التعتيم', 'he': 'אטימות', 'id': 'Opasitas', 'ja': '不透明度'},
    'Open guided tour': {'fr': 'Ouvrir la visite guidée', 'es': 'Abrir visita guiada', 'de': 'Geführte Tour öffnen', 'it': 'Apri visita guidata', 'pt': 'Abrir visita guiada', 'nl': 'Begeleide tour openen', 'ca': 'Obrir visita guiada', 'ro': 'Deschide turul ghidat', 'bg': 'Отвори разходката с водач', 'el': 'Άνοιγμα ξεναγήσεως', 'ar': 'فتح الجولة الإرشادية', 'he': 'פתח סיור מודרך', 'id': 'Buka tur terpandu', 'ja': 'ガイドツアーを開く'},
    'Option': {'fr': 'Option', 'es': 'Opción', 'de': 'Option', 'it': 'Opzione', 'pt': 'Opção', 'nl': 'Optie', 'ca': 'Opció', 'ro': 'Opțiune', 'bg': 'Опция', 'el': 'Επιλογή', 'ar': 'خيار', 'he': 'אפשרות', 'id': 'Opsi', 'ja': 'オプション'},
    'Or use this link to reset your password:': {'fr': 'Ou utilisez ce lien pour réinitialiser votre mot de passe :', 'es': 'O use este enlace para restablecer su contraseña:', 'de': 'Oder verwenden Sie diesen Link zum Zurücksetzen Ihres Passworts:', 'it': 'Oppure usa questo link per reimpostare la tua password:', 'pt': 'Ou use este link para redefinir a sua palavra-passe:', 'nl': 'Of gebruik deze link om uw wachtwoord te resetten:', 'ca': 'O feu servir aquest enllaç per restablir la contrasenya:', 'ro': 'Sau folosiți acest link pentru a reseta parola:', 'bg': 'Или използвайте тази връзка за нулиране на паролата:', 'el': 'Ή χρησιμοποιήστε αυτόν τον σύνδεσμο για να επαναφέρετε τον κωδικό σας:', 'ar': 'أو استخدم هذا الرابط لإعادة تعيين كلمة المرور الخاصة بك:', 'he': 'או השתמש בקישור זה לאיפוס הסיסמה שלך:', 'id': 'Atau gunakan tautan ini untuk mengatur ulang kata sandi Anda:', 'ja': 'またはこのリンクを使用してパスワードをリセットしてください：'},
    'Original id from an imported database': {'fr': "Identifiant d'origine d'une base de données importée", 'es': 'Id original de una base de datos importada', 'de': 'Original-ID aus einer importierten Datenbank', 'it': 'ID originale da un database importato', 'pt': 'ID original de uma base de dados importada', 'nl': 'Originele ID uit een geïmporteerde database', 'ca': 'ID original d\'una base de dades importada', 'ro': 'ID original dintr-o bază de date importată', 'bg': 'Оригинален идентификатор от импортирана база данни', 'el': 'Αρχικό αναγνωριστικό από εισαγόμενη βάση δεδομένων', 'ar': 'المعرف الأصلي من قاعدة بيانات مستوردة', 'he': 'מזהה מקורי מבסיס נתונים מיובא', 'id': 'ID asli dari database yang diimpor', 'ja': 'インポートされたデータベースの元のID'},
    'PLEASE NOTE:': {'fr': 'VEUILLEZ NOTER :', 'es': 'TENGA EN CUENTA:', 'de': 'BITTE BEACHTEN:', 'it': 'SI PREGA DI NOTARE:', 'pt': 'ATENÇÃO:', 'nl': 'LET OP:', 'ca': 'TINGUEU EN COMPTE:', 'ro': 'VĂ RUGĂM SĂ REȚINEȚI:', 'bg': 'МОЛЯ, ОБЪРНЕТЕ ВНИМАНИЕ:', 'el': 'ΠΑΡΑΚΑΛΩ ΣΗΜΕΙΩΣΤΕ:', 'ar': 'يرجى الملاحظة:', 'he': 'שים לב:', 'id': 'HARAP DIPERHATIKAN:', 'ja': '注意事項：'},
    'Page Comment': {'fr': 'Commentaire de page', 'es': 'Comentario de página', 'de': 'Seitenkommentar', 'it': 'Commento di pagina', 'pt': 'Comentário de página', 'nl': 'Paginacommentaar', 'ca': 'Comentari de pàgina', 'ro': 'Comentariu pagină', 'bg': 'Коментар на страница', 'el': 'Σχόλιο σελίδας', 'ar': 'تعليق الصفحة', 'he': 'הערת עמוד', 'id': 'Komentar halaman', 'ja': 'ページコメント'},
    'Page of all types of revision history for this entrance': {'fr': "Page de tous les types d'historique de révision pour cette entrée", 'es': 'Página de todos los tipos de historial de revisión para esta entrada', 'de': 'Seite mit allen Revisionshistorientypen für diesen Eingang', 'it': 'Pagina di tutti i tipi di cronologia delle revisioni per questo ingresso', 'pt': 'Página de todos os tipos de histórico de revisão para esta entrada', 'nl': 'Pagina van alle typen revisiegeschiedenissen voor deze ingang', 'ca': "Pàgina de tots els tipus d'historial de revisió per a aquesta entrada", 'ro': 'Pagina tuturor tipurilor de istorii de revizuire pentru această intrare', 'bg': 'Страница с всички видове история на ревизии за този вход', 'el': 'Σελίδα όλων των τύπων ιστορικού αναθεώρησης για αυτήν την είσοδο', 'ar': 'صفحة كل أنواع تاريخ المراجعة لهذا المدخل', 'he': 'עמוד של כל סוגי היסטוריית הגרסאות עבור כניסה זו', 'id': 'Halaman semua jenis riwayat revisi untuk pintu masuk ini', 'ja': 'この入口のすべての種類の改訂履歴ページ'},
    "Page where the document ends if it's part of another document (ex: an article in a magazine).": {'fr': "Page où se termine le document s'il fait partie d'un autre document (ex : un article dans un magazine).", 'es': "Página donde termina el documento si es parte de otro documento (ej: un artículo en una revista).", 'de': "Seite, auf der das Dokument endet, wenn es Teil eines anderen Dokuments ist (z.B. ein Artikel in einer Zeitschrift).", 'it': "Pagina dove finisce il documento se fa parte di un altro documento (es: un articolo in una rivista).", 'pt': "Página onde o documento termina se faz parte de outro documento (ex: um artigo numa revista).", 'nl': "Pagina waar het document eindigt als het deel uitmaakt van een ander document (bv: een artikel in een tijdschrift).", 'ca': "Pàgina on acaba el document si forma part d'un altre document (ex: un article en una revista).", 'ro': "Pagina unde se termină documentul dacă face parte dintr-un alt document (ex: un articol dintr-o revistă).", 'bg': 'Страница, на която завършва документът, ако е част от друг документ (напр. статия в списание).', 'el': 'Σελίδα όπου τελειώνει το έγγραφο αν αποτελεί μέρος άλλου εγγράφου (π.χ. άρθρο σε περιοδικό).', 'ar': 'الصفحة التي ينتهي فيها المستند إذا كان جزءاً من مستند آخر (مثل مقالة في مجلة).', 'he': 'העמוד בו מסתיים המסמך אם הוא חלק ממסמך אחר (למשל: מאמר במגזין).', 'id': 'Halaman di mana dokumen berakhir jika merupakan bagian dari dokumen lain (mis: artikel dalam majalah).', 'ja': '文書が別の文書の一部である場合の終了ページ（例：雑誌の記事）。'},
    "Page where the document starts if it's part of another document (ex: an article in a magazine). Leave it blank if you just want to mention the total number of pages (ex: a book).": {'fr': "Page où commence le document s'il fait partie d'un autre document (ex : un article dans un magazine). Laissez-le vide si vous souhaitez simplement indiquer le nombre total de pages (ex : un livre).", 'es': "Página donde comienza el documento si es parte de otro documento (ej: un artículo en una revista). Déjelo en blanco si solo desea mencionar el número total de páginas (ej: un libro).", 'de': "Seite, auf der das Dokument beginnt, wenn es Teil eines anderen Dokuments ist (z.B. ein Artikel in einer Zeitschrift). Leer lassen, wenn nur die Gesamtseitenzahl angegeben werden soll (z.B. ein Buch).", 'it': "Pagina dove inizia il documento se fa parte di un altro documento (es: un articolo in una rivista). Lascialo vuoto se vuoi solo indicare il numero totale di pagine (es: un libro).", 'pt': "Página onde o documento começa se faz parte de outro documento (ex: um artigo numa revista). Deixe em branco se apenas quiser indicar o número total de páginas (ex: um livro).", 'nl': "Pagina waar het document begint als het deel uitmaakt van een ander document (bv: een artikel in een tijdschrift). Laat leeg als u alleen het totale aantal pagina's wilt vermelden (bv: een boek).", 'ca': "Pàgina on comença el document si forma part d'un altre document (ex: un article en una revista). Deixeu-lo en blanc si només voleu esmentar el nombre total de pàgines (ex: un llibre).", 'ro': "Pagina unde începe documentul dacă face parte dintr-un alt document (ex: un articol dintr-o revistă). Lăsați-l gol dacă doriți să menționați doar numărul total de pagini (ex: o carte).", 'bg': 'Страница, на която започва документът, ако е част от друг документ (напр. статия в списание). Оставете го празно, ако само искате да посочите общия брой страници (напр. книга).', 'el': 'Σελίδα όπου ξεκινά το έγγραφο αν αποτελεί μέρος άλλου εγγράφου (π.χ. άρθρο σε περιοδικό). Αφήστε το κενό αν θέλετε να αναφέρετε μόνο τον συνολικό αριθμό σελίδων (π.χ. βιβλίο).', 'ar': 'الصفحة التي يبدأ فيها المستند إذا كان جزءاً من مستند آخر (مثل مقالة في مجلة). اتركه فارغاً إذا أردت فقط ذكر العدد الإجمالي للصفحات (مثل كتاب).', 'he': 'העמוד בו מתחיל המסמך אם הוא חלק ממסמך אחר (למשל: מאמר במגזין). השאר ריק אם רק רוצים לציין את מספר העמודים הכולל (למשל: ספר).', 'id': 'Halaman di mana dokumen dimulai jika merupakan bagian dari dokumen lain (mis: artikel dalam majalah). Biarkan kosong jika hanya ingin menyebutkan jumlah halaman total (mis: buku).', 'ja': '文書が別の文書の一部である場合の開始ページ（例：雑誌の記事）。総ページ数のみを記載したい場合（例：書籍）は空白のままにしてください。'},
    'Page {start} of {title}': {'fr': 'Page {start} de {title}', 'es': 'Página {start} de {title}', 'de': 'Seite {start} von {title}', 'it': 'Pagina {start} di {title}', 'pt': 'Página {start} de {title}', 'nl': 'Pagina {start} van {title}', 'ca': 'Pàgina {start} de {title}', 'ro': 'Pagina {start} din {title}', 'bg': 'Страница {start} от {title}', 'el': 'Σελίδα {start} από {title}', 'ar': 'صفحة {start} من {title}', 'he': 'עמוד {start} מתוך {title}', 'id': 'Halaman {start} dari {title}', 'ja': '{title}のページ{start}'},
    'Pages': {'fr': 'Pages', 'es': 'Páginas', 'de': 'Seiten', 'it': 'Pagine', 'pt': 'Páginas', 'nl': 'Pagina\'s', 'ca': 'Pàgines', 'ro': 'Pagini', 'bg': 'Страници', 'el': 'Σελίδες', 'ar': 'صفحات', 'he': 'עמודים', 'id': 'Halaman', 'ja': 'ページ'},
    'Pages {start}-{end} of {title}': {'fr': 'Pages {start}-{end} de {title}', 'es': 'Páginas {start}-{end} de {title}', 'de': 'Seiten {start}-{end} von {title}', 'it': 'Pagine {start}-{end} di {title}', 'pt': 'Páginas {start}-{end} de {title}', 'nl': "Pagina's {start}-{end} van {title}", 'ca': 'Pàgines {start}-{end} de {title}', 'ro': 'Pagini {start}-{end} din {title}', 'bg': 'Страници {start}-{end} от {title}', 'el': 'Σελίδες {start}-{end} από {title}', 'ar': 'صفحات {start}-{end} من {title}', 'he': 'עמודים {start}-{end} מתוך {title}', 'id': 'Halaman {start}-{end} dari {title}', 'ja': '{title}のページ{start}-{end}'},
    'Paleontospeleology': {'fr': 'Paléontospéléologie', 'es': 'Paleontología espeleológica', 'de': 'Paläontospeleologie', 'it': 'Paleontospeleologia', 'pt': 'Paleontospeleologia', 'nl': 'Paleontospeleologie', 'ca': 'Paleontospeleologia', 'ro': 'Paleontospeleologie', 'bg': 'Палеонтоспеология', 'el': 'Παλαιοντοσπηλαιολογία', 'ar': 'علم الحفريات الكهفي', 'he': 'ספלאולוגיה פלאונטולוגית', 'id': 'Paleontospeleologi', 'ja': '古生物洞窟学'},
}

with open(os.path.join(DIR, 'en.json'), encoding='utf-8') as f:
    en = json.load(f)

total = 0
for lang in ['fr','es','it','pt','de','nl','ca','ro','bg','el','ar','he','id','ja']:
    path = os.path.join(DIR, f'{lang}.json')
    with open(path, encoding='utf-8') as f:
        d = json.load(f)
    n = 0
    for k, langs in T.items():
        if k in en and lang in langs and (k not in d or d[k] == en[k]):
            d[k] = langs[lang]; n += 1
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(dict(sorted(d.items())), f, ensure_ascii=False, indent=2)
    total += n
    print(f'{lang}: +{n}')
print(f'Total: {total}')
