# -*- coding: utf-8 -*-
import json, os
DIR = os.path.dirname(os.path.abspath(__file__))

T = {
    'Parent document': {'fr': 'Document parent', 'es': 'Documento padre', 'de': 'Übergeordnetes Dokument', 'it': 'Documento padre', 'pt': 'Documento pai', 'nl': 'Bovenliggend document', 'ca': 'Document pare', 'ro': 'Document părinte', 'bg': 'Родителски документ', 'el': 'Γονικό έγγραφο', 'ar': 'المستند الأصلي', 'he': 'מסמך הורה', 'id': 'Dokumen induk', 'ja': '親文書'},
    'Partner entrances': {'fr': 'Entrées partenaires', 'es': 'Entradas de socios', 'de': 'Partnereingänge', 'it': 'Ingressi partner', 'pt': 'Entradas parceiras', 'nl': 'Partneringangen', 'ca': 'Entrades de soci', 'ro': 'Intrări partenere', 'bg': 'Входове на партньори', 'el': 'Είσοδοι συνεργατών', 'ar': 'مداخل الشركاء', 'he': 'כניסות שותפים', 'id': 'Pintu masuk mitra', 'ja': 'パートナーの入口'},
    'Partner networks': {'fr': 'Réseaux partenaires', 'es': 'Redes de socios', 'de': 'Partnernetzwerke', 'it': 'Reti partner', 'pt': 'Redes parceiras', 'nl': 'Partnernetwerken', 'ca': 'Xarxes de soci', 'ro': 'Rețele partenere', 'bg': 'Мрежи на партньори', 'el': 'Δίκτυα συνεργατών', 'ar': 'شبكات الشركاء', 'he': 'רשתות שותפים', 'id': 'Jaringan mitra', 'ja': 'パートナーネットワーク'},
    'Password reset email sent to {email}': {'fr': 'E-mail de réinitialisation du mot de passe envoyé à {email}', 'es': 'Correo de restablecimiento de contraseña enviado a {email}', 'de': 'Passwort-Reset-E-Mail an {email} gesendet', 'it': 'Email di reimpostazione password inviata a {email}', 'pt': 'E-mail de redefinição de palavra-passe enviado para {email}', 'nl': 'Wachtwoord-reset e-mail verzonden naar {email}', 'ca': 'Correu de restabliment de contrasenya enviat a {email}', 'ro': 'E-mail de resetare a parolei trimis la {email}', 'bg': 'Имейл за нулиране на паролата изпратен до {email}', 'el': 'Στάλθηκε email επαναφοράς κωδικού στο {email}', 'ar': 'تم إرسال بريد إعادة تعيين كلمة المرور إلى {email}', 'he': 'נשלח מייל לאיפוס סיסמה ל-{email}', 'id': 'Email reset kata sandi dikirim ke {email}', 'ja': 'パスワードリセットメールを{email}に送信しました'},
    'Per page:': {'fr': 'Par page :', 'es': 'Por página:', 'de': 'Pro Seite:', 'it': 'Per pagina:', 'pt': 'Por página:', 'nl': 'Per pagina:', 'ca': 'Per pàgina:', 'ro': 'Per pagină:', 'bg': 'На страница:', 'el': 'Ανά σελίδα:', 'ar': 'لكل صفحة:', 'he': 'לכל עמוד:', 'id': 'Per halaman:', 'ja': 'ページあたり：'},
    'Perform an advanced search on all the fields. Results displayed will have at least one field matching your request.': {'fr': 'Effectuez une recherche avancée sur tous les champs. Les résultats affichés auront au moins un champ correspondant à votre requête.', 'es': 'Realice una búsqueda avanzada en todos los campos. Los resultados mostrados tendrán al menos un campo que coincida con su solicitud.', 'de': 'Führen Sie eine erweiterte Suche über alle Felder durch. Die angezeigten Ergebnisse haben mindestens ein Feld, das Ihrer Anfrage entspricht.', 'it': 'Esegui una ricerca avanzata su tutti i campi. I risultati visualizzati avranno almeno un campo corrispondente alla tua richiesta.', 'pt': 'Efetue uma pesquisa avançada em todos os campos. Os resultados apresentados terão pelo menos um campo que corresponde ao seu pedido.', 'nl': 'Voer een geavanceerde zoekopdracht uit op alle velden. De weergegeven resultaten hebben minimaal één veld dat overeenkomt met uw verzoek.', 'ca': 'Realitzeu una cerca avançada en tots els camps. Els resultats mostrats tindran almenys un camp que coincideixi amb la vostra sol·licitud.', 'ro': 'Efectuați o căutare avansată pe toate câmpurile. Rezultatele afișate vor avea cel puțin un câmp care corespunde cererii dvs.', 'bg': 'Извършете разширено търсене по всички полета. Показаните резултати ще имат поне едно поле, отговарящо на заявката ви.', 'el': 'Εκτελέστε μια προχωρημένη αναζήτηση σε όλα τα πεδία. Τα αποτελέσματα που εμφανίζονται θα έχουν τουλάχιστον ένα πεδίο που ταιριάζει με το αίτημά σας.', 'ar': 'أجرِ بحثاً متقدماً في جميع الحقول. ستحتوي النتائج المعروضة على حقل واحد على الأقل يطابق طلبك.', 'he': 'בצע חיפוש מתקדם בכל השדות. התוצאות המוצגות יכללו לפחות שדה אחד התואם לבקשתך.', 'id': 'Lakukan pencarian lanjutan di semua bidang. Hasil yang ditampilkan akan memiliki setidaknya satu bidang yang cocok dengan permintaan Anda.', 'ja': 'すべてのフィールドで詳細検索を実行します。表示された結果には、リクエストに一致するフィールドが少なくとも1つあります。'},
    'Periodical issue': {'fr': 'Numéro de périodique', 'es': 'Número de periódico', 'de': 'Periodische Ausgabe', 'it': 'Numero periodico', 'pt': 'Número periódico', 'nl': 'Periodiek nummer', 'ca': 'Número periòdic', 'ro': 'Număr periodic', 'bg': 'Периодичен брой', 'el': 'Περιοδικό τεύχος', 'ar': 'عدد دوري', 'he': 'גיליון תקופתי', 'id': 'Edisi berkala', 'ja': '定期刊行物号'},
    'Persons': {'fr': 'Personnes', 'es': 'Personas', 'de': 'Personen', 'it': 'Persone', 'pt': 'Pessoas', 'nl': 'Personen', 'ca': 'Persones', 'ro': 'Persoane', 'bg': 'Лица', 'el': 'Πρόσωπα', 'ar': 'أشخاص', 'he': 'אנשים', 'id': 'Orang', 'ja': '人物'},
    'Physical Object': {'fr': 'Objet physique', 'es': 'Objeto físico', 'de': 'Physisches Objekt', 'it': 'Oggetto fisico', 'pt': 'Objeto físico', 'nl': 'Fysiek object', 'ca': 'Objecte físic', 'ro': 'Obiect fizic', 'bg': 'Физически обект', 'el': 'Φυσικό αντικείμενο', 'ar': 'كائن مادي', 'he': 'אובייקט פיזי', 'id': 'Objek fisik', 'ja': '物理オブジェクト'},
    'Please be careful not to import any documents or entrances which are already present in Grottocenter.': {'fr': "Veuillez vous assurer de ne pas importer de documents ou d'entrées déjà présents dans Grottocenter.", 'es': 'Por favor, tenga cuidado de no importar documentos o entradas que ya estén presentes en Grottocenter.', 'de': 'Bitte achten Sie darauf, keine Dokumente oder Eingänge zu importieren, die bereits in Grottocenter vorhanden sind.', 'it': 'Fare attenzione a non importare documenti o ingressi già presenti in Grottocenter.', 'pt': 'Por favor, tenha cuidado para não importar documentos ou entradas que já estão presentes no Grottocenter.', 'nl': 'Zorg ervoor dat u geen documenten of ingangen importeert die al aanwezig zijn in Grottocenter.', 'ca': 'Si us plau, tingueu cura de no importar cap document o entrada que ja estigui present a Grottocenter.', 'ro': 'Vă rugăm să fiți atenți să nu importați documente sau intrări care sunt deja prezente în Grottocenter.', 'bg': 'Моля, внимавайте да не импортирате документи или входове, които вече са налични в Grottocenter.', 'el': 'Παρακαλώ προσέξτε να μην εισάγετε έγγραφα ή εισόδους που είναι ήδη παρόντα στο Grottocenter.', 'ar': 'يرجى الانتباه إلى عدم استيراد أي مستندات أو مداخل موجودة بالفعل في Grottocenter.', 'he': 'אנא היזהר לא לייבא מסמכים או כניסות שכבר נמצאות ב-Grottocenter.', 'id': 'Harap berhati-hati untuk tidak mengimpor dokumen atau pintu masuk yang sudah ada di Grottocenter.', 'ja': 'Grottocenterにすでに存在する文書や入口をインポートしないよう注意してください。'},
    'Please delete this line or fill at least the obstacle cell.': {'fr': 'Veuillez supprimer cette ligne ou remplir au moins la cellule obstacle.', 'es': 'Por favor, elimine esta línea o rellene al menos la celda de obstáculo.', 'de': 'Bitte löschen Sie diese Zeile oder füllen Sie mindestens die Hindernis-Zelle aus.', 'it': 'Eliminare questa riga o riempire almeno la cella ostacolo.', 'pt': 'Por favor, elimine esta linha ou preencha pelo menos a célula de obstáculo.', 'nl': 'Verwijder deze lijn of vul minimaal de hinderniscel in.', 'ca': 'Si us plau, elimineu aquesta línia o empleneu almenys la cel·la d\'obstacle.', 'ro': 'Vă rugăm ștergeți această linie sau completați cel puțin celula obstacol.', 'bg': 'Моля, изтрийте този ред или попълнете поне клетката за препятствие.', 'el': 'Παρακαλώ διαγράψτε αυτή τη γραμμή ή συμπληρώστε τουλάχιστον το κελί εμποδίου.', 'ar': 'يرجى حذف هذا السطر أو ملء خلية العقبة على الأقل.', 'he': 'אנא מחק שורה זו או מלא לפחות את תא המכשול.', 'id': 'Harap hapus baris ini atau isi setidaknya sel rintangan.', 'ja': 'この行を削除するか、少なくとも障害物セルを入力してください。'},
    'Please finish editing the polygon before submitting.': {'fr': "Veuillez terminer la modification du polygone avant de soumettre.", 'es': 'Por favor, termine de editar el polígono antes de enviarlo.', 'de': 'Bitte beenden Sie die Bearbeitung des Polygons vor dem Absenden.', 'it': 'Finire di modificare il poligono prima di inviare.', 'pt': 'Por favor, termine de editar o polígono antes de submeter.', 'nl': 'Sluit het bewerken van het polygoon af voordat u het indient.', 'ca': 'Si us plau, acabeu d\'editar el polígon abans d\'enviar.', 'ro': 'Vă rugăm terminați editarea poligonului înainte de a trimite.', 'bg': 'Моля, завършете редактирането на полигона преди изпращане.', 'el': 'Παρακαλώ ολοκληρώστε την επεξεργασία του πολυγώνου πριν την υποβολή.', 'ar': 'يرجى الانتهاء من تعديل المضلع قبل الإرسال.', 'he': 'אנא סיים לערוך את הפוליגון לפני השליחה.', 'id': 'Harap selesaikan pengeditan poligon sebelum mengirim.', 'ja': '提出前にポリゴンの編集を完了してください。'},
    'Please select a .shp file or .zip containing shapefile.': {'fr': 'Veuillez sélectionner un fichier .shp ou un .zip contenant un shapefile.', 'es': 'Por favor, seleccione un archivo .shp o un .zip que contenga un shapefile.', 'de': 'Bitte wählen Sie eine .shp-Datei oder ein .zip mit Shapefile aus.', 'it': 'Selezionare un file .shp o un .zip contenente il shapefile.', 'pt': 'Por favor, selecione um ficheiro .shp ou um .zip contendo um shapefile.', 'nl': 'Selecteer een .shp-bestand of een .zip met shapefile.', 'ca': 'Si us plau, seleccioneu un fitxer .shp o un .zip que contingui un shapefile.', 'ro': 'Vă rugăm selectați un fișier .shp sau un .zip care conține shapefile.', 'bg': 'Моля, изберете файл .shp или .zip съдържащ shapefile.', 'el': 'Παρακαλώ επιλέξτε αρχείο .shp ή .zip που περιέχει shapefile.', 'ar': 'يرجى تحديد ملف .shp أو .zip يحتوي على ملف الشكل.', 'he': 'אנא בחר קובץ .shp או .zip המכיל shapefile.', 'id': 'Harap pilih file .shp atau .zip yang berisi shapefile.', 'ja': '.shpファイルまたはshapefileを含む.zipを選択してください。'},
    'Please select a GeoJSON (.geojson) or Shapefile ZIP (.zip) file': {'fr': 'Veuillez sélectionner un fichier GeoJSON (.geojson) ou Shapefile ZIP (.zip)', 'es': 'Por favor, seleccione un archivo GeoJSON (.geojson) o Shapefile ZIP (.zip)', 'de': 'Bitte wählen Sie eine GeoJSON (.geojson) oder Shapefile ZIP (.zip) Datei', 'it': 'Selezionare un file GeoJSON (.geojson) o Shapefile ZIP (.zip)', 'pt': 'Por favor, selecione um ficheiro GeoJSON (.geojson) ou Shapefile ZIP (.zip)', 'nl': 'Selecteer een GeoJSON (.geojson) of Shapefile ZIP (.zip) bestand', 'ca': 'Si us plau, seleccioneu un fitxer GeoJSON (.geojson) o Shapefile ZIP (.zip)', 'ro': 'Vă rugăm selectați un fișier GeoJSON (.geojson) sau Shapefile ZIP (.zip)', 'bg': 'Моля, изберете GeoJSON (.geojson) или Shapefile ZIP (.zip) файл', 'el': 'Παρακαλώ επιλέξτε αρχείο GeoJSON (.geojson) ή Shapefile ZIP (.zip)', 'ar': 'يرجى تحديد ملف GeoJSON (.geojson) أو Shapefile ZIP (.zip)', 'he': 'אנא בחר קובץ GeoJSON (.geojson) או Shapefile ZIP (.zip)', 'id': 'Harap pilih file GeoJSON (.geojson) atau Shapefile ZIP (.zip)', 'ja': 'GeoJSON (.geojson) またはShapefile ZIP (.zip) ファイルを選択してください'},
    'Please, contact the Wikicaves team to report this bug:': {'fr': "Veuillez contacter l'équipe Wikicaves pour signaler ce bug :", 'es': 'Por favor, contacte al equipo de Wikicaves para reportar este error:', 'de': 'Bitte wenden Sie sich an das Wikicaves-Team, um diesen Fehler zu melden:', 'it': "Contattare il team Wikicaves per segnalare questo bug:", 'pt': 'Por favor, contacte a equipa Wikicaves para reportar este erro:', 'nl': 'Neem contact op met het Wikicaves-team om deze bug te melden:', 'ca': "Si us plau, poseu-vos en contacte amb l'equip de Wikicaves per informar d'aquest error:", 'ro': 'Vă rugăm contactați echipa Wikicaves pentru a raporta această eroare:', 'bg': 'Моля, свържете се с екипа на Wikicaves, за да съобщите за тази грешка:', 'el': 'Παρακαλώ επικοινωνήστε με την ομάδα Wikicaves για να αναφέρετε αυτό το σφάλμα:', 'ar': 'يرجى التواصل مع فريق Wikicaves للإبلاغ عن هذا الخطأ:', 'he': 'אנא צור קשר עם צוות Wikicaves כדי לדווח על הבאג הזה:', 'id': 'Harap hubungi tim Wikicaves untuk melaporkan bug ini:', 'ja': 'このバグを報告するためにWikicavesチームにご連絡ください：'},
    'Please, do not reply to this message. This message is a service email related to your use of Grottocenter.': {'fr': "Merci de ne pas répondre à ce message. Ce message est un e-mail de service lié à votre utilisation de Grottocenter.", 'es': 'Por favor, no responda a este mensaje. Este mensaje es un correo de servicio relacionado con su uso de Grottocenter.', 'de': 'Bitte antworten Sie nicht auf diese Nachricht. Diese Nachricht ist eine Service-E-Mail im Zusammenhang mit Ihrer Nutzung von Grottocenter.', 'it': "Non rispondere a questo messaggio. Questo messaggio è un'e-mail di servizio relativa all'utilizzo di Grottocenter.", 'pt': 'Por favor, não responda a esta mensagem. Esta mensagem é um e-mail de serviço relacionado com a sua utilização do Grottocenter.', 'nl': 'Beantwoord dit bericht niet. Dit bericht is een service-e-mail gerelateerd aan uw gebruik van Grottocenter.', 'ca': "Si us plau, no respongueu a aquest missatge. Aquest missatge és un correu de servei relacionat amb el vostre ús de Grottocenter.", 'ro': 'Vă rugăm să nu răspundeți la acest mesaj. Acest mesaj este un e-mail de serviciu legat de utilizarea dvs. a Grottocenter.', 'bg': 'Моля, не отговаряйте на това съобщение. То е сервизен имейл, свързан с използването на Grottocenter.', 'el': 'Παρακαλώ μην απαντάτε σε αυτό το μήνυμα. Αυτό το μήνυμα είναι ένα email υπηρεσίας σχετικό με τη χρήση του Grottocenter.', 'ar': 'يرجى عدم الرد على هذه الرسالة. هذه الرسالة هي بريد إلكتروني خدمي متعلق باستخدامك لـ Grottocenter.', 'he': 'אנא אל תשיב להודעה זו. הודעה זו היא מייל שירות הקשור לשימוש שלך ב-Grottocenter.', 'id': 'Harap jangan membalas pesan ini. Pesan ini adalah email layanan terkait penggunaan Grottocenter Anda.', 'ja': 'このメッセージには返信しないでください。このメッセージはGrottocenterのご利用に関するサービスメールです。'},
    'Polygon': {'fr': 'Polygone', 'es': 'Polígono', 'de': 'Polygon', 'it': 'Poligono', 'pt': 'Polígono', 'nl': 'Polygoon', 'ca': 'Polígon', 'ro': 'Poligon', 'bg': 'Полигон', 'el': 'Πολύγωνο', 'ar': 'مضلع', 'he': 'פוליגון', 'id': 'Poligon', 'ja': 'ポリゴン'},
}

with open(os.path.join(DIR, 'en.json'), encoding='utf-8') as f:
    en = json.load(f)

total = 0
for lang in ['fr','es','it','pt','de','nl','ca','ro','bg','el','ar','he','id','ja']:
    path = os.path.join(DIR, f'{lang}.json')
    with open(path, encoding='utf-8') as f:
        d = json.load(f)
    n = 0
    for k, langs in T.items():
        if k in en and lang in langs and (k not in d or d[k] == en[k]):
            d[k] = langs[lang]; n += 1
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(dict(sorted(d.items())), f, ensure_ascii=False, indent=2)
    total += n
    print(f'{lang}: +{n}')
print(f'Total: {total}')
