# -*- coding: utf-8 -*-
import json, os
DIR = os.path.dirname(os.path.abspath(__file__))

T = {
    'Portuguese': {'fr': 'Portugais', 'es': 'Portugués', 'de': 'Portugiesisch', 'it': 'Portoghese', 'pt': 'Português', 'nl': 'Portugees', 'ca': 'Portuguès', 'ro': 'Portugheză', 'bg': 'Португалски', 'el': 'Πορτογαλικά', 'ar': 'البرتغالية', 'he': 'פורטוגזית', 'id': 'Portugis', 'ja': 'ポルトガル語'},
    'Posted': {'fr': 'Publié', 'es': 'Publicado', 'de': 'Veröffentlicht', 'it': 'Pubblicato', 'pt': 'Publicado', 'nl': 'Geplaatst', 'ca': 'Publicat', 'ro': 'Publicat', 'bg': 'Публикувано', 'el': 'Δημοσιεύτηκε', 'ar': 'نُشر', 'he': 'פורסם', 'id': 'Diposting', 'ja': '投稿済み'},
    'Posted by': {'fr': 'Publié par', 'es': 'Publicado por', 'de': 'Veröffentlicht von', 'it': 'Pubblicato da', 'pt': 'Publicado por', 'nl': 'Geplaatst door', 'ca': 'Publicat per', 'ro': 'Publicat de', 'bg': 'Публикувано от', 'el': 'Δημοσιεύτηκε από', 'ar': 'نُشر بواسطة', 'he': 'פורסם על ידי', 'id': 'Diposting oleh', 'ja': '投稿者'},
    'Previous Page': {'fr': 'Page précédente', 'es': 'Página anterior', 'de': 'Vorherige Seite', 'it': 'Pagina precedente', 'pt': 'Página anterior', 'nl': 'Vorige pagina', 'ca': 'Pàgina anterior', 'ro': 'Pagina anterioară', 'bg': 'Предишна страница', 'el': 'Προηγούμενη σελίδα', 'ar': 'الصفحة السابقة', 'he': 'עמוד קודם', 'id': 'Halaman sebelumnya', 'ja': '前のページ'},
    'Previous name': {'fr': 'Nom précédent', 'es': 'Nombre anterior', 'de': 'Vorheriger Name', 'it': 'Nome precedente', 'pt': 'Nome anterior', 'nl': 'Vorige naam', 'ca': 'Nom anterior', 'ro': 'Nume anterior', 'bg': 'Предишно име', 'el': 'Προηγούμενο όνομα', 'ar': 'الاسم السابق', 'he': 'שם קודם', 'id': 'Nama sebelumnya', 'ja': '以前の名前'},
    'Previous nickname': {'fr': 'Pseudo précédent', 'es': 'Apodo anterior', 'de': 'Vorheriger Spitzname', 'it': 'Soprannome precedente', 'pt': 'Apelido anterior', 'nl': 'Vorige bijnaam', 'ca': 'Sobrenom anterior', 'ro': 'Pseudonim anterior', 'bg': 'Предишен псевдоним', 'el': 'Προηγούμενο ψευδώνυμο', 'ar': 'اسم الشهرة السابق', 'he': 'כינוי קודם', 'id': 'Nama panggilan sebelumnya', 'ja': '以前のニックネーム'},
    'Previous surname': {'fr': 'Nom de famille précédent', 'es': 'Apellido anterior', 'de': 'Vorheriger Nachname', 'it': 'Cognome precedente', 'pt': 'Apelido anterior', 'nl': 'Vorige achternaam', 'ca': 'Cognom anterior', 'ro': 'Prenume anterior', 'bg': 'Предишна фамилия', 'el': 'Προηγούμενο επώνυμο', 'ar': 'اللقب السابق', 'he': 'שם משפחה קודם', 'id': 'Nama belakang sebelumnya', 'ja': '以前の姓'},
    'Proceedings, reports or summaries of a conference, study, expedition': {'fr': "Actes, rapports ou résumés d'une conférence, étude, expédition", 'es': 'Actas, informes o resúmenes de una conferencia, estudio, expedición', 'de': 'Tagungsberichte, Berichte oder Zusammenfassungen einer Konferenz, Studie, Expedition', 'it': 'Atti, relazioni o riassunti di una conferenza, studio, spedizione', 'pt': 'Atas, relatórios ou resumos de uma conferência, estudo, expedição', 'nl': 'Proceedings, rapporten of samenvattingen van een conferentie, studie, expeditie', 'ca': "Actes, informes o resums d'una conferència, estudi, expedició", 'ro': 'Acte, rapoarte sau rezumate ale unei conferințe, studiu, expediție', 'bg': 'Протоколи, доклади или резюмета на конференция, изследване, експедиция', 'el': 'Πρακτικά, αναφορές ή περιλήψεις συνεδρίου, μελέτης, αποστολής', 'ar': 'وقائع أو تقارير أو ملخصات مؤتمر أو دراسة أو رحلة استكشافية', 'he': 'הליכים, דוחות או סיכומים של כנס, מחקר, משלחת', 'id': 'Prosiding, laporan atau ringkasan konferensi, studi, ekspedisi', 'ja': '会議・研究・探検の議事録、報告書または要約'},
    'Profile page of the user': {'fr': "Page de profil de l'utilisateur", 'es': 'Página de perfil del usuario', 'de': 'Profilseite des Benutzers', 'it': "Pagina del profilo dell'utente", 'pt': 'Página de perfil do utilizador', 'nl': 'Profielpagina van de gebruiker', 'ca': "Pàgina de perfil de l'usuari", 'ro': 'Pagina de profil a utilizatorului', 'bg': 'Страница на профила на потребителя', 'el': 'Σελίδα προφίλ του χρήστη', 'ar': 'صفحة الملف الشخصي للمستخدم', 'he': 'עמוד הפרופיל של המשתמש', 'id': 'Halaman profil pengguna', 'ja': 'ユーザーのプロフィールページ'},
    'Property name': {'fr': 'Nom de la propriété', 'es': 'Nombre de propiedad', 'de': 'Eigenschaftsname', 'it': 'Nome proprietà', 'pt': 'Nome da propriedade', 'nl': 'Eigenschapsnaam', 'ca': 'Nom de la propietat', 'ro': 'Numele proprietății', 'bg': 'Име на свойство', 'el': 'Όνομα ιδιότητας', 'ar': 'اسم الخاصية', 'he': 'שם מאפיין', 'id': 'Nama properti', 'ja': 'プロパティ名'},
    'Property value': {'fr': 'Valeur de la propriété', 'es': 'Valor de propiedad', 'de': 'Eigenschaftswert', 'it': 'Valore proprietà', 'pt': 'Valor da propriedade', 'nl': 'Eigenschapswaarde', 'ca': 'Valor de la propietat', 'ro': 'Valoarea proprietății', 'bg': 'Стойност на свойство', 'el': 'Τιμή ιδιότητας', 'ar': 'قيمة الخاصية', 'he': 'ערך מאפיין', 'id': 'Nilai properti', 'ja': 'プロパティ値'},
    'Publication': {'fr': 'Publication', 'es': 'Publicación', 'de': 'Publikation', 'it': 'Pubblicazione', 'pt': 'Publicação', 'nl': 'Publicatie', 'ca': 'Publicació', 'ro': 'Publicație', 'bg': 'Публикация', 'el': 'Δημοσίευση', 'ar': 'منشور', 'he': 'פרסום', 'id': 'Publikasi', 'ja': '出版物'},
    'Publication (BBS legacy)': {'fr': 'Publication (héritage BBS)', 'es': 'Publicación (legado BBS)', 'de': 'Publikation (BBS-Legacy)', 'it': 'Pubblicazione (legacy BBS)', 'pt': 'Publicação (legado BBS)', 'nl': 'Publicatie (BBS legacy)', 'ca': 'Publicació (llegat BBS)', 'ro': 'Publicație (moștenire BBS)', 'bg': 'Публикация (BBS наследство)', 'el': 'Δημοσίευση (BBS κληρονομιά)', 'ar': 'منشور (موروث BBS)', 'he': 'פרסום (BBS legacy)', 'id': 'Publikasi (warisan BBS)', 'ja': '出版物（BBSレガシー）'},
    'Publication Date': {'fr': 'Date de publication', 'es': 'Fecha de publicación', 'de': 'Erscheinungsdatum', 'it': 'Data di pubblicazione', 'pt': 'Data de publicação', 'nl': 'Publicatiedatum', 'ca': 'Data de publicació', 'ro': 'Data publicației', 'bg': 'Дата на публикуване', 'el': 'Ημερομηνία δημοσίευσης', 'ar': 'تاريخ النشر', 'he': 'תאריך פרסום', 'id': 'Tanggal publikasi', 'ja': '出版日'},
    'Publication date': {'fr': 'Date de publication', 'es': 'Fecha de publicación', 'de': 'Erscheinungsdatum', 'it': 'Data di pubblicazione', 'pt': 'Data de publicação', 'nl': 'Publicatiedatum', 'ca': 'Data de publicació', 'ro': 'Data publicației', 'bg': 'Дата на публикуване', 'el': 'Ημερομηνία δημοσίευσης', 'ar': 'تاريخ النشر', 'he': 'תאריך פרסום', 'id': 'Tanggal publikasi', 'ja': '出版日'},
    'Publication date of the document, i.e., when it was publicily available. You can refer to the printed date on the document.': {'fr': "Date de publication du document, c'est-à-dire quand il a été rendu publiquement disponible. Vous pouvez vous référer à la date imprimée sur le document.", 'es': 'Fecha de publicación del documento, es decir, cuándo estuvo disponible públicamente. Puede consultar la fecha impresa en el documento.', 'de': 'Veröffentlichungsdatum des Dokuments, d.h. wann es öffentlich verfügbar war. Sie können das auf dem Dokument aufgedruckte Datum verwenden.', 'it': 'Data di pubblicazione del documento, ovvero quando era disponibile pubblicamente. Puoi fare riferimento alla data stampata sul documento.', 'pt': 'Data de publicação do documento, ou seja, quando ficou disponível ao público. Pode consultar a data impressa no documento.', 'nl': 'Publicatiedatum van het document, d.w.z. wanneer het publiekelijk beschikbaar was. U kunt de gedrukte datum op het document raadplegen.', 'ca': "Data de publicació del document, és a dir, quan va estar disponible públicament. Podeu consultar la data impresa al document.", 'ro': 'Data publicării documentului, adică când a fost disponibil public. Puteți consulta data tipărită pe document.', 'bg': 'Датата на публикуване на документа, т.е. кога е станал публично достъпен. Можете да се позовете на отпечатаната дата на документа.', 'el': 'Ημερομηνία δημοσίευσης του εγγράφου, δηλαδή πότε έγινε δημόσια διαθέσιμο. Μπορείτε να ανατρέξτε στην τυπωμένη ημερομηνία στο έγγραφο.', 'ar': 'تاريخ نشر الوثيقة، أي متى أصبحت متاحة للعموم. يمكنك الرجوع إلى التاريخ المطبوع على الوثيقة.', 'he': 'תאריך פרסום המסמך, כלומר מתי הפך לזמין לציבור. ניתן להתייחס לתאריך המודפס על המסמך.', 'id': 'Tanggal publikasi dokumen, yaitu kapan tersedia untuk umum. Anda dapat merujuk pada tanggal yang tercetak pada dokumen.', 'ja': '文書の出版日、つまり公開された日付。文書に印刷された日付を参照できます。'},
}

with open(os.path.join(DIR, 'en.json'), encoding='utf-8') as f:
    en = json.load(f)

total = 0
for lang in ['fr','es','it','pt','de','nl','ca','ro','bg','el','ar','he','id','ja']:
    path = os.path.join(DIR, f'{lang}.json')
    with open(path, encoding='utf-8') as f:
        d = json.load(f)
    n = 0
    for k, langs in T.items():
        if k in en and lang in langs and (k not in d or d[k] == en[k]):
            d[k] = langs[lang]; n += 1
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(dict(sorted(d.items())), f, ensure_ascii=False, indent=2)
    total += n
    print(f'{lang}: +{n}')
print(f'Total: {total}')
