# -*- coding: utf-8 -*-
import json, os
DIR = os.path.dirname(os.path.abspath(__file__))

T = {
    'Search for a {entityFmt}': {'fr': 'Rechercher un(e) {entityFmt}', 'es': 'Buscar un(a) {entityFmt}', 'de': 'Suche nach {entityFmt}', 'it': 'Cerca un(a) {entityFmt}', 'pt': 'Pesquisar um(a) {entityFmt}', 'nl': 'Zoek een {entityFmt}', 'ca': 'Cercar un(a) {entityFmt}', 'ro': 'Căutați un(o) {entityFmt}', 'bg': 'Търсене на {entityFmt}', 'el': 'Αναζήτηση για {entityFmt}', 'ar': 'البحث عن {entityFmt}', 'he': 'חפש {entityFmt}', 'id': 'Cari {entityFmt}', 'ja': '{entityFmt}を検索'},
    'Search for an editor...': {'fr': 'Rechercher un éditeur...', 'es': 'Buscar un editor...', 'de': 'Herausgeber suchen...', 'it': 'Cerca un editore...', 'pt': 'Pesquisar um editor...', 'nl': 'Zoek een redacteur...', 'ca': 'Cercar un editor...', 'ro': 'Căutați un editor...', 'bg': 'Търсене на редактор...', 'el': 'Αναζήτηση συντάκτη...', 'ar': 'البحث عن محرر...', 'he': 'חיפוש עורך...', 'id': 'Cari editor...', 'ja': '編集者を検索...'},
    'Select a cave or network using the search bar below.': {'fr': 'Sélectionnez une cavité ou un réseau en utilisant la barre de recherche ci-dessous.', 'es': 'Seleccione una cueva o red utilizando la barra de búsqueda a continuación.', 'de': 'Wählen Sie eine Höhle oder ein Netzwerk über die Suchleiste unten aus.', 'it': 'Seleziona una grotta o una rete usando la barra di ricerca qui sotto.', 'pt': 'Selecione uma caverna ou rede usando a barra de pesquisa abaixo.', 'nl': 'Selecteer een grot of netwerk via de zoekbalk hieronder.', 'ca': 'Seleccioneu una cova o xarxa usant la barra de cerca a continuació.', 'ro': 'Selectați o peșteră sau rețea folosind bara de căutare de mai jos.', 'bg': 'Изберете пещера или мрежа чрез лентата за търсене по-долу.', 'el': 'Επιλέξτε σπήλαιο ή δίκτυο χρησιμοποιώντας τη γραμμή αναζήτησης παρακάτω.', 'ar': 'حدد كهفاً أو شبكة باستخدام شريط البحث أدناه.', 'he': 'בחר מערה או רשת באמצעות שורת החיפוש למטה.', 'id': 'Pilih gua atau jaringan menggunakan bilah pencarian di bawah.', 'ja': '下の検索バーを使って洞窟またはネットワークを選択してください。'},
    'Select a type of authorization': {'fr': "Sélectionnez un type d'autorisation", 'es': 'Seleccione un tipo de autorización', 'de': 'Wählen Sie einen Autorisierungstyp', 'it': 'Seleziona un tipo di autorizzazione', 'pt': 'Selecione um tipo de autorização', 'nl': 'Selecteer een type autorisatie', 'ca': "Seleccioneu un tipus d'autorització", 'ro': 'Selectați un tip de autorizare', 'bg': 'Изберете вид разрешение', 'el': 'Επιλέξτε τύπο εξουσιοδότησης', 'ar': 'حدد نوع التخويل', 'he': 'בחר סוג הרשאה', 'id': 'Pilih jenis otorisasi', 'ja': '認証タイプを選択'},
    'Select an authorization document': {'fr': "Sélectionnez un document d'autorisation", 'es': 'Seleccione un documento de autorización', 'de': 'Wählen Sie ein Autorisierungsdokument', 'it': 'Seleziona un documento di autorizzazione', 'pt': 'Selecione um documento de autorização', 'nl': 'Selecteer een autorisatiedocument', 'ca': "Seleccioneu un document d'autorització", 'ro': 'Selectați un document de autorizare', 'bg': 'Изберете документ за разрешение', 'el': 'Επιλέξτε έγγραφο εξουσιοδότησης', 'ar': 'حدد مستند التخويل', 'he': 'בחר מסמך הרשאה', 'id': 'Pilih dokumen otorisasi', 'ja': '認証文書を選択'},
    'Select an identifier type': {'fr': "Sélectionnez un type d'identifiant", 'es': 'Seleccione un tipo de identificador', 'de': 'Identifikatortyp auswählen', 'it': 'Seleziona un tipo di identificatore', 'pt': 'Selecione um tipo de identificador', 'nl': 'Selecteer een identificatortype', 'ca': "Seleccioneu un tipus d'identificador", 'ro': 'Selectați un tip de identificator', 'bg': 'Изберете вид идентификатор', 'el': 'Επιλέξτε τύπο αναγνωριστικού', 'ar': 'حدد نوع المعرف', 'he': 'בחר סוג מזהה', 'id': 'Pilih jenis pengidentifikasi', 'ja': '識別子タイプを選択'},
    'Select document(s) by clicking on the result table above.': {'fr': 'Sélectionnez le(s) document(s) en cliquant sur le tableau de résultats ci-dessus.', 'es': 'Seleccione el/los documento(s) haciendo clic en la tabla de resultados arriba.', 'de': 'Wählen Sie Dokument(e) aus, indem Sie auf die Ergebnistabelle oben klicken.', 'it': 'Seleziona i documenti cliccando sulla tabella dei risultati sopra.', 'pt': 'Selecione o(s) documento(s) clicando na tabela de resultados acima.', 'nl': 'Selecteer document(en) door op de resultaattabel hierboven te klikken.', 'ca': 'Seleccioneu els documents fent clic a la taula de resultats de dalt.', 'ro': 'Selectați document(e) făcând clic pe tabelul de rezultate de mai sus.', 'bg': 'Изберете документ(и) като щракнете върху таблицата с резултати по-горе.', 'el': 'Επιλέξτε έγγραφο(-α) κάνοντας κλικ στον παραπάνω πίνακα αποτελεσμάτων.', 'ar': 'حدد المستند(ات) بالنقر على جدول النتائج أعلاه.', 'he': 'בחר מסמך/ים על ידי לחיצה על טבלת התוצאות למעלה.', 'id': 'Pilih dokumen dengan mengklik tabel hasil di atas.', 'ja': '上の結果テーブルをクリックして文書を選択してください。'},
    'Selected': {'fr': 'Sélectionné', 'es': 'Seleccionado', 'de': 'Ausgewählt', 'it': 'Selezionato', 'pt': 'Selecionado', 'nl': 'Geselecteerd', 'ca': 'Seleccionat', 'ro': 'Selectat', 'bg': 'Избрано', 'el': 'Επιλεγμένο', 'ar': 'محدد', 'he': 'נבחר', 'id': 'Dipilih', 'ja': '選択済み'},
    'Server-side creation of the document is not available.': {'fr': "La création du document côté serveur n'est pas disponible.", 'es': 'La creación del documento en el servidor no está disponible.', 'de': 'Die serverseitige Erstellung des Dokuments ist nicht verfügbar.', 'it': 'La creazione del documento lato server non è disponibile.', 'pt': 'A criação do documento no servidor não está disponível.', 'nl': 'Aanmaken van document aan serverzijde is niet beschikbaar.', 'ca': 'La creació del document al servidor no està disponible.', 'ro': 'Crearea documentului pe server nu este disponibilă.', 'bg': 'Създаването на документа от страна на сървъра не е налично.', 'el': 'Η δημιουργία εγγράφου από την πλευρά του διακομιστή δεν είναι διαθέσιμη.', 'ar': 'إنشاء المستند من جهة الخادم غير متاح.', 'he': 'יצירת המסמך בצד השרת אינה זמינה.', 'id': 'Pembuatan dokumen dari sisi server tidak tersedia.', 'ja': 'サーバー側でのドキュメント作成は利用できません。'},
    'Service': {'fr': 'Service', 'es': 'Servicio', 'de': 'Dienst', 'it': 'Servizio', 'pt': 'Serviço', 'nl': 'Dienst', 'ca': 'Servei', 'ro': 'Serviciu', 'bg': 'Услуга', 'el': 'Υπηρεσία', 'ar': 'خدمة', 'he': 'שירות', 'id': 'Layanan', 'ja': 'サービス'},
    'Shapefile imported successfully!': {'fr': 'Shapefile importé avec succès !', 'es': '¡Shapefile importado con éxito!', 'de': 'Shapefile erfolgreich importiert!', 'it': 'Shapefile importato con successo!', 'pt': 'Shapefile importado com sucesso!', 'nl': 'Shapefile succesvol geïmporteerd!', 'ca': 'Shapefile importat correctament!', 'ro': 'Shapefile importat cu succes!', 'bg': 'Shapefile е импортиран успешно!', 'el': 'Το shapefile εισήχθη επιτυχώς!', 'ar': 'تم استيراد ملف الشكل بنجاح!', 'he': 'קובץ ה-shapefile יובא בהצלחה!', 'id': 'Shapefile berhasil diimpor!', 'ja': 'シェープファイルのインポートに成功しました！'},
    'Share': {'fr': 'Partager', 'es': 'Compartir', 'de': 'Teilen', 'it': 'Condividi', 'pt': 'Partilhar', 'nl': 'Delen', 'ca': 'Compartir', 'ro': 'Distribuiți', 'bg': 'Споделяне', 'el': 'Κοινοποίηση', 'ar': 'مشاركة', 'he': 'שתף', 'id': 'Bagikan', 'ja': 'シェア'},
    'Simplification Tolerance': {'fr': 'Tolérance de simplification', 'es': 'Tolerancia de simplificación', 'de': 'Vereinfachungstoleranz', 'it': 'Tolleranza di semplificazione', 'pt': 'Tolerância de simplificação', 'nl': 'Vereenvoudigingstolerantie', 'ca': 'Tolerància de simplificació', 'ro': 'Toleranță de simplificare', 'bg': 'Толеранс на опростяване', 'el': 'Ανοχή απλοποίησης', 'ar': 'تسامح التبسيط', 'he': 'סובלנות פישוט', 'id': 'Toleransi penyederhanaan', 'ja': '単純化の許容値'},
    'Size': {'fr': 'Taille', 'es': 'Tamaño', 'de': 'Größe', 'it': 'Dimensione', 'pt': 'Tamanho', 'nl': 'Grootte', 'ca': 'Mida', 'ro': 'Dimensiune', 'bg': 'Размер', 'el': 'Μέγεθος', 'ar': 'الحجم', 'he': 'גודל', 'id': 'Ukuran', 'ja': 'サイズ'},
    'Software': {'fr': 'Logiciel', 'es': 'Software', 'de': 'Software', 'it': 'Software', 'pt': 'Software', 'nl': 'Software', 'ca': 'Programari', 'ro': 'Software', 'bg': 'Софтуер', 'el': 'Λογισμικό', 'ar': 'برنامج', 'he': 'תוכנה', 'id': 'Perangkat lunak', 'ja': 'ソフトウェア'},
    'Some helper text for Identifier Type.': {'fr': "Texte d'aide pour le type d'identifiant.", 'es': 'Texto de ayuda para el tipo de identificador.', 'de': 'Hilfetext für den Identifikatortyp.', 'it': 'Testo di aiuto per il tipo di identificatore.', 'pt': 'Texto de ajuda para o tipo de identificador.', 'nl': 'Helptekst voor identificatortype.', 'ca': "Text d'ajuda per al tipus d'identificador.", 'ro': 'Text de ajutor pentru tipul de identificator.', 'bg': 'Помощен текст за вида идентификатор.', 'el': 'Βοηθητικό κείμενο για τον τύπο αναγνωριστικού.', 'ar': 'نص تعليمي لنوع المعرف.', 'he': 'טקסט עזרה לסוג המזהה.', 'id': 'Teks bantuan untuk Tipe Pengidentifikasi.', 'ja': '識別子タイプのヘルプテキスト。'},
    'Some polygons are very thin or elongated. Check them before saving.': {'fr': 'Certains polygones sont très fins ou allongés. Vérifiez-les avant de sauvegarder.', 'es': 'Algunos polígonos son muy delgados o alargados. Compruébelos antes de guardar.', 'de': 'Einige Polygone sind sehr dünn oder gestreckt. Überprüfen Sie diese vor dem Speichern.', 'it': 'Alcuni poligoni sono molto sottili o allungati. Controllali prima di salvare.', 'pt': 'Alguns polígonos são muito finos ou alongados. Verifique-os antes de guardar.', 'nl': 'Sommige polygonen zijn erg dun of langwerpig. Controleer ze voor het opslaan.', 'ca': 'Alguns polígons són molt prims o allargats. Comproveu-los abans de desar.', 'ro': 'Unele poligoane sunt foarte subțiri sau alungite. Verificați-le înainte de salvare.', 'bg': 'Някои полигони са много тесни или издължени. Проверете ги преди запазване.', 'el': 'Μερικά πολύγωνα είναι πολύ λεπτά ή επιμήκη. Ελέγξτε τα πριν την αποθήκευση.', 'ar': 'بعض المضلعات رفيعة جداً أو طويلة. تحقق منها قبل الحفظ.', 'he': 'כמה פוליגונים דקים מאוד או מוארכים. בדוק אותם לפני השמירה.', 'id': 'Beberapa poligon sangat tipis atau memanjang. Periksa sebelum menyimpan.', 'ja': '非常に薄いまたは細長いポリゴンがあります。保存前に確認してください。'},
    'Sound': {'fr': 'Son', 'es': 'Sonido', 'de': 'Ton', 'it': 'Suono', 'pt': 'Som', 'nl': 'Geluid', 'ca': 'So', 'ro': 'Sunet', 'bg': 'Звук', 'el': 'Ήχος', 'ar': 'صوت', 'he': 'צליל', 'id': 'Suara', 'ja': 'サウンド'},
    'Source': {'fr': 'Source', 'es': 'Fuente', 'de': 'Quelle', 'it': 'Fonte', 'pt': 'Fonte', 'nl': 'Bron', 'ca': 'Font', 'ro': 'Sursă', 'bg': 'Източник', 'el': 'Πηγή', 'ar': 'المصدر', 'he': 'מקור', 'id': 'Sumber', 'ja': 'ソース'},
}

with open(os.path.join(DIR, 'en.json'), encoding='utf-8') as f:
    en = json.load(f)

total = 0
for lang in ['fr','es','it','pt','de','nl','ca','ro','bg','el','ar','he','id','ja']:
    path = os.path.join(DIR, f'{lang}.json')
    with open(path, encoding='utf-8') as f:
        d = json.load(f)
    n = 0
    for k, langs in T.items():
        if k in en and lang in langs and (k not in d or d[k] == en[k]):
            d[k] = langs[lang]; n += 1
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(dict(sorted(d.items())), f, ensure_ascii=False, indent=2)
    total += n
    print(f'{lang}: +{n}')
print(f'Total: {total}')
