# -*- coding: utf-8 -*-
import json, os
DIR = os.path.dirname(os.path.abspath(__file__))

T = {
    'Source id': {'fr': 'ID source', 'es': 'ID de fuente', 'de': 'Quell-ID', 'it': 'ID fonte', 'pt': 'ID de fonte', 'nl': 'Bron-ID', 'ca': 'ID de font', 'ro': 'ID sursă', 'bg': 'Идентификатор на източника', 'el': 'ID πηγής', 'ar': 'معرف المصدر', 'he': 'מזהה מקור', 'id': 'ID sumber', 'ja': 'ソースID'},
    'Sovereign countries and autonomous territories (ISO 3166-1)': {'fr': 'Pays souverains et territoires autonomes (ISO 3166-1)', 'es': 'Países soberanos y territorios autónomos (ISO 3166-1)', 'de': 'Souveräne Länder und autonome Gebiete (ISO 3166-1)', 'it': 'Paesi sovrani e territori autonomi (ISO 3166-1)', 'pt': 'Países soberanos e territórios autónomos (ISO 3166-1)', 'nl': 'Soevereine landen en autonome gebieden (ISO 3166-1)', 'ca': 'Països sobirans i territoris autònoms (ISO 3166-1)', 'ro': 'Țări suverane și teritorii autonome (ISO 3166-1)', 'bg': 'Суверенни държави и автономни територии (ISO 3166-1)', 'el': 'Κυρίαρχες χώρες και αυτόνομα εδάφη (ISO 3166-1)', 'ar': 'الدول ذات السيادة والأقاليم المستقلة (ISO 3166-1)', 'he': 'מדינות ריבוניות ושטחים אוטונומיים (ISO 3166-1)', 'id': 'Negara berdaulat dan wilayah otonom (ISO 3166-1)', 'ja': '主権国家および自治領（ISO 3166-1）'},
    'Specifics caves': {'fr': 'Cavités spécifiques', 'es': 'Cuevas específicas', 'de': 'Bestimmte Höhlen', 'it': 'Grotte specifiche', 'pt': 'Cavernas específicas', 'nl': 'Specifieke grotten', 'ca': 'Coves específiques', 'ro': 'Peșteri specifice', 'bg': 'Конкретни пещери', 'el': 'Συγκεκριμένα σπήλαια', 'ar': 'كهوف محددة', 'he': 'מערות ספציפיות', 'id': 'Gua-gua tertentu', 'ja': '特定の洞窟'},
    'Specify if the search results must match all the fields you typed above (default is yes).': {'fr': 'Indiquez si les résultats de recherche doivent correspondre à tous les champs saisis ci-dessus (par défaut : oui).', 'es': 'Especifique si los resultados de búsqueda deben coincidir con todos los campos que escribió arriba (el valor predeterminado es sí).', 'de': 'Geben Sie an, ob die Suchergebnisse alle oben eingegebenen Felder übereinstimmen müssen (Standard: ja).', 'it': 'Specifica se i risultati della ricerca devono corrispondere a tutti i campi inseriti sopra (il valore predefinito è sì).', 'pt': 'Especifique se os resultados da pesquisa devem corresponder a todos os campos que digitou acima (o padrão é sim).', 'nl': 'Geef aan of de zoekresultaten moeten overeenkomen met alle velden die u hierboven hebt ingetypt (standaard is ja).', 'ca': 'Especifiqueu si els resultats de cerca han de coincidir amb tots els camps que heu escrit (el valor per defecte és sí).', 'ro': 'Specificați dacă rezultatele căutării trebuie să corespundă tuturor câmpurilor introduse mai sus (implicit este da).', 'bg': 'Посочете дали резултатите от търсенето трябва да съответстват на всички въведени полета по-горе (по подразбиране е да).', 'el': 'Καθορίστε αν τα αποτελέσματα αναζήτησης πρέπει να ταιριάζουν με όλα τα πεδία που πληκτρολογήσατε παραπάνω (προεπιλογή ναι).', 'ar': 'حدد ما إذا كانت نتائج البحث يجب أن تطابق جميع الحقول التي كتبتها أعلاه (الافتراضي نعم).', 'he': 'ציין אם תוצאות החיפוש חייבות להתאים לכל השדות שהזנת למעלה (ברירת המחדל היא כן).', 'id': 'Tentukan apakah hasil pencarian harus cocok dengan semua bidang yang Anda ketik di atas (default adalah ya).', 'ja': '検索結果が上記で入力したすべてのフィールドと一致する必要があるかどうかを指定してください（デフォルトははい）。'},
    'Speleological Abstracts': {'fr': 'Abstracts Spéléologiques', 'es': 'Resúmenes Espeleológicos', 'de': 'Speleologische Abstracts', 'it': 'Abstract Speleologici', 'pt': 'Resumos Espeleológicos', 'nl': 'Speleologische abstracts', 'ca': 'Resums Espeleològics', 'ro': 'Rezumate Speologice', 'bg': 'Спелеоложки абстракти', 'el': 'Σπηλαιολογικές Περιλήψεις', 'ar': 'ملخصات كهفية', 'he': 'תקצירים ספלאולוגיים', 'id': 'Abstrak Speleologi', 'ja': '洞窟学要約'},
    'Stay on trail': {'fr': 'Rester sur le sentier', 'es': 'Mantenerse en el camino', 'de': 'Auf dem Weg bleiben', 'it': 'Restare in percorso', 'pt': 'Manter-se na trilha', 'nl': 'Op het pad blijven', 'ca': 'Mantenir-se al camí', 'ro': 'Rămâneți pe traseu', 'bg': 'Останете на пътеката', 'el': 'Μείνετε στο μονοπάτι', 'ar': 'ابقَ على المسار', 'he': 'הישאר בנתיב', 'id': 'Tetap di jalur', 'ja': 'コースにとどまる'},
    'Subjects': {'fr': 'Sujets', 'es': 'Temas', 'de': 'Themen', 'it': 'Soggetti', 'pt': 'Assuntos', 'nl': 'Onderwerpen', 'ca': 'Temes', 'ro': 'Subiecte', 'bg': 'Теми', 'el': 'Θέματα', 'ar': 'موضوعات', 'he': 'נושאים', 'id': 'Subjek', 'ja': 'テーマ'},
    'Subscriptions': {'fr': 'Abonnements', 'es': 'Suscripciones', 'de': 'Abonnements', 'it': 'Abbonamenti', 'pt': 'Subscrições', 'nl': 'Abonnementen', 'ca': 'Subscripcions', 'ro': 'Abonamente', 'bg': 'Абонаменти', 'el': 'Συνδρομές', 'ar': 'الاشتراكات', 'he': 'מנויים', 'id': 'Langganan', 'ja': 'サブスクリプション'},
    'Subtheme': {'fr': 'Sous-thème', 'es': 'Subtema', 'de': 'Unterthema', 'it': 'Sottotema', 'pt': 'Sub-tema', 'nl': 'Subthema', 'ca': 'Sub-tema', 'ro': 'Subtemă', 'bg': 'Подтема', 'el': 'Υποθέμα', 'ar': 'موضوع فرعي', 'he': 'תת-נושא', 'id': 'Subtema', 'ja': 'サブテーマ'},
    'Summary': {'fr': 'Résumé', 'es': 'Resumen', 'de': 'Zusammenfassung', 'it': 'Riassunto', 'pt': 'Resumo', 'nl': 'Samenvatting', 'ca': 'Resum', 'ro': 'Rezumat', 'bg': 'Резюме', 'el': 'Περίληψη', 'ar': 'ملخص', 'he': 'סיכום', 'id': 'Ringkasan', 'ja': '要約'},
    'Summary of document content': {'fr': 'Résumé du contenu du document', 'es': 'Resumen del contenido del documento', 'de': 'Zusammenfassung des Dokumentinhalts', 'it': 'Riassunto del contenuto del documento', 'pt': 'Resumo do conteúdo do documento', 'nl': 'Samenvatting van documentinhoud', 'ca': 'Resum del contingut del document', 'ro': 'Rezumatul conținutului documentului', 'bg': 'Резюме на съдържанието на документа', 'el': 'Περίληψη περιεχομένου εγγράφου', 'ar': 'ملخص محتوى الوثيقة', 'he': 'סיכום תוכן המסמך', 'id': 'Ringkasan isi dokumen', 'ja': '文書の内容の要約'},
    'Synthesis': {'fr': 'Synthèse', 'es': 'Síntesis', 'de': 'Synthese', 'it': 'Sintesi', 'pt': 'Síntese', 'nl': 'Synthese', 'ca': 'Síntesi', 'ro': 'Sinteză', 'bg': 'Синтез', 'el': 'Σύνθεση', 'ar': 'تركيب', 'he': 'סינתזה', 'id': 'Sintesis', 'ja': '総合'},
    'Temperature': {'fr': 'Température', 'es': 'Temperatura', 'de': 'Temperatur', 'it': 'Temperatura', 'pt': 'Temperatura', 'nl': 'Temperatuur', 'ca': 'Temperatura', 'ro': 'Temperatură', 'bg': 'Температура', 'el': 'Θερμοκρασία', 'ar': 'درجة الحرارة', 'he': 'טמפרטורה', 'id': 'Suhu', 'ja': '温度'},
    'Temperature must be an integer (in °C)': {'fr': 'La température doit être un entier (en °C)', 'es': 'La temperatura debe ser un número entero (en °C)', 'de': 'Die Temperatur muss eine ganze Zahl sein (in °C)', 'it': 'La temperatura deve essere un numero intero (in °C)', 'pt': 'A temperatura deve ser um número inteiro (em °C)', 'nl': 'Temperatuur moet een geheel getal zijn (in °C)', 'ca': 'La temperatura ha de ser un nombre enter (en °C)', 'ro': 'Temperatura trebuie să fie un număr întreg (în °C)', 'bg': 'Температурата трябва да е цяло число (в °C)', 'el': 'Η θερμοκρασία πρέπει να είναι ακέραιος αριθμός (σε °C)', 'ar': 'يجب أن تكون درجة الحرارة عدداً صحيحاً (بدرجة مئوية)', 'he': 'הטמפרטורה חייבת להיות מספר שלם (ב-°C)', 'id': 'Suhu harus bilangan bulat (dalam °C)', 'ja': '温度は整数でなければなりません（°C）'},
    'Temperature must be between -100 and 100 °C': {'fr': 'La température doit être comprise entre -100 et 100 °C', 'es': 'La temperatura debe estar entre -100 y 100 °C', 'de': 'Die Temperatur muss zwischen -100 und 100 °C liegen', 'it': 'La temperatura deve essere compresa tra -100 e 100 °C', 'pt': 'A temperatura deve estar entre -100 e 100 °C', 'nl': 'Temperatuur moet tussen -100 en 100 °C liggen', 'ca': 'La temperatura ha d\'estar entre -100 i 100 °C', 'ro': 'Temperatura trebuie să fie între -100 și 100 °C', 'bg': 'Температурата трябва да е между -100 и 100 °C', 'el': 'Η θερμοκρασία πρέπει να είναι μεταξύ -100 και 100 °C', 'ar': 'يجب أن تكون درجة الحرارة بين -100 و 100 °C', 'he': 'הטמפרטורה חייבת להיות בין -100 ל-100 °C', 'id': 'Suhu harus antara -100 dan 100 °C', 'ja': '温度は-100から100°Cの間でなければなりません'},
    'Text': {'fr': 'Texte', 'es': 'Texto', 'de': 'Text', 'it': 'Testo', 'pt': 'Texto', 'nl': 'Tekst', 'ca': 'Text', 'ro': 'Text', 'bg': 'Текст', 'el': 'Κείμενο', 'ar': 'نص', 'he': 'טקסט', 'id': 'Teks', 'ja': 'テキスト'},
}

with open(os.path.join(DIR, 'en.json'), encoding='utf-8') as f:
    en = json.load(f)

total = 0
for lang in ['fr','es','it','pt','de','nl','ca','ro','bg','el','ar','he','id','ja']:
    path = os.path.join(DIR, f'{lang}.json')
    with open(path, encoding='utf-8') as f:
        d = json.load(f)
    n = 0
    for k, langs in T.items():
        if k in en and lang in langs and (k not in d or d[k] == en[k]):
            d[k] = langs[lang]; n += 1
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(dict(sorted(d.items())), f, ensure_ascii=False, indent=2)
    total += n
    print(f'{lang}: +{n}')
print(f'Total: {total}')
