# -*- coding: utf-8 -*-
import json, os
DIR = os.path.dirname(os.path.abspath(__file__))

T = {
    'Thanks': {'fr': 'Merci', 'es': 'Gracias', 'de': 'Danke', 'it': 'Grazie', 'pt': 'Obrigado', 'nl': 'Bedankt', 'ca': 'Gràcies', 'ro': 'Mulțumesc', 'bg': 'Благодаря', 'el': 'Ευχαριστώ', 'ar': 'شكراً', 'he': 'תודה', 'id': 'Terima kasih', 'ja': 'ありがとう'},
    'The BBS ("Bulletin Bibliographique Spéléologique" in french) is an annual review of the worldwide speleological literature.': {'fr': 'Le BBS (« Bulletin Bibliographique Spéléologique ») est une revue annuelle de la littérature spéléologique mondiale.', 'es': 'El BBS ("Bulletin Bibliographique Spéléologique" en francés) es una revisión anual de la literatura espeleológica mundial.', 'de': 'Das BBS ("Bulletin Bibliographique Spéléologique" auf Französisch) ist eine jährliche Übersicht der weltweiten speleologischen Literatur.', 'it': 'Il BBS ("Bulletin Bibliographique Spéléologique" in francese) è una revisione annuale della letteratura speleologica mondiale.', 'pt': 'O BBS ("Bulletin Bibliographique Spéléologique" em francês) é uma revisão anual da literatura espeleológica mundial.', 'nl': 'De BBS ("Bulletin Bibliographique Spéléologique" in het Frans) is een jaarlijks overzicht van de wereldwijde speleologische literatuur.', 'ca': 'El BBS ("Bulletin Bibliographique Spéléologique" en francès) és una revisió anual de la literatura espeleològica mundial.', 'ro': 'BBS ("Bulletin Bibliographique Spéléologique" în franceză) este o revizuire anuală a literaturii speleologice mondiale.', 'bg': 'BBS ("Bulletin Bibliographique Spéléologique" на френски) е годишен преглед на световната спелеоложка литература.', 'el': 'Το BBS ("Bulletin Bibliographique Spéléologique" στα γαλλικά) είναι μια ετήσια επισκόπηση της παγκόσμιας σπηλαιολογικής βιβλιογραφίας.', 'ar': 'BBS ("Bulletin Bibliographique Spéléologique" بالفرنسية) هو مراجعة سنوية للأدبيات الكهفية العالمية.', 'he': 'ה-BBS ("Bulletin Bibliographique Spéléologique" בצרפתית) הוא סקירה שנתית של הספרות הספלאולוגית העולמית.', 'id': 'BBS ("Bulletin Bibliographique Spéléologique" dalam bahasa Prancis) adalah tinjauan tahunan literatur speleologi dunia.', 'ja': 'BBS（フランス語で「Bulletin Bibliographique Spéléologique」）は、世界の洞窟学文献の年次レビューです。'},
    'The BBS is now directly integrated in Grottocenter and provides a summary of any document published on paper or online.': {'fr': 'Le BBS est maintenant directement intégré dans Grottocenter et fournit un résumé de tout document publié sur papier ou en ligne.', 'es': 'El BBS está ahora directamente integrado en Grottocenter y proporciona un resumen de cualquier documento publicado en papel o en línea.', 'de': 'Das BBS ist jetzt direkt in Grottocenter integriert und bietet eine Zusammenfassung jedes auf Papier oder online veröffentlichten Dokuments.', 'it': 'Il BBS è ora direttamente integrato in Grottocenter e fornisce un riepilogo di qualsiasi documento pubblicato su carta o online.', 'pt': 'O BBS está agora diretamente integrado no Grottocenter e fornece um resumo de qualquer documento publicado em papel ou online.', 'nl': 'De BBS is nu direct geïntegreerd in Grottocenter en biedt een samenvatting van elk document dat op papier of online is gepubliceerd.', 'ca': 'El BBS ara està directament integrat a Grottocenter i proporciona un resum de qualsevol document publicat en paper o en línia.', 'ro': 'BBS este acum integrat direct în Grottocenter și oferă un rezumat al oricărui document publicat pe hârtie sau online.', 'bg': 'BBS вече е директно интегриран в Grottocenter и предоставя резюме на всеки документ, публикуван на хартия или онлайн.', 'el': 'Το BBS είναι τώρα άμεσα ενσωματωμένο στο Grottocenter και παρέχει περίληψη κάθε εγγράφου που δημοσιεύτηκε σε χαρτί ή διαδικτυακά.', 'ar': 'تم دمج BBS الآن مباشرة في Grottocenter ويوفر ملخصاً لأي وثيقة منشورة على الورق أو عبر الإنترنت.', 'he': 'ה-BBS משולב כעת ישירות ב-Grottocenter ומספק סיכום של כל מסמך שפורסם בנייר או אונליין.', 'id': 'BBS kini terintegrasi langsung di Grottocenter dan menyediakan ringkasan dokumen yang diterbitkan di kertas atau online.', 'ja': 'BBSはGrottocenterに直接統合され、紙またはオンラインで公開されたすべての文書の要約を提供します。'},
    'The cave access is not restricted.': {'fr': "L'accès à la cavité n'est pas restreint.", 'es': 'El acceso a la cueva no está restringido.', 'de': 'Der Höhlenzugang ist nicht eingeschränkt.', 'it': "L'accesso alla grotta non è limitato.", 'pt': 'O acesso à caverna não está restrito.', 'nl': 'De toegang tot de grot is niet beperkt.', 'ca': "L'accés a la cova no és restringit.", 'ro': 'Accesul la peșteră nu este restricționat.', 'bg': 'Достъпът до пещерата не е ограничен.', 'el': 'Η πρόσβαση στο σπήλαιο δεν είναι περιορισμένη.', 'ar': 'الوصول إلى الكهف غير مقيد.', 'he': 'הגישה למערה אינה מוגבלת.', 'id': 'Akses gua tidak dibatasi.', 'ja': '洞窟へのアクセスは制限されていません。'},
    'The cave access is restricted.': {'fr': "L'accès à la cavité est restreint.", 'es': 'El acceso a la cueva está restringido.', 'de': 'Der Höhlenzugang ist eingeschränkt.', 'it': "L'accesso alla grotta è limitato.", 'pt': 'O acesso à caverna está restrito.', 'nl': 'De toegang tot de grot is beperkt.', 'ca': "L'accés a la cova és restringit.", 'ro': 'Accesul la peșteră este restricționat.', 'bg': 'Достъпът до пещерата е ограничен.', 'el': 'Η πρόσβαση στο σπήλαιο είναι περιορισμένη.', 'ar': 'الوصول إلى الكهف مقيد.', 'he': 'הגישה למערה מוגבלת.', 'id': 'Akses gua dibatasi.', 'ja': '洞窟へのアクセスは制限されています。'},
    'The cave contains water': {'fr': "La cavité contient de l'eau", 'es': 'La cueva contiene agua', 'de': 'Die Höhle enthält Wasser', 'it': "La grotta contiene acqua", 'pt': 'A caverna contém água', 'nl': 'De grot bevat water', 'ca': "La cova conté aigua", 'ro': 'Peștera conține apă', 'bg': 'Пещерата съдържа вода', 'el': 'Το σπήλαιο περιέχει νερό', 'ar': 'الكهف يحتوي على ماء', 'he': 'המערה מכילה מים', 'id': 'Gua mengandung air', 'ja': '洞窟に水があります'},
    'The email must be valid.': {'fr': "L'e-mail doit être valide.", 'es': 'El correo electrónico debe ser válido.', 'de': 'Die E-Mail-Adresse muss gültig sein.', 'it': "L'email deve essere valida.", 'pt': 'O e-mail deve ser válido.', 'nl': 'Het e-mailadres moet geldig zijn.', 'ca': 'El correu electrònic ha de ser vàlid.', 'ro': 'E-mailul trebuie să fie valid.', 'bg': 'Имейлът трябва да е валиден.', 'el': 'Το e-mail πρέπει να είναι έγκυρο.', 'ar': 'يجب أن يكون البريد الإلكتروني صالحاً.', 'he': 'האימייל חייב להיות תקין.', 'id': 'Email harus valid.', 'ja': 'メールアドレスは有効でなければなりません。'},
    'The end page must be greater or equal to the start page.': {'fr': 'La page de fin doit être supérieure ou égale à la page de début.', 'es': 'La página final debe ser mayor o igual a la página inicial.', 'de': 'Die Endseite muss größer oder gleich der Startseite sein.', 'it': 'La pagina finale deve essere maggiore o uguale alla pagina iniziale.', 'pt': 'A página final deve ser maior ou igual à página inicial.', 'nl': 'De eindpagina moet groter of gelijk zijn aan de startpagina.', 'ca': 'La pàgina final ha de ser major o igual a la pàgina inicial.', 'ro': 'Pagina de sfârșit trebuie să fie mai mare sau egală cu pagina de start.', 'bg': 'Крайната страница трябва да е по-голяма или равна на началната страница.', 'el': 'Η τελευταία σελίδα πρέπει να είναι μεγαλύτερη ή ίση με την αρχική σελίδα.', 'ar': 'يجب أن تكون الصفحة الأخيرة أكبر من أو تساوي الصفحة الأولى.', 'he': 'עמוד הסיום חייב להיות גדול מ- או שווה לעמוד ההתחלה.', 'id': 'Halaman akhir harus lebih besar atau sama dengan halaman awal.', 'ja': '終了ページは開始ページ以上でなければなりません。'},
    'The end page must be positive.': {'fr': 'La page de fin doit être positive.', 'es': 'La página final debe ser positiva.', 'de': 'Die Endseite muss positiv sein.', 'it': 'La pagina finale deve essere positiva.', 'pt': 'A página final deve ser positiva.', 'nl': 'De eindpagina moet positief zijn.', 'ca': 'La pàgina final ha de ser positiva.', 'ro': 'Pagina de sfârșit trebuie să fie pozitivă.', 'bg': 'Крайната страница трябва да е положително число.', 'el': 'Η τελευταία σελίδα πρέπει να είναι θετική.', 'ar': 'يجب أن تكون الصفحة الأخيرة موجبة.', 'he': 'עמוד הסיום חייב להיות חיובי.', 'id': 'Halaman akhir harus positif.', 'ja': '終了ページは正の数でなければなりません。'},
    'The following file is too big: {file}. Max accepted size: {maxSize}': {'fr': 'Le fichier suivant est trop grand : {file}. Taille maximale acceptée : {maxSize}', 'es': 'El siguiente archivo es demasiado grande: {file}. Tamaño máximo aceptado: {maxSize}', 'de': 'Die folgende Datei ist zu groß: {file}. Maximal akzeptierte Größe: {maxSize}', 'it': 'Il seguente file è troppo grande: {file}. Dimensione massima accettata: {maxSize}', 'pt': 'O seguinte ficheiro é demasiado grande: {file}. Tamanho máximo aceite: {maxSize}', 'nl': 'Het volgende bestand is te groot: {file}. Maximaal geaccepteerde grootte: {maxSize}', 'ca': 'El fitxer següent és massa gran: {file}. Mida màxima acceptada: {maxSize}', 'ro': 'Următorul fișier este prea mare: {file}. Dimensiunea maximă acceptată: {maxSize}', 'bg': 'Следният файл е твърде голям: {file}. Максимален приет размер: {maxSize}', 'el': 'Το παρακάτω αρχείο είναι πολύ μεγάλο: {file}. Μέγιστο αποδεκτό μέγεθος: {maxSize}', 'ar': 'الملف التالي كبير جداً: {file}. الحجم الأقصى المقبول: {maxSize}', 'he': 'הקובץ הבא גדול מדי: {file}. גודל מקסימלי מקובל: {maxSize}', 'id': 'File berikut terlalu besar: {file}. Ukuran maksimal yang diterima: {maxSize}', 'ja': '次のファイルが大きすぎます: {file}。最大許容サイズ: {maxSize}'},
    'The identifier must match the identifier type format.': {'fr': "L'identifiant doit correspondre au format du type d'identifiant.", 'es': 'El identificador debe coincidir con el formato del tipo de identificador.', 'de': 'Der Identifikator muss dem Format des Identifikatortyps entsprechen.', 'it': "L'identificatore deve corrispondere al formato del tipo di identificatore.", 'pt': 'O identificador deve corresponder ao formato do tipo de identificador.', 'nl': 'De identificator moet overeenkomen met het formaat van het identificatortype.', 'ca': "L'identificador ha de coincidir amb el format del tipus d'identificador.", 'ro': 'Identificatorul trebuie să corespundă formatului tipului de identificator.', 'bg': 'Идентификаторът трябва да съответства на формата на типа идентификатор.', 'el': 'Το αναγνωριστικό πρέπει να ταιριάζει με τη μορφή του τύπου αναγνωριστικού.', 'ar': 'يجب أن يطابق المعرف تنسيق نوع المعرف.', 'he': 'המזהה חייב להתאים לפורמט של סוג המזהה.', 'id': 'Pengidentifikasi harus sesuai dengan format jenis pengidentifikasi.', 'ja': '識別子は識別子タイプのフォーマットと一致する必要があります。'},
}

with open(os.path.join(DIR, 'en.json'), encoding='utf-8') as f:
    en = json.load(f)

total = 0
for lang in ['fr','es','it','pt','de','nl','ca','ro','bg','el','ar','he','id','ja']:
    path = os.path.join(DIR, f'{lang}.json')
    with open(path, encoding='utf-8') as f:
        d = json.load(f)
    n = 0
    for k, langs in T.items():
        if k in en and lang in langs and (k not in d or d[k] == en[k]):
            d[k] = langs[lang]; n += 1
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(dict(sorted(d.items())), f, ensure_ascii=False, indent=2)
    total += n
    print(f'{lang}: +{n}')
print(f'Total: {total}')
