# -*- coding: utf-8 -*-
import json, os
DIR = os.path.dirname(os.path.abspath(__file__))

T = {
    'The Speleological Abstracts (SA / BBS) has joined Grottocenter to give you access to a very important collection of documents.': {'fr': 'Les Speleological Abstracts (SA / BBS) ont rejoint Grottocenter pour vous donner accès à une très importante collection de documents.', 'es': 'Los Speleological Abstracts (SA / BBS) se han unido a Grottocenter para darle acceso a una colección muy importante de documentos.', 'de': 'Die Speleological Abstracts (SA / BBS) sind Grottocenter beigetreten, um Ihnen Zugang zu einer sehr wichtigen Dokumentensammlung zu geben.', 'it': 'Gli Speleological Abstracts (SA / BBS) si sono uniti a Grottocenter per darvi accesso a una collezione molto importante di documenti.', 'pt': 'Os Speleological Abstracts (SA / BBS) juntaram-se ao Grottocenter para lhe dar acesso a uma coleção muito importante de documentos.', 'nl': 'De Speleological Abstracts (SA / BBS) hebben zich bij Grottocenter aangesloten om u toegang te geven tot een zeer belangrijke documentenverzameling.', 'ca': 'Els Speleological Abstracts (SA / BBS) s\'han unit a Grottocenter per donar-vos accés a una col·lecció molt important de documents.', 'ro': 'Speleological Abstracts (SA / BBS) s-au alăturat Grottocenter pentru a vă oferi acces la o colecție foarte importantă de documente.', 'bg': 'Speleological Abstracts (SA / BBS) се присъединиха към Grottocenter, за да ви осигурят достъп до много важна колекция от документи.', 'el': 'Τα Speleological Abstracts (SA / BBS) εντάχθηκαν στο Grottocenter για να σας δώσουν πρόσβαση σε μια πολύ σημαντική συλλογή εγγράφων.', 'ar': 'انضمت Speleological Abstracts (SA / BBS) إلى Grottocenter لتمنحك الوصول إلى مجموعة مهمة جداً من الوثائق.', 'he': 'Speleological Abstracts (SA / BBS) הצטרפו ל-Grottocenter כדי לתת לך גישה לאוסף חשוב מאוד של מסמכים.', 'id': 'Speleological Abstracts (SA / BBS) telah bergabung dengan Grottocenter untuk memberi Anda akses ke koleksi dokumen yang sangat penting.', 'ja': 'Speleological Abstracts（SA / BBS）がGrottocenterに参加し、非常に重要なドキュメントコレクションへのアクセスを提供します。'},
    'The authorization document of the document has been deduced from the parent document': {'fr': "Le document d'autorisation a été déduit du document parent", 'es': 'El documento de autorización ha sido deducido del documento padre', 'de': 'Das Autorisierungsdokument wurde aus dem übergeordneten Dokument abgeleitet', 'it': "Il documento di autorizzazione è stato dedotto dal documento padre", 'pt': 'O documento de autorização foi deduzido do documento pai', 'nl': 'Het autorisatiedocument is afgeleid van het bovenliggende document', 'ca': "El document d'autorització s'ha deduït del document pare", 'ro': 'Documentul de autorizare a fost dedus din documentul părinte', 'bg': 'Документът за разрешение е изведен от родителския документ', 'el': 'Το έγγραφο εξουσιοδότησης προήλθε από το γονικό έγγραφο', 'ar': 'تم استنتاج وثيقة التخويل من الوثيقة الأصل', 'he': 'מסמך ההרשאה הוסק ממסמך ההורה', 'id': 'Dokumen otorisasi telah disimpulkan dari dokumen induk', 'ja': '認証文書は親文書から導出されました'},
    'The chosen color code is as follows:': {'fr': 'Le code couleur choisi est le suivant :', 'es': 'El código de color elegido es el siguiente:', 'de': 'Der gewählte Farbcode lautet wie folgt:', 'it': 'Il codice colore scelto è il seguente:', 'pt': 'O código de cor escolhido é o seguinte:', 'nl': 'De gekozen kleurcode is als volgt:', 'ca': 'El codi de color escollit és el següent:', 'ro': 'Codul de culoare ales este următorul:', 'bg': 'Избраният цветови код е следният:', 'el': 'Ο επιλεγμένος κωδικός χρώματος είναι ο εξής:', 'ar': 'رمز اللون المختار هو كما يلي:', 'he': 'קוד הצבע שנבחר הוא כדלקמן:', 'id': 'Kode warna yang dipilih adalah sebagai berikut:', 'ja': '選択した色コードは以下の通りです：'},
    'The data provided is of high quality, a verification would guarantee the quality level of this data.': {'fr': 'Les données fournies sont de haute qualité, une vérification garantirait le niveau de qualité de ces données.', 'es': 'Los datos proporcionados son de alta calidad, una verificación garantizaría el nivel de calidad de estos datos.', 'de': 'Die bereitgestellten Daten sind von hoher Qualität, eine Verifizierung würde das Qualitätsniveau dieser Daten garantieren.', 'it': 'I dati forniti sono di alta qualità, una verifica garantirebbe il livello qualitativo di questi dati.', 'pt': 'Os dados fornecidos são de alta qualidade, uma verificação garantiria o nível de qualidade destes dados.', 'nl': 'De verstrekte gegevens zijn van hoge kwaliteit, een verificatie zou het kwaliteitsniveau van deze gegevens garanderen.', 'ca': 'Les dades proporcionades són d\'alta qualitat, una verificació garantiria el nivell de qualitat d\'aquestes dades.', 'ro': 'Datele furnizate sunt de înaltă calitate, o verificare ar garanta nivelul de calitate al acestor date.', 'bg': 'Предоставените данни са с високо качество, проверката би гарантирала нивото на качество на тези данни.', 'el': 'Τα δεδομένα που παρέχονται είναι υψηλής ποιότητας, μια επαλήθευση θα εγγυούνταν το επίπεδο ποιότητας αυτών των δεδομένων.', 'ar': 'البيانات المقدمة عالية الجودة، التحقق منها سيضمن مستوى الجودة.', 'he': 'הנתונים שסופקו הם באיכות גבוהה, אימות יבטיח את רמת האיכות של נתונים אלו.', 'id': 'Data yang diberikan berkualitas tinggi, verifikasi akan menjamin tingkat kualitas data ini.', 'ja': '提供されたデータは高品質です。検証によってデータの品質レベルが保証されます。'},
    'The documents entered via this form are compatible with the BBS. The BBS is now directly integrated in Grottocenter.': {'fr': 'Les documents saisis via ce formulaire sont compatibles avec le BBS. Le BBS est maintenant directement intégré dans Grottocenter.', 'es': 'Los documentos introducidos mediante este formulario son compatibles con el BBS. El BBS está ahora directamente integrado en Grottocenter.', 'de': 'Die über dieses Formular eingegebenen Dokumente sind mit dem BBS kompatibel. Das BBS ist jetzt direkt in Grottocenter integriert.', 'it': 'I documenti inseriti tramite questo modulo sono compatibili con il BBS. Il BBS è ora direttamente integrato in Grottocenter.', 'pt': 'Os documentos inseridos através deste formulário são compatíveis com o BBS. O BBS está agora diretamente integrado no Grottocenter.', 'nl': 'De via dit formulier ingevoerde documenten zijn compatibel met de BBS. De BBS is nu direct geïntegreerd in Grottocenter.', 'ca': 'Els documents introduïts mitjançant aquest formulari són compatibles amb el BBS. El BBS ara està directament integrat a Grottocenter.', 'ro': 'Documentele introduse prin acest formular sunt compatibile cu BBS. BBS este acum integrat direct în Grottocenter.', 'bg': 'Документите, въведени чрез този формуляр, са съвместими с BBS. BBS вече е директно интегриран в Grottocenter.', 'el': 'Τα έγγραφα που εισάγονται μέσω αυτής της φόρμας είναι συμβατά με το BBS. Το BBS είναι τώρα άμεσα ενσωματωμένο στο Grottocenter.', 'ar': 'المستندات المدخلة عبر هذا النموذج متوافقة مع BBS. تم الآن دمج BBS مباشرة في Grottocenter.', 'he': 'המסמכים שהוזנו דרך טופס זה תואמים ל-BBS. ה-BBS משולב כעת ישירות ב-Grottocenter.', 'id': 'Dokumen yang dimasukkan melalui formulir ini kompatibel dengan BBS. BBS kini terintegrasi langsung di Grottocenter.', 'ja': 'このフォームで入力した文書はBBSと互換性があります。BBSはGrottocenterに直接統合されました。'},
    'The editor has been deduced from the parent document.': {'fr': "L'éditeur a été déduit du document parent.", 'es': 'El editor ha sido deducido del documento padre.', 'de': 'Der Herausgeber wurde aus dem übergeordneten Dokument abgeleitet.', 'it': "L'editore è stato dedotto dal documento padre.", 'pt': 'O editor foi deduzido do documento pai.', 'nl': 'De redacteur is afgeleid van het bovenliggende document.', 'ca': "L'editor s'ha deduït del document pare.", 'ro': 'Editorul a fost dedus din documentul părinte.', 'bg': 'Редакторът е изведен от родителския документ.', 'el': 'Ο εκδότης προήλθε από το γονικό έγγραφο.', 'ar': 'تم استنتاج المحرر من الوثيقة الأصل.', 'he': 'העורך הוסק ממסמך ההורה.', 'id': 'Editor telah disimpulkan dari dokumen induk.', 'ja': '編集者は親文書から導出されました。'},
    'The library has been deduced from the parent document.': {'fr': 'La bibliothèque a été déduite du document parent.', 'es': 'La biblioteca ha sido deducida del documento padre.', 'de': 'Die Bibliothek wurde aus dem übergeordneten Dokument abgeleitet.', 'it': 'La biblioteca è stata dedotta dal documento padre.', 'pt': 'A biblioteca foi deduzida do documento pai.', 'nl': 'De bibliotheek is afgeleid van het bovenliggende document.', 'ca': 'La biblioteca s\'ha deduït del document pare.', 'ro': 'Biblioteca a fost dedusă din documentul părinte.', 'bg': 'Библиотеката е изведена от родителския документ.', 'el': 'Η βιβλιοθήκη προήλθε από το γονικό έγγραφο.', 'ar': 'تم استنتاج المكتبة من الوثيقة الأصل.', 'he': 'הספרייה הוסקה ממסמך ההורה.', 'id': 'Perpustakaan telah disimpulkan dari dokumen induk.', 'ja': '図書館は親文書から導出されました。'},
    'The license is written in the files': {'fr': 'La licence est écrite dans les fichiers', 'es': 'La licencia está escrita en los archivos', 'de': 'Die Lizenz ist in den Dateien geschrieben', 'it': 'La licenza è scritta nei file', 'pt': 'A licença está escrita nos ficheiros', 'nl': 'De licentie staat in de bestanden', 'ca': 'La llicència està escrita als fitxers', 'ro': 'Licența este scrisă în fișiere', 'bg': 'Лицензът е записан във файловете', 'el': 'Η άδεια είναι γραμμένη στα αρχεία', 'ar': 'الترخيص مكتوب في الملفات', 'he': 'הרישיון כתוב בקבצים', 'id': 'Lisensi tertulis dalam file', 'ja': 'ライセンスはファイルに記載されています'},
    'The license of the document has been deduced from the parent document': {'fr': 'La licence du document a été déduite du document parent', 'es': 'La licencia del documento ha sido deducida del documento padre', 'de': 'Die Lizenz des Dokuments wurde aus dem übergeordneten Dokument abgeleitet', 'it': 'La licenza del documento è stata dedotta dal documento padre', 'pt': 'A licença do documento foi deduzida do documento pai', 'nl': 'De licentie van het document is afgeleid van het bovenliggende document', 'ca': 'La llicència del document s\'ha deduït del document pare', 'ro': 'Licența documentului a fost dedusă din documentul părinte', 'bg': 'Лицензът на документа е изведен от родителския документ', 'el': 'Η άδεια του εγγράφου προήλθε από το γονικό έγγραφο', 'ar': 'تم استنتاج ترخيص الوثيقة من الوثيقة الأصل', 'he': 'הרישיון של המסמך הוסק ממסמך ההורה', 'id': 'Lisensi dokumen telah disimpulkan dari dokumen induk', 'ja': '文書のライセンスは親文書から導出されました'},
    'The mails do not match': {'fr': 'Les adresses e-mail ne correspondent pas', 'es': 'Los correos electrónicos no coinciden', 'de': 'Die E-Mail-Adressen stimmen nicht überein', 'it': 'Le e-mail non corrispondono', 'pt': 'Os e-mails não correspondem', 'nl': 'De e-mailadressen komen niet overeen', 'ca': 'Els correus electrònics no coincideixen', 'ro': 'E-mailurile nu se potrivesc', 'bg': 'Имейлите не съвпадат', 'el': 'Τα e-mail δεν ταιριάζουν', 'ar': 'البريد الإلكتروني غير متطابق', 'he': 'כתובות האימייל אינן תואמות', 'id': 'Email tidak cocok', 'ja': 'メールアドレスが一致しません'},
    'The main language of the document has been deduced from the parent document.': {'fr': 'La langue principale du document a été déduite du document parent.', 'es': 'El idioma principal del documento ha sido deducido del documento padre.', 'de': 'Die Hauptsprache des Dokuments wurde aus dem übergeordneten Dokument abgeleitet.', 'it': 'La lingua principale del documento è stata dedotta dal documento padre.', 'pt': 'A língua principal do documento foi deduzida do documento pai.', 'nl': 'De hoofdtaal van het document is afgeleid van het bovenliggende document.', 'ca': 'La llengua principal del document s\'ha deduït del document pare.', 'ro': 'Limba principală a documentului a fost dedusă din documentul părinte.', 'bg': 'Основният език на документа е изведен от родителския документ.', 'el': 'Η κύρια γλώσσα του εγγράφου προήλθε από το γονικό έγγραφο.', 'ar': 'تم استنتاج اللغة الرئيسية للوثيقة من الوثيقة الأصل.', 'he': 'השפה הראשית של המסמך הוסקה ממסמך ההורה.', 'id': 'Bahasa utama dokumen telah disimpulkan dari dokumen induk.', 'ja': '文書の主要言語は親文書から導出されました。'},
    'The new cave is:': {'fr': 'La nouvelle cavité est :', 'es': 'La nueva cueva es:', 'de': 'Die neue Höhle ist:', 'it': 'La nuova grotta è:', 'pt': 'A nova caverna é:', 'nl': 'De nieuwe grot is:', 'ca': 'La nova cova és:', 'ro': 'Noua peșteră este:', 'bg': 'Новата пещера е:', 'el': 'Το νέο σπήλαιο είναι:', 'ar': 'الكهف الجديد هو:', 'he': 'המערה החדשה היא:', 'id': 'Gua baru adalah:', 'ja': '新しい洞窟は：'},
    'The nickname defines how other users see you.': {'fr': 'Le pseudo définit comment les autres utilisateurs vous voient.', 'es': 'El apodo define cómo te ven otros usuarios.', 'de': 'Der Spitzname legt fest, wie andere Benutzer Sie sehen.', 'it': 'Il soprannome definisce come gli altri utenti ti vedono.', 'pt': 'O apelido define como os outros utilizadores o veem.', 'nl': 'De bijnaam bepaalt hoe andere gebruikers u zien.', 'ca': 'El sobrenom defineix com et veuen els altres usuaris.', 'ro': 'Pseudonimul definește cum te văd ceilalți utilizatori.', 'bg': 'Псевдонимът определя как другите потребители ви виждат.', 'el': 'Το ψευδώνυμο καθορίζει πώς σας βλέπουν οι άλλοι χρήστες.', 'ar': 'يحدد اسم الشهرة كيف يراك المستخدمون الآخرون.', 'he': 'הכינוי מגדיר כיצד משתמשים אחרים רואים אותך.', 'id': 'Nama panggilan menentukan bagaimana pengguna lain melihat Anda.', 'ja': 'ニックネームは他のユーザーがあなたをどのように見るかを定義します。'},
    'The passwords do not match': {'fr': 'Les mots de passe ne correspondent pas', 'es': 'Las contraseñas no coinciden', 'de': 'Die Passwörter stimmen nicht überein', 'it': 'Le password non corrispondono', 'pt': 'As palavras-passe não correspondem', 'nl': 'De wachtwoorden komen niet overeen', 'ca': 'Les contrasenyes no coincideixen', 'ro': 'Parolele nu se potrivesc', 'bg': 'Паролите не съвпадат', 'el': 'Οι κωδικοί δεν ταιριάζουν', 'ar': 'كلمات المرور غير متطابقة', 'he': 'הסיסמאות אינן תואמות', 'id': 'Kata sandi tidak cocok', 'ja': 'パスワードが一致しません'},
    'The passwords must match.': {'fr': 'Les mots de passe doivent correspondre.', 'es': 'Las contraseñas deben coincidir.', 'de': 'Die Passwörter müssen übereinstimmen.', 'it': 'Le password devono corrispondere.', 'pt': 'As palavras-passe devem corresponder.', 'nl': 'De wachtwoorden moeten overeenkomen.', 'ca': 'Les contrasenyes han de coincidir.', 'ro': 'Parolele trebuie să se potrivească.', 'bg': 'Паролите трябва да съвпадат.', 'el': 'Οι κωδικοί πρέπει να ταιριάζουν.', 'ar': 'يجب أن تتطابق كلمات المرور.', 'he': 'הסיסמאות חייבות להיות זהות.', 'id': 'Kata sandi harus cocok.', 'ja': 'パスワードは一致しなければなりません。'},
    "The person you are looking for doesn't exist.": {'fr': "La personne que vous recherchez n'existe pas.", 'es': 'La persona que busca no existe.', 'de': 'Die gesuchte Person existiert nicht.', 'it': 'La persona che stai cercando non esiste.', 'pt': 'A pessoa que procura não existe.', 'nl': 'De persoon die u zoekt bestaat niet.', 'ca': 'La persona que busqueu no existeix.', 'ro': 'Persoana pe care o căutați nu există.', 'bg': 'Лицето, което търсите, не съществува.', 'el': 'Το άτομο που αναζητάτε δεν υπάρχει.', 'ar': 'الشخص الذي تبحث عنه غير موجود.', 'he': 'האדם שאתה מחפש אינו קיים.', 'id': 'Orang yang Anda cari tidak ada.', 'ja': 'お探しの方は存在しません。'},
}

with open(os.path.join(DIR, 'en.json'), encoding='utf-8') as f:
    en = json.load(f)

total = 0
for lang in ['fr','es','it','pt','de','nl','ca','ro','bg','el','ar','he','id','ja']:
    path = os.path.join(DIR, f'{lang}.json')
    with open(path, encoding='utf-8') as f:
        d = json.load(f)
    n = 0
    for k, langs in T.items():
        if k in en and lang in langs and (k not in d or d[k] == en[k]):
            d[k] = langs[lang]; n += 1
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(dict(sorted(d.items())), f, ensure_ascii=False, indent=2)
    total += n
    print(f'{lang}: +{n}')
print(f'Total: {total}')
