# -*- coding: utf-8 -*-
import json, os
DIR = os.path.dirname(os.path.abspath(__file__))

T = {
    'There is currently no history for this entrance.': {'fr': "Il n'y a actuellement aucun historique pour cette entrée.", 'es': 'Actualmente no hay historial para esta entrada.', 'de': 'Zurzeit gibt es keine Historie für diesen Eingang.', 'it': 'Al momento non ci sono storici per questo ingresso.', 'pt': 'Atualmente não existe nenhum histórico para esta entrada.', 'nl': 'Er is momenteel geen geschiedenis voor deze ingang.', 'ca': "Actualment no hi ha cap historial per a aquesta entrada.", 'ro': 'Nu există momentan niciun istoric pentru această intrare.', 'bg': 'В момента няма история за този вход.', 'el': 'Δεν υπάρχει προς το παρόν κανένα ιστορικό για αυτήν την είσοδο.', 'ar': 'لا يوجد حالياً أي سجل لهذا المدخل.', 'he': 'כרגע אין היסטוריה לכניסה זו.', 'id': 'Saat ini tidak ada riwayat untuk pintu masuk ini.', 'ja': '現在、この入口の履歴はありません。'},
    'There is currently no location for this entrance.': {'fr': "Il n'y a actuellement aucun emplacement pour cette entrée.", 'es': 'Actualmente no hay ubicación para esta entrada.', 'de': 'Zurzeit gibt es keinen Standort für diesen Eingang.', 'it': 'Al momento non ci sono posizioni per questo ingresso.', 'pt': 'Atualmente não existe nenhuma localização para esta entrada.', 'nl': 'Er is momenteel geen locatie voor deze ingang.', 'ca': "Actualment no hi ha cap ubicació per a aquesta entrada.", 'ro': 'Nu există momentan nicio locație pentru această intrare.', 'bg': 'В момента няма местоположение за този вход.', 'el': 'Δεν υπάρχει προς το παρόν καμία τοποθεσία για αυτήν την είσοδο.', 'ar': 'لا يوجد حالياً أي موقع لهذا المدخل.', 'he': 'כרגע אין מיקום לכניסה זו.', 'id': 'Saat ini tidak ada lokasi untuk pintu masuk ini.', 'ja': '現在、この入口の場所はありません。'},
    'There is currently no rigging for this entrance.': {'fr': "Il n'y a actuellement aucun équipement pour cette entrée.", 'es': 'Actualmente no hay equipamiento para esta entrada.', 'de': 'Zurzeit gibt es keine Ausrüstung für diesen Eingang.', 'it': 'Al momento non ci sono attrezzature per questo ingresso.', 'pt': 'Atualmente não existe nenhum equipamento para esta entrada.', 'nl': 'Er is momenteel geen uitrusting voor deze ingang.', 'ca': "Actualment no hi ha cap equipament per a aquesta entrada.", 'ro': 'Nu există momentan niciun echipament pentru această intrare.', 'bg': 'В момента няма оборудване за този вход.', 'el': 'Δεν υπάρχει προς το παρόν κανένας εξοπλισμός για αυτήν την είσοδο.', 'ar': 'لا يوجد حالياً أي تجهيزات لهذا المدخل.', 'he': 'כרגע אין ציוד לכניסה זו.', 'id': 'Saat ini tidak ada perlengkapan untuk pintu masuk ini.', 'ja': '現在、この入口のリギングはありません。'},
    'There is currently not enough information about this country.': {'fr': "Il n'y a actuellement pas assez d'informations sur ce pays.", 'es': 'Actualmente no hay suficiente información sobre este país.', 'de': 'Zurzeit gibt es nicht genügend Informationen über dieses Land.', 'it': 'Al momento non ci sono abbastanza informazioni su questo paese.', 'pt': 'Atualmente não há informações suficientes sobre este país.', 'nl': 'Er is momenteel niet genoeg informatie over dit land.', 'ca': "Actualment no hi ha prou informació sobre aquest país.", 'ro': 'Nu există momentan suficiente informații despre această țară.', 'bg': 'В момента няма достатъчно информация за тази страна.', 'el': 'Δεν υπάρχουν αρκετές πληροφορίες για αυτήν τη χώρα προς το παρόν.', 'ar': 'لا توجد حالياً معلومات كافية عن هذا البلد.', 'he': 'כרגע אין מספיק מידע על מדינה זו.', 'id': 'Saat ini tidak ada cukup informasi tentang negara ini.', 'ja': '現在、この国に関する情報が十分ではありません。'},
    'There is currently not enough information about this massif.': {'fr': "Il n'y a actuellement pas assez d'informations sur ce massif.", 'es': 'Actualmente no hay suficiente información sobre este macizo.', 'de': 'Zurzeit gibt es nicht genügend Informationen über dieses Massiv.', 'it': 'Al momento non ci sono abbastanza informazioni su questo massiccio.', 'pt': 'Atualmente não há informações suficientes sobre este maciço.', 'nl': 'Er is momenteel niet genoeg informatie over dit massief.', 'ca': "Actualment no hi ha prou informació sobre aquest massís.", 'ro': 'Nu există momentan suficiente informații despre acest masiv.', 'bg': 'В момента няма достатъчно информация за този масив.', 'el': 'Δεν υπάρχουν αρκετές πληροφορίες για αυτό το μασίφ προς το παρόν.', 'ar': 'لا توجد حالياً معلومات كافية عن هذا الجبل.', 'he': 'כרגע אין מספיק מידע על מסיף זה.', 'id': 'Saat ini tidak ada cukup informasi tentang masif ini.', 'ja': '現在、このマシフに関する情報が十分ではありません。'},
    'There is currently not enough information about this region.': {'fr': "Il n'y a actuellement pas assez d'informations sur cette région.", 'es': 'Actualmente no hay suficiente información sobre esta región.', 'de': 'Zurzeit gibt es nicht genügend Informationen über diese Region.', 'it': 'Al momento non ci sono abbastanza informazioni su questa regione.', 'pt': 'Atualmente não há informações suficientes sobre esta região.', 'nl': 'Er is momenteel niet genoeg informatie over deze regio.', 'ca': "Actualment no hi ha prou informació sobre aquesta regió.", 'ro': 'Nu există momentan suficiente informații despre această regiune.', 'bg': 'В момента няма достатъчно информация за тази регион.', 'el': 'Δεν υπάρχουν αρκετές πληροφορίες για αυτήν την περιοχή προς το παρόν.', 'ar': 'لا توجد حالياً معلومات كافية عن هذه المنطقة.', 'he': 'כרגע אין מספיק מידע על אזור זה.', 'id': 'Saat ini tidak ada cukup informasi tentang wilayah ini.', 'ja': '現在、この地域に関する情報が十分ではありません。'},
    'There is no api documentation for version {apiVersion}.': {'fr': "Il n'y a pas de documentation API pour la version {apiVersion}.", 'es': 'No hay documentación de API para la versión {apiVersion}.', 'de': 'Es gibt keine API-Dokumentation für Version {apiVersion}.', 'it': 'Non ci sono documentazioni API per la versione {apiVersion}.', 'pt': 'Não existe documentação API para a versão {apiVersion}.', 'nl': 'Er is geen API-documentatie voor versie {apiVersion}.', 'ca': 'No hi ha documentació API per a la versió {apiVersion}.', 'ro': 'Nu există documentație API pentru versiunea {apiVersion}.', 'bg': 'Няма API документация за версия {apiVersion}.', 'el': 'Δεν υπάρχει τεκμηρίωση API για την έκδοση {apiVersion}.', 'ar': 'لا توجد وثائق API للإصدار {apiVersion}.', 'he': 'אין תיעוד API לגרסה {apiVersion}.', 'id': 'Tidak ada dokumentasi API untuk versi {apiVersion}.', 'ja': 'バージョン{apiVersion}のAPIドキュメントはありません。'},
    'There is no entrance in this massif.': {'fr': "Il n'y a pas d'entrée dans ce massif.", 'es': 'No hay entrada en este macizo.', 'de': 'Es gibt keinen Eingang in diesem Massiv.', 'it': 'Non ci sono ingressi in questo massiccio.', 'pt': 'Não existe nenhuma entrada neste maciço.', 'nl': 'Er is geen ingang in dit massief.', 'ca': "No hi ha cap entrada en aquest massís.", 'ro': 'Nu există nicio intrare în acest masiv.', 'bg': 'Няма вход в този масив.', 'el': 'Δεν υπάρχει είσοδος σε αυτό το μασίφ.', 'ar': 'لا يوجد مدخل في هذا الجبل.', 'he': 'אין כניסה במסיף זה.', 'id': 'Tidak ada pintu masuk di masif ini.', 'ja': 'このマシフには入口がありません。'},
    'They are not duplicates': {'fr': "Ce ne sont pas des doublons", 'es': 'No son duplicados', 'de': 'Sie sind keine Duplikate', 'it': 'Non sono duplicati', 'pt': 'Não são duplicados', 'nl': 'Ze zijn geen duplicaten', 'ca': 'No són duplicats', 'ro': 'Nu sunt duplicate', 'bg': 'Те не са дубликати', 'el': 'Δεν είναι διπλότυπα', 'ar': 'هم ليسوا نسخاً مكررة', 'he': 'הם אינם כפולים', 'id': 'Mereka bukan duplikat', 'ja': '重複ではありません'},
    'This entrance has a restricted access, you can not see its locations.': {'fr': "Cette entrée a un accès restreint, vous ne pouvez pas voir ses emplacements.", 'es': 'Esta entrada tiene acceso restringido, no puede ver sus ubicaciones.', 'de': 'Dieser Eingang hat einen eingeschränkten Zugang, Sie können seine Standorte nicht sehen.', 'it': "Questo ingresso ha un accesso limitato, non è possibile vedere le sue posizioni.", 'pt': 'Esta entrada tem acesso restrito, não pode ver as suas localizações.', 'nl': 'Deze ingang heeft beperkte toegang, u kunt de locaties niet zien.', 'ca': "Aquesta entrada té accés restringit, no podeu veure les seves ubicacions.", 'ro': 'Această intrare are acces restricționat, nu puteți vedea locațiile sale.', 'bg': 'Този вход има ограничен достъп, не можете да видите неговите местоположения.', 'el': 'Αυτή η είσοδος έχει περιορισμένη πρόσβαση, δεν μπορείτε να δείτε τις τοποθεσίες της.', 'ar': 'هذا المدخل له وصول مقيد، لا يمكنك رؤية مواقعه.', 'he': 'לכניסה זו גישה מוגבלת, לא ניתן לראות את מיקומיה.', 'id': 'Pintu masuk ini memiliki akses terbatas, Anda tidak dapat melihat lokasinya.', 'ja': 'この入口はアクセス制限があり、場所を表示できません。'},
    'This massif has no caves listed yet': {'fr': "Ce massif n'a pas encore de cavités listées", 'es': 'Este macizo todavía no tiene cuevas listadas', 'de': 'Dieses Massiv hat noch keine gelisteten Höhlen', 'it': 'Questo massiccio non ha ancora grotte elencate', 'pt': 'Este maciço ainda não tem cavernas listadas', 'nl': 'Dit massief heeft nog geen grotten vermeld', 'ca': "Aquest massís no té cap cova llistada encara", 'ro': 'Acest masiv nu are peșteri listate încă', 'bg': 'Този масив все още няма изброени пещери', 'el': 'Αυτό το μασίφ δεν έχει ακόμη καταχωρημένα σπήλαια', 'ar': 'لا يوجد في هذا الجبل كهوف مدرجة حتى الآن', 'he': 'למסיף זה אין עדיין מערות ברשימה', 'id': 'Masif ini belum memiliki gua yang terdaftar', 'ja': 'このマシフにはまだ洞窟が登録されていません'},
    'This massif has no descriptions listed yet.': {'fr': "Ce massif n'a pas encore de descriptions listées.", 'es': 'Este macizo todavía no tiene descripciones listadas.', 'de': 'Dieses Massiv hat noch keine Beschreibungen gelistet.', 'it': 'Questo massiccio non ha ancora descrizioni elencate.', 'pt': 'Este maciço ainda não tem descrições listadas.', 'nl': 'Dit massief heeft nog geen beschrijvingen vermeld.', 'ca': "Aquest massís no té cap descripció llistada encara.", 'ro': 'Acest masiv nu are descrieri listate încă.', 'bg': 'Този масив все още няма изброени описания.', 'el': 'Αυτό το μασίφ δεν έχει ακόμη καταχωρημένες περιγραφές.', 'ar': 'لا يوجد في هذا الجبل أوصاف مدرجة حتى الآن.', 'he': 'למסיף זה אין עדיין תיאורים ברשימה.', 'id': 'Masif ini belum memiliki deskripsi yang terdaftar.', 'ja': 'このマシフにはまだ説明が登録されていません。'},
    'This massif has no documents listed yet.': {'fr': "Ce massif n'a pas encore de documents listés.", 'es': 'Este macizo todavía no tiene documentos listados.', 'de': 'Dieses Massiv hat noch keine Dokumente gelistet.', 'it': 'Questo massiccio non ha ancora documenti elencati.', 'pt': 'Este maciço ainda não tem documentos listados.', 'nl': 'Dit massief heeft nog geen documenten vermeld.', 'ca': "Aquest massís no té cap document llistat encara.", 'ro': 'Acest masiv nu are documente listate încă.', 'bg': 'Този масив все още няма изброени документи.', 'el': 'Αυτό το μασίφ δεν έχει ακόμη καταχωρημένα έγγραφα.', 'ar': 'لا يوجد في هذا الجبل مستندات مدرجة حتى الآن.', 'he': 'למסיף זה אין עדיין מסמכים ברשימה.', 'id': 'Masif ini belum memiliki dokumen yang terdaftar.', 'ja': 'このマシフにはまだ文書が登録されていません。'},
}

with open(os.path.join(DIR, 'en.json'), encoding='utf-8') as f:
    en = json.load(f)

total = 0
for lang in ['fr','es','it','pt','de','nl','ca','ro','bg','el','ar','he','id','ja']:
    path = os.path.join(DIR, f'{lang}.json')
    with open(path, encoding='utf-8') as f:
        d = json.load(f)
    n = 0
    for k, langs in T.items():
        if k in en and lang in langs and (k not in d or d[k] == en[k]):
            d[k] = langs[lang]; n += 1
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(dict(sorted(d.items())), f, ensure_ascii=False, indent=2)
    total += n
    print(f'{lang}: +{n}')
print(f'Total: {total}')
