# -*- coding: utf-8 -*-
import json, os
DIR = os.path.dirname(os.path.abspath(__file__))

T = {
    'This massif has no entrances listed yet.': {'fr': "Ce massif n'a pas encore d'entrées listées.", 'es': 'Este macizo todavía no tiene entradas listadas.', 'de': 'Dieses Massiv hat noch keine Eingänge gelistet.', 'it': 'Questo massiccio non ha ancora ingressi elencati.', 'pt': 'Este maciço ainda não tem entradas listadas.', 'nl': 'Dit massief heeft nog geen ingangen vermeld.', 'ca': "Aquest massís no té cap entrada llistada encara.", 'ro': 'Acest masiv nu are intrări listate încă.', 'bg': 'Този масив все още няма изброени входове.', 'el': 'Αυτό το μασίφ δεν έχει ακόμη καταχωρημένες εισόδους.', 'ar': 'لا يوجد في هذا الجبل مداخل مدرجة حتى الآن.', 'he': 'למסיף זה אין עדיין כניסות ברשימה.', 'id': 'Masif ini belum memiliki pintu masuk yang terdaftar.', 'ja': 'このマシフにはまだ入口が登録されていません。'},
    'This massif has no networks listed yet.': {'fr': "Ce massif n'a pas encore de réseaux listés.", 'es': 'Este macizo todavía no tiene redes listadas.', 'de': 'Dieses Massiv hat noch keine Netzwerke gelistet.', 'it': 'Questo massiccio non ha ancora reti elencate.', 'pt': 'Este maciço ainda não tem redes listadas.', 'nl': 'Dit massief heeft nog geen netwerken vermeld.', 'ca': "Aquest massís no té cap xarxa llistada encara.", 'ro': 'Acest masiv nu are rețele listate încă.', 'bg': 'Този масив все още няма изброени мрежи.', 'el': 'Αυτό το μασίφ δεν έχει ακόμη καταχωρημένα δίκτυα.', 'ar': 'لا يوجد في هذا الجبل شبكات مدرجة حتى الآن.', 'he': 'למסיף זה אין עדיין רשתות ברשימה.', 'id': 'Masif ini belum memiliki jaringan yang terdaftar.', 'ja': 'このマシフにはまだネットワークが登録されていません。'},
    'This organization has no documents listed yet.': {'fr': "Cette organisation n'a pas encore de documents listés.", 'es': 'Esta organización todavía no tiene documentos listados.', 'de': 'Diese Organisation hat noch keine Dokumente gelistet.', 'it': 'Questa organizzazione non ha ancora documenti elencati.', 'pt': 'Esta organização ainda não tem documentos listados.', 'nl': 'Deze organisatie heeft nog geen documenten vermeld.', 'ca': "Aquesta organització no té cap document llistat encara.", 'ro': 'Această organizație nu are documente listate încă.', 'bg': 'Тази организация все още няма изброени документи.', 'el': 'Αυτή η οργάνωση δεν έχει ακόμη καταχωρημένα έγγραφα.', 'ar': 'لا تحتوي هذه المنظمة على مستندات مدرجة حتى الآن.', 'he': 'לארגון זה אין עדיין מסמכים ברשימה.', 'id': 'Organisasi ini belum memiliki dokumen yang terdaftar.', 'ja': 'この組織にはまだ文書が登録されていません。'},
    'This organization has no members yet.': {'fr': "Cette organisation n'a pas encore de membres.", 'es': 'Esta organización todavía no tiene miembros.', 'de': 'Diese Organisation hat noch keine Mitglieder.', 'it': 'Questa organizzazione non ha ancora membri.', 'pt': 'Esta organização ainda não tem membros.', 'nl': 'Deze organisatie heeft nog geen leden.', 'ca': "Aquesta organització encara no té membres.", 'ro': 'Această organizație nu are membri încă.', 'bg': 'Тази организация все още няма членове.', 'el': 'Αυτή η οργάνωση δεν έχει ακόμη μέλη.', 'ar': 'لا تحتوي هذه المنظمة على أعضاء حتى الآن.', 'he': 'לארגון זה אין עדיין חברים.', 'id': 'Organisasi ini belum memiliki anggota.', 'ja': 'この組織にはまだメンバーがいません。'},
    'This person has no documents listed yet.': {'fr': "Cette personne n'a pas encore de documents listés.", 'es': 'Esta persona todavía no tiene documentos listados.', 'de': 'Diese Person hat noch keine Dokumente gelistet.', 'it': 'Questa persona non ha ancora documenti elencati.', 'pt': 'Esta pessoa ainda não tem documentos listados.', 'nl': 'Deze persoon heeft nog geen documenten vermeld.', 'ca': "Aquesta persona no té cap document llistat encara.", 'ro': 'Această persoană nu are documente listate încă.', 'bg': 'Това лице все още няма изброени документи.', 'el': 'Αυτό το άτομο δεν έχει ακόμη καταχωρημένα έγγραφα.', 'ar': 'لا يحتوي هذا الشخص على مستندات مدرجة حتى الآن.', 'he': 'לאדם זה אין עדיין מסמכים ברשימה.', 'id': 'Orang ini belum memiliki dokumen yang terdaftar.', 'ja': 'この人にはまだ文書が登録されていません。'},
    'This person has no entrances listed yet.': {'fr': "Cette personne n'a pas encore d'entrées listées.", 'es': 'Esta persona todavía no tiene entradas listadas.', 'de': 'Diese Person hat noch keine Eingänge gelistet.', 'it': 'Questa persona non ha ancora ingressi elencati.', 'pt': 'Esta pessoa ainda não tem entradas listadas.', 'nl': 'Deze persoon heeft nog geen ingangen vermeld.', 'ca': "Aquesta persona no té cap entrada llistada encara.", 'ro': 'Această persoană nu are intrări listate încă.', 'bg': 'Това лице все още няма изброени входове.', 'el': 'Αυτό το άτομο δεν έχει ακόμη καταχωρημένες εισόδους.', 'ar': 'لا يحتوي هذا الشخص على مداخل مدرجة حتى الآن.', 'he': 'לאדם זה אין עדיין כניסות ברשימה.', 'id': 'Orang ini belum memiliki pintu masuk yang terdaftar.', 'ja': 'この人にはまだ入口が登録されていません。'},
    'This person has no organization listed yet.': {'fr': "Cette personne n'a pas encore d'organisation listée.", 'es': 'Esta persona todavía no tiene organización listada.', 'de': 'Diese Person hat noch keine Organisation gelistet.', 'it': 'Questa persona non ha ancora organizzazioni elencate.', 'pt': 'Esta pessoa ainda não tem organização listada.', 'nl': 'Deze persoon heeft nog geen organisatie vermeld.', 'ca': "Aquesta persona no té cap organització llistada encara.", 'ro': 'Această persoană nu are organizație listată încă.', 'bg': 'Това лице все още няма изброена организация.', 'el': 'Αυτό το άτομο δεν έχει ακόμη καταχωρημένη οργάνωση.', 'ar': 'لا يحتوي هذا الشخص على منظمة مدرجة حتى الآن.', 'he': 'לאדם זה אין עדיין ארגון ברשימה.', 'id': 'Orang ini belum memiliki organisasi yang terdaftar.', 'ja': 'この人にはまだ組織が登録されていません。'},
    'This person has no subscriptions listed yet.': {'fr': "Cette personne n'a pas encore d'abonnements listés.", 'es': 'Esta persona todavía no tiene suscripciones listadas.', 'de': 'Diese Person hat noch keine Abonnements gelistet.', 'it': 'Questa persona non ha ancora abbonamenti elencati.', 'pt': 'Esta pessoa ainda não tem subscrições listadas.', 'nl': 'Deze persoon heeft nog geen abonnementen vermeld.', 'ca': "Aquesta persona no té cap subscripció llistada encara.", 'ro': 'Această persoană nu are abonamente listate încă.', 'bg': 'Това лице все още няма изброени абонаменти.', 'el': 'Αυτό το άτομο δεν έχει ακόμη καταχωρημένες συνδρομές.', 'ar': 'لا يحتوي هذا الشخص على اشتراكات مدرجة حتى الآن.', 'he': 'לאדם זה אין עדיין מנויים ברשימה.', 'id': 'Orang ini belum memiliki langganan yang terdaftar.', 'ja': 'この人にはまだサブスクリプションが登録されていません。'},
    'Time to go': {'fr': 'Temps pour y aller', 'es': 'Tiempo para ir', 'de': 'Zeit zum Aufbruch', 'it': 'Tempo per andarci', 'pt': 'Tempo para ir', 'nl': 'Tijd om te gaan', 'ca': 'Temps per anar-hi', 'ro': 'Timp pentru a ajunge', 'bg': 'Време за тръгване', 'el': 'Ώρα για αναχώρηση', 'ar': 'وقت الذهاب', 'he': 'זמן ללכת', 'id': 'Waktu untuk pergi', 'ja': '出発時間'},
    'Title of the document description': {'fr': 'Titre de la description du document', 'es': 'Título de la descripción del documento', 'de': 'Titel der Dokumentbeschreibung', 'it': 'Titolo della descrizione del documento', 'pt': 'Título da descrição do documento', 'nl': 'Titel van de documentbeschrijving', 'ca': 'Títol de la descripció del document', 'ro': 'Titlul descrierii documentului', 'bg': 'Заглавие на описанието на документа', 'el': 'Τίτλος περιγραφής εγγράφου', 'ar': 'عنوان وصف الوثيقة', 'he': 'כותרת תיאור המסמך', 'id': 'Judul deskripsi dokumen', 'ja': '文書説明のタイトル'},
    'Titles': {'fr': 'Titres', 'es': 'Títulos', 'de': 'Titel', 'it': 'Titoli', 'pt': 'Títulos', 'nl': 'Titels', 'ca': 'Títols', 'ro': 'Titluri', 'bg': 'Заглавия', 'el': 'Τίτλοι', 'ar': 'عناوين', 'he': 'כותרות', 'id': 'Judul', 'ja': 'タイトル'},
    'Today': {'fr': "Aujourd'hui", 'es': 'Hoy', 'de': 'Heute', 'it': 'Oggi', 'pt': 'Hoje', 'nl': 'Vandaag', 'ca': 'Avui', 'ro': 'Astăzi', 'bg': 'Днес', 'el': 'Σήμερα', 'ar': 'اليوم', 'he': 'היום', 'id': 'Hari ini', 'ja': '今日'},
    'Too many results to download ({0}). You can only download {1} results at once.': {'fr': 'Trop de résultats à télécharger ({0}). Vous ne pouvez télécharger que {1} résultats à la fois.', 'es': 'Demasiados resultados para descargar ({0}). Solo puede descargar {1} resultados a la vez.', 'de': 'Zu viele Ergebnisse zum Herunterladen ({0}). Sie können nur {1} Ergebnisse auf einmal herunterladen.', 'it': 'Troppi risultati da scaricare ({0}). Puoi scaricare solo {1} risultati alla volta.', 'pt': 'Demasiados resultados para transferir ({0}). Só pode transferir {1} resultados de uma vez.', 'nl': 'Te veel resultaten om te downloaden ({0}). U kunt slechts {1} resultaten tegelijk downloaden.', 'ca': 'Massa resultats per descarregar ({0}). Només podeu descarregar {1} resultats alhora.', 'ro': 'Prea multe rezultate de descărcat ({0}). Puteți descărca doar {1} rezultate odată.', 'bg': 'Твърде много резултати за изтегляне ({0}). Можете да изтеглите само {1} резултата наведнъж.', 'el': 'Πολλά αποτελέσματα για λήψη ({0}). Μπορείτε να κατεβάσετε μόνο {1} αποτελέσματα ταυτόχρονα.', 'ar': 'نتائج كثيرة جداً للتنزيل ({0}). يمكنك تنزيل {1} نتيجة فقط في المرة الواحدة.', 'he': 'יותר מדי תוצאות להורדה ({0}). ניתן להוריד רק {1} תוצאות בבת אחת.', 'id': 'Terlalu banyak hasil untuk diunduh ({0}). Anda hanya dapat mengunduh {1} hasil sekaligus.', 'ja': 'ダウンロードする結果が多すぎます（{0}）。一度に{1}件の結果しかダウンロードできません。'},
    'Toolbox': {'fr': 'Boîte à outils', 'es': 'Caja de herramientas', 'de': 'Werkzeugkasten', 'it': 'Cassetta degli attrezzi', 'pt': 'Caixa de ferramentas', 'nl': 'Gereedschapskist', 'ca': 'Caixa d\'eines', 'ro': 'Cutie de scule', 'bg': 'Кутия с инструменти', 'el': 'Εργαλειοθήκη', 'ar': 'صندوق الأدوات', 'he': 'ארגז כלים', 'id': 'Kotak alat', 'ja': 'ツールボックス'},
    'Topographic Data': {'fr': 'Données topographiques', 'es': 'Datos topográficos', 'de': 'Topografische Daten', 'it': 'Dati topografici', 'pt': 'Dados topográficos', 'nl': 'Topografische gegevens', 'ca': 'Dades topogràfiques', 'ro': 'Date topografice', 'bg': 'Топографски данни', 'el': 'Τοπογραφικά δεδομένα', 'ar': 'بيانات طبوغرافية', 'he': 'נתונים טופוגרפיים', 'id': 'Data topografi', 'ja': '地形データ'},
    'Topographic Drawing': {'fr': 'Dessin topographique', 'es': 'Dibujo topográfico', 'de': 'Topografische Zeichnung', 'it': 'Disegno topografico', 'pt': 'Desenho topográfico', 'nl': 'Topografische tekening', 'ca': 'Dibuix topogràfic', 'ro': 'Desen topografic', 'bg': 'Топографска рисунка', 'el': 'Τοπογραφικό σχέδιο', 'ar': 'رسم طبوغرافي', 'he': 'ציור טופוגרפי', 'id': 'Gambar topografi', 'ja': '地形図'},
}

with open(os.path.join(DIR, 'en.json'), encoding='utf-8') as f:
    en = json.load(f)

total = 0
for lang in ['fr','es','it','pt','de','nl','ca','ro','bg','el','ar','he','id','ja']:
    path = os.path.join(DIR, f'{lang}.json')
    with open(path, encoding='utf-8') as f:
        d = json.load(f)
    n = 0
    for k, langs in T.items():
        if k in en and lang in langs and (k not in d or d[k] == en[k]):
            d[k] = langs[lang]; n += 1
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(dict(sorted(d.items())), f, ensure_ascii=False, indent=2)
    total += n
    print(f'{lang}: +{n}')
print(f'Total: {total}')
