# -*- coding: utf-8 -*-
import json, os
DIR = os.path.dirname(os.path.abspath(__file__))

T = {
    'Topography': {'fr': 'Topographie', 'es': 'Topografía', 'de': 'Topografie', 'it': 'Topografia', 'pt': 'Topografia', 'nl': 'Topografie', 'ca': 'Topografia', 'ro': 'Topografie', 'bg': 'Топография', 'el': 'Τοπογραφία', 'ar': 'الطبوغرافيا', 'he': 'טופוגרפיה', 'id': 'Topografi', 'ja': '地形'},
    'Total': {'fr': 'Total', 'es': 'Total', 'de': 'Gesamt', 'it': 'Totale', 'pt': 'Total', 'nl': 'Totaal', 'ca': 'Total', 'ro': 'Total', 'bg': 'Общо', 'el': 'Σύνολο', 'ar': 'المجموع', 'he': 'סה"כ', 'id': 'Total', 'ja': '合計'},
    'Tour - Back': {'fr': 'Visite - Retour', 'es': 'Tour - Atrás', 'de': 'Tour - Zurück', 'it': 'Tour - Indietro', 'pt': 'Tour - Voltar', 'nl': 'Rondleiding - Terug', 'ca': 'Tour - Enrere', 'ro': 'Tur - Înapoi', 'bg': 'Обиколка - Назад', 'el': 'Περιήγηση - Πίσω', 'ar': 'الجولة - رجوع', 'he': 'סיור - חזרה', 'id': 'Tur - Kembali', 'ja': 'ツアー - 戻る'},
    'Tour - Data control': {'fr': 'Visite - Contrôle des données', 'es': 'Tour - Control de datos', 'de': 'Tour - Datenkontrolle', 'it': 'Tour - Controllo dati', 'pt': 'Tour - Controlo de dados', 'nl': 'Rondleiding - Gegevenscontrole', 'ca': 'Tour - Control de dades', 'ro': 'Tur - Control date', 'bg': 'Обиколка - Контрол на данните', 'el': 'Περιήγηση - Έλεγχος δεδομένων', 'ar': 'الجولة - التحكم بالبيانات', 'he': 'סיור - בקרת נתונים', 'id': 'Tur - Kontrol data', 'ja': 'ツアー - データコントロール'},
    'Tour - Data control description': {'fr': 'Visite - Description du contrôle des données', 'es': 'Tour - Descripción del control de datos', 'de': 'Tour - Datenkontroll-Beschreibung', 'it': 'Tour - Descrizione controllo dati', 'pt': 'Tour - Descrição do controlo de dados', 'nl': 'Rondleiding - Beschrijving gegevenscontrole', 'ca': 'Tour - Descripció del control de dades', 'ro': 'Tur - Descriere control date', 'bg': 'Обиколка - Описание на контрола на данните', 'el': 'Περιήγηση - Περιγραφή ελέγχου δεδομένων', 'ar': 'الجولة - وصف التحكم بالبيانات', 'he': 'סיור - תיאור בקרת נתונים', 'id': 'Tur - Deskripsi kontrol data', 'ja': 'ツアー - データコントロールの説明'},
    'Tour - Do not show again': {'fr': 'Visite - Ne plus afficher', 'es': 'Tour - No mostrar de nuevo', 'de': 'Tour - Nicht mehr anzeigen', 'it': 'Tour - Non mostrare più', 'pt': 'Tour - Não mostrar novamente', 'nl': 'Rondleiding - Niet meer tonen', 'ca': 'Tour - No tornar a mostrar', 'ro': 'Tur - Nu mai afișa', 'bg': 'Обиколка - Да не се показва отново', 'el': 'Περιήγηση - Να μην εμφανιστεί ξανά', 'ar': 'الجولة - لا تظهر مرة أخرى', 'he': 'סיור - אל תציג שוב', 'id': 'Tur - Jangan tampilkan lagi', 'ja': 'ツアー - 次回から表示しない'},
    'Tour - Finish': {'fr': 'Visite - Terminer', 'es': 'Tour - Finalizar', 'de': 'Tour - Beenden', 'it': 'Tour - Fine', 'pt': 'Tour - Terminar', 'nl': 'Rondleiding - Voltooien', 'ca': 'Tour - Finalitzar', 'ro': 'Tur - Finalizare', 'bg': 'Обиколка - Край', 'el': 'Περιήγηση - Τέλος', 'ar': 'الجولة - إنهاء', 'he': 'סיור - סיום', 'id': 'Tur - Selesai', 'ja': 'ツアー - 終了'},
    'Tour - Map layers': {'fr': 'Visite - Couches de carte', 'es': 'Tour - Capas del mapa', 'de': 'Tour - Kartenebenen', 'it': 'Tour - Livelli della mappa', 'pt': 'Tour - Camadas do mapa', 'nl': 'Rondleiding - Kaartlagen', 'ca': 'Tour - Capes del mapa', 'ro': 'Tur - Straturi hartă', 'bg': 'Обиколка - Слоеве на картата', 'el': 'Περιήγηση - Επίπεδα χάρτη', 'ar': 'الجولة - طبقات الخريطة', 'he': 'סיור - שכבות מפה', 'id': 'Tur - Lapisan peta', 'ja': 'ツアー - マップレイヤー'},
    'Tour - Map layers description': {'fr': 'Visite - Description des couches de carte', 'es': 'Tour - Descripción de capas del mapa', 'de': 'Tour - Beschreibung der Kartenebenen', 'it': 'Tour - Descrizione livelli mappa', 'pt': 'Tour - Descrição das camadas do mapa', 'nl': 'Rondleiding - Beschrijving kaartlagen', 'ca': 'Tour - Descripció de capes del mapa', 'ro': 'Tur - Descriere straturi hartă', 'bg': 'Обиколка - Описание на слоевете на картата', 'el': 'Περιήγηση - Περιγραφή επιπέδων χάρτη', 'ar': 'الجولة - وصف طبقات الخريطة', 'he': 'סיור - תיאור שכבות מפה', 'id': 'Tur - Deskripsi lapisan peta', 'ja': 'ツアー - マップレイヤーの説明'},
    'Tour - Next': {'fr': 'Visite - Suivant', 'es': 'Tour - Siguiente', 'de': 'Tour - Weiter', 'it': 'Tour - Avanti', 'pt': 'Tour - Próximo', 'nl': 'Rondleiding - Volgende', 'ca': 'Tour - Següent', 'ro': 'Tur - Următor', 'bg': 'Обиколка - Напред', 'el': 'Περιήγηση - Επόμενο', 'ar': 'الجولة - التالي', 'he': 'סיור - הבא', 'id': 'Tur - Berikutnya', 'ja': 'ツアー - 次へ'},
    'Tour - Skip': {'fr': 'Visite - Passer', 'es': 'Tour - Saltar', 'de': 'Tour - Überspringen', 'it': 'Tour - Salta', 'pt': 'Tour - Saltar', 'nl': 'Rondleiding - Overslaan', 'ca': 'Tour - Saltar', 'ro': 'Tur - Omite', 'bg': 'Обиколка - Пропускане', 'el': 'Περιήγηση - Παράλειψη', 'ar': 'الجولة - تخطي', 'he': 'סיור - דלג', 'id': 'Tur - Lewati', 'ja': 'ツアー - スキップ'},
    'Touristic site': {'fr': 'Site touristique', 'es': 'Sitio turístico', 'de': 'Touristischer Ort', 'it': 'Sito turistico', 'pt': 'Sítio turístico', 'nl': 'Toeristische site', 'ca': 'Lloc turístic', 'ro': 'Site turistic', 'bg': 'Туристически обект', 'el': 'Τουριστική τοποθεσία', 'ar': 'موقع سياحي', 'he': 'אתר תיירותי', 'id': 'Situs wisata', 'ja': '観光地'},
    'True': {'fr': 'Vrai', 'es': 'Verdadero', 'de': 'Wahr', 'it': 'Vero', 'pt': 'Verdadeiro', 'nl': 'Waar', 'ca': 'Cert', 'ro': 'Adevărat', 'bg': 'Вярно', 'el': 'Αληθές', 'ar': 'صحيح', 'he': 'נכון', 'id': 'Benar', 'ja': '真'},
    "Try to go straight to the point, mention keywords and be precise. Don't start with \"this document is about...\".": {'fr': "Essayez d'aller droit au but, mentionnez des mots-clés et soyez précis. Ne commencez pas par « ce document parle de... ».", 'es': 'Trate de ir directamente al grano, mencione palabras clave y sea preciso. No comience con "este documento trata de...".', 'de': 'Kommen Sie direkt auf den Punkt, erwähnen Sie Schlüsselwörter und seien Sie präzise. Beginnen Sie nicht mit "Dieses Dokument handelt von...".', 'it': 'Cercate di andare dritti al punto, menzionate parole chiave e siate precisi. Non iniziate con "questo documento riguarda...".', 'pt': 'Tente ir direto ao ponto, mencione palavras-chave e seja preciso. Não comece com "este documento é sobre...".', 'nl': 'Probeer direct ter zake te komen, noem trefwoorden en wees precies. Begin niet met "dit document gaat over...".', 'ca': "Intenteu anar directament al gra, esmenteu paraules clau i sigueu precisos. No comenceu amb \"aquest document tracta sobre...\".", 'ro': 'Încercați să mergeți direct la subiect, menționați cuvinte cheie și fiți precis. Nu începeți cu "acest document este despre...".', 'bg': 'Опитайте се да стигнете директно до същността, споменете ключови думи и бъдете точни. Не започвайте с "този документ е за...".', 'el': 'Προσπαθήστε να πάτε κατευθείαν στο θέμα, αναφέρτε λέξεις-κλειδιά και να είστε ακριβής. Μην αρχίζετε με "αυτό το έγγραφο αφορά...".', 'ar': 'حاول الوصول مباشرة إلى النقطة، اذكر الكلمات المفتاحية وكن دقيقاً. لا تبدأ بـ "هذه الوثيقة تتحدث عن...".', 'he': 'נסה ללכת ישר לעניין, ציין מילות מפתח והיה מדויק. אל תתחיל ב-"מסמך זה עוסק ב-...".', 'id': 'Cobalah langsung ke intinya, sebutkan kata kunci dan jadilah tepat. Jangan mulai dengan "dokumen ini tentang...".', 'ja': '要点を直接述べ、キーワードを挙げ、正確にしてください。「この文書は...について」などで始めないでください。'},
    'Type': {'fr': 'Type', 'es': 'Tipo', 'de': 'Typ', 'it': 'Tipo', 'pt': 'Tipo', 'nl': 'Type', 'ca': 'Tipus', 'ro': 'Tip', 'bg': 'Тип', 'el': 'Τύπος', 'ar': 'النوع', 'he': 'סוג', 'id': 'Jenis', 'ja': 'タイプ'},
    'Type at least {nbOfChars} character(s)': {'fr': 'Saisissez au moins {nbOfChars} caractère(s)', 'es': 'Escriba al menos {nbOfChars} carácter(es)', 'de': 'Geben Sie mindestens {nbOfChars} Zeichen ein', 'it': 'Digita almeno {nbOfChars} carattere/i', 'pt': 'Escreva pelo menos {nbOfChars} carácter(es)', 'nl': 'Typ minimaal {nbOfChars} teken(s)', 'ca': 'Escriu almenys {nbOfChars} caràcter(s)', 'ro': 'Introduceți cel puțin {nbOfChars} caracter(e)', 'bg': 'Въведете поне {nbOfChars} знак(а)', 'el': 'Πληκτρολογήστε τουλάχιστον {nbOfChars} χαρακτήρα(-ες)', 'ar': 'اكتب {nbOfChars} حرف على الأقل', 'he': 'הקלד לפחות {nbOfChars} תו/תווים', 'id': 'Ketik minimal {nbOfChars} karakter', 'ja': '少なくとも{nbOfChars}文字を入力してください'},
    'Type of the new entity to create': {'fr': 'Type de la nouvelle entité à créer', 'es': 'Tipo de la nueva entidad a crear', 'de': 'Typ der zu erstellenden neuen Entität', 'it': 'Tipo della nuova entità da creare', 'pt': 'Tipo da nova entidade a criar', 'nl': 'Type van de nieuwe entiteit om te maken', 'ca': 'Tipus de la nova entitat a crear', 'ro': 'Tipul noii entități de creat', 'bg': 'Тип на новия обект за създаване', 'el': 'Τύπος νέας οντότητας προς δημιουργία', 'ar': 'نوع الكيان الجديد المراد إنشاؤه', 'he': 'סוג הישות החדשה ליצירה', 'id': 'Jenis entitas baru yang akan dibuat', 'ja': '作成する新しいエンティティのタイプ'},
    'Underground time': {'fr': 'Temps sous terre', 'es': 'Tiempo bajo tierra', 'de': 'Unterirdische Zeit', 'it': 'Tempo sottoterra', 'pt': 'Tempo subterrâneo', 'nl': 'Ondergrondse tijd', 'ca': 'Temps subterrani', 'ro': 'Timp subteran', 'bg': 'Подземно време', 'el': 'Υπόγειος χρόνος', 'ar': 'الوقت تحت الأرض', 'he': 'זמן תת-קרקעי', 'id': 'Waktu bawah tanah', 'ja': '地下時間'},
    'Undo': {'fr': 'Annuler', 'es': 'Deshacer', 'de': 'Rückgängig', 'it': 'Annulla', 'pt': 'Desfazer', 'nl': 'Ongedaan maken', 'ca': 'Desfer', 'ro': 'Anulați', 'bg': 'Отмени', 'el': 'Αναίρεση', 'ar': 'تراجع', 'he': 'בטל', 'id': 'Batalkan', 'ja': '元に戻す'},
    'Undo successful': {'fr': 'Annulation réussie', 'es': 'Deshacer exitoso', 'de': 'Rückgängig erfolgreich', 'it': 'Annullamento riuscito', 'pt': 'Desfazer concluído', 'nl': 'Ongedaan maken geslaagd', 'ca': 'Desfer correctament', 'ro': 'Anulare reușită', 'bg': 'Отмяната е успешна', 'el': 'Επιτυχής αναίρεση', 'ar': 'تم التراجع بنجاح', 'he': 'הביטול הצליח', 'id': 'Batal berhasil', 'ja': '元に戻すことに成功しました'},
}

with open(os.path.join(DIR, 'en.json'), encoding='utf-8') as f:
    en = json.load(f)

total = 0
for lang in ['fr','es','it','pt','de','nl','ca','ro','bg','el','ar','he','id','ja']:
    path = os.path.join(DIR, f'{lang}.json')
    with open(path, encoding='utf-8') as f:
        d = json.load(f)
    n = 0
    for k, langs in T.items():
        if k in en and lang in langs and (k not in d or d[k] == en[k]):
            d[k] = langs[lang]; n += 1
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(dict(sorted(d.items())), f, ensure_ascii=False, indent=2)
    total += n
    print(f'{lang}: +{n}')
print(f'Total: {total}')
