# -*- coding: utf-8 -*-
import json, os
DIR = os.path.dirname(os.path.abspath(__file__))

T = {
    'URL': {'fr': 'URL', 'es': 'URL', 'de': 'URL', 'it': 'URL', 'pt': 'URL', 'nl': 'URL', 'ca': 'URL', 'ro': 'URL', 'bg': 'URL адрес', 'el': 'URL', 'ar': 'رابط URL', 'he': 'כתובת URL', 'id': 'URL', 'ja': 'URL'},
    'Unique identifier of the document. It can be a DOI, an URL, an ISBN or an ISSN.': {'fr': "Identifiant unique du document. Il peut s'agir d'un DOI, d'une URL, d'un ISBN ou d'un ISSN.", 'es': 'Identificador único del documento. Puede ser un DOI, una URL, un ISBN o un ISSN.', 'de': 'Eindeutiger Bezeichner des Dokuments. Es kann eine DOI, eine URL, eine ISBN oder eine ISSN sein.', 'it': 'Identificatore univoco del documento. Può essere un DOI, un URL, un ISBN o un ISSN.', 'pt': 'Identificador único do documento. Pode ser um DOI, um URL, um ISBN ou um ISSN.', 'nl': 'Unieke identificator van het document. Het kan een DOI, een URL, een ISBN of een ISSN zijn.', 'ca': "Identificador únic del document. Pot ser un DOI, una URL, un ISBN o un ISSN.", 'ro': 'Identificator unic al documentului. Poate fi un DOI, un URL, un ISBN sau un ISSN.', 'bg': 'Уникален идентификатор на документа. Може да бъде DOI, URL, ISBN или ISSN.', 'el': 'Μοναδικό αναγνωριστικό του εγγράφου. Μπορεί να είναι DOI, URL, ISBN ή ISSN.', 'ar': 'المعرف الفريد للوثيقة. يمكن أن يكون DOI أو URL أو ISBN أو ISSN.', 'he': 'מזהה ייחודי של המסמך. יכול להיות DOI, URL, ISBN או ISSN.', 'id': 'Pengidentifikasi unik dokumen. Bisa berupa DOI, URL, ISBN, atau ISSN.', 'ja': '文書の一意識別子。DOI、URL、ISBN、またはISSNが使えます。'},
    'Unless stated otherwise, the CC-BY-SA license applies for documents and texts subject to copyright.': {'fr': "Sauf indication contraire, la licence CC-BY-SA s'applique aux documents et textes soumis au droit d'auteur.", 'es': 'Salvo que se indique lo contrario, la licencia CC-BY-SA se aplica a los documentos y textos sujetos a derechos de autor.', 'de': 'Sofern nicht anders angegeben, gilt die CC-BY-SA-Lizenz für urheberrechtlich geschützte Dokumente und Texte.', 'it': "Salvo diversa indicazione, la licenza CC-BY-SA si applica ai documenti e testi soggetti a copyright.", 'pt': 'Salvo indicação contrária, a licença CC-BY-SA aplica-se a documentos e textos sujeitos a direitos de autor.', 'nl': 'Tenzij anders vermeld, geldt de CC-BY-SA-licentie voor documenten en teksten die onderhevig zijn aan auteursrecht.', 'ca': "Tret que s'indiqui el contrari, la llicència CC-BY-SA s'aplica als documents i textos subjectes a drets d'autor.", 'ro': 'Cu excepția cazului în care se specifică altfel, licența CC-BY-SA se aplică documentelor și textelor supuse dreptului de autor.', 'bg': 'Освен ако не е посочено друго, лицензът CC-BY-SA се прилага за документи и текстове, обект на авторско право.', 'el': 'Εκτός εάν δηλώνεται διαφορετικά, η άδεια CC-BY-SA ισχύει για έγγραφα και κείμενα που υπόκεινται σε πνευματικά δικαιώματα.', 'ar': 'ما لم ينص على خلاف ذلك، تنطبق رخصة CC-BY-SA على المستندات والنصوص الخاضعة لحقوق النشر.', 'he': 'אלא אם נאמר אחרת, רישיון CC-BY-SA חל על מסמכים וטקסטים הכפופים לזכויות יוצרים.', 'id': 'Kecuali dinyatakan sebaliknya, lisensi CC-BY-SA berlaku untuk dokumen dan teks yang tunduk pada hak cipta.', 'ja': '特に記載がない限り、著作権の対象となる文書およびテキストにはCC-BY-SAライセンスが適用されます。'},
    'Unlink this document': {'fr': 'Dissocier ce document', 'es': 'Desvincular este documento', 'de': 'Dieses Dokument trennen', 'it': 'Scollega questo documento', 'pt': 'Desassociar este documento', 'nl': 'Dit document ontkoppelen', 'ca': 'Desvincula aquest document', 'ro': 'Dezlegați acest document', 'bg': 'Откачи този документ', 'el': 'Αποσύνδεση αυτού του εγγράφου', 'ar': 'إلغاء ارتباط هذا المستند', 'he': 'נתק מסמך זה', 'id': 'Putuskan tautan dokumen ini', 'ja': 'この文書のリンクを解除'},
    'Unlink this document?': {'fr': 'Dissocier ce document ?', 'es': '¿Desvincular este documento?', 'de': 'Dieses Dokument trennen?', 'it': 'Scollega questo documento?', 'pt': 'Desassociar este documento?', 'nl': 'Dit document ontkoppelen?', 'ca': 'Desvincula aquest document?', 'ro': 'Dezlegați acest document?', 'bg': 'Откачи ли този документ?', 'el': 'Αποσύνδεση αυτού του εγγράφου;', 'ar': 'إلغاء ارتباط هذا المستند؟', 'he': 'לנתק מסמך זה?', 'id': 'Putuskan tautan dokumen ini?', 'ja': 'この文書のリンクを解除しますか？'},
    'Unselect document': {'fr': 'Désélectionner le document', 'es': 'Deseleccionar documento', 'de': 'Dokument abwählen', 'it': 'Deseleziona documento', 'pt': 'Desselecionar documento', 'nl': 'Document deselecteren', 'ca': 'Deselecciona document', 'ro': 'Deselectați documentul', 'bg': 'Премахни избора на документ', 'el': 'Αποεπιλογή εγγράφου', 'ar': 'إلغاء تحديد المستند', 'he': 'בטל בחירת מסמך', 'id': 'Batalkan pilihan dokumen', 'ja': '文書の選択を解除'},
    'Unselect user': {'fr': "Désélectionner l'utilisateur", 'es': 'Deseleccionar usuario', 'de': 'Benutzer abwählen', 'it': "Deseleziona l'utente", 'pt': 'Desselecionar utilizador', 'nl': 'Gebruiker deselecteren', 'ca': "Deselecciona l'usuari", 'ro': 'Deselectați utilizatorul', 'bg': 'Премахни избора на потребител', 'el': 'Αποεπιλογή χρήστη', 'ar': 'إلغاء تحديد المستخدم', 'he': 'בטל בחירת משתמש', 'id': 'Batalkan pilihan pengguna', 'ja': 'ユーザーの選択を解除'},
    'Update user': {'fr': "Mettre à jour l'utilisateur", 'es': 'Actualizar usuario', 'de': 'Benutzer aktualisieren', 'it': "Aggiorna l'utente", 'pt': 'Atualizar utilizador', 'nl': 'Gebruiker bijwerken', 'ca': "Actualitza l'usuari", 'ro': 'Actualizați utilizatorul', 'bg': 'Актуализирай потребителя', 'el': 'Ενημέρωση χρήστη', 'ar': 'تحديث المستخدم', 'he': 'עדכן משתמש', 'id': 'Perbarui pengguna', 'ja': 'ユーザーを更新'},
    'Updated by': {'fr': 'Mis à jour par', 'es': 'Actualizado por', 'de': 'Aktualisiert von', 'it': 'Aggiornato da', 'pt': 'Atualizado por', 'nl': 'Bijgewerkt door', 'ca': 'Actualitzat per', 'ro': 'Actualizat de', 'bg': 'Актуализирано от', 'el': 'Ενημερώθηκε από', 'ar': 'تم التحديث بواسطة', 'he': 'עודכן על ידי', 'id': 'Diperbarui oleh', 'ja': '更新者'},
    'Updating cave...': {'fr': 'Mise à jour de la cavité...', 'es': 'Actualizando cueva...', 'de': 'Höhle wird aktualisiert...', 'it': 'Aggiornamento grotta...', 'pt': 'A atualizar caverna...', 'nl': 'Grot bijwerken...', 'ca': 'Actualitzant cova...', 'ro': 'Se actualizează peștera...', 'bg': 'Обновяване на пещерата...', 'el': 'Ενημέρωση σπηλαίου...', 'ar': 'جارٍ تحديث الكهف...', 'he': 'מעדכן מערה...', 'id': 'Memperbarui gua...', 'ja': '洞窟を更新中...'},
    'Updating entrance...': {'fr': "Mise à jour de l'entrée...", 'es': 'Actualizando entrada...', 'de': 'Eingang wird aktualisiert...', 'it': "Aggiornamento ingresso...", 'pt': 'A atualizar entrada...', 'nl': 'Ingang bijwerken...', 'ca': "Actualitzant entrada...", 'ro': 'Se actualizează intrarea...', 'bg': 'Обновяване на входа...', 'el': 'Ενημέρωση εισόδου...', 'ar': 'جارٍ تحديث المدخل...', 'he': 'מעדכן כניסה...', 'id': 'Memperbarui pintu masuk...', 'ja': '入口を更新中...'},
    'Updating massif...': {'fr': 'Mise à jour du massif...', 'es': 'Actualizando macizo...', 'de': 'Massiv wird aktualisiert...', 'it': 'Aggiornamento massiccio...', 'pt': 'A atualizar maciço...', 'nl': 'Massief bijwerken...', 'ca': 'Actualitzant massís...', 'ro': 'Se actualizează masivul...', 'bg': 'Обновяване на масива...', 'el': 'Ενημέρωση μασίφ...', 'ar': 'جارٍ تحديث الجبل...', 'he': 'מעדכן מסיף...', 'id': 'Memperbarui masif...', 'ja': 'マシフを更新中...'},
    'Updating network...': {'fr': 'Mise à jour du réseau...', 'es': 'Actualizando red...', 'de': 'Netzwerk wird aktualisiert...', 'it': 'Aggiornamento rete...', 'pt': 'A atualizar rede...', 'nl': 'Netwerk bijwerken...', 'ca': 'Actualitzant xarxa...', 'ro': 'Se actualizează rețeaua...', 'bg': 'Обновяване на мрежата...', 'el': 'Ενημέρωση δικτύου...', 'ar': 'جارٍ تحديث الشبكة...', 'he': 'מעדכן רשת...', 'id': 'Memperbarui jaringan...', 'ja': 'ネットワークを更新中...'},
    'Updating organization...': {'fr': "Mise à jour de l'organisation...", 'es': 'Actualizando organización...', 'de': 'Organisation wird aktualisiert...', 'it': "Aggiornamento organizzazione...", 'pt': 'A atualizar organização...', 'nl': 'Organisatie bijwerken...', 'ca': "Actualitzant organització...", 'ro': 'Se actualizează organizația...', 'bg': 'Обновяване на организацията...', 'el': 'Ενημέρωση οργανισμού...', 'ar': 'جارٍ تحديث المنظمة...', 'he': 'מעדכן ארגון...', 'id': 'Memperbarui organisasi...', 'ja': '組織を更新中...'},
    'Updating person...': {'fr': 'Mise à jour de la personne...', 'es': 'Actualizando persona...', 'de': 'Person wird aktualisiert...', 'it': 'Aggiornamento persona...', 'pt': 'A atualizar pessoa...', 'nl': 'Persoon bijwerken...', 'ca': 'Actualitzant persona...', 'ro': 'Se actualizează persoana...', 'bg': 'Обновяване на лицето...', 'el': 'Ενημέρωση ατόμου...', 'ar': 'جارٍ تحديث الشخص...', 'he': 'מעדכן אדם...', 'id': 'Memperbarui orang...', 'ja': '人物を更新中...'},
    'Updating user...': {'fr': "Mise à jour de l'utilisateur...", 'es': 'Actualizando usuario...', 'de': 'Benutzer wird aktualisiert...', 'it': "Aggiornamento utente...", 'pt': 'A atualizar utilizador...', 'nl': 'Gebruiker bijwerken...', 'ca': "Actualitzant usuari...", 'ro': 'Se actualizează utilizatorul...', 'bg': 'Обновяване на потребителя...', 'el': 'Ενημέρωση χρήστη...', 'ar': 'جارٍ تحديث المستخدم...', 'he': 'מעדכן משתמש...', 'id': 'Memperbarui pengguna...', 'ja': 'ユーザーを更新中...'},
    'Upload File (.geojson, .json, .zip)': {'fr': 'Téléverser un fichier (.geojson, .json, .zip)', 'es': 'Subir archivo (.geojson, .json, .zip)', 'de': 'Datei hochladen (.geojson, .json, .zip)', 'it': 'Carica file (.geojson, .json, .zip)', 'pt': 'Carregar ficheiro (.geojson, .json, .zip)', 'nl': 'Bestand uploaden (.geojson, .json, .zip)', 'ca': 'Carregar fitxer (.geojson, .json, .zip)', 'ro': 'Încărcați fișier (.geojson, .json, .zip)', 'bg': 'Качи файл (.geojson, .json, .zip)', 'el': 'Ανέβασμα αρχείου (.geojson, .json, .zip)', 'ar': 'تحميل ملف (.geojson, .json, .zip)', 'he': 'העלה קובץ (.geojson, .json, .zip)', 'id': 'Unggah File (.geojson, .json, .zip)', 'ja': 'ファイルをアップロード (.geojson, .json, .zip)'},
    'Upload a logo': {'fr': 'Téléverser un logo', 'es': 'Subir un logotipo', 'de': 'Logo hochladen', 'it': 'Carica un logo', 'pt': 'Carregar um logótipo', 'nl': 'Logo uploaden', 'ca': 'Carregar un logotip', 'ro': 'Încărcați un logo', 'bg': 'Качи лого', 'el': 'Ανέβασμα λογοτύπου', 'ar': 'تحميل شعار', 'he': 'העלה לוגו', 'id': 'Unggah logo', 'ja': 'ロゴをアップロード'},
    'Upload files': {'fr': 'Téléverser des fichiers', 'es': 'Subir archivos', 'de': 'Dateien hochladen', 'it': 'Carica file', 'pt': 'Carregar ficheiros', 'nl': 'Bestanden uploaden', 'ca': 'Carregar fitxers', 'ro': 'Încărcați fișiere', 'bg': 'Качи файлове', 'el': 'Ανέβασμα αρχείων', 'ar': 'تحميل الملفات', 'he': 'העלה קבצים', 'id': 'Unggah file', 'ja': 'ファイルをアップロード'},
    'Use the same wording that is used on the document: Vol.12, Number 15, No.158...': {'fr': 'Utilisez le même libellé que celui utilisé sur le document : Vol.12, Numéro 15, No.158...', 'es': 'Utilice el mismo texto que se usa en el documento: Vol.12, Número 15, No.158...', 'de': 'Verwenden Sie dieselbe Formulierung wie im Dokument: Vol.12, Nummer 15, No.158...', 'it': 'Utilizzare la stessa formulazione usata nel documento: Vol.12, Numero 15, No.158...', 'pt': 'Utilize a mesma formulação que é usada no documento: Vol.12, Número 15, No.158...', 'nl': 'Gebruik dezelfde bewoording als in het document: Vol.12, Nummer 15, No.158...', 'ca': 'Useu la mateixa formulació que s\'utilitza al document: Vol.12, Número 15, No.158...', 'ro': 'Folosiți aceeași formulare care este utilizată în document: Vol.12, Număr 15, No.158...', 'bg': 'Използвайте същата формулировка, която се използва в документа: Vol.12, Number 15, No.158...', 'el': 'Χρησιμοποιήστε την ίδια διατύπωση που χρησιμοποιείται στο έγγραφο: Vol.12, Number 15, No.158...', 'ar': 'استخدم نفس الصياغة المستخدمة في الوثيقة: Vol.12, Number 15, No.158...', 'he': 'השתמש באותו ניסוח שמשמש במסמך: Vol.12, Number 15, No.158...', 'id': 'Gunakan kata-kata yang sama seperti yang digunakan di dokumen: Vol.12, Number 15, No.158...', 'ja': '文書で使用されているのと同じ表記を使用してください: Vol.12, Number 15, No.158...'},
}

with open(os.path.join(DIR, 'en.json'), encoding='utf-8') as f:
    en = json.load(f)

total = 0
for lang in ['fr','es','it','pt','de','nl','ca','ro','bg','el','ar','he','id','ja']:
    path = os.path.join(DIR, f'{lang}.json')
    with open(path, encoding='utf-8') as f:
        d = json.load(f)
    n = 0
    for k, langs in T.items():
        if k in en and lang in langs and (k not in d or d[k] == en[k]):
            d[k] = langs[lang]; n += 1
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(dict(sorted(d.items())), f, ensure_ascii=False, indent=2)
    total += n
    print(f'{lang}: +{n}')
print(f'Total: {total}')
