# -*- coding: utf-8 -*-
import json, os
DIR = os.path.dirname(os.path.abspath(__file__))

T = {
    'You are unsubscribed from the massif.': {'fr': 'Vous êtes désabonné du massif.', 'es': 'Se ha cancelado su suscripción al macizo.', 'de': 'Sie haben das Massiv abonniert.', 'it': 'Hai annullato l\'iscrizione al massiccio.', 'pt': 'Cancelou a subscrição do maciço.', 'nl': 'U bent afgemeld van het massief.', 'ca': 'Heu cancel·lat la subscripció al massís.', 'ro': 'V-ați dezabonat de la masiv.', 'bg': 'Отписахте се от масива.', 'el': 'Έχετε απεγγραφεί από το μασίφ.', 'ar': 'لقد ألغيت اشتراكك في الجبل.', 'he': 'ביטלת את המנוי למסיף.', 'id': 'Anda berhenti berlangganan masif.', 'ja': 'マシフの購読を解除しました。'},
    'You are unsubscribed from the region.': {'fr': 'Vous êtes désabonné de la région.', 'es': 'Se ha cancelado su suscripción a la región.', 'de': 'Sie haben die Region abonniert.', 'it': 'Hai annullato l\'iscrizione alla regione.', 'pt': 'Cancelou a subscrição da região.', 'nl': 'U bent afgemeld van de regio.', 'ca': 'Heu cancel·lat la subscripció a la regió.', 'ro': 'V-ați dezabonat de la regiune.', 'bg': 'Отписахте се от региона.', 'el': 'Έχετε απεγγραφεί από την περιοχή.', 'ar': 'لقد ألغيت اشتراكك في المنطقة.', 'he': 'ביטלת את המנוי לאזור.', 'id': 'Anda berhenti berlangganan wilayah.', 'ja': '地域の購読を解除しました。'},
    'You can also provide a collection of documents of which you are the author.': {'fr': 'Vous pouvez également fournir une collection de documents dont vous êtes l\'auteur.', 'es': 'También puede proporcionar una colección de documentos de los que es autor.', 'de': 'Sie können auch eine Sammlung von Dokumenten bereitstellen, deren Autor Sie sind.', 'it': 'Puoi anche fornire una raccolta di documenti di cui sei l\'autore.', 'pt': 'Pode também fornecer uma coleção de documentos dos quais é o autor.', 'nl': 'U kunt ook een verzameling documenten aanleveren waarvan u de auteur bent.', 'ca': 'Podeu també proporcionar una col·lecció de documents dels quals sou l\'autor.', 'ro': 'Puteți, de asemenea, furniza o colecție de documente al căror autor ești.', 'bg': 'Можете също да предоставите колекция от документи, чийто автор сте.', 'el': 'Μπορείτε επίσης να παρέχετε μια συλλογή εγγράφων των οποίων είστε ο συγγραφέας.', 'ar': 'يمكنك أيضاً تقديم مجموعة من المستندات التي أنت مؤلفها.', 'he': 'ניתן גם לספק אוסף של מסמכים שאתה המחבר שלהם.', 'id': 'Anda juga dapat menyediakan kumpulan dokumen yang Anda adalah penulisnya.', 'ja': 'あなたが著者である文書のコレクションを提供することもできます。'},
    'You have probably wondered how to find data on caves?': {'fr': 'Vous vous êtes probablement demandé comment trouver des données sur les grottes ?', 'es': '¿Se ha preguntado cómo encontrar datos sobre cuevas?', 'de': 'Haben Sie sich wahrscheinlich gefragt, wie man Daten über Höhlen findet?', 'it': 'Probabilmente vi siete chiesti come trovare dati sulle grotte?', 'pt': 'Provavelmente já se perguntou como encontrar dados sobre cavernas?', 'nl': 'U heeft zich waarschijnlijk afgevraagd hoe u gegevens over grotten kunt vinden?', 'ca': 'Probablement us heu preguntat com trobar dades sobre coves?', 'ro': 'V-ați întrebat probabil cum să găsiți date despre peșteri?', 'bg': 'Вероятно сте се чудили как да намерите данни за пещери?', 'el': 'Πιθανώς έχετε αναρωτηθεί πώς να βρείτε δεδομένα για σπήλαια;', 'ar': 'ربما تساءلت كيف تجد بيانات عن الكهوف؟', 'he': 'כנראה תהית איך למצוא נתונים על מערות?', 'id': 'Anda mungkin bertanya-tanya bagaimana cara menemukan data tentang gua?', 'ja': '洞窟のデータをどうやって探すのか疑問に思ったことがあるでしょう？'},
    'You must be authenticated to submit a new entity to Grottocenter.': {'fr': 'Vous devez être authentifié pour soumettre une nouvelle entité à Grottocenter.', 'es': 'Debe estar autenticado para enviar una nueva entidad a Grottocenter.', 'de': 'Sie müssen authentifiziert sein, um eine neue Entität bei Grottocenter einzureichen.', 'it': 'Devi essere autenticato per inviare una nuova entità a Grottocenter.', 'pt': 'Deve estar autenticado para submeter uma nova entidade ao Grottocenter.', 'nl': 'U moet geauthenticeerd zijn om een nieuwe entiteit in te dienen bij Grottocenter.', 'ca': 'Heu d\'estar autenticat per enviar una nova entitat a Grottocenter.', 'ro': 'Trebuie să fiți autentificat pentru a trimite o nouă entitate la Grottocenter.', 'bg': 'Трябва да сте удостоверени, за да изпратите нов обект в Grottocenter.', 'el': 'Πρέπει να είστε ταυτοποιημένος για να υποβάλετε νέα οντότητα στο Grottocenter.', 'ar': 'يجب أن تكون مصادقاً لتقديم كيان جديد إلى Grottocenter.', 'he': 'עליך להיות מאומת כדי להגיש ישות חדשה ל-Grottocenter.', 'id': 'Anda harus terautentikasi untuk mengirimkan entitas baru ke Grottocenter.', 'ja': 'Grottocenterに新しいエンティティを提出するには認証が必要です。'},
    'You must have a name': {'fr': 'Vous devez avoir un nom', 'es': 'Debe tener un nombre', 'de': 'Sie müssen einen Namen haben', 'it': 'Devi avere un nome', 'pt': 'Deve ter um nome', 'nl': 'U moet een naam hebben', 'ca': 'Heu de tenir un nom', 'ro': 'Trebuie să aveți un nume', 'bg': 'Трябва да имате име', 'el': 'Πρέπει να έχετε όνομα', 'ar': 'يجب أن يكون لك اسم', 'he': 'חייב להיות לך שם', 'id': 'Anda harus memiliki nama', 'ja': '名前が必要です'},
    'You must have a surname': {'fr': 'Vous devez avoir un nom de famille', 'es': 'Debe tener un apellido', 'de': 'Sie müssen einen Nachnamen haben', 'it': 'Devi avere un cognome', 'pt': 'Deve ter um apelido', 'nl': 'U moet een achternaam hebben', 'ca': 'Heu de tenir un cognom', 'ro': 'Trebuie să aveți un prenume', 'bg': 'Трябва да имате фамилия', 'el': 'Πρέπει να έχετε επώνυμο', 'ar': 'يجب أن يكون لك لقب', 'he': 'חייב להיות לך שם משפחה', 'id': 'Anda harus memiliki nama belakang', 'ja': '姓が必要です'},
    'You must provide a password.': {'fr': 'Vous devez fournir un mot de passe.', 'es': 'Debe proporcionar una contraseña.', 'de': 'Sie müssen ein Passwort angeben.', 'it': 'Devi fornire una password.', 'pt': 'Deve fornecer uma palavra-passe.', 'nl': 'U moet een wachtwoord opgeven.', 'ca': 'Heu de proporcionar una contrasenya.', 'ro': 'Trebuie să furnizați o parolă.', 'bg': 'Трябва да предоставите парола.', 'el': 'Πρέπει να παρέχετε κωδικό πρόσβασης.', 'ar': 'يجب تقديم كلمة مرور.', 'he': 'עליך לספק סיסמה.', 'id': 'Anda harus menyediakan kata sandi.', 'ja': 'パスワードを指定してください。'},
    'You must provide an email.': {'fr': 'Vous devez fournir un e-mail.', 'es': 'Debe proporcionar un correo electrónico.', 'de': 'Sie müssen eine E-Mail-Adresse angeben.', 'it': 'Devi fornire un\'e-mail.', 'pt': 'Deve fornecer um e-mail.', 'nl': 'U moet een e-mailadres opgeven.', 'ca': 'Heu de proporcionar un correu electrònic.', 'ro': 'Trebuie să furnizați un e-mail.', 'bg': 'Трябва да предоставите имейл.', 'el': 'Πρέπει να παρέχετε e-mail.', 'ar': 'يجب تقديم بريد إلكتروني.', 'he': 'עליך לספק אימייל.', 'id': 'Anda harus menyediakan email.', 'ja': 'メールアドレスを指定してください。'},
    'You must select a different cave than the initial one.': {'fr': 'Vous devez sélectionner une cavité différente de la cavité initiale.', 'es': 'Debe seleccionar una cueva diferente a la inicial.', 'de': 'Sie müssen eine andere Höhle als die ursprüngliche auswählen.', 'it': 'Devi selezionare una grotta diversa da quella iniziale.', 'pt': 'Deve selecionar uma caverna diferente da inicial.', 'nl': 'U moet een andere grot selecteren dan de oorspronkelijke.', 'ca': 'Heu de seleccionar una cova diferent de la inicial.', 'ro': 'Trebuie să selectați o peșteră diferită de cea inițială.', 'bg': 'Трябва да изберете различна пещера от първоначалната.', 'el': 'Πρέπει να επιλέξετε διαφορετικό σπήλαιο από το αρχικό.', 'ar': 'يجب عليك اختيار كهف مختلف عن الكهف الأولي.', 'he': 'עליך לבחור מערה שונה מהמקורית.', 'id': 'Anda harus memilih gua yang berbeda dari yang awal.', 'ja': '最初の洞窟とは別の洞窟を選択してください。'},
    'Your password must be at least {passwordMinLength} characters.': {'fr': 'Votre mot de passe doit comporter au moins {passwordMinLength} caractères.', 'es': 'Su contraseña debe tener al menos {passwordMinLength} caracteres.', 'de': 'Ihr Passwort muss mindestens {passwordMinLength} Zeichen lang sein.', 'it': 'La tua password deve essere lunga almeno {passwordMinLength} caratteri.', 'pt': 'A sua palavra-passe deve ter pelo menos {passwordMinLength} caracteres.', 'nl': 'Uw wachtwoord moet minimaal {passwordMinLength} tekens bevatten.', 'ca': 'La vostra contrasenya ha de tenir almenys {passwordMinLength} caràcters.', 'ro': 'Parola dvs. trebuie să aibă cel puțin {passwordMinLength} caractere.', 'bg': 'Вашата парола трябва да е поне {passwordMinLength} знака.', 'el': 'Ο κωδικός σας πρέπει να είναι τουλάχιστον {passwordMinLength} χαρακτήρες.', 'ar': 'يجب أن تكون كلمة مرورك {passwordMinLength} أحرف على الأقل.', 'he': 'הסיסמה שלך חייבת להכיל לפחות {passwordMinLength} תווים.', 'id': 'Kata sandi Anda harus setidaknya {passwordMinLength} karakter.', 'ja': 'パスワードは少なくとも{passwordMinLength}文字必要です。'},
    'Your password will be changed': {'fr': 'Votre mot de passe sera modifié', 'es': 'Su contraseña será cambiada', 'de': 'Ihr Passwort wird geändert', 'it': 'La tua password verrà cambiata', 'pt': 'A sua palavra-passe será alterada', 'nl': 'Uw wachtwoord wordt gewijzigd', 'ca': 'La vostra contrasenya serà canviada', 'ro': 'Parola dvs. va fi schimbată', 'bg': 'Вашата парола ще бъде сменена', 'el': 'Ο κωδικός σας θα αλλάξει', 'ar': 'سيتم تغيير كلمة مرورك', 'he': 'הסיסמה שלך תשתנה', 'id': 'Kata sandi Anda akan diubah', 'ja': 'パスワードが変更されます'},
    'Your real name (optional).': {'fr': 'Votre vrai prénom (optionnel).', 'es': 'Su nombre real (opcional).', 'de': 'Ihr richtiger Name (optional).', 'it': 'Il tuo vero nome (facoltativo).', 'pt': 'O seu nome real (opcional).', 'nl': 'Uw echte naam (optioneel).', 'ca': 'El vostre nom real (opcional).', 'ro': 'Numele real (opțional).', 'bg': 'Вашето истинско име (по избор).', 'el': 'Το πραγματικό σας όνομα (προαιρετικό).', 'ar': 'اسمك الحقيقي (اختياري).', 'he': 'שמך האמיתי (אופציונלי).', 'id': 'Nama asli Anda (opsional).', 'ja': '本名（任意）。'},
    'Your real surname (optional).': {'fr': 'Votre vrai nom de famille (optionnel).', 'es': 'Su apellido real (opcional).', 'de': 'Ihr richtiger Nachname (optional).', 'it': 'Il tuo vero cognome (facoltativo).', 'pt': 'O seu apelido real (opcional).', 'nl': 'Uw echte achternaam (optioneel).', 'ca': 'El vostre cognom real (opcional).', 'ro': 'Prenumele real (opțional).', 'bg': 'Вашата истинска фамилия (по избор).', 'el': 'Το πραγματικό σας επώνυμο (προαιρετικό).', 'ar': 'لقبك الحقيقي (اختياري).', 'he': 'שם המשפחה שלך האמיתי (אופציונלי).', 'id': 'Nama belakang asli Anda (opsional).', 'ja': '本名の姓（任意）。'},
    'Z39.50 Server': {'fr': 'Serveur Z39.50', 'es': 'Servidor Z39.50', 'de': 'Z39.50-Server', 'it': 'Server Z39.50', 'pt': 'Servidor Z39.50', 'nl': 'Z39.50-server', 'ca': 'Servidor Z39.50', 'ro': 'Server Z39.50', 'bg': 'Z39.50 сървър', 'el': 'Διακομιστής Z39.50', 'ar': 'خادم Z39.50', 'he': 'שרת Z39.50', 'id': 'Server Z39.50', 'ja': 'Z39.50サーバー'},
    'Zip code': {'fr': 'Code postal', 'es': 'Código postal', 'de': 'Postleitzahl', 'it': 'Codice postale', 'pt': 'Código postal', 'nl': 'Postcode', 'ca': 'Codi postal', 'ro': 'Cod poștal', 'bg': 'Пощенски код', 'el': 'Ταχυδρομικός κωδικός', 'ar': 'الرمز البريدي', 'he': 'מיקוד', 'id': 'Kode pos', 'ja': '郵便番号'},
    'Zone:': {'fr': 'Zone :', 'es': 'Zona:', 'de': 'Zone:', 'it': 'Zona:', 'pt': 'Zona:', 'nl': 'Zone:', 'ca': 'Zona:', 'ro': 'Zonă:', 'bg': 'Зона:', 'el': 'Ζώνη:', 'ar': 'المنطقة:', 'he': 'אזור:', 'id': 'Zona:', 'ja': 'ゾーン：'},
    '[ALL]': {'fr': '[TOUS]', 'es': '[TODOS]', 'de': '[ALLE]', 'it': '[TUTTI]', 'pt': '[TODOS]', 'nl': '[ALLE]', 'ca': '[TOTS]', 'ro': '[TOATE]', 'bg': '[ВСИЧКИ]', 'el': '[ΟΛΑ]', 'ar': '[الكل]', 'he': '[הכל]', 'id': '[SEMUA]', 'ja': '[すべて]'},
    'all': {'fr': 'tous', 'es': 'todos', 'de': 'alle', 'it': 'tutti', 'pt': 'todos', 'nl': 'alle', 'ca': 'tots', 'ro': 'toate', 'bg': 'всички', 'el': 'όλα', 'ar': 'الكل', 'he': 'הכל', 'id': 'semua', 'ja': 'すべて'},
    'and': {'fr': 'et', 'es': 'y', 'de': 'und', 'it': 'e', 'pt': 'e', 'nl': 'en', 'ca': 'i', 'ro': 'și', 'bg': 'и', 'el': 'και', 'ar': 'و', 'he': 'ו', 'id': 'dan', 'ja': 'そして'},
    'at': {'fr': 'à', 'es': 'en', 'de': 'um', 'it': 'a', 'pt': 'às', 'nl': 'om', 'ca': 'a', 'ro': 'la', 'bg': 'в', 'el': 'στις', 'ar': 'في', 'he': 'ב', 'id': 'pada', 'ja': 'に'},
    'centered': {'fr': 'centré', 'es': 'centrado', 'de': 'zentriert', 'it': 'centrato', 'pt': 'centrado', 'nl': 'gecentreerd', 'ca': 'centrat', 'ro': 'centrat', 'bg': 'центриран', 'el': 'κεντρωμένο', 'ar': 'في المنتصف', 'he': 'ממורכז', 'id': 'terpusat', 'ja': '中央揃え'},
    'clear rate': {'fr': 'taux de clarté', 'es': 'tasa de claridad', 'de': 'Klarheitsrate', 'it': 'tasso di chiarezza', 'pt': 'taxa de clareza', 'nl': 'helderheidspercentage', 'ca': 'taxa de claredat', 'ro': 'rata de claritate', 'bg': 'степен на яснота', 'el': 'ποσοστό διαύγειας', 'ar': 'معدل الوضوح', 'he': 'שיעור בהירות', 'id': 'tingkat kejernihan', 'ja': 'クリアレート'},
    'code': {'fr': 'code', 'es': 'código', 'de': 'Code', 'it': 'codice', 'pt': 'código', 'nl': 'code', 'ca': 'codi', 'ro': 'cod', 'bg': 'код', 'el': 'κωδικός', 'ar': 'رمز', 'he': 'קוד', 'id': 'kode', 'ja': 'コード'},
    'comment': {'fr': 'commentaire', 'es': 'comentario', 'de': 'Kommentar', 'it': 'commento', 'pt': 'comentário', 'nl': 'opmerking', 'ca': 'comentari', 'ro': 'comentariu', 'bg': 'коментар', 'el': 'σχόλιο', 'ar': 'تعليق', 'he': 'הערה', 'id': 'komentar', 'ja': 'コメント'},
    'countries': {'fr': 'pays', 'es': 'países', 'de': 'Länder', 'it': 'paesi', 'pt': 'países', 'nl': 'landen', 'ca': 'països', 'ro': 'țări', 'bg': 'страни', 'el': 'χώρες', 'ar': 'الدول', 'he': 'מדינות', 'id': 'negara', 'ja': '国'},
    'create': {'fr': 'créer', 'es': 'crear', 'de': 'erstellen', 'it': 'crea', 'pt': 'criar', 'nl': 'aanmaken', 'ca': 'crear', 'ro': 'crea', 'bg': 'създай', 'el': 'δημιουργία', 'ar': 'إنشاء', 'he': 'צור', 'id': 'buat', 'ja': '作成'},
    'created': {'fr': 'créé', 'es': 'creado', 'de': 'erstellt', 'it': 'creato', 'pt': 'criado', 'nl': 'aangemaakt', 'ca': 'creat', 'ro': 'creat', 'bg': 'създадено', 'el': 'δημιουργήθηκε', 'ar': 'تم الإنشاء', 'he': 'נוצר', 'id': 'dibuat', 'ja': '作成済み'},
    'csvImport.errorRecap': {'fr': 'Récapitulatif des erreurs', 'es': 'Resumen de errores', 'de': 'Fehlerzusammenfassung', 'it': 'Riepilogo errori', 'pt': 'Resumo de erros', 'nl': 'Foutenoverzicht', 'ca': 'Resum d\'errors', 'ro': 'Rezumat erori', 'bg': 'Обобщение на грешките', 'el': 'Σύνοψη σφαλμάτων', 'ar': 'ملخص الأخطاء', 'he': 'סיכום שגיאות', 'id': 'Ringkasan kesalahan', 'ja': 'エラーサマリー'},
    'csvImport.incorrectTypeColumn': {'fr': 'Colonne de type incorrect', 'es': 'Columna de tipo incorrecto', 'de': 'Spalte mit falschem Typ', 'it': 'Colonna di tipo errato', 'pt': 'Coluna de tipo incorreto', 'nl': 'Kolom met onjuist type', 'ca': 'Columna de tipus incorrecte', 'ro': 'Coloană de tip incorect', 'bg': 'Колона с неправилен тип', 'el': 'Στήλη εσφαλμένου τύπου', 'ar': 'عمود من نوع غير صحيح', 'he': 'עמודה מסוג שגוי', 'id': 'Kolom dengan tipe yang salah', 'ja': '不正なタイプの列'},
    'csvImport.missingColumn': {'fr': 'Colonne manquante', 'es': 'Columna faltante', 'de': 'Fehlende Spalte', 'it': 'Colonna mancante', 'pt': 'Coluna em falta', 'nl': 'Ontbrekende kolom', 'ca': 'Columna faltant', 'ro': 'Coloană lipsă', 'bg': 'Липсваща колона', 'el': 'Λείπει στήλη', 'ar': 'عمود مفقود', 'he': 'עמודה חסרה', 'id': 'Kolom hilang', 'ja': '列が欠落'},
    'csvImport.successAsDuplicatesRecap': {'fr': 'Importés comme doublons', 'es': 'Importados como duplicados', 'de': 'Als Duplikate importiert', 'it': 'Importati come duplicati', 'pt': 'Importados como duplicados', 'nl': 'Geïmporteerd als duplicaten', 'ca': 'Importats com a duplicats', 'ro': 'Importate ca duplicate', 'bg': 'Импортирани като дубликати', 'el': 'Εισήχθησαν ως διπλότυπα', 'ar': 'تم الاستيراد كنسخ مكررة', 'he': 'יובאו ככפולים', 'id': 'Diimpor sebagai duplikat', 'ja': '重複としてインポート'},
    'csvImport.successRecap': {'fr': 'Importés avec succès', 'es': 'Importados con éxito', 'de': 'Erfolgreich importiert', 'it': 'Importati con successo', 'pt': 'Importados com sucesso', 'nl': 'Succesvol geïmporteerd', 'ca': 'Importats correctament', 'ro': 'Importate cu succes', 'bg': 'Импортирани успешно', 'el': 'Εισήχθησαν επιτυχώς', 'ar': 'تم الاستيراد بنجاح', 'he': 'יובאו בהצלחה', 'id': 'Berhasil diimpor', 'ja': 'インポート成功'},
    'csvImport.willBeImported': {'fr': 'Seront importés', 'es': 'Serán importados', 'de': 'Werden importiert', 'it': 'Saranno importati', 'pt': 'Serão importados', 'nl': 'Worden geïmporteerd', 'ca': 'Seran importats', 'ro': 'Vor fi importate', 'bg': 'Ще бъдат импортирани', 'el': 'Θα εισαχθούν', 'ar': 'سيتم استيرادها', 'he': 'יובאו', 'id': 'Akan diimpor', 'ja': 'インポートされます'},
    'csvImport.willBeImportedAsDuplicates': {'fr': 'Seront importés comme doublons', 'es': 'Serán importados como duplicados', 'de': 'Werden als Duplikate importiert', 'it': 'Saranno importati come duplicati', 'pt': 'Serão importados como duplicados', 'nl': 'Worden geïmporteerd als duplicaten', 'ca': 'Seran importats com a duplicats', 'ro': 'Vor fi importate ca duplicate', 'bg': 'Ще бъдат импортирани като дубликати', 'el': 'Θα εισαχθούν ως διπλότυπα', 'ar': 'سيتم استيرادها كنسخ مكررة', 'he': 'יובאו ככפולים', 'id': 'Akan diimpor sebagai duplikat', 'ja': '重複としてインポートされます'},
    'csvImport.willNotBeImported': {'fr': 'Ne seront pas importés', 'es': 'No serán importados', 'de': 'Werden nicht importiert', 'it': 'Non saranno importati', 'pt': 'Não serão importados', 'nl': 'Worden niet geïmporteerd', 'ca': 'No seran importats', 'ro': 'Nu vor fi importate', 'bg': 'Няма да бъдат импортирани', 'el': 'Δεν θα εισαχθούν', 'ar': 'لن يتم استيرادها', 'he': 'לא יובאו', 'id': 'Tidak akan diimpor', 'ja': 'インポートされません'},
    'data-control': {'fr': 'contrôle des données', 'es': 'control de datos', 'de': 'Datenkontrolle', 'it': 'controllo dati', 'pt': 'controlo de dados', 'nl': 'gegevenscontrole', 'ca': 'control de dades', 'ro': 'control date', 'bg': 'контрол на данните', 'el': 'έλεγχος δεδομένων', 'ar': 'التحكم بالبيانات', 'he': 'בקרת נתונים', 'id': 'kontrol data', 'ja': 'データコントロール'},
}

with open(os.path.join(DIR, 'en.json'), encoding='utf-8') as f:
    en = json.load(f)

total = 0
for lang in ['fr','es','it','pt','de','nl','ca','ro','bg','el','ar','he','id','ja']:
    path = os.path.join(DIR, f'{lang}.json')
    with open(path, encoding='utf-8') as f:
        d = json.load(f)
    n = 0
    for k, langs in T.items():
        if k in en and lang in langs and (k not in d or d[k] == en[k]):
            d[k] = langs[lang]; n += 1
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(dict(sorted(d.items())), f, ensure_ascii=False, indent=2)
    total += n
    print(f'{lang}: +{n}')
print(f'Total: {total}')
