# -*- coding: utf-8 -*-
"""Part 3: D-G keys."""
import json, os

LANG_DIR = os.path.dirname(os.path.abspath(__file__))

T = {
    'Data quality': {'it': 'Qualità dei dati', 'pt': 'Qualidade dos dados', 'de': 'Datenqualität', 'nl': 'Datakwaliteit', 'ca': 'Qualitat de les dades', 'ro': 'Calitatea datelor', 'bg': 'Качество на данните', 'el': 'Ποιότητα δεδομένων', 'ar': 'جودة البيانات', 'he': 'איכות הנתונים', 'id': 'Kualitas data', 'ja': 'データ品質'},
    'Data quality computation': {'it': 'Calcolo qualità dati', 'pt': 'Cálculo de qualidade de dados', 'de': 'Datenqualitätsberechnung', 'nl': 'Berekening datakwaliteit', 'ca': 'Càlcul de la qualitat de les dades', 'ro': 'Calculul calității datelor', 'bg': 'Изчисляване на качеството на данните', 'el': 'Υπολογισμός ποιότητας δεδομένων', 'ar': 'حساب جودة البيانات', 'he': 'חישוב איכות נתונים', 'id': 'Perhitungan kualitas data', 'ja': 'データ品質計算'},
    'Database export': {'it': 'Esportazione database', 'pt': 'Exportação de base de dados', 'de': 'Datenbankexport', 'nl': 'Database-export', 'ca': 'Exportació de base de dades', 'ro': 'Export bază de date', 'bg': 'Експорт на база данни', 'el': 'Εξαγωγή βάσης δεδομένων', 'ar': 'تصدير قاعدة البيانات', 'he': 'ייצוא בסיס נתונים', 'id': 'Ekspor database', 'ja': 'データベースのエクスポート'},
    'Date': {'it': 'Data', 'pt': 'Data', 'de': 'Datum', 'nl': 'Datum', 'ca': 'Data', 'ro': 'Dată', 'bg': 'Дата', 'el': 'Ημερομηνία', 'ar': 'التاريخ', 'he': 'תאריך', 'id': 'Tanggal', 'ja': '日付'},
    'Days ago': {'it': 'Giorni fa', 'pt': 'Dias atrás', 'de': 'Tage her', 'nl': 'Dagen geleden', 'ca': 'Dies enrere', 'ro': 'Acum {n} zile', 'bg': 'Дни назад', 'el': 'Μέρες πριν', 'ar': 'أيام مضت', 'he': 'ימים לפני', 'id': 'Hari lalu', 'ja': '日前'},
    'Decline': {'it': 'Rifiuta', 'pt': 'Recusar', 'de': 'Ablehnen', 'nl': 'Afwijzen', 'ca': 'Rebutjar', 'ro': 'Refuzați', 'bg': 'Откажи', 'el': 'Απόρριψη', 'ar': 'رفض', 'he': 'דחה', 'id': 'Tolak', 'ja': '却下'},
    'Delete': {'it': 'Elimina', 'pt': 'Eliminar', 'de': 'Löschen', 'nl': 'Verwijderen', 'ca': 'Eliminar', 'ro': 'Ștergeți', 'bg': 'Изтриване', 'el': 'Διαγραφή', 'ar': 'حذف', 'he': 'מחק', 'id': 'Hapus', 'ja': '削除'},
    'Delete last point': {'it': 'Elimina ultimo punto', 'pt': 'Eliminar último ponto', 'de': 'Letzten Punkt löschen', 'nl': 'Laatste punt verwijderen', 'ca': 'Elimina l\'últim punt', 'ro': 'Ștergeți ultimul punct', 'bg': 'Изтриване на последната точка', 'el': 'Διαγραφή τελευταίου σημείου', 'ar': 'حذف آخر نقطة', 'he': 'מחק נקודה אחרונה', 'id': 'Hapus titik terakhir', 'ja': '最後のポイントを削除'},
    'Delete layers': {'it': 'Elimina livelli', 'pt': 'Eliminar camadas', 'de': 'Ebenen löschen', 'nl': 'Lagen verwijderen', 'ca': 'Elimina capes', 'ro': 'Ștergeți straturi', 'bg': 'Изтриване на слоеве', 'el': 'Διαγραφή επιπέδων', 'ar': 'حذف الطبقات', 'he': 'מחק שכבות', 'id': 'Hapus lapisan', 'ja': 'レイヤーを削除'},
    'Deletion confirmation': {'it': 'Conferma eliminazione', 'pt': 'Confirmação de eliminação', 'de': 'Löschbestätigung', 'nl': 'Verwijderbevestiging', 'ca': 'Confirmació d\'eliminació', 'ro': 'Confirmare ștergere', 'bg': 'Потвърждение за изтриване', 'el': 'Επιβεβαίωση διαγραφής', 'ar': 'تأكيد الحذف', 'he': 'אישור מחיקה', 'id': 'Konfirmasi penghapusan', 'ja': '削除の確認'},
    'Depth icon': {'it': 'Icona profondità', 'pt': 'Ícone de profundidade', 'de': 'Tiefensymbol', 'nl': 'Diepte-icoon', 'ca': 'Icona de profunditat', 'ro': 'Pictogramă adâncime', 'bg': 'Икона за дълбочина', 'el': 'Εικονίδιο βάθους', 'ar': 'أيقونة العمق', 'he': 'סמל עומק', 'id': 'Ikon kedalaman', 'ja': '深度アイコン'},
    'Details': {'it': 'Dettagli', 'pt': 'Detalhes', 'de': 'Details', 'nl': 'Details', 'ca': 'Detalls', 'ro': 'Detalii', 'bg': 'Подробности', 'el': 'Λεπτομέρειες', 'ar': 'التفاصيل', 'he': 'פרטים', 'id': 'Detail', 'ja': '詳細'},
    'Development': {'it': 'Sviluppo', 'pt': 'Desenvolvimento', 'de': 'Entwicklung', 'nl': 'Ontwikkeling', 'ca': 'Desenvolupament', 'ro': 'Dezvoltare', 'bg': 'Развитие', 'el': 'Ανάπτυξη', 'ar': 'تطوير', 'he': 'פיתוח', 'id': 'Pengembangan', 'ja': '開発'},
    'Document Submission Form': {'it': 'Modulo di invio documento', 'pt': 'Formulário de envio de documento', 'de': 'Dokumentübermittlungsformular', 'nl': 'Documentindienformulier', 'ca': 'Formulari d\'enviament de document', 'ro': 'Formular de trimitere a documentului', 'bg': 'Формуляр за подаване на документ', 'el': 'Φόρμα υποβολής εγγράφου', 'ar': 'نموذج تقديم الوثيقة', 'he': 'טופס הגשת מסמך', 'id': 'Formulir pengiriman dokumen', 'ja': '文書提出フォーム'},
    'Document creator': {'it': 'Creatore del documento', 'pt': 'Criador do documento', 'de': 'Dokumentersteller', 'nl': 'Documentmaker', 'ca': 'Creador del document', 'ro': 'Creatorul documentului', 'bg': 'Създател на документа', 'el': 'Δημιουργός εγγράφου', 'ar': 'منشئ الوثيقة', 'he': 'יוצר המסמך', 'id': 'Pembuat dokumen', 'ja': '文書作成者'},
    'Document description': {'it': 'Descrizione del documento', 'pt': 'Descrição do documento', 'de': 'Dokumentbeschreibung', 'nl': 'Documentbeschrijving', 'ca': 'Descripció del document', 'ro': 'Descrierea documentului', 'bg': 'Описание на документа', 'el': 'Περιγραφή εγγράφου', 'ar': 'وصف الوثيقة', 'he': 'תיאור המסמך', 'id': 'Deskripsi dokumen', 'ja': '文書の説明'},
    'Document language': {'it': 'Lingua del documento', 'pt': 'Idioma do documento', 'de': 'Dokumentsprache', 'nl': 'Documenttaal', 'ca': 'Idioma del document', 'ro': 'Limba documentului', 'bg': 'Език на документа', 'el': 'Γλώσσα εγγράφου', 'ar': 'لغة الوثيقة', 'he': 'שפת המסמך', 'id': 'Bahasa dokumen', 'ja': '文書の言語'},
    'Document successfully updated.': {'it': 'Documento aggiornato con successo.', 'pt': 'Documento atualizado com sucesso.', 'de': 'Dokument erfolgreich aktualisiert.', 'nl': 'Document succesvol bijgewerkt.', 'ca': 'Document actualitzat correctament.', 'ro': 'Document actualizat cu succes.', 'bg': 'Документът е актуализиран успешно.', 'el': 'Το έγγραφο ενημερώθηκε επιτυχώς.', 'ar': 'تم تحديث الوثيقة بنجاح.', 'he': 'המסמך עודכן בהצלחה.', 'id': 'Dokumen berhasil diperbarui.', 'ja': '文書が正常に更新されました。'},
    'Document type': {'it': 'Tipo di documento', 'pt': 'Tipo de documento', 'de': 'Dokumenttyp', 'nl': 'Documenttype', 'ca': 'Tipus de document', 'ro': 'Tipul documentului', 'bg': 'Тип на документа', 'el': 'Τύπος εγγράφου', 'ar': 'نوع الوثيقة', 'he': 'סוג מסמך', 'id': 'Jenis dokumen', 'ja': '文書タイプ'},
    'Document validation': {'it': 'Validazione del documento', 'pt': 'Validação do documento', 'de': 'Dokumentvalidierung', 'nl': 'Documentvalidatie', 'ca': 'Validació del document', 'ro': 'Validarea documentului', 'bg': 'Потвърждение на документа', 'el': 'Επικύρωση εγγράφου', 'ar': 'التحقق من صحة الوثيقة', 'he': 'אימות מסמך', 'id': 'Validasi dokumen', 'ja': '文書の検証'},
    'Documents awaiting validation': {'it': 'Documenti in attesa di validazione', 'pt': 'Documentos aguardando validação', 'de': 'Dokumente warten auf Validierung', 'nl': 'Documenten wachten op validatie', 'ca': 'Documents a l\'espera de validació', 'ro': 'Documente care așteaptă validarea', 'bg': 'Документи, очакващи потвърждение', 'el': 'Έγγραφα που αναμένουν επικύρωση', 'ar': 'وثائق بانتظار التحقق', 'he': 'מסמכים הממתינים לאישור', 'id': 'Dokumen menunggu validasi', 'ja': '承認待ちの文書'},
    'Documents import': {'it': 'Importazione documenti', 'pt': 'Importação de documentos', 'de': 'Dokumentimport', 'nl': 'Documenten importeren', 'ca': 'Importació de documents', 'ro': 'Import documente', 'bg': 'Импорт на документи', 'el': 'Εισαγωγή εγγράφων', 'ar': 'استيراد الوثائق', 'he': 'ייבוא מסמכים', 'id': 'Impor dokumen', 'ja': '文書のインポート'},
    'Download information': {'it': 'Informazioni sul download', 'pt': 'Informações de download', 'de': 'Download-Informationen', 'nl': 'Downloadinformatie', 'ca': 'Informació de descàrrega', 'ro': 'Informații de descărcare', 'bg': 'Информация за изтегляне', 'el': 'Πληροφορίες λήψης', 'ar': 'معلومات التنزيل', 'he': 'מידע הורדה', 'id': 'Informasi unduhan', 'ja': 'ダウンロード情報'},
    'Draw a polygon': {'it': 'Disegna un poligono', 'pt': 'Desenhar um polígono', 'de': 'Ein Polygon zeichnen', 'nl': 'Een veelhoek tekenen', 'ca': 'Dibuixa un polígon', 'ro': 'Desenați un poligon', 'bg': 'Нарисувайте полигон', 'el': 'Σχεδιάστε ένα πολύγωνο', 'ar': 'ارسم مضلعاً', 'he': 'צייר מצולע', 'id': 'Gambar poligon', 'ja': 'ポリゴンを描く'},
    'Edit document': {'it': 'Modifica documento', 'pt': 'Editar documento', 'de': 'Dokument bearbeiten', 'nl': 'Document bewerken', 'ca': 'Edita document', 'ro': 'Editați documentul', 'bg': 'Редактиране на документ', 'el': 'Επεξεργασία εγγράφου', 'ar': 'تعديل الوثيقة', 'he': 'ערוך מסמך', 'id': 'Edit dokumen', 'ja': '文書を編集'},
    'Edit layers': {'it': 'Modifica livelli', 'pt': 'Editar camadas', 'de': 'Ebenen bearbeiten', 'nl': 'Lagen bewerken', 'ca': 'Edita capes', 'ro': 'Editați straturile', 'bg': 'Редактиране на слоеве', 'el': 'Επεξεργασία επιπέδων', 'ar': 'تعديل الطبقات', 'he': 'ערוך שכבות', 'id': 'Edit lapisan', 'ja': 'レイヤーを編集'},
    'Edit properties': {'it': 'Modifica proprietà', 'pt': 'Editar propriedades', 'de': 'Eigenschaften bearbeiten', 'nl': 'Eigenschappen bewerken', 'ca': 'Edita propietats', 'ro': 'Editați proprietățile', 'bg': 'Редактиране на свойства', 'el': 'Επεξεργασία ιδιοτήτων', 'ar': 'تعديل الخصائص', 'he': 'ערוך מאפיינים', 'id': 'Edit properti', 'ja': 'プロパティを編集'},
    'Edit these riggings': {'it': 'Modifica questi attrezzaggi', 'pt': 'Editar estes equipamentos', 'de': 'Diese Seilausrüstungen bearbeiten', 'nl': 'Deze uitrustingen bewerken', 'ca': 'Edita aquests equipaments', 'ro': 'Editați aceste echipamente', 'bg': 'Редактиране на тези оборудвания', 'el': 'Επεξεργασία αυτών των εξοπλισμών', 'ar': 'تعديل هذه التجهيزات', 'he': 'ערוך ציודים אלה', 'id': 'Edit rigging ini', 'ja': 'このロープ設置を編集'},
    'Edit this comment': {'it': 'Modifica questo commento', 'pt': 'Editar este comentário', 'de': 'Diesen Kommentar bearbeiten', 'nl': 'Dit commentaar bewerken', 'ca': 'Edita aquest comentari', 'ro': 'Editați acest comentariu', 'bg': 'Редактиране на този коментар', 'el': 'Επεξεργασία αυτού του σχολίου', 'ar': 'تعديل هذا التعليق', 'he': 'ערוך תגובה זו', 'id': 'Edit komentar ini', 'ja': 'このコメントを編集'},
    'Edit this description': {'it': 'Modifica questa descrizione', 'pt': 'Editar esta descrição', 'de': 'Diese Beschreibung bearbeiten', 'nl': 'Deze beschrijving bewerken', 'ca': 'Edita aquesta descripció', 'ro': 'Editați această descriere', 'bg': 'Редактиране на това описание', 'el': 'Επεξεργασία αυτής της περιγραφής', 'ar': 'تعديل هذا الوصف', 'he': 'ערוך תיאור זה', 'id': 'Edit deskripsi ini', 'ja': 'この説明を編集'},
    'Edit this history': {'it': 'Modifica questa storia', 'pt': 'Editar este histórico', 'de': 'Diesen Verlauf bearbeiten', 'nl': 'Deze geschiedenis bewerken', 'ca': 'Edita aquest historial', 'ro': 'Editați acest istoric', 'bg': 'Редактиране на тази история', 'el': 'Επεξεργασία αυτού του ιστορικού', 'ar': 'تعديل هذا السجل التاريخي', 'he': 'ערוך היסטוריה זו', 'id': 'Edit riwayat ini', 'ja': 'この履歴を編集'},
    'Edit this location': {'it': 'Modifica questa posizione', 'pt': 'Editar esta localização', 'de': 'Diesen Standort bearbeiten', 'nl': 'Deze locatie bewerken', 'ca': 'Edita aquesta localització', 'ro': 'Editați această locație', 'bg': 'Редактиране на това местоположение', 'el': 'Επεξεργασία αυτής της τοποθεσίας', 'ar': 'تعديل هذا الموقع', 'he': 'ערוך מיקום זה', 'id': 'Edit lokasi ini', 'ja': 'この場所を編集'},
    'Edit your profile': {'it': 'Modifica il tuo profilo', 'pt': 'Editar o seu perfil', 'de': 'Ihr Profil bearbeiten', 'nl': 'Uw profiel bewerken', 'ca': 'Edita el teu perfil', 'ro': 'Editați-vă profilul', 'bg': 'Редактиране на профила', 'el': 'Επεξεργασία προφίλ σας', 'ar': 'تعديل ملفك الشخصي', 'he': 'ערוך את הפרופיל שלך', 'id': 'Edit profil Anda', 'ja': 'プロフィールを編集'},
    'Editor': {'it': 'Editore', 'pt': 'Editor', 'de': 'Redakteur', 'nl': 'Redacteur', 'ca': 'Editor', 'ro': 'Editor', 'bg': 'Редактор', 'el': 'Συντάκτης', 'ar': 'محرر', 'he': 'עורך', 'id': 'Editor', 'ja': '編集者'},
    'Email': {'it': 'E-mail', 'pt': 'E-mail', 'de': 'E-Mail', 'nl': 'E-mail', 'ca': 'Correu electrònic', 'ro': 'E-mail', 'bg': 'Имейл', 'el': 'Email', 'ar': 'البريد الإلكتروني', 'he': 'דוא"ל', 'id': 'Email', 'ja': 'メール'},
    'Email confirmation': {'it': 'Conferma e-mail', 'pt': 'Confirmação de e-mail', 'de': 'E-Mail-Bestätigung', 'nl': 'E-mailbevestiging', 'ca': 'Confirmació de correu electrònic', 'ro': 'Confirmare e-mail', 'bg': 'Потвърждение на имейл', 'el': 'Επιβεβαίωση email', 'ar': 'تأكيد البريد الإلكتروني', 'he': 'אישור דוא"ל', 'id': 'Konfirmasi email', 'ja': 'メール確認'},
    'English': {'it': 'Inglese', 'pt': 'Inglês', 'de': 'Englisch', 'nl': 'Engels', 'ca': 'Anglès', 'ro': 'Engleză', 'bg': 'Английски', 'el': 'Αγγλικά', 'ar': 'الإنجليزية', 'he': 'אנגלית', 'id': 'Bahasa Inggris', 'ja': '英語'},
    'Entity': {'it': 'Entità', 'pt': 'Entidade', 'de': 'Entität', 'nl': 'Entiteit', 'ca': 'Entitat', 'ro': 'Entitate', 'bg': 'Единица', 'el': 'Οντότητα', 'ar': 'كيان', 'he': 'ישות', 'id': 'Entitas', 'ja': 'エンティティ'},
    'Entity type': {'it': 'Tipo di entità', 'pt': 'Tipo de entidade', 'de': 'Entitätstyp', 'nl': 'Entiteitstype', 'ca': 'Tipus d\'entitat', 'ro': 'Tipul entității', 'bg': 'Тип единица', 'el': 'Τύπος οντότητας', 'ar': 'نوع الكيان', 'he': 'סוג ישות', 'id': 'Jenis entitas', 'ja': 'エンティティタイプ'},
    'Entrance edition': {'it': 'Modifica entrata', 'pt': 'Edição de entrada', 'de': 'Eingang bearbeiten', 'nl': 'Ingang bewerken', 'ca': 'Edició d\'entrada', 'ro': 'Editare intrare', 'bg': 'Редактиране на вход', 'el': 'Επεξεργασία εισόδου', 'ar': 'تحرير المدخل', 'he': 'עריכת כניסה', 'id': 'Edit pintu masuk', 'ja': '入口を編集'},
    'Entrance information': {'it': 'Informazioni sull\'entrata', 'pt': 'Informações da entrada', 'de': 'Eingangsinformationen', 'nl': 'Ingangsinformatie', 'ca': 'Informació de l\'entrada', 'ro': 'Informații despre intrare', 'bg': 'Информация за входа', 'el': 'Πληροφορίες εισόδου', 'ar': 'معلومات المدخل', 'he': 'מידע על הכניסה', 'id': 'Informasi pintu masuk', 'ja': '入口情報'},
    'Entrance name': {'it': 'Nome dell\'entrata', 'pt': 'Nome da entrada', 'de': 'Eingangsname', 'nl': 'Ingangsnaam', 'ca': 'Nom de l\'entrada', 'ro': 'Numele intrării', 'bg': 'Наименование на входа', 'el': 'Όνομα εισόδου', 'ar': 'اسم المدخل', 'he': 'שם הכניסה', 'id': 'Nama pintu masuk', 'ja': '入口名'},
    'Entrance properties': {'it': 'Proprietà dell\'entrata', 'pt': 'Propriedades da entrada', 'de': 'Eingangeigenschaften', 'nl': 'Ingangseigenschappen', 'ca': 'Propietats de l\'entrada', 'ro': 'Proprietățile intrării', 'bg': 'Свойства на входа', 'el': 'Ιδιότητες εισόδου', 'ar': 'خصائص المدخل', 'he': 'מאפייני הכניסה', 'id': 'Properti pintu masuk', 'ja': '入口のプロパティ'},
    'Entrance successfully created!': {'it': 'Entrata creata con successo!', 'pt': 'Entrada criada com sucesso!', 'de': 'Eingang erfolgreich erstellt!', 'nl': 'Ingang succesvol aangemaakt!', 'ca': 'Entrada creada correctament!', 'ro': 'Intrare creată cu succes!', 'bg': 'Входът е създаден успешно!', 'el': 'Η είσοδος δημιουργήθηκε με επιτυχία!', 'ar': 'تم إنشاء المدخل بنجاح!', 'he': 'הכניסה נוצרה בהצלחה!', 'id': 'Pintu masuk berhasil dibuat!', 'ja': '入口が正常に作成されました！'},
    'Entrance successfully updated!': {'it': 'Entrata aggiornata con successo!', 'pt': 'Entrada atualizada com sucesso!', 'de': 'Eingang erfolgreich aktualisiert!', 'nl': 'Ingang succesvol bijgewerkt!', 'ca': 'Entrada actualitzada correctament!', 'ro': 'Intrare actualizată cu succes!', 'bg': 'Входът е актуализиран успешно!', 'el': 'Η είσοδος ενημερώθηκε με επιτυχία!', 'ar': 'تم تحديث المدخل بنجاح!', 'he': 'הכניסה עודכנה בהצלחה!', 'id': 'Pintu masuk berhasil diperbarui!', 'ja': '入口が正常に更新されました！'},
    'Entrances import': {'it': 'Importazione entrate', 'pt': 'Importação de entradas', 'de': 'Eingänge importieren', 'nl': 'Ingangen importeren', 'ca': 'Importació d\'entrades', 'ro': 'Import intrări', 'bg': 'Импорт на входове', 'el': 'Εισαγωγή εισόδων', 'ar': 'استيراد المداخل', 'he': 'ייבוא כניסות', 'id': 'Impor pintu masuk', 'ja': '入口のインポート'},
    'Entrances list': {'it': 'Elenco entrate', 'pt': 'Lista de entradas', 'de': 'Eingangsliste', 'nl': 'Inganglijst', 'ca': 'Llista d\'entrades', 'ro': 'Lista intrărilor', 'bg': 'Списък на входовете', 'el': 'Λίστα εισόδων', 'ar': 'قائمة المداخل', 'he': 'רשימת כניסות', 'id': 'Daftar pintu masuk', 'ja': '入口リスト'},
    'Entry rules': {'it': 'Regole di accesso', 'pt': 'Regras de acesso', 'de': 'Zugangsregeln', 'nl': 'Toegangsregels', 'ca': 'Regles d\'accés', 'ro': 'Reguli de acces', 'bg': 'Правила за достъп', 'el': 'Κανόνες εισόδου', 'ar': 'قواعد الدخول', 'he': 'כללי כניסה', 'id': 'Aturan masuk', 'ja': '入場ルール'},
    # === F ===
    'FAQ': {'it': 'FAQ', 'pt': 'FAQ', 'de': 'FAQ', 'nl': 'FAQ', 'ca': 'FAQ', 'ro': 'FAQ', 'bg': 'ЧЗВ', 'el': 'Συχνές ερωτήσεις', 'ar': 'أسئلة شائعة', 'he': 'שאלות נפוצות', 'id': 'FAQ', 'ja': 'よくある質問'},
    'Filled': {'it': 'Compilato', 'pt': 'Preenchido', 'de': 'Ausgefüllt', 'nl': 'Ingevuld', 'ca': 'Omplert', 'ro': 'Completat', 'bg': 'Попълнен', 'el': 'Συμπληρωμένο', 'ar': 'مملوء', 'he': 'מלא', 'id': 'Terisi', 'ja': '入力済み'},
    'Filter': {'it': 'Filtro', 'pt': 'Filtro', 'de': 'Filter', 'nl': 'Filter', 'ca': 'Filtre', 'ro': 'Filtru', 'bg': 'Филтър', 'el': 'Φίλτρο', 'ar': 'تصفية', 'he': 'סינון', 'id': 'Filter', 'ja': 'フィルター'},
    'Forgotten password': {'it': 'Password dimenticata', 'pt': 'Senha esquecida', 'de': 'Passwort vergessen', 'nl': 'Wachtwoord vergeten', 'ca': 'Contrasenya oblidada', 'ro': 'Parolă uitată', 'bg': 'Забравена парола', 'el': 'Ξεχασμένος κωδικός', 'ar': 'نسيت كلمة المرور', 'he': 'שכחתי סיסמה', 'id': 'Lupa kata sandi', 'ja': 'パスワードを忘れた'},
    'Form': {'it': 'Modulo', 'pt': 'Formulário', 'de': 'Formular', 'nl': 'Formulier', 'ca': 'Formulari', 'ro': 'Formular', 'bg': 'Формуляр', 'el': 'Φόρμα', 'ar': 'نموذج', 'he': 'טופס', 'id': 'Formulir', 'ja': 'フォーム'},
    'French': {'it': 'Francese', 'pt': 'Francês', 'de': 'Französisch', 'nl': 'Frans', 'ca': 'Francès', 'ro': 'Franceză', 'bg': 'Френски', 'el': 'Γαλλικά', 'ar': 'الفرنسية', 'he': 'צרפתית', 'id': 'Bahasa Prancis', 'ja': 'フランス語'},
    # === G ===
    'General information': {'it': 'Informazioni generali', 'pt': 'Informações gerais', 'de': 'Allgemeine Informationen', 'nl': 'Algemene informatie', 'ca': 'Informació general', 'ro': 'Informații generale', 'bg': 'Обща информация', 'el': 'Γενικές πληροφορίες', 'ar': 'معلومات عامة', 'he': 'מידע כללי', 'id': 'Informasi umum', 'ja': '一般情報'},
    'Geospeleology': {'it': 'Geospeleologia', 'pt': 'Geoespeleologia', 'de': 'Geospeleologie', 'nl': 'Geospeleologie', 'ca': 'Geoespeleologia', 'ro': 'Geospeleologie', 'bg': 'Геоспелеология', 'el': 'Γεωσπηλαιολογία', 'ar': 'الجيولوجيا الكهفية', 'he': 'גאוספלאולוגיה', 'id': 'Geospeleologi', 'ja': '地学洞窟学'},
    'German': {'it': 'Tedesco', 'pt': 'Alemão', 'de': 'Deutsch', 'nl': 'Duits', 'ca': 'Alemany', 'ro': 'Germană', 'bg': 'Немски', 'el': 'Γερμανικά', 'ar': 'الألمانية', 'he': 'גרמנית', 'id': 'Bahasa Jerman', 'ja': 'ドイツ語'},
    'Go to my profile': {'it': 'Vai al mio profilo', 'pt': 'Ir para o meu perfil', 'de': 'Zu meinem Profil gehen', 'nl': 'Naar mijn profiel gaan', 'ca': 'Ves al meu perfil', 'ro': 'Mergeți la profilul meu', 'bg': 'Към моя профил', 'el': 'Μεταβείτε στο προφίλ μου', 'ar': 'اذهب إلى ملفي الشخصي', 'he': 'עבור לפרופיל שלי', 'id': 'Pergi ke profil saya', 'ja': '自分のプロフィールへ'},
    # === H ===
    'Heat map': {'it': 'Mappa di calore', 'pt': 'Mapa de calor', 'de': 'Wärmekarte', 'nl': 'Warmtekaart', 'ca': 'Mapa de calor', 'ro': 'Hartă termică', 'bg': 'Топлинна карта', 'el': 'Χάρτης θερμότητας', 'ar': 'خريطة حرارية', 'he': 'מפת חום', 'id': 'Peta panas', 'ja': 'ヒートマップ'},
    'Hide': {'it': 'Nascondi', 'pt': 'Ocultar', 'de': 'Ausblenden', 'nl': 'Verbergen', 'ca': 'Amaga', 'ro': 'Ascundeți', 'bg': 'Скриване', 'el': 'Απόκρυψη', 'ar': 'إخفاء', 'he': 'הסתר', 'id': 'Sembunyikan', 'ja': '非表示'},
    'Hide map': {'it': 'Nascondi mappa', 'pt': 'Ocultar mapa', 'de': 'Karte ausblenden', 'nl': 'Kaart verbergen', 'ca': 'Amaga el mapa', 'ro': 'Ascundeți harta', 'bg': 'Скриване на картата', 'el': 'Απόκρυψη χάρτη', 'ar': 'إخفاء الخريطة', 'he': 'הסתר מפה', 'id': 'Sembunyikan peta', 'ja': '地図を隠す'},
    'History': {'it': 'Storia', 'pt': 'Histórico', 'de': 'Geschichte', 'nl': 'Geschiedenis', 'ca': 'Historial', 'ro': 'Istoric', 'bg': 'История', 'el': 'Ιστορικό', 'ar': 'السجل التاريخي', 'he': 'היסטוריה', 'id': 'Riwayat', 'ja': '履歴'},
    # === I ===
    'Import': {'it': 'Importa', 'pt': 'Importar', 'de': 'Importieren', 'nl': 'Importeren', 'ca': 'Importa', 'ro': 'Importați', 'bg': 'Импортиране', 'el': 'Εισαγωγή', 'ar': 'استيراد', 'he': 'ייבוא', 'id': 'Impor', 'ja': 'インポート'},
    'Import results': {'it': 'Risultati importazione', 'pt': 'Resultados de importação', 'de': 'Importergebnisse', 'nl': 'Importresultaten', 'ca': 'Resultats d\'importació', 'ro': 'Rezultate import', 'bg': 'Резултати от импорта', 'el': 'Αποτελέσματα εισαγωγής', 'ar': 'نتائج الاستيراد', 'he': 'תוצאות ייבוא', 'id': 'Hasil impor', 'ja': 'インポート結果'},
    'Indonesian': {'it': 'Indonesiano', 'pt': 'Indonésio', 'de': 'Indonesisch', 'nl': 'Indonesisch', 'ca': 'Indonesi', 'ro': 'Indoneziană', 'bg': 'Индонезийски', 'el': 'Ινδονησιακά', 'ar': 'الإندونيسية', 'he': 'אינדונזית', 'id': 'Bahasa Indonesia', 'ja': 'インドネシア語'},
    'Information': {'it': 'Informazioni', 'pt': 'Informações', 'de': 'Informationen', 'nl': 'Informatie', 'ca': 'Informació', 'ro': 'Informații', 'bg': 'Информация', 'el': 'Πληροφορίες', 'ar': 'معلومات', 'he': 'מידע', 'id': 'Informasi', 'ja': '情報'},
    'Invalid date': {'it': 'Data non valida', 'pt': 'Data inválida', 'de': 'Ungültiges Datum', 'nl': 'Ongeldige datum', 'ca': 'Data no vàlida', 'ro': 'Dată invalidă', 'bg': 'Невалидна дата', 'el': 'Μη έγκυρη ημερομηνία', 'ar': 'تاريخ غير صالح', 'he': 'תאריך לא חוקי', 'id': 'Tanggal tidak valid', 'ja': '無効な日付'},
    'Invalid email': {'it': 'E-mail non valida', 'pt': 'E-mail inválido', 'de': 'Ungültige E-Mail', 'nl': 'Ongeldig e-mailadres', 'ca': 'Correu electrònic no vàlid', 'ro': 'E-mail invalid', 'bg': 'Невалиден имейл', 'el': 'Μη έγκυρο email', 'ar': 'بريد إلكتروني غير صالح', 'he': 'דוא"ל לא חוקי', 'id': 'Email tidak valid', 'ja': '無効なメールアドレス'},
    'Italian': {'it': 'Italiano', 'pt': 'Italiano', 'de': 'Italienisch', 'nl': 'Italiaans', 'ca': 'Italià', 'ro': 'Italiană', 'bg': 'Италиански', 'el': 'Ιταλικά', 'ar': 'الإيطالية', 'he': 'איטלקית', 'id': 'Bahasa Italia', 'ja': 'イタリア語'},
    # === J/K/L ===
    'Japanese': {'it': 'Giapponese', 'pt': 'Japonês', 'de': 'Japanisch', 'nl': 'Japans', 'ca': 'Japonès', 'ro': 'Japoneză', 'bg': 'Японски', 'el': 'Ιαπωνικά', 'ar': 'اليابانية', 'he': 'יפנית', 'id': 'Bahasa Jepang', 'ja': '日本語'},
    'Language': {'it': 'Lingua', 'pt': 'Idioma', 'de': 'Sprache', 'nl': 'Taal', 'ca': 'Idioma', 'ro': 'Limbă', 'bg': 'Език', 'el': 'Γλώσσα', 'ar': 'اللغة', 'he': 'שפה', 'id': 'Bahasa', 'ja': '言語'},
    'Last modification': {'it': 'Ultima modifica', 'pt': 'Última modificação', 'de': 'Letzte Änderung', 'nl': 'Laatste wijziging', 'ca': 'Última modificació', 'ro': 'Ultima modificare', 'bg': 'Последна промяна', 'el': 'Τελευταία τροποποίηση', 'ar': 'آخر تعديل', 'he': 'שינוי אחרון', 'id': 'Modifikasi terakhir', 'ja': '最終変更'},
    'License': {'it': 'Licenza', 'pt': 'Licença', 'de': 'Lizenz', 'nl': 'Licentie', 'ca': 'Llicència', 'ro': 'Licență', 'bg': 'Лиценз', 'el': 'Άδεια', 'ar': 'رخصة', 'he': 'רישיון', 'id': 'Lisensi', 'ja': 'ライセンス'},
    'Link': {'it': 'Collegamento', 'pt': 'Ligação', 'de': 'Link', 'nl': 'Link', 'ca': 'Enllaç', 'ro': 'Legătură', 'bg': 'Връзка', 'el': 'Σύνδεσμος', 'ar': 'رابط', 'he': 'קישור', 'id': 'Tautan', 'ja': 'リンク'},
    'List': {'it': 'Elenco', 'pt': 'Lista', 'de': 'Liste', 'nl': 'Lijst', 'ca': 'Llista', 'ro': 'Listă', 'bg': 'Списък', 'el': 'Λίστα', 'ar': 'قائمة', 'he': 'רשימה', 'id': 'Daftar', 'ja': 'リスト'},
    'Loading': {'it': 'Caricamento', 'pt': 'A carregar', 'de': 'Laden', 'nl': 'Laden', 'ca': 'Carregant', 'ro': 'Încărcare', 'bg': 'Зареждане', 'el': 'Φόρτωση', 'ar': 'جاري التحميل', 'he': 'טוען', 'id': 'Memuat', 'ja': '読み込み中'},
    'Location': {'it': 'Posizione', 'pt': 'Localização', 'de': 'Standort', 'nl': 'Locatie', 'ca': 'Localització', 'ro': 'Locație', 'bg': 'Местоположение', 'el': 'Τοποθεσία', 'ar': 'الموقع', 'he': 'מיקום', 'id': 'Lokasi', 'ja': '場所'},
    'Login': {'it': 'Accedi', 'pt': 'Entrar', 'de': 'Anmelden', 'nl': 'Inloggen', 'ca': 'Inicia sessió', 'ro': 'Autentificați-vă', 'bg': 'Влизане', 'el': 'Σύνδεση', 'ar': 'تسجيل الدخول', 'he': 'כניסה', 'id': 'Masuk', 'ja': 'ログイン'},
    'Logout': {'it': 'Disconnetti', 'pt': 'Sair', 'de': 'Abmelden', 'nl': 'Uitloggen', 'ca': 'Tanca sessió', 'ro': 'Deconectați-vă', 'bg': 'Излизане', 'el': 'Αποσύνδεση', 'ar': 'تسجيل الخروج', 'he': 'יציאה', 'id': 'Keluar', 'ja': 'ログアウト'},
    # === M ===
    'Map': {'it': 'Mappa', 'pt': 'Mapa', 'de': 'Karte', 'nl': 'Kaart', 'ca': 'Mapa', 'ro': 'Hartă', 'bg': 'Карта', 'el': 'Χάρτης', 'ar': 'خريطة', 'he': 'מפה', 'id': 'Peta', 'ja': '地図'},
    'Map view': {'it': 'Vista mappa', 'pt': 'Vista de mapa', 'de': 'Kartenansicht', 'nl': 'Kaartweergave', 'ca': 'Vista de mapa', 'ro': 'Vedere hartă', 'bg': 'Изглед на карта', 'el': 'Προβολή χάρτη', 'ar': 'عرض الخريطة', 'he': 'תצוגת מפה', 'id': 'Tampilan peta', 'ja': 'マップビュー'},
    'Massif edition': {'it': 'Modifica massiccio', 'pt': 'Edição de maciço', 'de': 'Massiv bearbeiten', 'nl': 'Massief bewerken', 'ca': 'Edició de massís', 'ro': 'Editare masiv', 'bg': 'Редактиране на масив', 'el': 'Επεξεργασία μαζικής περιοχής', 'ar': 'تحرير الكتلة الجبلية', 'he': 'עריכת מסיב', 'id': 'Edit massif', 'ja': 'マシフを編集'},
    'Massif information': {'it': 'Informazioni sul massiccio', 'pt': 'Informações do maciço', 'de': 'Massivinformationen', 'nl': 'Massierinformatie', 'ca': 'Informació del massís', 'ro': 'Informații despre masiv', 'bg': 'Информация за масива', 'el': 'Πληροφορίες μαζικής περιοχής', 'ar': 'معلومات الكتلة الجبلية', 'he': 'מידע על מסיב', 'id': 'Informasi massif', 'ja': 'マシフ情報'},
    'Massif successfully created!': {'it': 'Massiccio creato con successo!', 'pt': 'Maciço criado com sucesso!', 'de': 'Massiv erfolgreich erstellt!', 'nl': 'Massief succesvol aangemaakt!', 'ca': 'Massís creat correctament!', 'ro': 'Masiv creat cu succes!', 'bg': 'Масивът е създаден успешно!', 'el': 'Η μαζική περιοχή δημιουργήθηκε με επιτυχία!', 'ar': 'تم إنشاء الكتلة الجبلية بنجاح!', 'he': 'המסיב נוצר בהצלחה!', 'id': 'Massif berhasil dibuat!', 'ja': 'マシフが正常に作成されました！'},
    'Massif successfully updated!': {'it': 'Massiccio aggiornato con successo!', 'pt': 'Maciço atualizado com sucesso!', 'de': 'Massiv erfolgreich aktualisiert!', 'nl': 'Massief succesvol bijgewerkt!', 'ca': 'Massís actualitzat correctament!', 'ro': 'Masiv actualizat cu succes!', 'bg': 'Масивът е актуализиран успешно!', 'el': 'Η μαζική περιοχή ενημερώθηκε με επιτυχία!', 'ar': 'تم تحديث الكتلة الجبلية بنجاح!', 'he': 'המסיב עודכן בהצלחה!', 'id': 'Massif berhasil diperbarui!', 'ja': 'マシフが正常に更新されました！'},
    'Moderator': {'it': 'Moderatore', 'pt': 'Moderador', 'de': 'Moderator', 'nl': 'Moderator', 'ca': 'Moderador', 'ro': 'Moderator', 'bg': 'Модератор', 'el': 'Συντονιστής', 'ar': 'مشرف', 'he': 'מנחה', 'id': 'Moderator', 'ja': 'モデレーター'},
    # === N ===
    'Name': {'it': 'Nome', 'pt': 'Nome', 'de': 'Name', 'nl': 'Naam', 'ca': 'Nom', 'ro': 'Nume', 'bg': 'Име', 'el': 'Όνομα', 'ar': 'الاسم', 'he': 'שם', 'id': 'Nama', 'ja': '名前'},
    'Network': {'it': 'Rete', 'pt': 'Rede', 'de': 'Netzwerk', 'nl': 'Netwerk', 'ca': 'Xarxa', 'ro': 'Rețea', 'bg': 'Мрежа', 'el': 'Δίκτυο', 'ar': 'شبكة', 'he': 'רשת', 'id': 'Jaringan', 'ja': 'ネットワーク'},
    'Network edition': {'it': 'Modifica rete', 'pt': 'Edição de rede', 'de': 'Netzwerk bearbeiten', 'nl': 'Netwerk bewerken', 'ca': 'Edició de xarxa', 'ro': 'Editare rețea', 'bg': 'Редактиране на мрежа', 'el': 'Επεξεργασία δικτύου', 'ar': 'تحرير الشبكة', 'he': 'עריכת רשת', 'id': 'Edit jaringan', 'ja': 'ネットワークを編集'},
    'Network information': {'it': 'Informazioni sulla rete', 'pt': 'Informações da rede', 'de': 'Netzwerkinformationen', 'nl': 'Netwerkinformatie', 'ca': 'Informació de la xarxa', 'ro': 'Informații despre rețea', 'bg': 'Информация за мрежата', 'el': 'Πληροφορίες δικτύου', 'ar': 'معلومات الشبكة', 'he': 'מידע על הרשת', 'id': 'Informasi jaringan', 'ja': 'ネットワーク情報'},
    'Network successfully created!': {'it': 'Rete creata con successo!', 'pt': 'Rede criada com sucesso!', 'de': 'Netzwerk erfolgreich erstellt!', 'nl': 'Netwerk succesvol aangemaakt!', 'ca': 'Xarxa creada correctament!', 'ro': 'Rețea creată cu succes!', 'bg': 'Мрежата е създадена успешно!', 'el': 'Το δίκτυο δημιουργήθηκε με επιτυχία!', 'ar': 'تم إنشاء الشبكة بنجاح!', 'he': 'הרשת נוצרה בהצלחה!', 'id': 'Jaringan berhasil dibuat!', 'ja': 'ネットワークが正常に作成されました！'},
    'Network successfully updated!': {'it': 'Rete aggiornata con successo!', 'pt': 'Rede atualizada com sucesso!', 'de': 'Netzwerk erfolgreich aktualisiert!', 'nl': 'Netwerk succesvol bijgewerkt!', 'ca': 'Xarxa actualitzada correctament!', 'ro': 'Rețea actualizată cu succes!', 'bg': 'Мрежата е актуализирана успешно!', 'el': 'Το δίκτυο ενημερώθηκε με επιτυχία!', 'ar': 'تم تحديث الشبكة بنجاح!', 'he': 'הרשת עודכנה בהצלחה!', 'id': 'Jaringan berhasil diperbarui!', 'ja': 'ネットワークが正常に更新されました！'},
    'New': {'it': 'Nuovo', 'pt': 'Novo', 'de': 'Neu', 'nl': 'Nieuw', 'ca': 'Nou', 'ro': 'Nou', 'bg': 'Нов', 'el': 'Νέο', 'ar': 'جديد', 'he': 'חדש', 'id': 'Baru', 'ja': '新規'},
    'Next': {'it': 'Avanti', 'pt': 'Seguinte', 'de': 'Weiter', 'nl': 'Volgende', 'ca': 'Següent', 'ro': 'Următor', 'bg': 'Следващ', 'el': 'Επόμενο', 'ar': 'التالي', 'he': 'הבא', 'id': 'Berikutnya', 'ja': '次へ'},
    'No': {'it': 'No', 'pt': 'Não', 'de': 'Nein', 'nl': 'Nee', 'ca': 'No', 'ro': 'Nu', 'bg': 'Не', 'el': 'Όχι', 'ar': 'لا', 'he': 'לא', 'id': 'Tidak', 'ja': 'いいえ'},
    'No data available': {'it': 'Nessun dato disponibile', 'pt': 'Sem dados disponíveis', 'de': 'Keine Daten verfügbar', 'nl': 'Geen gegevens beschikbaar', 'ca': 'No hi ha dades disponibles', 'ro': 'Nu sunt date disponibile', 'bg': 'Няма налични данни', 'el': 'Δεν υπάρχουν διαθέσιμα δεδομένα', 'ar': 'لا توجد بيانات متاحة', 'he': 'אין נתונים זמינים', 'id': 'Tidak ada data tersedia', 'ja': 'データがありません'},
    # === O ===
    'Optional': {'it': 'Opzionale', 'pt': 'Opcional', 'de': 'Optional', 'nl': 'Optioneel', 'ca': 'Opcional', 'ro': 'Opțional', 'bg': 'По избор', 'el': 'Προαιρετικό', 'ar': 'اختياري', 'he': 'אופציונלי', 'id': 'Opsional', 'ja': 'オプション'},
    'Organization': {'it': 'Organizzazione', 'pt': 'Organização', 'de': 'Organisation', 'nl': 'Organisatie', 'ca': 'Organització', 'ro': 'Organizație', 'bg': 'Организация', 'el': 'Οργανισμός', 'ar': 'منظمة', 'he': 'ארגון', 'id': 'Organisasi', 'ja': '組織'},
    'Organization edition': {'it': 'Modifica organizzazione', 'pt': 'Edição de organização', 'de': 'Organisation bearbeiten', 'nl': 'Organisatie bewerken', 'ca': 'Edició d\'organització', 'ro': 'Editare organizație', 'bg': 'Редактиране на организация', 'el': 'Επεξεργασία οργανισμού', 'ar': 'تحرير المنظمة', 'he': 'עריכת ארגון', 'id': 'Edit organisasi', 'ja': '組織を編集'},
    'Organization information': {'it': 'Informazioni sull\'organizzazione', 'pt': 'Informações da organização', 'de': 'Organisationsinformationen', 'nl': 'Organisatie-informatie', 'ca': 'Informació de l\'organització', 'ro': 'Informații despre organizație', 'bg': 'Информация за организацията', 'el': 'Πληροφορίες οργανισμού', 'ar': 'معلومات المنظمة', 'he': 'מידע על הארגון', 'id': 'Informasi organisasi', 'ja': '組織情報'},
    'Organization successfully created!': {'it': 'Organizzazione creata con successo!', 'pt': 'Organização criada com sucesso!', 'de': 'Organisation erfolgreich erstellt!', 'nl': 'Organisatie succesvol aangemaakt!', 'ca': 'Organització creada correctament!', 'ro': 'Organizație creată cu succes!', 'bg': 'Организацията е създадена успешно!', 'el': 'Ο οργανισμός δημιουργήθηκε με επιτυχία!', 'ar': 'تم إنشاء المنظمة بنجاح!', 'he': 'הארגון נוצר בהצלחה!', 'id': 'Organisasi berhasil dibuat!', 'ja': '組織が正常に作成されました！'},
    'Organization successfully updated!': {'it': 'Organizzazione aggiornata con successo!', 'pt': 'Organização atualizada com sucesso!', 'de': 'Organisation erfolgreich aktualisiert!', 'nl': 'Organisatie succesvol bijgewerkt!', 'ca': 'Organització actualitzada correctament!', 'ro': 'Organizație actualizată cu succes!', 'bg': 'Организацията е актуализирана успешно!', 'el': 'Ο οργανισμός ενημερώθηκε με επιτυχία!', 'ar': 'تم تحديث المنظمة بنجاح!', 'he': 'הארגון עודכן בהצלחה!', 'id': 'Organisasi berhasil diperbarui!', 'ja': '組織が正常に更新されました！'},
    # === P ===
    'Password': {'it': 'Password', 'pt': 'Senha', 'de': 'Passwort', 'nl': 'Wachtwoord', 'ca': 'Contrasenya', 'ro': 'Parolă', 'bg': 'Парола', 'el': 'Κωδικός πρόσβασης', 'ar': 'كلمة المرور', 'he': 'סיסמה', 'id': 'Kata sandi', 'ja': 'パスワード'},
    'Person': {'it': 'Persona', 'pt': 'Pessoa', 'de': 'Person', 'nl': 'Persoon', 'ca': 'Persona', 'ro': 'Persoană', 'bg': 'Лице', 'el': 'Πρόσωπο', 'ar': 'شخص', 'he': 'אדם', 'id': 'Orang', 'ja': '人物'},
    'Preview': {'it': 'Anteprima', 'pt': 'Pré-visualização', 'de': 'Vorschau', 'nl': 'Voorbeeld', 'ca': 'Vista prèvia', 'ro': 'Previzualizare', 'bg': 'Предварителен преглед', 'el': 'Προεπισκόπηση', 'ar': 'معاينة', 'he': 'תצוגה מקדימה', 'id': 'Pratinjau', 'ja': 'プレビュー'},
    'Previous': {'it': 'Precedente', 'pt': 'Anterior', 'de': 'Zurück', 'nl': 'Vorige', 'ca': 'Anterior', 'ro': 'Anterior', 'bg': 'Предишен', 'el': 'Προηγούμενο', 'ar': 'السابق', 'he': 'הקודם', 'id': 'Sebelumnya', 'ja': '前へ'},
    'Profile': {'it': 'Profilo', 'pt': 'Perfil', 'de': 'Profil', 'nl': 'Profiel', 'ca': 'Perfil', 'ro': 'Profil', 'bg': 'Профил', 'el': 'Προφίλ', 'ar': 'الملف الشخصي', 'he': 'פרופיל', 'id': 'Profil', 'ja': 'プロフィール'},
    # === R ===
    'Rating': {'it': 'Valutazione', 'pt': 'Classificação', 'de': 'Bewertung', 'nl': 'Beoordeling', 'ca': 'Valoració', 'ro': 'Rating', 'bg': 'Оценка', 'el': 'Βαθμολογία', 'ar': 'تقييم', 'he': 'דירוג', 'id': 'Penilaian', 'ja': '評価'},
    'Register': {'it': 'Registrati', 'pt': 'Registar', 'de': 'Registrieren', 'nl': 'Registreren', 'ca': 'Registra\'t', 'ro': 'Înregistrați-vă', 'bg': 'Регистрация', 'el': 'Εγγραφή', 'ar': 'تسجيل', 'he': 'הירשם', 'id': 'Daftar', 'ja': '登録'},
    'Required': {'it': 'Obbligatorio', 'pt': 'Obrigatório', 'de': 'Erforderlich', 'nl': 'Verplicht', 'ca': 'Obligatori', 'ro': 'Obligatoriu', 'bg': 'Задължително', 'el': 'Απαιτείται', 'ar': 'مطلوب', 'he': 'נדרש', 'id': 'Wajib', 'ja': '必須'},
    'Reset password': {'it': 'Reimposta password', 'pt': 'Redefinir senha', 'de': 'Passwort zurücksetzen', 'nl': 'Wachtwoord opnieuw instellen', 'ca': 'Restableix la contrasenya', 'ro': 'Resetați parola', 'bg': 'Нулиране на паролата', 'el': 'Επαναφορά κωδικού', 'ar': 'إعادة تعيين كلمة المرور', 'he': 'איפוס סיסמה', 'id': 'Setel ulang kata sandi', 'ja': 'パスワードをリセット'},
    'Revision': {'it': 'Revisione', 'pt': 'Revisão', 'de': 'Revision', 'nl': 'Revisie', 'ca': 'Revisió', 'ro': 'Revizuire', 'bg': 'Ревизия', 'el': 'Αναθεώρηση', 'ar': 'مراجعة', 'he': 'גרסה', 'id': 'Revisi', 'ja': '改訂'},
    'Revisions': {'it': 'Revisioni', 'pt': 'Revisões', 'de': 'Revisionen', 'nl': 'Revisies', 'ca': 'Revisions', 'ro': 'Revizuiri', 'bg': 'Ревизии', 'el': 'Αναθεωρήσεις', 'ar': 'المراجعات', 'he': 'גרסאות', 'id': 'Revisi', 'ja': '改訂版'},
    # === S ===
    'Save': {'it': 'Salva', 'pt': 'Guardar', 'de': 'Speichern', 'nl': 'Opslaan', 'ca': 'Desa', 'ro': 'Salvați', 'bg': 'Запазване', 'el': 'Αποθήκευση', 'ar': 'حفظ', 'he': 'שמור', 'id': 'Simpan', 'ja': '保存'},
    'Search': {'it': 'Cerca', 'pt': 'Pesquisar', 'de': 'Suchen', 'nl': 'Zoeken', 'ca': 'Cerca', 'ro': 'Căutare', 'bg': 'Търсене', 'el': 'Αναζήτηση', 'ar': 'بحث', 'he': 'חיפוש', 'id': 'Cari', 'ja': '検索'},
    'Select': {'it': 'Seleziona', 'pt': 'Selecionar', 'de': 'Auswählen', 'nl': 'Selecteer', 'ca': 'Selecciona', 'ro': 'Selectați', 'bg': 'Изберете', 'el': 'Επιλέξτε', 'ar': 'اختر', 'he': 'בחר', 'id': 'Pilih', 'ja': '選択'},
    'Settings': {'it': 'Impostazioni', 'pt': 'Configurações', 'de': 'Einstellungen', 'nl': 'Instellingen', 'ca': 'Configuració', 'ro': 'Setări', 'bg': 'Настройки', 'el': 'Ρυθμίσεις', 'ar': 'الإعدادات', 'he': 'הגדרות', 'id': 'Pengaturan', 'ja': '設定'},
    'Show': {'it': 'Mostra', 'pt': 'Mostrar', 'de': 'Anzeigen', 'nl': 'Tonen', 'ca': 'Mostra', 'ro': 'Afișați', 'bg': 'Показване', 'el': 'Εμφάνιση', 'ar': 'عرض', 'he': 'הצג', 'id': 'Tampilkan', 'ja': '表示'},
    'Show map': {'it': 'Mostra mappa', 'pt': 'Mostrar mapa', 'de': 'Karte anzeigen', 'nl': 'Kaart tonen', 'ca': 'Mostra el mapa', 'ro': 'Afișați harta', 'bg': 'Показване на картата', 'el': 'Εμφάνιση χάρτη', 'ar': 'إظهار الخريطة', 'he': 'הצג מפה', 'id': 'Tampilkan peta', 'ja': '地図を表示'},
    'Sign in': {'it': 'Accedi', 'pt': 'Entrar', 'de': 'Anmelden', 'nl': 'Inloggen', 'ca': 'Inicia sessió', 'ro': 'Autentificați-vă', 'bg': 'Вход', 'el': 'Σύνδεση', 'ar': 'تسجيل الدخول', 'he': 'התחבר', 'id': 'Masuk', 'ja': 'サインイン'},
    'Sign up': {'it': 'Registrati', 'pt': 'Registar', 'de': 'Registrieren', 'nl': 'Aanmelden', 'ca': 'Registra\'t', 'ro': 'Înregistrați-vă', 'bg': 'Регистрация', 'el': 'Εγγραφή', 'ar': 'إنشاء حساب', 'he': 'הירשם', 'id': 'Daftar', 'ja': 'サインアップ'},
    'Spanish': {'it': 'Spagnolo', 'pt': 'Espanhol', 'de': 'Spanisch', 'nl': 'Spaans', 'ca': 'Espanyol', 'ro': 'Spaniolă', 'bg': 'Испански', 'el': 'Ισπανικά', 'ar': 'الإسبانية', 'he': 'ספרדית', 'id': 'Bahasa Spanyol', 'ja': 'スペイン語'},
    'Statistics': {'it': 'Statistiche', 'pt': 'Estatísticas', 'de': 'Statistiken', 'nl': 'Statistieken', 'ca': 'Estadístiques', 'ro': 'Statistici', 'bg': 'Статистики', 'el': 'Στατιστικά', 'ar': 'إحصائيات', 'he': 'סטטיסטיקות', 'id': 'Statistik', 'ja': '統計'},
    'Submit': {'it': 'Invia', 'pt': 'Enviar', 'de': 'Absenden', 'nl': 'Verzenden', 'ca': 'Envia', 'ro': 'Trimiteți', 'bg': 'Изпращане', 'el': 'Υποβολή', 'ar': 'إرسال', 'he': 'שלח', 'id': 'Kirim', 'ja': '送信'},
    'Subscribe': {'it': 'Iscriviti', 'pt': 'Subscrever', 'de': 'Abonnieren', 'nl': 'Abonneren', 'ca': 'Subscriu-te', 'ro': 'Abonați-vă', 'bg': 'Абониране', 'el': 'Εγγραφή', 'ar': 'اشتراك', 'he': 'הירשם', 'id': 'Berlangganan', 'ja': '購読'},
    # === T ===
    'Table view': {'it': 'Vista tabella', 'pt': 'Vista de tabela', 'de': 'Tabellenansicht', 'nl': 'Tabelweergave', 'ca': 'Vista de taula', 'ro': 'Vedere tabel', 'bg': 'Изглед на таблица', 'el': 'Προβολή πίνακα', 'ar': 'عرض الجدول', 'he': 'תצוגת טבלה', 'id': 'Tampilan tabel', 'ja': 'テーブルビュー'},
    'Title': {'it': 'Titolo', 'pt': 'Título', 'de': 'Titel', 'nl': 'Titel', 'ca': 'Títol', 'ro': 'Titlu', 'bg': 'Заглавие', 'el': 'Τίτλος', 'ar': 'العنوان', 'he': 'כותרת', 'id': 'Judul', 'ja': 'タイトル'},
    # === U ===
    'Unsubscribe': {'it': 'Annulla iscrizione', 'pt': 'Cancelar subscrição', 'de': 'Abonnement kündigen', 'nl': 'Afmelden', 'ca': 'Cancella la subscripció', 'ro': 'Dezabonați-vă', 'bg': 'Отписване', 'el': 'Κατάργηση εγγραφής', 'ar': 'إلغاء الاشتراك', 'he': 'בטל מנוי', 'id': 'Berhenti berlangganan', 'ja': '購読解除'},
    'Update': {'it': 'Aggiorna', 'pt': 'Atualizar', 'de': 'Aktualisieren', 'nl': 'Bijwerken', 'ca': 'Actualitza', 'ro': 'Actualizați', 'bg': 'Актуализиране', 'el': 'Ενημέρωση', 'ar': 'تحديث', 'he': 'עדכן', 'id': 'Perbarui', 'ja': '更新'},
    'User': {'it': 'Utente', 'pt': 'Utilizador', 'de': 'Benutzer', 'nl': 'Gebruiker', 'ca': 'Usuari', 'ro': 'Utilizator', 'bg': 'Потребител', 'el': 'Χρήστης', 'ar': 'مستخدم', 'he': 'משתמש', 'id': 'Pengguna', 'ja': 'ユーザー'},
    'User profile': {'it': 'Profilo utente', 'pt': 'Perfil do utilizador', 'de': 'Benutzerprofil', 'nl': 'Gebruikersprofiel', 'ca': 'Perfil d\'usuari', 'ro': 'Profilul utilizatorului', 'bg': 'Потребителски профил', 'el': 'Προφίλ χρήστη', 'ar': 'ملف المستخدم', 'he': 'פרופיל משתמש', 'id': 'Profil pengguna', 'ja': 'ユーザープロフィール'},
    # === V ===
    'Validate': {'it': 'Valida', 'pt': 'Validar', 'de': 'Validieren', 'nl': 'Valideren', 'ca': 'Valida', 'ro': 'Validați', 'bg': 'Потвърдете', 'el': 'Επικύρωση', 'ar': 'تحقق', 'he': 'אמת', 'id': 'Validasi', 'ja': '検証'},
    'Validation': {'it': 'Validazione', 'pt': 'Validação', 'de': 'Validierung', 'nl': 'Validatie', 'ca': 'Validació', 'ro': 'Validare', 'bg': 'Потвърждение', 'el': 'Επικύρωση', 'ar': 'التحقق', 'he': 'אימות', 'id': 'Validasi', 'ja': '検証'},
    'Version': {'it': 'Versione', 'pt': 'Versão', 'de': 'Version', 'nl': 'Versie', 'ca': 'Versió', 'ro': 'Versiune', 'bg': 'Версия', 'el': 'Έκδοση', 'ar': 'الإصدار', 'he': 'גרסה', 'id': 'Versi', 'ja': 'バージョン'},
    # === W/Y ===
    'Warning': {'it': 'Avviso', 'pt': 'Aviso', 'de': 'Warnung', 'nl': 'Waarschuwing', 'ca': 'Avís', 'ro': 'Avertisment', 'bg': 'Предупреждение', 'el': 'Προειδοποίηση', 'ar': 'تحذير', 'he': 'אזהרה', 'id': 'Peringatan', 'ja': '警告'},
    'Yes': {'it': 'Sì', 'pt': 'Sim', 'de': 'Ja', 'nl': 'Ja', 'ca': 'Sí', 'ro': 'Da', 'bg': 'Да', 'el': 'Ναι', 'ar': 'نعم', 'he': 'כן', 'id': 'Ya', 'ja': 'はい'},
    # === BBS classification codes ===
    '1.0': {'it': 'Geospeleologia e carsologia', 'pt': 'Geoespeleologia e carstologia', 'de': 'Geospeleologie und Karstologie', 'nl': 'Geospeleologie en karstologie', 'ca': 'Geoespeleologia i carstologia', 'ro': 'Geospeleologie și carstologie', 'bg': 'Геоспелеология и карстология', 'el': 'Γεωσπηλαιολογία και καρστολογία', 'ar': 'الجيولوجيا الكهفية والكارستولوجيا', 'he': 'גאוספלאולוגיה וקרסטולוגיה', 'id': 'Geospeleologi dan Karstologi', 'ja': '地学洞窟学とカルスト学'},
    '2.0': {'it': 'Speleologia regionale', 'pt': 'Espeleologia regional', 'de': 'Regionale Höhlenkunde', 'nl': 'Regionale speleologie', 'ca': 'Espeleologia regional', 'ro': 'Speleologie regională', 'bg': 'Регионална спелеология', 'el': 'Περιφερειακή σπηλαιολογία', 'ar': 'علم الكهوف الإقليمي', 'he': 'ספלאולוגיה אזורית', 'id': 'Speleologi regional', 'ja': '地域洞窟学'},
    '3.0': {'it': 'Biospeleologia', 'pt': 'Bioespeleologia', 'de': 'Biospeleologie', 'nl': 'Biospeleologie', 'ca': 'Bioespeleologia', 'ro': 'Biospeleologie', 'bg': 'Биоспелеология', 'el': 'Βιοσπηλαιολογία', 'ar': 'علم الأحياء الكهفي', 'he': 'ביוספלאולוגיה', 'id': 'Biospeleologi', 'ja': '生物洞窟学'},
    '4.0': {'it': 'Antropospeleologia', 'pt': 'Antropoespeleologia', 'de': 'Anthropospeleologie', 'nl': 'Antropospeleologie', 'ca': 'Antropoespeleologia', 'ro': 'Antropospeleologie', 'bg': 'Антропоспелеология', 'el': 'Ανθρωπολογική σπηλαιολογία', 'ar': 'الأنثروبولوجيا الكهفية', 'he': 'אנתרופוספלאולוגיה', 'id': 'Antropospeleologi', 'ja': '人類洞窟学'},
    '5.0': {'it': 'Paleontospeleologia', 'pt': 'Paleontospeleologia', 'de': 'Paläontospeleologie', 'nl': 'Paleontospeleologie', 'ca': 'Paleontospeleologia', 'ro': 'Paleontospeleologie', 'bg': 'Палеонтоспелеология', 'el': 'Παλαιοντολογική σπηλαιολογία', 'ar': 'علم الأحياء الكهفي القديم', 'he': 'פאלאונטוספלאולוגיה', 'id': 'Paleontospeleologi', 'ja': '古生物洞窟学'},
    '6.0': {'it': 'Speleologia applicata', 'pt': 'Espeleologia aplicada', 'de': 'Angewandte Höhlenkunde', 'nl': 'Toegepaste speleologie', 'ca': 'Espeleologia aplicada', 'ro': 'Speleologie aplicată', 'bg': 'Приложна спелеология', 'el': 'Εφαρμοσμένη σπηλαιολογία', 'ar': 'علم الكهوف التطبيقي', 'he': 'ספלאולוגיה יישומית', 'id': 'Speleologi terapan', 'ja': '応用洞窟学'},
    '7.0': {'it': 'Speleologia sportiva', 'pt': 'Espeleologia desportiva', 'de': 'Sport-Höhlenkunde', 'nl': 'Sport speleologie', 'ca': 'Espeleologia esportiva', 'ro': 'Speleologie sportivă', 'bg': 'Спортна спелеология', 'el': 'Αθλητική σπηλαιολογία', 'ar': 'علم الكهوف الرياضي', 'he': 'ספלאולוגיה ספורטיבית', 'id': 'Speleologi olahraga', 'ja': 'スポーツ洞窟学'},
    '8.0': {'it': 'Documentazione e insegnamento', 'pt': 'Documentação e ensino', 'de': 'Dokumentation und Lehre', 'nl': 'Documentatie en onderwijs', 'ca': 'Documentació i ensenyament', 'ro': 'Documentare și predare', 'bg': 'Документация и обучение', 'el': 'Τεκμηρίωση και διδασκαλία', 'ar': 'التوثيق والتدريس', 'he': 'תיעוד והוראה', 'id': 'Dokumentasi dan pengajaran', 'ja': '文書化と教育'},
    '9.0': {'it': 'Supplemento', 'pt': 'Suplemento', 'de': 'Ergänzung', 'nl': 'Supplement', 'ca': 'Suplement', 'ro': 'Supliment', 'bg': 'Добавка', 'el': 'Συμπλήρωμα', 'ar': 'ملحق', 'he': 'תוספת', 'id': 'Suplemen', 'ja': '補足'},
}


def load_json(path):
    with open(path, encoding='utf-8') as f:
        return json.load(f)


def save_json(path, data):
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2, sort_keys=True)
        f.write('\n')


def apply():
    en = load_json(os.path.join(LANG_DIR, 'en.json'))
    total = 0
    langs = ['fr', 'es', 'it', 'pt', 'de', 'nl', 'ca', 'ro', 'bg', 'el', 'ar', 'he', 'id', 'ja']
    for lang in langs:
        path = os.path.join(LANG_DIR, f'{lang}.json')
        data = load_json(path)
        count = 0
        for key, translations in T.items():
            if lang in translations:
                if data.get(key, '') == '' or data.get(key, '') == en.get(key, ''):
                    data[key] = translations[lang]
                    count += 1
        save_json(path, data)
        total += count
        if count:
            print(f'{lang}: +{count}')
    print(f'Total: {total}')


if __name__ == '__main__':
    apply()
