# -*- coding: utf-8 -*-
#!/usr/bin/env python3
"""Part 2: Action buttons, common labels, error messages."""
import json, os

LANG_DIR = os.path.dirname(os.path.abspath(__file__))

T = {
    # === ACTION BUTTONS ===
    'A book': {'it': 'Un libro', 'pt': 'Um livro', 'de': 'Ein Buch', 'nl': 'Een boek', 'ca': 'Un llibre', 'ro': 'O carte', 'bg': 'Книга', 'el': 'Ένα βιβλίο', 'ar': 'كتاب', 'he': 'ספר', 'id': 'Sebuah buku', 'ja': '書籍'},
    'A computer program in source or compiled form': {'it': 'Un programma informatico in forma sorgente o compilata', 'pt': 'Um programa de computador em forma fonte ou compilada', 'de': 'Ein Computerprogramm in Quell- oder kompilierter Form', 'nl': 'Een computerprogramma in bron- of gecompileerde vorm', 'ca': 'Un programa informàtic en forma de font o compilat', 'ro': 'Un program de calculator în formă sursă sau compilată', 'bg': 'Компютърна програма в изходен или компилиран вид', 'el': 'Πρόγραμμα υπολογιστή σε πηγαίο ή μεταγλωττισμένο μορφή', 'ar': 'برنامج حاسوبي في شكل مصدر أو مترجم', 'he': 'תוכנת מחשב בצורת קוד מקור או מקומפלת', 'id': 'Program komputer dalam bentuk sumber atau terkompilasi', 'ja': 'ソースまたはコンパイル済みのコンピュータプログラム'},
    'A geographical map': {'it': 'Una mappa geografica', 'pt': 'Um mapa geográfico', 'de': 'Eine geografische Karte', 'nl': 'Een geografische kaart', 'ca': 'Un mapa geogràfic', 'ro': 'O hartă geografică', 'bg': 'Географска карта', 'el': 'Γεωγραφικός χάρτης', 'ar': 'خريطة جغرافية', 'he': 'מפה גיאוגרפית', 'id': 'Peta geografis', 'ja': '地理地図'},
    'A moderator needs to validate the last modification before being able to edit the document again.': {'it': 'Un moderatore deve convalidare l\'ultima modifica prima di poter modificare nuovamente il documento.', 'pt': 'Um moderador precisa validar a última modificação antes de poder editar o documento novamente.', 'de': 'Ein Moderator muss die letzte Änderung bestätigen, bevor das Dokument erneut bearbeitet werden kann.', 'nl': 'Een moderator moet de laatste wijziging valideren voordat het document opnieuw kan worden bewerkt.', 'ca': 'Un moderador ha de validar la darrera modificació abans de poder tornar a editar el document.', 'ro': 'Un moderator trebuie să valideze ultima modificare înainte de a putea edita din nou documentul.', 'bg': 'Модератор трябва да потвърди последната промяна, преди да може да редактира документа отново.', 'el': 'Ένας συντονιστής πρέπει να επικυρώσει την τελευταία τροποποίηση πριν μπορέσει να επεξεργαστεί ξανά το έγγραφο.', 'ar': 'يحتاج المشرف إلى التحقق من صحة آخر تعديل قبل التمكن من تحرير المستند مرة أخرى.', 'he': 'מנחה צריך לאמת את השינוי האחרון לפני שניתן לערוך את המסמך שוב.', 'id': 'Moderator perlu memvalidasi modifikasi terakhir sebelum dapat mengedit dokumen lagi.', 'ja': 'モデレーターが最後の変更を承認しないと、文書を再度編集できません。'},
    'A non-persistent, time-based occurrence': {'it': 'Un\'occorrenza temporale non persistente', 'pt': 'Uma ocorrência temporal não persistente', 'de': 'Ein nicht dauerhaftes, zeitbasiertes Ereignis', 'nl': 'Een niet-persistent, tijdgebonden gebeurtenis', 'ca': 'Una ocurrència temporal no persistent', 'ro': 'O ocurență temporală nepersistentă', 'bg': 'Непостоянно, времево събитие', 'el': 'Μη μόνιμο, χρονικά βασισμένο γεγονός', 'ar': 'حدث زمني غير دائم', 'he': 'אירוע זמני לא קבוע', 'id': 'Kejadian berbasis waktu yang tidak persisten', 'ja': '一時的な時間ベースの出来事'},
    'A resource consisting primarily of words for reading': {'it': 'Una risorsa consistente principalmente in parole da leggere', 'pt': 'Um recurso composto principalmente de palavras para leitura', 'de': 'Eine Ressource, die hauptsächlich aus Lesewörtern besteht', 'nl': 'Een resource die voornamelijk bestaat uit woorden om te lezen', 'ca': 'Un recurs consistent principalment en paraules per llegir', 'ro': 'O resursă constând în principal din cuvinte de citit', 'bg': 'Ресурс, съставен предимно от думи за четене', 'el': 'Πόρος που αποτελείται κυρίως από λέξεις για ανάγνωση', 'ar': 'مورد يتكون أساساً من كلمات للقراءة', 'he': 'משאב המורכב בעיקר ממילים לקריאה', 'id': 'Sumber yang terdiri terutama dari kata-kata untuk dibaca', 'ja': '主に読むための文字で構成されたリソース'},
    'A resource primarily intended to be heard': {'it': 'Una risorsa principalmente destinata all\'ascolto', 'pt': 'Um recurso principalmente destinado a ser ouvido', 'de': 'Eine Ressource, die hauptsächlich zum Anhören bestimmt ist', 'nl': 'Een resource die voornamelijk bedoeld is om te worden gehoord', 'ca': 'Un recurs principalment destinat a ser escoltat', 'ro': 'O resursă destinată în principal ascultării', 'bg': 'Ресурс, предназначен предимно за слушане', 'el': 'Πόρος που προορίζεται κυρίως για ακρόαση', 'ar': 'مورد مخصص أساساً للاستماع', 'he': 'משאב המיועד בעיקר להאזנה', 'id': 'Sumber yang terutama dimaksudkan untuk didengar', 'ja': '主に聴くことを目的としたリソース'},
    'A resource requiring interaction from the user to be understood, executed, or experienced': {'it': 'Una risorsa che richiede l\'interazione dell\'utente per essere compresa, eseguita o vissuta', 'pt': 'Um recurso que requer interação do utilizador para ser compreendido, executado ou vivenciado', 'de': 'Eine Ressource, die Benutzerinteraktion erfordert, um verstanden, ausgeführt oder erlebt zu werden', 'nl': 'Een resource die gebruikersinteractie vereist om begrepen, uitgevoerd of beleefd te worden', 'ca': 'Un recurs que requereix interacció de l\'usuari per ser comprès, executat o experimentat', 'ro': 'O resursă care necesită interacțiunea utilizatorului pentru a fi înțeleasă, executată sau trăită', 'bg': 'Ресурс, изискващ взаимодействие с потребителя, за да бъде разбран, изпълнен или преживян', 'el': 'Πόρος που απαιτεί αλληλεπίδραση χρήστη για να γίνει κατανοητός, εκτελεστεί ή βιωθεί', 'ar': 'مورد يتطلب تفاعل المستخدم ليُفهم أو يُنفَّذ أو يُختبر', 'he': 'משאב הדורש אינטראקציה עם המשתמש כדי להבינו, להריצו או לחוות אותו', 'id': 'Sumber yang memerlukan interaksi pengguna untuk dipahami, dieksekusi, atau dialami', 'ja': '理解・実行・体験するためにユーザーの操作が必要なリソース'},
    'A series of visual representations imparting an impression of motion when shown in succession': {'it': 'Una serie di rappresentazioni visive che danno l\'impressione di movimento quando mostrate in successione', 'pt': 'Uma série de representações visuais que transmitem uma impressão de movimento quando mostradas em sucessão', 'de': 'Eine Reihe von visuellen Darstellungen, die einen Bewegungseindruck erzeugen, wenn sie nacheinander gezeigt werden', 'nl': 'Een reeks visuele representaties die een indruk van beweging geven wanneer ze achtereenvolgens worden getoond', 'ca': 'Una sèrie de representacions visuals que transmeten una impressió de moviment quan es mostren successivament', 'ro': 'O serie de reprezentări vizuale care transmit o impresie de mișcare când sunt afișate succesiv', 'bg': 'Поредица от визуални изображения, които създават впечатление за движение при последователно показване', 'el': 'Σειρά οπτικών αναπαραστάσεων που δίνουν εντύπωση κίνησης όταν εμφανίζονται διαδοχικά', 'ar': 'سلسلة من التمثيلات المرئية التي تُعطي انطباعاً بالحركة عند عرضها تباعاً', 'he': 'סדרה של ייצוגים חזותיים המעניקים רושם של תנועה כשמוצגים ברצף', 'id': 'Serangkaian representasi visual yang memberikan kesan gerakan saat ditampilkan berurutan', 'ja': '連続して表示すると動きの印象を与える視覚的表現のシリーズ'},
    'A server error occurred': {'it': 'Si è verificato un errore del server', 'pt': 'Ocorreu um erro no servidor', 'de': 'Ein Serverfehler ist aufgetreten', 'nl': 'Er is een serverfout opgetreden', 'ca': 'S\'ha produït un error del servidor', 'ro': 'A apărut o eroare de server', 'bg': 'Възникна грешка на сървъра', 'el': 'Παρουσιάστηκε σφάλμα διακομιστή', 'ar': 'حدث خطأ في الخادم', 'he': 'אירעה שגיאת שרת', 'id': 'Terjadi kesalahan server', 'ja': 'サーバーエラーが発生しました'},
    'A system that provides one or more functions': {'it': 'Un sistema che fornisce una o più funzioni', 'pt': 'Um sistema que fornece uma ou mais funções', 'de': 'Ein System, das eine oder mehrere Funktionen bereitstellt', 'nl': 'Een systeem dat één of meer functies biedt', 'ca': 'Un sistema que proporciona una o més funcions', 'ro': 'Un sistem care oferă una sau mai multe funcții', 'bg': 'Система, предоставяща една или повече функции', 'el': 'Σύστημα που παρέχει μία ή περισσότερες λειτουργίες', 'ar': 'نظام يوفر وظيفة أو أكثر', 'he': 'מערכת המספקת פונקציה אחת או יותר', 'id': 'Sistem yang menyediakan satu atau lebih fungsi', 'ja': '1つ以上の機能を提供するシステム'},
    'A text is required.': {'it': 'È richiesto un testo.', 'pt': 'É necessário um texto.', 'de': 'Ein Text ist erforderlich.', 'nl': 'Een tekst is vereist.', 'ca': 'Es requereix un text.', 'ro': 'Este necesar un text.', 'bg': 'Необходим е текст.', 'el': 'Απαιτείται κείμενο.', 'ar': 'النص مطلوب.', 'he': 'נדרש טקסט.', 'id': 'Teks diperlukan.', 'ja': 'テキストが必要です。'},
    'A title is required.': {'it': 'È richiesto un titolo.', 'pt': 'É necessário um título.', 'de': 'Ein Titel ist erforderlich.', 'nl': 'Een titel is vereist.', 'ca': 'Es requereix un títol.', 'ro': 'Este necesar un titlu.', 'bg': 'Необходимо е заглавие.', 'el': 'Απαιτείται τίτλος.', 'ar': 'العنوان مطلوب.', 'he': 'נדרש כותרת.', 'id': 'Judul diperlukan.', 'ja': 'タイトルが必要です。'},
    'A visual representation of a topography': {'it': 'Una rappresentazione visiva di una topografia', 'pt': 'Uma representação visual de uma topografia', 'de': 'Eine visuelle Darstellung einer Topographie', 'nl': 'Een visuele weergave van een topografie', 'ca': 'Una representació visual d\'una topografia', 'ro': 'O reprezentare vizuală a unei topografii', 'bg': 'Визуално представяне на топография', 'el': 'Οπτική αναπαράσταση τοπογραφίας', 'ar': 'تمثيل بصري للتضاريس', 'he': 'ייצוג חזותי של טופוגרפיה', 'id': 'Representasi visual dari topografi', 'ja': '地形の視覚的表現'},
    'A visual representation other than text': {'it': 'Una rappresentazione visiva diversa dal testo', 'pt': 'Uma representação visual diferente de texto', 'de': 'Eine visuelle Darstellung, die kein Text ist', 'nl': 'Een visuele weergave anders dan tekst', 'ca': 'Una representació visual diferent del text', 'ro': 'O reprezentare vizuală alta decât text', 'bg': 'Визуално представяне, различно от текст', 'el': 'Οπτική αναπαράσταση εκτός κειμένου', 'ar': 'تمثيل بصري غير نصي', 'he': 'ייצוג חזותי שאינו טקסט', 'id': 'Representasi visual selain teks', 'ja': 'テキスト以外の視覚的表現'},
    'API documentation': {'it': 'Documentazione API', 'pt': 'Documentação da API', 'de': 'API-Dokumentation', 'nl': 'API-documentatie', 'ca': 'Documentació de l\'API', 'ro': 'Documentație API', 'bg': 'API документация', 'el': 'Τεκμηρίωση API', 'ar': 'وثائق API', 'he': 'תיעוד API', 'id': 'Dokumentasi API', 'ja': 'APIドキュメント'},
    'Abstract': {'it': 'Riassunto', 'pt': 'Resumo', 'de': 'Zusammenfassung', 'nl': 'Samenvatting', 'ca': 'Resum', 'ro': 'Rezumat', 'bg': 'Резюме', 'el': 'Περίληψη', 'ar': 'ملخص', 'he': 'תקציר', 'id': 'Abstrak', 'ja': '要約'},
    'Accepted file formats: {extensions}': {'it': 'Formati di file accettati: {extensions}', 'pt': 'Formatos de arquivo aceitos: {extensions}', 'de': 'Akzeptierte Dateiformate: {extensions}', 'nl': 'Geaccepteerde bestandsformaten: {extensions}', 'ca': 'Formats de fitxer acceptats: {extensions}', 'ro': 'Formate de fișier acceptate: {extensions}', 'bg': 'Приемани формати на файлове: {extensions}', 'el': 'Αποδεκτές μορφές αρχείων: {extensions}', 'ar': 'تنسيقات الملفات المقبولة: {extensions}', 'he': 'פורמטי קבצים מקובלים: {extensions}', 'id': 'Format file yang diterima: {extensions}', 'ja': '受け入れ可能なファイル形式: {extensions}'},
    'Access duration': {'it': 'Durata dell\'accesso', 'pt': 'Duração do acesso', 'de': 'Zugangsdauer', 'nl': 'Toegangsduur', 'ca': 'Durada de l\'accés', 'ro': 'Durata accesului', 'bg': 'Продължителност на достъп', 'el': 'Διάρκεια πρόσβασης', 'ar': 'مدة الوصول', 'he': 'משך הגישה', 'id': 'Durasi akses', 'ja': 'アクセス時間'},
    'Access entrances list': {'it': 'Accedi all\'elenco delle entrate', 'pt': 'Aceder à lista de entradas', 'de': 'Auf die Eingansliste zugreifen', 'nl': 'Toegang tot de inganglijst', 'ca': 'Accedir a la llista d\'entrades', 'ro': 'Accesați lista de intrări', 'bg': 'Достъп до списъка с входове', 'el': 'Πρόσβαση στη λίστα εισόδων', 'ar': 'الوصول إلى قائمة المداخل', 'he': 'גישה לרשימת הכניסות', 'id': 'Akses daftar pintu masuk', 'ja': '入口リストへのアクセス'},
    'Access the revision history page': {'it': 'Accedi alla pagina della cronologia delle revisioni', 'pt': 'Aceder à página do histórico de revisões', 'de': 'Auf die Revisionshistorieseite zugreifen', 'nl': 'Toegang tot de revisiegeschiedenispagina', 'ca': 'Accedir a la pàgina de l\'historial de revisions', 'ro': 'Accesați pagina de istoric al revizuirilor', 'bg': 'Достъп до страницата с история на ревизиите', 'el': 'Πρόσβαση στη σελίδα ιστορικού αναθεωρήσεων', 'ar': 'الوصول إلى صفحة تاريخ المراجعات', 'he': 'גישה לדף היסטוריית הגרסאות', 'id': 'Akses halaman riwayat revisi', 'ja': '改訂履歴ページにアクセス'},
    'Add a BBS document': {'it': 'Aggiungi un documento BBS', 'pt': 'Adicionar um documento BBS', 'de': 'Ein BBS-Dokument hinzufügen', 'nl': 'Een BBS-document toevoegen', 'ca': 'Afegir un document BBS', 'ro': 'Adăugați un document BBS', 'bg': 'Добавяне на BBS документ', 'el': 'Προσθήκη εγγράφου BBS', 'ar': 'إضافة وثيقة BBS', 'he': 'הוסף מסמך BBS', 'id': 'Tambahkan dokumen BBS', 'ja': 'BBSドキュメントを追加'},
    'Add a cave': {'it': 'Aggiungi una grotta', 'pt': 'Adicionar uma cavidade', 'de': 'Eine Höhle hinzufügen', 'nl': 'Een grot toevoegen', 'ca': 'Afegir una cavitat', 'ro': 'Adăugați o peșteră', 'bg': 'Добавяне на пещера', 'el': 'Προσθήκη σπηλαίου', 'ar': 'إضافة كهف', 'he': 'הוסף מערה', 'id': 'Tambahkan gua', 'ja': '洞窟を追加'},
    'Add a comment on why the selected documents have to be declined.': {'it': 'Aggiungi un commento sul motivo per cui i documenti selezionati devono essere rifiutati.', 'pt': 'Adicione um comentário sobre o motivo pelo qual os documentos selecionados devem ser recusados.', 'de': 'Fügen Sie einen Kommentar hinzu, warum die ausgewählten Dokumente abgelehnt werden müssen.', 'nl': 'Voeg een opmerking toe over waarom de geselecteerde documenten moeten worden afgewezen.', 'ca': 'Afegiu un comentari sobre per què els documents seleccionats han de ser rebutjats.', 'ro': 'Adăugați un comentariu despre motivul pentru care documentele selectate trebuie respinse.', 'bg': 'Добавете коментар защо избраните документи трябва да бъдат отказани.', 'el': 'Προσθέστε σχόλιο για τον λόγο που τα επιλεγμένα έγγραφα πρέπει να απορριφθούν.', 'ar': 'أضف تعليقاً حول سبب رفض المستندات المحددة.', 'he': 'הוסף הערה על הסיבה לדחיית המסמכים הנבחרים.', 'id': 'Tambahkan komentar mengapa dokumen yang dipilih harus ditolak.', 'ja': '選択した文書を却下する理由のコメントを追加してください。'},
    'Add a comment on why the selected documents have to be validated.': {'it': 'Aggiungi un commento sul motivo per cui i documenti selezionati devono essere convalidati.', 'pt': 'Adicione um comentário sobre o motivo pelo qual os documentos selecionados devem ser validados.', 'de': 'Fügen Sie einen Kommentar hinzu, warum die ausgewählten Dokumente validiert werden müssen.', 'nl': 'Voeg een opmerking toe over waarom de geselecteerde documenten moeten worden gevalideerd.', 'ca': 'Afegiu un comentari sobre per què els documents seleccionats han de ser validats.', 'ro': 'Adăugați un comentariu despre motivul pentru care documentele selectate trebuie validate.', 'bg': 'Добавете коментар защо избраните документи трябва да бъдат потвърдени.', 'el': 'Προσθέστε σχόλιο για τον λόγο που τα επιλεγμένα έγγραφα πρέπει να επικυρωθούν.', 'ar': 'أضف تعليقاً حول سبب التحقق من صحة المستندات المحددة.', 'he': 'הוסף הערה על הסיבה לאישור המסמכים הנבחרים.', 'id': 'Tambahkan komentar mengapa dokumen yang dipilih harus divalidasi.', 'ja': '選択した文書を承認する理由のコメントを追加してください。'},
    'Add a location': {'it': 'Aggiungi una posizione', 'pt': 'Adicionar uma localização', 'de': 'Einen Standort hinzufügen', 'nl': 'Een locatie toevoegen', 'ca': 'Afegir una localització', 'ro': 'Adăugați o locație', 'bg': 'Добавяне на местоположение', 'el': 'Προσθήκη τοποθεσίας', 'ar': 'إضافة موقع', 'he': 'הוסף מיקום', 'id': 'Tambahkan lokasi', 'ja': '場所を追加'},
    'Add a new comment': {'it': 'Aggiungi un nuovo commento', 'pt': 'Adicionar um novo comentário', 'de': 'Einen neuen Kommentar hinzufügen', 'nl': 'Een nieuw commentaar toevoegen', 'ca': 'Afegir un nou comentari', 'ro': 'Adăugați un nou comentariu', 'bg': 'Добавяне на нов коментар', 'el': 'Προσθήκη νέου σχολίου', 'ar': 'إضافة تعليق جديد', 'he': 'הוסף תגובה חדשה', 'id': 'Tambahkan komentar baru', 'ja': '新しいコメントを追加'},
    'Add a new description': {'it': 'Aggiungi una nuova descrizione', 'pt': 'Adicionar uma nova descrição', 'de': 'Eine neue Beschreibung hinzufügen', 'nl': 'Een nieuwe beschrijving toevoegen', 'ca': 'Afegir una nova descripció', 'ro': 'Adăugați o nouă descriere', 'bg': 'Добавяне на ново описание', 'el': 'Προσθήκη νέας περιγραφής', 'ar': 'إضافة وصف جديد', 'he': 'הוסף תיאור חדש', 'id': 'Tambahkan deskripsi baru', 'ja': '新しい説明を追加'},
    'Add a new history': {'it': 'Aggiungi una nuova storia', 'pt': 'Adicionar um novo histórico', 'de': 'Eine neue Geschichte hinzufügen', 'nl': 'Een nieuwe geschiedenis toevoegen', 'ca': 'Afegir un nou historial', 'ro': 'Adăugați un nou istoric', 'bg': 'Добавяне на нова история', 'el': 'Προσθήκη νέου ιστορικού', 'ar': 'إضافة سجل تاريخي جديد', 'he': 'הוסף היסטוריה חדשה', 'id': 'Tambahkan riwayat baru', 'ja': '新しい履歴を追加'},
    'Add a new location': {'it': 'Aggiungi una nuova posizione', 'pt': 'Adicionar uma nova localização', 'de': 'Einen neuen Standort hinzufügen', 'nl': 'Een nieuwe locatie toevoegen', 'ca': 'Afegir una nova localització', 'ro': 'Adăugați o nouă locație', 'bg': 'Добавяне на ново местоположение', 'el': 'Προσθήκη νέας τοποθεσίας', 'ar': 'إضافة موقع جديد', 'he': 'הוסף מיקום חדש', 'id': 'Tambahkan lokasi baru', 'ja': '新しい場所を追加'},
    'Add a new rigging': {'it': 'Aggiungi un nuovo attrezzaggio', 'pt': 'Adicionar um novo equipamento', 'de': 'Eine neue Seilausrüstung hinzufügen', 'nl': 'Een nieuwe uitrusting toevoegen', 'ca': 'Afegir un nou equipament', 'ro': 'Adăugați un nou echipament', 'bg': 'Добавяне на ново оборудване', 'el': 'Προσθήκη νέου εξοπλισμού', 'ar': 'إضافة تجهيز جديد', 'he': 'הוסף ציוד חדש', 'id': 'Tambahkan rigging baru', 'ja': '新しいロープ設置を追加'},
    'Add document': {'it': 'Aggiungi documento', 'pt': 'Adicionar documento', 'de': 'Dokument hinzufügen', 'nl': 'Document toevoegen', 'ca': 'Afegir document', 'ro': 'Adăugați document', 'bg': 'Добавяне на документ', 'el': 'Προσθήκη εγγράφου', 'ar': 'إضافة وثيقة', 'he': 'הוסף מסמך', 'id': 'Tambahkan dokumen', 'ja': '文書を追加'},
    'Add to Map': {'it': 'Aggiungi alla mappa', 'pt': 'Adicionar ao mapa', 'de': 'Zur Karte hinzufügen', 'nl': 'Toevoegen aan kaart', 'ca': 'Afegir al mapa', 'ro': 'Adăugați pe hartă', 'bg': 'Добавяне към картата', 'el': 'Προσθήκη στον χάρτη', 'ar': 'إضافة إلى الخريطة', 'he': 'הוסף למפה', 'id': 'Tambahkan ke Peta', 'ja': '地図に追加'},
    'Add to my explored caves': {'it': 'Aggiungi alle mie grotte esplorate', 'pt': 'Adicionar às minhas grutas exploradas', 'de': 'Zu meinen erkundeten Höhlen hinzufügen', 'nl': 'Toevoegen aan mijn verkende grotten', 'ca': 'Afegir a les meves cavitats explorades', 'ro': 'Adăugați la peșterile mele explorate', 'bg': 'Добавяне към моите проучени пещери', 'el': 'Προσθήκη στα εξερευνημένα μου σπήλαια', 'ar': 'إضافة إلى كهوفي المستكشفة', 'he': 'הוסף למערות שחקרתי', 'id': 'Tambahkan ke gua yang saya jelajahi', 'ja': '探検済みの洞窟に追加'},
    'Added at': {'it': 'Aggiunto il', 'pt': 'Adicionado em', 'de': 'Hinzugefügt am', 'nl': 'Toegevoegd op', 'ca': 'Afegit el', 'ro': 'Adăugat la', 'bg': 'Добавено на', 'el': 'Προστέθηκε στις', 'ar': 'أضيف في', 'he': 'נוסף ב-', 'id': 'Ditambahkan pada', 'ja': '追加日時'},
    'Adding caves...': {'it': 'Aggiunta grotte in corso...', 'pt': 'A adicionar cavidades...', 'de': 'Höhlen werden hinzugefügt...', 'nl': 'Grotten toevoegen...', 'ca': 'Afegint cavitats...', 'ro': 'Se adaugă peșteri...', 'bg': 'Добавяне на пещери...', 'el': 'Προσθήκη σπηλαίων...', 'ar': 'جاري إضافة الكهوف...', 'he': 'מוסיף מערות...', 'id': 'Menambahkan gua...', 'ja': '洞窟を追加中...'},
    'Additional information': {'it': 'Informazioni aggiuntive', 'pt': 'Informações adicionais', 'de': 'Zusätzliche Informationen', 'nl': 'Aanvullende informatie', 'ca': 'Informació addicional', 'ro': 'Informații suplimentare', 'bg': 'Допълнителна информация', 'el': 'Πρόσθετες πληροφορίες', 'ar': 'معلومات إضافية', 'he': 'מידע נוסף', 'id': 'Informasi tambahan', 'ja': '追加情報'},
    'Additional information about the document.': {'it': 'Informazioni aggiuntive sul documento.', 'pt': 'Informações adicionais sobre o documento.', 'de': 'Zusätzliche Informationen über das Dokument.', 'nl': 'Aanvullende informatie over het document.', 'ca': 'Informació addicional sobre el document.', 'ro': 'Informații suplimentare despre document.', 'bg': 'Допълнителна информация за документа.', 'el': 'Πρόσθετες πληροφορίες για το έγγραφο.', 'ar': 'معلومات إضافية حول الوثيقة.', 'he': 'מידע נוסף על המסמך.', 'id': 'Informasi tambahan tentang dokumen.', 'ja': '文書に関する追加情報。'},
    'Address': {'it': 'Indirizzo', 'pt': 'Endereço', 'de': 'Adresse', 'nl': 'Adres', 'ca': 'Adreça', 'ro': 'Adresă', 'bg': 'Адрес', 'el': 'Διεύθυνση', 'ar': 'عنوان', 'he': 'כתובת', 'id': 'Alamat', 'ja': '住所'},
    'Address (line 2)': {'it': 'Indirizzo (riga 2)', 'pt': 'Endereço (linha 2)', 'de': 'Adresse (Zeile 2)', 'nl': 'Adres (regel 2)', 'ca': 'Adreça (línia 2)', 'ro': 'Adresă (linia 2)', 'bg': 'Адрес (ред 2)', 'el': 'Διεύθυνση (γραμμή 2)', 'ar': 'عنوان (السطر 2)', 'he': 'כתובת (שורה 2)', 'id': 'Alamat (baris 2)', 'ja': '住所（行2）'},
    'Administrator': {'it': 'Amministratore', 'pt': 'Administrador', 'de': 'Administrator', 'nl': 'Beheerder', 'ca': 'Administrador', 'ro': 'Administrator', 'bg': 'Администратор', 'el': 'Διαχειριστής', 'ar': 'مدير النظام', 'he': 'מנהל מערכת', 'id': 'Administrator', 'ja': '管理者'},
    'All Revisions': {'it': 'Tutte le revisioni', 'pt': 'Todas as revisões', 'de': 'Alle Revisionen', 'nl': 'Alle revisies', 'ca': 'Totes les revisions', 'ro': 'Toate revizuirile', 'bg': 'Всички ревизии', 'el': 'Όλες οι αναθεωρήσεις', 'ar': 'جميع المراجعات', 'he': 'כל הגרסאות', 'id': 'Semua Revisi', 'ja': 'すべての改訂版'},
    'All document types': {'it': 'Tutti i tipi di documenti', 'pt': 'Todos os tipos de documentos', 'de': 'Alle Dokumenttypen', 'nl': 'Alle documenttypen', 'ca': 'Tots els tipus de documents', 'ro': 'Toate tipurile de documente', 'bg': 'Всички типове документи', 'el': 'Όλοι οι τύποι εγγράφων', 'ar': 'جميع أنواع الوثائق', 'he': 'כל סוגי המסמכים', 'id': 'Semua jenis dokumen', 'ja': 'すべての文書タイプ'},
    'All revisions': {'it': 'Tutte le revisioni', 'pt': 'Todas as revisões', 'de': 'Alle Revisionen', 'nl': 'Alle revisies', 'ca': 'Totes les revisions', 'ro': 'Toate revizuirile', 'bg': 'Всички ревизии', 'el': 'Όλες οι αναθεωρήσεις', 'ar': 'جميع المراجعات', 'he': 'כל הגרסאות', 'id': 'Semua revisi', 'ja': 'すべての改訂版'},
    'All steps completed': {'it': 'Tutti i passaggi completati', 'pt': 'Todos os passos concluídos', 'de': 'Alle Schritte abgeschlossen', 'nl': 'Alle stappen voltooid', 'ca': 'Tots els passos completats', 'ro': 'Toți pașii completați', 'bg': 'Всички стъпки завършени', 'el': 'Όλα τα βήματα ολοκληρώθηκαν', 'ar': 'اكتملت جميع الخطوات', 'he': 'כל השלבים הושלמו', 'id': 'Semua langkah selesai', 'ja': 'すべてのステップ完了'},
    'All subjects': {'it': 'Tutti i soggetti', 'pt': 'Todos os assuntos', 'de': 'Alle Themen', 'nl': 'Alle onderwerpen', 'ca': 'Tots els temes', 'ro': 'Toate subiectele', 'bg': 'Всички теми', 'el': 'Όλα τα θέματα', 'ar': 'جميع الموضوعات', 'he': 'כל הנושאים', 'id': 'Semua subjek', 'ja': 'すべての主題'},
    'An aggregation of resources': {'it': 'Un\'aggregazione di risorse', 'pt': 'Uma agregação de recursos', 'de': 'Eine Zusammenstellung von Ressourcen', 'nl': 'Een verzameling van bronnen', 'ca': 'Una agregació de recursos', 'ro': 'O agregare de resurse', 'bg': 'Агрегация от ресурси', 'el': 'Συγκέντρωση πόρων', 'ar': 'تجميع الموارد', 'he': 'אגרגציה של משאבים', 'id': 'Agregasi sumber daya', 'ja': 'リソースの集合体'},
    'An article from a source': {'it': 'Un articolo da una fonte', 'pt': 'Um artigo de uma fonte', 'de': 'Ein Artikel aus einer Quelle', 'nl': 'Een artikel uit een bron', 'ca': 'Un article d\'una font', 'ro': 'Un articol dintr-o sursă', 'bg': 'Статия от източник', 'el': 'Άρθρο από πηγή', 'ar': 'مقالة من مصدر', 'he': 'מאמר ממקור', 'id': 'Artikel dari sumber', 'ja': '出典からの記事'},
    'An email will be sent to:': {'it': 'Verrà inviata un\'e-mail a:', 'pt': 'Será enviado um e-mail para:', 'de': 'Eine E-Mail wird gesendet an:', 'nl': 'Er wordt een e-mail gestuurd naar:', 'ca': 'S\'enviarà un correu electrònic a:', 'ro': 'Un e-mail va fi trimis la:', 'bg': 'Ще бъде изпратен имейл на:', 'el': 'Θα σταλεί email στο:', 'ar': 'سيتم إرسال بريد إلكتروني إلى:', 'he': 'יישלח דוא"ל אל:', 'id': 'Email akan dikirim ke:', 'ja': 'メールが送信されます:'},
    'An error occurred when creating a massif.': {'it': 'Si è verificato un errore durante la creazione di un massiccio.', 'pt': 'Ocorreu um erro ao criar um maciço.', 'de': 'Beim Erstellen eines Massivs ist ein Fehler aufgetreten.', 'nl': 'Er is een fout opgetreden bij het aanmaken van een massief.', 'ca': 'S\'ha produït un error en crear un massís.', 'ro': 'A apărut o eroare la crearea unui masiv.', 'bg': 'Възникна грешка при създаването на масив.', 'el': 'Παρουσιάστηκε σφάλμα κατά τη δημιουργία μαζικής περιοχής.', 'ar': 'حدث خطأ عند إنشاء كتلة جبلية.', 'he': 'אירעה שגיאה בעת יצירת מסיב.', 'id': 'Terjadi kesalahan saat membuat massif.', 'ja': 'マシフの作成中にエラーが発生しました。'},
    'An error occurred when creating a network.': {'it': 'Si è verificato un errore durante la creazione di una rete.', 'pt': 'Ocorreu um erro ao criar uma rede.', 'de': 'Beim Erstellen eines Netzwerks ist ein Fehler aufgetreten.', 'nl': 'Er is een fout opgetreden bij het aanmaken van een netwerk.', 'ca': 'S\'ha produït un error en crear una xarxa.', 'ro': 'A apărut o eroare la crearea unei rețele.', 'bg': 'Възникна грешка при създаването на мрежа.', 'el': 'Παρουσιάστηκε σφάλμα κατά τη δημιουργία δικτύου.', 'ar': 'حدث خطأ عند إنشاء شبكة.', 'he': 'אירעה שגיאה בעת יצירת רשת.', 'id': 'Terjadi kesalahan saat membuat jaringan.', 'ja': 'ネットワークの作成中にエラーが発生しました。'},
    'An error occurred when creating a organization.': {'it': 'Si è verificato un errore durante la creazione di un\'organizzazione.', 'pt': 'Ocorreu um erro ao criar uma organização.', 'de': 'Beim Erstellen einer Organisation ist ein Fehler aufgetreten.', 'nl': 'Er is een fout opgetreden bij het aanmaken van een organisatie.', 'ca': 'S\'ha produït un error en crear una organització.', 'ro': 'A apărut o eroare la crearea unei organizații.', 'bg': 'Възникна грешка при създаването на организация.', 'el': 'Παρουσιάστηκε σφάλμα κατά τη δημιουργία οργανισμού.', 'ar': 'حدث خطأ عند إنشاء منظمة.', 'he': 'אירעה שגיאה בעת יצירת ארגון.', 'id': 'Terjadi kesalahan saat membuat organisasi.', 'ja': '組織の作成中にエラーが発生しました。'},
    'An error occurred when creating a person.': {'it': 'Si è verificato un errore durante la creazione di una persona.', 'pt': 'Ocorreu um erro ao criar uma pessoa.', 'de': 'Beim Erstellen einer Person ist ein Fehler aufgetreten.', 'nl': 'Er is een fout opgetreden bij het aanmaken van een persoon.', 'ca': 'S\'ha produït un error en crear una persona.', 'ro': 'A apărut o eroare la crearea unei persoane.', 'bg': 'Възникна грешка при създаването на лице.', 'el': 'Παρουσιάστηκε σφάλμα κατά τη δημιουργία ατόμου.', 'ar': 'حدث خطأ عند إنشاء شخص.', 'he': 'אירעה שגיאה בעת יצירת אדם.', 'id': 'Terjadi kesalahan saat membuat orang.', 'ja': '人物の作成中にエラーが発生しました。'},
    'An error occurred when creating an entrance.': {'it': 'Si è verificato un errore durante la creazione di un\'entrata.', 'pt': 'Ocorreu um erro ao criar uma entrada.', 'de': 'Beim Erstellen eines Eingangs ist ein Fehler aufgetreten.', 'nl': 'Er is een fout opgetreden bij het aanmaken van een ingang.', 'ca': 'S\'ha produït un error en crear una entrada.', 'ro': 'A apărut o eroare la crearea unei intrări.', 'bg': 'Възникна грешка при създаването на вход.', 'el': 'Παρουσιάστηκε σφάλμα κατά τη δημιουργία εισόδου.', 'ar': 'حدث خطأ عند إنشاء مدخل.', 'he': 'אירעה שגיאה בעת יצירת כניסה.', 'id': 'Terjadi kesalahan saat membuat pintu masuk.', 'ja': '入口の作成中にエラーが発生しました。'},
    'An error occurred when getting the subscriptions.': {'it': 'Si è verificato un errore durante il recupero degli abbonamenti.', 'pt': 'Ocorreu um erro ao obter as subscrições.', 'de': 'Beim Abrufen der Abonnements ist ein Fehler aufgetreten.', 'nl': 'Er is een fout opgetreden bij het ophalen van de abonnementen.', 'ca': 'S\'ha produït un error en obtenir les subscripcions.', 'ro': 'A apărut o eroare la obținerea abonamentelor.', 'bg': 'Възникна грешка при получаването на абонаментите.', 'el': 'Παρουσιάστηκε σφάλμα κατά τη λήψη συνδρομών.', 'ar': 'حدث خطأ عند الحصول على الاشتراكات.', 'he': 'אירעה שגיאה בעת קבלת המנויים.', 'id': 'Terjadi kesalahan saat mendapatkan langganan.', 'ja': 'サブスクリプションの取得中にエラーが発生しました。'},
    'An error occurred when updating a massif.': {'it': 'Si è verificato un errore durante l\'aggiornamento di un massiccio.', 'pt': 'Ocorreu um erro ao atualizar um maciço.', 'de': 'Beim Aktualisieren eines Massivs ist ein Fehler aufgetreten.', 'nl': 'Er is een fout opgetreden bij het bijwerken van een massief.', 'ca': 'S\'ha produït un error en actualitzar un massís.', 'ro': 'A apărut o eroare la actualizarea unui masiv.', 'bg': 'Възникна грешка при актуализирането на масив.', 'el': 'Παρουσιάστηκε σφάλμα κατά την ενημέρωση μαζικής περιοχής.', 'ar': 'حدث خطأ عند تحديث كتلة جبلية.', 'he': 'אירעה שגיאה בעת עדכון מסיב.', 'id': 'Terjadi kesalahan saat memperbarui massif.', 'ja': 'マシフの更新中にエラーが発生しました。'},
    'An error occurred when updating the user.': {'it': 'Si è verificato un errore durante l\'aggiornamento dell\'utente.', 'pt': 'Ocorreu um erro ao atualizar o utilizador.', 'de': 'Beim Aktualisieren des Benutzers ist ein Fehler aufgetreten.', 'nl': 'Er is een fout opgetreden bij het bijwerken van de gebruiker.', 'ca': 'S\'ha produït un error en actualitzar l\'usuari.', 'ro': 'A apărut o eroare la actualizarea utilizatorului.', 'bg': 'Възникна грешка при актуализирането на потребителя.', 'el': 'Παρουσιάστηκε σφάλμα κατά την ενημέρωση χρήστη.', 'ar': 'حدث خطأ عند تحديث المستخدم.', 'he': 'אירעה שגיאה בעת עדכון המשתמש.', 'id': 'Terjadi kesalahan saat memperbarui pengguna.', 'ja': 'ユーザーの更新中にエラーが発生しました。'},
    'An inanimate, three-dimensional object or substance': {'it': 'Un oggetto o una sostanza tridimensionale inanimata', 'pt': 'Um objeto ou substância tridimensional inanimado', 'de': 'Ein unbelebtes, dreidimensionales Objekt oder eine Substanz', 'nl': 'Een levenloos, driedimensionaal object of stof', 'ca': 'Un objecte o substància tridimensional inanimat', 'ro': 'Un obiect sau substanță tridimensional inanimat', 'bg': 'Неживо триизмерно обекто или вещество', 'el': 'Άψυχο τρισδιάστατο αντικείμενο ή ουσία', 'ar': 'جسم أو مادة ثلاثية الأبعاد غير حية', 'he': 'עצם או חומר תלת-ממדי דומם', 'id': 'Objek atau zat tiga dimensi tak bernyawa', 'ja': '無生物の3次元物体または物質'},
    'An issue of a periodic publication': {'it': 'Un numero di una pubblicazione periodica', 'pt': 'Um número de uma publicação periódica', 'de': 'Eine Ausgabe einer periodischen Veröffentlichung', 'nl': 'Een nummer van een periodieke publicatie', 'ca': 'Un número d\'una publicació periòdica', 'ro': 'Un număr dintr-o publicație periodică', 'bg': 'Брой от периодично издание', 'el': 'Τεύχος περιοδικής έκδοσης', 'ar': 'عدد من منشور دوري', 'he': 'גיליון של פרסום תקופתי', 'id': 'Edisi publikasi berkala', 'ja': '定期刊行物の号'},
    'Anthropospeleology': {'it': 'Antropospeleologia', 'pt': 'Antropoespeleologia', 'de': 'Anthropospeleologie', 'nl': 'Antropospeleologie', 'ca': 'Antropoespeleologia', 'ro': 'Antropospeleologie', 'bg': 'Антропоспелеология', 'el': 'Ανθρωπολογική σπηλαιολογία', 'ar': 'الأنثروبولوجيا الكهفية', 'he': 'אנתרופוספלאולוגיה', 'id': 'Antropospeleologi', 'ja': '人類洞窟学'},
    'Applied speleology': {'it': 'Speleologia applicata', 'pt': 'Espeleologia aplicada', 'de': 'Angewandte Höhlenkunde', 'nl': 'Toegepaste speleologie', 'ca': 'Espeleologia aplicada', 'ro': 'Speleologie aplicată', 'bg': 'Приложна спелеология', 'el': 'Εφαρμοσμένη σπηλαιολογία', 'ar': 'علم الكهوف التطبيقي', 'he': 'ספלאולוגיה יישומית', 'id': 'Speleologi terapan', 'ja': '応用洞窟学'},
    'Area': {'it': 'Area', 'pt': 'Área', 'de': 'Bereich', 'nl': 'Gebied', 'ca': 'Àrea', 'ro': 'Zonă', 'bg': 'Зона', 'el': 'Περιοχή', 'ar': 'منطقة', 'he': 'אזור', 'id': 'Area', 'ja': 'エリア'},
    'Assign an existing document': {'it': 'Assegna un documento esistente', 'pt': 'Atribuir um documento existente', 'de': 'Ein vorhandenes Dokument zuweisen', 'nl': 'Een bestaand document toewijzen', 'ca': 'Assignar un document existent', 'ro': 'Atribuiți un document existent', 'bg': 'Присвояване на съществуващ документ', 'el': 'Ανάθεση υπάρχοντος εγγράφου', 'ar': 'تعيين وثيقة موجودة', 'he': 'הקצה מסמך קיים', 'id': 'Tetapkan dokumen yang ada', 'ja': '既存の文書を割り当て'},
    'Associate': {'it': 'Associa', 'pt': 'Associar', 'de': 'Verknüpfen', 'nl': 'Koppelen', 'ca': 'Associar', 'ro': 'Asociați', 'bg': 'Свързване', 'el': 'Συσχέτιση', 'ar': 'ربط', 'he': 'שייך', 'id': 'Asosiasikan', 'ja': '関連付け'},
    'Associate 1 document': {'it': 'Associa 1 documento', 'pt': 'Associar 1 documento', 'de': '1 Dokument verknüpfen', 'nl': '1 document koppelen', 'ca': 'Associar 1 document', 'ro': 'Asociați 1 document', 'bg': 'Свързване на 1 документ', 'el': 'Συσχέτιση 1 εγγράφου', 'ar': 'ربط وثيقة واحدة', 'he': 'שייך מסמך 1', 'id': 'Asosiasikan 1 dokumen', 'ja': '1つの文書を関連付け'},
    'Associate {nb} documents': {'it': 'Associa {nb} documenti', 'pt': 'Associar {nb} documentos', 'de': '{nb} Dokumente verknüpfen', 'nl': '{nb} documenten koppelen', 'ca': 'Associar {nb} documents', 'ro': 'Asociați {nb} documente', 'bg': 'Свързване на {nb} документа', 'el': 'Συσχέτιση {nb} εγγράφων', 'ar': 'ربط {nb} وثيقة', 'he': 'שייך {nb} מסמכים', 'id': 'Asosiasikan {nb} dokumen', 'ja': '{nb}個の文書を関連付け'},
    'At least one polygon must not be marked as a hole.': {'it': 'Almeno un poligono non deve essere contrassegnato come buco.', 'pt': 'Pelo menos um polígono não deve ser marcado como buraco.', 'de': 'Mindestens ein Polygon darf nicht als Loch markiert sein.', 'nl': 'Minstens één polygoon mag niet als een gat worden gemarkeerd.', 'ca': 'Almenys un polígon no ha d\'estar marcat com a forat.', 'ro': 'Cel puțin un poligon nu trebuie marcat ca un gol.', 'bg': 'Поне един полигон не трябва да бъде маркиран като дупка.', 'el': 'Τουλάχιστον ένα πολύγωνο δεν πρέπει να επισημανθεί ως τρύπα.', 'ar': 'يجب ألا يُعلَّم ما لا يقل عن مضلع واحد كفجوة.', 'he': 'לפחות מצולע אחד לא צריך להיות מסומן כחור.', 'id': 'Setidaknya satu poligon tidak boleh ditandai sebagai lubang.', 'ja': '少なくとも1つのポリゴンは穴としてマークしないでください。'},
    'At this time, there is no comment for this entry': {'it': 'Al momento non ci sono commenti per questa voce', 'pt': 'Neste momento, não há comentários para esta entrada', 'de': 'Derzeit gibt es keinen Kommentar für diesen Eintrag', 'nl': 'Er is momenteel geen commentaar voor dit item', 'ca': 'En aquest moment, no hi ha cap comentari per a aquesta entrada', 'ro': 'În acest moment, nu există niciun comentariu pentru această intrare', 'bg': 'В момента няма коментари за този запис', 'el': 'Προς το παρόν, δεν υπάρχουν σχόλια για αυτή την καταχώριση', 'ar': 'في الوقت الحالي، لا توجد تعليقات لهذا الإدخال', 'he': 'כרגע אין תגובות לערך זה', 'id': 'Saat ini, tidak ada komentar untuk entri ini', 'ja': '現時点では、このエントリにコメントはありません'},
    'Attributes': {'it': 'Attributi', 'pt': 'Atributos', 'de': 'Attribute', 'nl': 'Attributen', 'ca': 'Atributs', 'ro': 'Atribute', 'bg': 'Атрибути', 'el': 'Χαρακτηριστικά', 'ar': 'السمات', 'he': 'תכונות', 'id': 'Atribut', 'ja': '属性'},
    'Author comment': {'it': 'Commento dell\'autore', 'pt': 'Comentário do autor', 'de': 'Autorenkommentar', 'nl': 'Auteurscommentaar', 'ca': 'Comentari de l\'autor', 'ro': 'Comentariul autorului', 'bg': 'Коментар на автора', 'el': 'Σχόλιο συγγραφέα', 'ar': 'تعليق المؤلف', 'he': 'תגובת המחבר', 'id': 'Komentar penulis', 'ja': '著者のコメント'},
    'Author created this document': {'it': 'L\'autore ha creato questo documento', 'pt': 'O autor criou este documento', 'de': 'Der Autor hat dieses Dokument erstellt', 'nl': 'De auteur heeft dit document gemaakt', 'ca': 'L\'autor ha creat aquest document', 'ro': 'Autorul a creat acest document', 'bg': 'Авторът е създал този документ', 'el': 'Ο συγγραφέας δημιούργησε αυτό το έγγραφο', 'ar': 'أنشأ المؤلف هذا المستند', 'he': 'המחבר יצר מסמך זה', 'id': 'Penulis membuat dokumen ini', 'ja': '著者がこの文書を作成しました'},
    'Authorization': {'it': 'Autorizzazione', 'pt': 'Autorização', 'de': 'Genehmigung', 'nl': 'Autorisatie', 'ca': 'Autorització', 'ro': 'Autorizare', 'bg': 'Разрешение', 'el': 'Εξουσιοδότηση', 'ar': 'إذن', 'he': 'הרשאה', 'id': 'Otorisasi', 'ja': '承認'},
    # === B ===
    'BBS - Speleological bibliographies': {'it': 'BBS - Bibliografie speleologiche', 'pt': 'BBS - Bibliografias espeleológicas', 'de': 'BBS - Speleologische Bibliographien', 'nl': 'BBS - Speleologische bibliografieën', 'ca': 'BBS - Bibliografies espeleològiques', 'ro': 'BBS - Bibliografii speleologice', 'bg': 'BBS - Спелеологически библиографии', 'el': 'BBS - Σπηλαιολογικές βιβλιογραφίες', 'ar': 'BBS - الببليوغرافيات الكهفية', 'he': 'BBS - ביבליוגרפיות ספלאולוגיות', 'id': 'BBS - Bibliografi speleologi', 'ja': 'BBS - 洞窟学文献目録'},
    'BBS Reference': {'it': 'Riferimento BBS', 'pt': 'Referência BBS', 'de': 'BBS-Referenz', 'nl': 'BBS-referentie', 'ca': 'Referència BBS', 'ro': 'Referință BBS', 'bg': 'BBS референция', 'el': 'Αναφορά BBS', 'ar': 'مرجع BBS', 'he': 'הפניה BBS', 'id': 'Referensi BBS', 'ja': 'BBS参照'},
    'BBS document submission form': {'it': 'Modulo di invio documenti BBS', 'pt': 'Formulário de envio de documento BBS', 'de': 'BBS-Dokument-Einreichungsformular', 'nl': 'BBS-document indienformulier', 'ca': 'Formulari d\'enviament de document BBS', 'ro': 'Formular de trimitere a documentului BBS', 'bg': 'Формуляр за подаване на BBS документ', 'el': 'Φόρμα υποβολής εγγράφου BBS', 'ar': 'نموذج تقديم وثيقة BBS', 'he': 'טופס הגשת מסמך BBS', 'id': 'Formulir pengiriman dokumen BBS', 'ja': 'BBS文書提出フォーム'},
    'BBS properties': {'it': 'Proprietà BBS', 'pt': 'Propriedades BBS', 'de': 'BBS-Eigenschaften', 'nl': 'BBS-eigenschappen', 'ca': 'Propietats BBS', 'ro': 'Proprietăți BBS', 'bg': 'BBS свойства', 'el': 'Ιδιότητες BBS', 'ar': 'خصائص BBS', 'he': 'מאפייני BBS', 'id': 'Properti BBS', 'ja': 'BBSプロパティ'},
    'BBS reference': {'it': 'Riferimento BBS', 'pt': 'Referência BBS', 'de': 'BBS-Referenz', 'nl': 'BBS-referentie', 'ca': 'Referència BBS', 'ro': 'Referință BBS', 'bg': 'BBS референция', 'el': 'Αναφορά BBS', 'ar': 'مرجع BBS', 'he': 'הפניה BBS', 'id': 'Referensi BBS', 'ja': 'BBS参照'},
    'BBS regions': {'it': 'Regioni BBS', 'pt': 'Regiões BBS', 'de': 'BBS-Regionen', 'nl': 'BBS-regio\'s', 'ca': 'Regions BBS', 'ro': 'Regiuni BBS', 'bg': 'BBS региони', 'el': 'Περιοχές BBS', 'ar': 'مناطق BBS', 'he': 'אזורי BBS', 'id': 'Wilayah BBS', 'ja': 'BBS地域'},
    'BBS subjects': {'it': 'Soggetti BBS', 'pt': 'Assuntos BBS', 'de': 'BBS-Themen', 'nl': 'BBS-onderwerpen', 'ca': 'Temes BBS', 'ro': 'Subiecte BBS', 'bg': 'BBS теми', 'el': 'Θέματα BBS', 'ar': 'موضوعات BBS', 'he': 'נושאי BBS', 'id': 'Subjek BBS', 'ja': 'BBSテーマ'},
    'Back': {'it': 'Indietro', 'pt': 'Voltar', 'de': 'Zurück', 'nl': 'Terug', 'ca': 'Enrere', 'ro': 'Înapoi', 'bg': 'Назад', 'el': 'Πίσω', 'ar': 'رجوع', 'he': 'חזרה', 'id': 'Kembali', 'ja': '戻る'},
    'Back to Country': {'it': 'Torna al Paese', 'pt': 'Voltar ao País', 'de': 'Zurück zum Land', 'nl': 'Terug naar Land', 'ca': 'Tornar al país', 'ro': 'Înapoi la țară', 'bg': 'Назад към страната', 'el': 'Επιστροφή στη χώρα', 'ar': 'العودة إلى الدولة', 'he': 'חזרה לארץ', 'id': 'Kembali ke Negara', 'ja': '国に戻る'},
    'Back to List': {'it': 'Torna alla lista', 'pt': 'Voltar à lista', 'de': 'Zurück zur Liste', 'nl': 'Terug naar lijst', 'ca': 'Tornar a la llista', 'ro': 'Înapoi la listă', 'bg': 'Назад към списъка', 'el': 'Επιστροφή στη λίστα', 'ar': 'العودة إلى القائمة', 'he': 'חזרה לרשימה', 'id': 'Kembali ke Daftar', 'ja': 'リストに戻る'},
    'Ban updated with success!': {'it': 'Ban aggiornato con successo!', 'pt': 'Banimento atualizado com sucesso!', 'de': 'Bann erfolgreich aktualisiert!', 'nl': 'Ban succesvol bijgewerkt!', 'ca': 'Bloqueig actualitzat amb èxit!', 'ro': 'Interdicție actualizată cu succes!', 'bg': 'Банът е актуализиран успешно!', 'el': 'Αποκλεισμός ενημερώθηκε με επιτυχία!', 'ar': 'تم تحديث الحظر بنجاح!', 'he': 'החסימה עודכנה בהצלחה!', 'id': 'Ban berhasil diperbarui!', 'ja': 'banを更新しました！'},
    'Banned': {'it': 'Bannato', 'pt': 'Banido', 'de': 'Gesperrt', 'nl': 'Verbannen', 'ca': 'Bloquejat', 'ro': 'Interzis', 'bg': 'Блокиран', 'el': 'Αποκλεισμένος', 'ar': 'محظور', 'he': 'חסום', 'id': 'Dilarang', 'ja': 'バン済み'},
    'Basic Information': {'it': 'Informazioni di base', 'pt': 'Informações básicas', 'de': 'Grundinformationen', 'nl': 'Basisinformatie', 'ca': 'Informació bàsica', 'ro': 'Informații de bază', 'bg': 'Основна информация', 'el': 'Βασικές πληροφορίες', 'ar': 'المعلومات الأساسية', 'he': 'מידע בסיסי', 'id': 'Informasi Dasar', 'ja': '基本情報'},
    'Bat habitat': {'it': 'Habitat dei pipistrelli', 'pt': 'Habitat de morcegos', 'de': 'Fledermaushabitat', 'nl': 'Vleermuishabitat', 'ca': 'Hàbitat de ratpenats', 'ro': 'Habitat pentru lilieci', 'bg': 'Прилепно местообитание', 'el': 'Βιότοπος νυχτερίδων', 'ar': 'موئل الخفافيش', 'he': 'בית גידול עטלפים', 'id': 'Habitat kelelawar', 'ja': 'コウモリの生息地'},
    'Bibliography': {'it': 'Bibliografia', 'pt': 'Bibliografia', 'de': 'Bibliographie', 'nl': 'Bibliografie', 'ca': 'Bibliografia', 'ro': 'Bibliografie', 'bg': 'Библиография', 'el': 'Βιβλιογραφία', 'ar': 'قائمة المراجع', 'he': 'ביבליוגרפיה', 'id': 'Bibliografi', 'ja': '参考文献'},
    'Biospeleology': {'it': 'Biospeleologia', 'pt': 'Bioespeleologia', 'de': 'Biospeleologie', 'nl': 'Biospeleologie', 'ca': 'Bioespeleologia', 'ro': 'Biospeleologie', 'bg': 'Биоспелеология', 'el': 'Βιοσπηλαιολογία', 'ar': 'علم الأحياء الكهفي', 'he': 'ביוספלאולוגיה', 'id': 'Biospeleologi', 'ja': '生物洞窟学'},
    'Book': {'it': 'Libro', 'pt': 'Livro', 'de': 'Buch', 'nl': 'Boek', 'ca': 'Llibre', 'ro': 'Carte', 'bg': 'Книга', 'el': 'Βιβλίο', 'ar': 'كتاب', 'he': 'ספר', 'id': 'Buku', 'ja': '書籍'},
    'By': {'it': 'Da', 'pt': 'Por', 'de': 'Von', 'nl': 'Door', 'ca': 'Per', 'ro': 'De', 'bg': 'От', 'el': 'Από', 'ar': 'بواسطة', 'he': 'על ידי', 'id': 'Oleh', 'ja': 'によって'},
    # === C ===
    'CO2 risk': {'it': 'Rischio CO2', 'pt': 'Risco de CO2', 'de': 'CO2-Risiko', 'nl': 'CO2-risico', 'ca': 'Risc de CO2', 'ro': 'Risc de CO2', 'bg': 'Риск от CO2', 'el': 'Κίνδυνος CO2', 'ar': 'خطر ثاني أكسيد الكربون', 'he': 'סיכון CO2', 'id': 'Risiko CO2', 'ja': 'CO2リスク'},
    'CSV Import': {'it': 'Importazione CSV', 'pt': 'Importar CSV', 'de': 'CSV-Import', 'nl': 'CSV-import', 'ca': 'Importació CSV', 'ro': 'Import CSV', 'bg': 'CSV импорт', 'el': 'Εισαγωγή CSV', 'ar': 'استيراد CSV', 'he': 'ייבוא CSV', 'id': 'Impor CSV', 'ja': 'CSVインポート'},
    'Cancel adding a new comment': {'it': 'Annulla l\'aggiunta di un nuovo commento', 'pt': 'Cancelar adição de novo comentário', 'de': 'Neuen Kommentar hinzufügen abbrechen', 'nl': 'Toevoegen nieuw commentaar annuleren', 'ca': 'Cancel·la l\'afegiment d\'un nou comentari', 'ro': 'Anulați adăugarea unui nou comentariu', 'bg': 'Отказ от добавяне на нов коментар', 'el': 'Ακύρωση προσθήκης νέου σχολίου', 'ar': 'إلغاء إضافة تعليق جديد', 'he': 'בטל הוספת תגובה חדשה', 'id': 'Batalkan menambahkan komentar baru', 'ja': '新しいコメントの追加をキャンセル'},
    'Cancel adding a new description': {'it': 'Annulla l\'aggiunta di una nuova descrizione', 'pt': 'Cancelar adição de nova descrição', 'de': 'Neue Beschreibung hinzufügen abbrechen', 'nl': 'Toevoegen nieuwe beschrijving annuleren', 'ca': 'Cancel·la l\'afegiment d\'una nova descripció', 'ro': 'Anulați adăugarea unei noi descrieri', 'bg': 'Отказ от добавяне на ново описание', 'el': 'Ακύρωση προσθήκης νέας περιγραφής', 'ar': 'إلغاء إضافة وصف جديد', 'he': 'בטל הוספת תיאור חדש', 'id': 'Batalkan menambahkan deskripsi baru', 'ja': '新しい説明の追加をキャンセル'},
    'Cancel adding a new history': {'it': 'Annulla l\'aggiunta di una nuova storia', 'pt': 'Cancelar adição de novo histórico', 'de': 'Neues Verlaufseintrag hinzufügen abbrechen', 'nl': 'Toevoegen nieuwe geschiedenis annuleren', 'ca': 'Cancel·la l\'afegiment d\'un nou historial', 'ro': 'Anulați adăugarea unui nou istoric', 'bg': 'Отказ от добавяне на нова история', 'el': 'Ακύρωση προσθήκης νέου ιστορικού', 'ar': 'إلغاء إضافة سجل تاريخي جديد', 'he': 'בטל הוספת היסטוריה חדשה', 'id': 'Batalkan menambahkan riwayat baru', 'ja': '新しい履歴の追加をキャンセル'},
    'Cancel adding a new location': {'it': 'Annulla l\'aggiunta di una nuova posizione', 'pt': 'Cancelar adição de nova localização', 'de': 'Neuen Standort hinzufügen abbrechen', 'nl': 'Toevoegen nieuwe locatie annuleren', 'ca': 'Cancel·la l\'afegiment d\'una nova localització', 'ro': 'Anulați adăugarea unei noi locații', 'bg': 'Отказ от добавяне на ново местоположение', 'el': 'Ακύρωση προσθήκης νέας τοποθεσίας', 'ar': 'إلغاء إضافة موقع جديد', 'he': 'בטל הוספת מיקום חדש', 'id': 'Batalkan menambahkan lokasi baru', 'ja': '新しい場所の追加をキャンセル'},
    'Cancel adding a new rigging': {'it': 'Annulla l\'aggiunta di un nuovo attrezzaggio', 'pt': 'Cancelar adição de novo equipamento', 'de': 'Neue Seilausrüstung hinzufügen abbrechen', 'nl': 'Toevoegen nieuwe uitrusting annuleren', 'ca': 'Cancel·la l\'afegiment d\'un nou equipament', 'ro': 'Anulați adăugarea unui nou echipament', 'bg': 'Отказ от добавяне на ново оборудване', 'el': 'Ακύρωση προσθήκης νέου εξοπλισμού', 'ar': 'إلغاء إضافة تجهيز جديد', 'he': 'בטל הוספת ציוד חדש', 'id': 'Batalkan menambahkan rigging baru', 'ja': '新しいロープ設置の追加をキャンセル'},
    'Cancel drawing': {'it': 'Annulla disegno', 'pt': 'Cancelar desenho', 'de': 'Zeichnen abbrechen', 'nl': 'Tekenen annuleren', 'ca': 'Cancel·la el dibuix', 'ro': 'Anulați desenul', 'bg': 'Отказ от рисуване', 'el': 'Ακύρωση σχεδίασης', 'ar': 'إلغاء الرسم', 'he': 'בטל ציור', 'id': 'Batalkan menggambar', 'ja': '描画をキャンセル'},
    'Cancel edit': {'it': 'Annulla modifica', 'pt': 'Cancelar edição', 'de': 'Bearbeitung abbrechen', 'nl': 'Bewerking annuleren', 'ca': 'Cancel·la l\'edició', 'ro': 'Anulați editarea', 'bg': 'Отказ от редактиране', 'el': 'Ακύρωση επεξεργασίας', 'ar': 'إلغاء التحرير', 'he': 'בטל עריכה', 'id': 'Batalkan edit', 'ja': '編集をキャンセル'},
    'Cancel editing, discards all changes': {'it': 'Annulla modifica, scarta tutte le modifiche', 'pt': 'Cancelar edição, descarta todas as alterações', 'de': 'Bearbeitung abbrechen, alle Änderungen verwerfen', 'nl': 'Bewerking annuleren, alle wijzigingen verwerpen', 'ca': 'Cancel·la l\'edició, descarta tots els canvis', 'ro': 'Anulați editarea, renunțați la toate modificările', 'bg': 'Отказ от редактиране, отхвърляне на всички промени', 'el': 'Ακύρωση επεξεργασίας, απόρριψη όλων των αλλαγών', 'ar': 'إلغاء التحرير، تجاهل جميع التغييرات', 'he': 'בטל עריכה, מחק את כל השינויים', 'id': 'Batalkan pengeditan, buang semua perubahan', 'ja': '編集をキャンセルし、すべての変更を破棄'},
    'Cancel this search': {'it': 'Annulla questa ricerca', 'pt': 'Cancelar esta pesquisa', 'de': 'Diese Suche abbrechen', 'nl': 'Deze zoekopdracht annuleren', 'ca': 'Cancel·la aquesta cerca', 'ro': 'Anulați această căutare', 'bg': 'Отказ от тази търсене', 'el': 'Ακύρωση αυτής της αναζήτησης', 'ar': 'إلغاء هذا البحث', 'he': 'בטל חיפוש זה', 'id': 'Batalkan pencarian ini', 'ja': 'この検索をキャンセル'},
    'Cave': {'it': 'Grotta', 'pt': 'Cavidade', 'de': 'Höhle', 'nl': 'Grot', 'ca': 'Cavitat', 'ro': 'Peșteră', 'bg': 'Пещера', 'el': 'Σπήλαιο', 'ar': 'كهف', 'he': 'מערה', 'id': 'Gua', 'ja': '洞窟'},
    'Cave information': {'it': 'Informazioni sulla grotta', 'pt': 'Informações da cavidade', 'de': 'Höhleninformationen', 'nl': 'Grotinformatie', 'ca': 'Informació de la cavitat', 'ro': 'Informații despre peșteră', 'bg': 'Информация за пещерата', 'el': 'Πληροφορίες σπηλαίου', 'ar': 'معلومات الكهف', 'he': 'מידע על המערה', 'id': 'Informasi gua', 'ja': '洞窟情報'},
    'Cave name language': {'it': 'Lingua del nome della grotta', 'pt': 'Idioma do nome da cavidade', 'de': 'Sprache des Höhlennamens', 'nl': 'Taal van de grotnaam', 'ca': 'Idioma del nom de la cavitat', 'ro': 'Limba numelui peșterii', 'bg': 'Език на името на пещерата', 'el': 'Γλώσσα ονόματος σπηλαίου', 'ar': 'لغة اسم الكهف', 'he': 'שפת שם המערה', 'id': 'Bahasa nama gua', 'ja': '洞窟名の言語'},
    'Cavers': {'it': 'Speleologi', 'pt': 'Espeleólogos', 'de': 'Höhlenforscher', 'nl': 'Grottoeducators', 'ca': 'Espeleòlegs', 'ro': 'Speologi', 'bg': 'Спелеолози', 'el': 'Σπηλαιολόγοι', 'ar': 'المستكشفون الكهفيون', 'he': 'חוקרי מערות', 'id': 'Penjelajah gua', 'ja': '洞窟探検家'},
    'Change columns': {'it': 'Cambia colonne', 'pt': 'Alterar colunas', 'de': 'Spalten ändern', 'nl': 'Kolommen wijzigen', 'ca': 'Canviar columnes', 'ro': 'Schimbați coloanele', 'bg': 'Промяна на колоните', 'el': 'Αλλαγή στηλών', 'ar': 'تغيير الأعمدة', 'he': 'שנה עמודות', 'id': 'Ubah kolom', 'ja': '列を変更'},
    'Change user groups': {'it': 'Modifica gruppi utente', 'pt': 'Alterar grupos de utilizadores', 'de': 'Benutzergruppen ändern', 'nl': 'Gebruikersgroepen wijzigen', 'ca': 'Canviar grups d\'usuaris', 'ro': 'Schimbați grupurile de utilizatori', 'bg': 'Промяна на потребителски групи', 'el': 'Αλλαγή ομάδων χρηστών', 'ar': 'تغيير مجموعات المستخدمين', 'he': 'שנה קבוצות משתמשים', 'id': 'Ubah grup pengguna', 'ja': 'ユーザーグループを変更'},
    'Cities': {'it': 'Città', 'pt': 'Cidades', 'de': 'Städte', 'nl': 'Steden', 'ca': 'Ciutats', 'ro': 'Orașe', 'bg': 'Градове', 'el': 'Πόλεις', 'ar': 'مدن', 'he': 'ערים', 'id': 'Kota', 'ja': '都市'},
    'Clear': {'it': 'Cancella', 'pt': 'Limpar', 'de': 'Löschen', 'nl': 'Wissen', 'ca': 'Netejar', 'ro': 'Ștergeți', 'bg': 'Изчистване', 'el': 'Εκκαθάριση', 'ar': 'مسح', 'he': 'נקה', 'id': 'Bersihkan', 'ja': 'クリア'},
    'Comment': {'it': 'Commento', 'pt': 'Comentário', 'de': 'Kommentar', 'nl': 'Commentaar', 'ca': 'Comentari', 'ro': 'Comentariu', 'bg': 'Коментар', 'el': 'Σχόλιο', 'ar': 'تعليق', 'he': 'תגובה', 'id': 'Komentar', 'ja': 'コメント'},
    'Contribute': {'it': 'Contribuisci', 'pt': 'Contribuir', 'de': 'Beitragen', 'nl': 'Bijdragen', 'ca': 'Contribuir', 'ro': 'Contribuiți', 'bg': 'Допринесете', 'el': 'Συνεισφορά', 'ar': 'ساهم', 'he': 'תרום', 'id': 'Berkontribusi', 'ja': '貢献する'},
    'Contributor nickname': {'it': 'Soprannome del contributore', 'pt': 'Apelido do contribuidor', 'de': 'Spitzname des Beitragenden', 'nl': 'Bijnaam van de bijdrager', 'ca': 'Sobrenom del contribuïdor', 'ro': 'Pseudonimul contribuitorului', 'bg': 'Псевдоним на участника', 'el': 'Ψευδώνυμο συντελεστή', 'ar': 'لقب المساهم', 'he': 'כינוי התורם', 'id': 'Nama panggilan kontributor', 'ja': '貢献者のニックネーム'},
    'Countries': {'it': 'Paesi', 'pt': 'Países', 'de': 'Länder', 'nl': 'Landen', 'ca': 'Països', 'ro': 'Țări', 'bg': 'Държави', 'el': 'Χώρες', 'ar': 'الدول', 'he': 'מדינות', 'id': 'Negara', 'ja': '国'},
    'Country / Region': {'it': 'Paese / Regione', 'pt': 'País / Região', 'de': 'Land / Region', 'nl': 'Land / Regio', 'ca': 'País / Regió', 'ro': 'Țară / Regiune', 'bg': 'Страна / Регион', 'el': 'Χώρα / Περιοχή', 'ar': 'الدولة / المنطقة', 'he': 'מדינה / אזור', 'id': 'Negara / Wilayah', 'ja': '国 / 地域'},
    'Country not found': {'it': 'Paese non trovato', 'pt': 'País não encontrado', 'de': 'Land nicht gefunden', 'nl': 'Land niet gevonden', 'ca': 'País no trobat', 'ro': 'Țara nu a fost găsită', 'bg': 'Страната не е намерена', 'el': 'Χώρα δεν βρέθηκε', 'ar': 'لم يتم العثور على الدولة', 'he': 'מדינה לא נמצאה', 'id': 'Negara tidak ditemukan', 'ja': '国が見つかりません'},
    'Country subscriptions': {'it': 'Abbonamenti al paese', 'pt': 'Assinaturas de país', 'de': 'Landesabonnements', 'nl': 'Landsabonnementen', 'ca': 'Subscripcions al país', 'ro': 'Abonamente la țară', 'bg': 'Абонаменти за страна', 'el': 'Συνδρομές χώρας', 'ar': 'اشتراكات الدولة', 'he': 'מנויים למדינה', 'id': 'Langganan negara', 'ja': '国のサブスクリプション'},
    'Create': {'it': 'Crea', 'pt': 'Criar', 'de': 'Erstellen', 'nl': 'Aanmaken', 'ca': 'Crear', 'ro': 'Creați', 'bg': 'Създаване', 'el': 'Δημιουργία', 'ar': 'إنشاء', 'he': 'צור', 'id': 'Buat', 'ja': '作成'},
    'Create a new Entrance': {'it': 'Crea una nuova entrata', 'pt': 'Criar uma nova entrada', 'de': 'Einen neuen Eingang erstellen', 'nl': 'Een nieuwe ingang aanmaken', 'ca': 'Crea una nova entrada', 'ro': 'Creați o nouă intrare', 'bg': 'Създаване на нов вход', 'el': 'Δημιουργία νέας εισόδου', 'ar': 'إنشاء مدخل جديد', 'he': 'צור כניסה חדשה', 'id': 'Buat Pintu Masuk baru', 'ja': '新しい入口を作成'},
    'Create a new entity in Grottocenter': {'it': 'Crea una nuova entità in Grottocenter', 'pt': 'Criar uma nova entidade no Grottocenter', 'de': 'Eine neue Entität in Grottocenter erstellen', 'nl': 'Een nieuwe entiteit aanmaken in Grottocenter', 'ca': 'Crea una nova entitat a Grottocenter', 'ro': 'Creați o nouă entitate în Grottocenter', 'bg': 'Създаване на нова единица в Grottocenter', 'el': 'Δημιουργία νέας οντότητας στο Grottocenter', 'ar': 'إنشاء كيان جديد في Grottocenter', 'he': 'צור ישות חדשה ב-Grottocenter', 'id': 'Buat entitas baru di Grottocenter', 'ja': 'Grottocenterで新しいエンティティを作成'},
    'Created by': {'it': 'Creato da', 'pt': 'Criado por', 'de': 'Erstellt von', 'nl': 'Aangemaakt door', 'ca': 'Creat per', 'ro': 'Creat de', 'bg': 'Създадено от', 'el': 'Δημιουργήθηκε από', 'ar': 'أنشأه', 'he': 'נוצר על ידי', 'id': 'Dibuat oleh', 'ja': '作成者'},
    'Creating document...': {'it': 'Creazione documento in corso...', 'pt': 'Criando documento...', 'de': 'Dokument wird erstellt...', 'nl': 'Document aanmaken...', 'ca': 'Creant document...', 'ro': 'Se creează documentul...', 'bg': 'Създаване на документ...', 'el': 'Δημιουργία εγγράφου...', 'ar': 'جاري إنشاء الوثيقة...', 'he': 'יוצר מסמך...', 'id': 'Membuat dokumen...', 'ja': '文書を作成中...'},
    'Creating entrance...': {'it': 'Creazione entrata in corso...', 'pt': 'Criando entrada...', 'de': 'Eingang wird erstellt...', 'nl': 'Ingang aanmaken...', 'ca': 'Creant entrada...', 'ro': 'Se creează intrarea...', 'bg': 'Създаване на вход...', 'el': 'Δημιουργία εισόδου...', 'ar': 'جاري إنشاء المدخل...', 'he': 'יוצר כניסה...', 'id': 'Membuat pintu masuk...', 'ja': '入口を作成中...'},
    'Creating massif...': {'it': 'Creazione massiccio in corso...', 'pt': 'Criando maciço...', 'de': 'Massiv wird erstellt...', 'nl': 'Massief aanmaken...', 'ca': 'Creant massís...', 'ro': 'Se creează masivul...', 'bg': 'Създаване на масив...', 'el': 'Δημιουργία μαζικής περιοχής...', 'ar': 'جاري إنشاء الكتلة الجبلية...', 'he': 'יוצר מסיב...', 'id': 'Membuat massif...', 'ja': 'マシフを作成中...'},
    'Creating network...': {'it': 'Creazione rete in corso...', 'pt': 'Criando rede...', 'de': 'Netzwerk wird erstellt...', 'nl': 'Netwerk aanmaken...', 'ca': 'Creant xarxa...', 'ro': 'Se creează rețeaua...', 'bg': 'Създаване на мрежа...', 'el': 'Δημιουργία δικτύου...', 'ar': 'جاري إنشاء الشبكة...', 'he': 'יוצר רשת...', 'id': 'Membuat jaringan...', 'ja': 'ネットワークを作成中...'},
    'Creating organization...': {'it': 'Creazione organizzazione in corso...', 'pt': 'Criando organização...', 'de': 'Organisation wird erstellt...', 'nl': 'Organisatie aanmaken...', 'ca': 'Creant organització...', 'ro': 'Se creează organizația...', 'bg': 'Създаване на организация...', 'el': 'Δημιουργία οργανισμού...', 'ar': 'جاري إنشاء المنظمة...', 'he': 'יוצר ארגון...', 'id': 'Membuat organisasi...', 'ja': '組織を作成中...'},
    'Creating person...': {'it': 'Creazione persona in corso...', 'pt': 'Criando pessoa...', 'de': 'Person wird erstellt...', 'nl': 'Persoon aanmaken...', 'ca': 'Creant persona...', 'ro': 'Se creează persoana...', 'bg': 'Създаване на лице...', 'el': 'Δημιουργία ατόμου...', 'ar': 'جاري إنشاء الشخص...', 'he': 'יוצר אדם...', 'id': 'Membuat orang...', 'ja': '人物を作成中...'},
    'Creation completed': {'it': 'Creazione completata', 'pt': 'Criação concluída', 'de': 'Erstellung abgeschlossen', 'nl': 'Aanmaken voltooid', 'ca': 'Creació completada', 'ro': 'Creare finalizată', 'bg': 'Създаването е завършено', 'el': 'Η δημιουργία ολοκληρώθηκε', 'ar': 'اكتمل الإنشاء', 'he': 'היצירה הושלמה', 'id': 'Pembuatan selesai', 'ja': '作成完了'},
}


def load_json(path):
    with open(path, encoding='utf-8') as f:
        return json.load(f)


def save_json(path, data):
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2, sort_keys=True)
        f.write('\n')


def apply():
    en = load_json(os.path.join(LANG_DIR, 'en.json'))
    total = 0
    langs = ['fr', 'es', 'it', 'pt', 'de', 'nl', 'ca', 'ro', 'bg', 'el', 'ar', 'he', 'id', 'ja']
    for lang in langs:
        path = os.path.join(LANG_DIR, f'{lang}.json')
        data = load_json(path)
        count = 0
        for key, translations in T.items():
            if lang in translations:
                if data.get(key, '') == '' or data.get(key, '') == en.get(key, ''):
                    data[key] = translations[lang]
                    count += 1
        save_json(path, data)
        total += count
        if count:
            print(f'{lang}: +{count}')
    print(f'Total: {total}')


if __name__ == '__main__':
    apply()
